#!/bin/sh
set -e
( cd /usr/lib/moose/python && python setup.py install --record installed_files.txt )
( cd /usr/lib/moose/python && python setup-moogli.py install --record installed_files_moogli.txt )
