#!/bin/sh
set -e
mkdir -p /etc/moose
mkdir -p /etc/moogli
( cd /usr/lib/moose && python setup.py install --record /etc/moose/installed_files.txt )
( cd /usr/lib/moogli && python setup-moogli.py install --record /etc/moogli/installed_files.txt )
