#!/bin/sh
set +e
if [ -d /etc/moose ]; then
    cd /etc/moose && cat installed_files.txt | xargs rm -rf 
fi
if [ -d /etc/moogli ]; then
    cd /etc/moogli && cat installed_files.txt | xargs rm -rf 
fi
