#!/bin/sh
set -e

if [ -d /usr/lib/moose/python ]; then
    ( cd /usr/lib/moose/python && cat installed_files.txt | xargs rm -rf )
    ( cd /usr/lib/moose/python && cat installed_files_moogli.txt | xargs rm -rf )
fi

if [ -d /usr/lib/moose ]; then
    rm -R /usr/lib/moose
fi

if [ -d /usr/share/doc/moose ]; then
    rm -R /usr/share/doc/moose
fi

if [ -d /usr/share/moose ]; then
    rm -R /usr/share/moose
fi

if [ -d /usr/share/pyshared/moose ]; then
    rm -R /usr/share/pyshared/moose
fi

pydistpkg_dir=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
if [ -d $pydistpkg_dir/moose ];
then 
    rm -R $pydistpkg_dir/moose
fi
if [ -f $HOME/Desktop/MooseGUI.desktop ];
then 
    rm $HOME/Desktop/MooseGUI.desktop
fi
if [ -f $HOME/Desktop/HHSquidDemo.desktop ];
then 
    rm $HOME/Desktop/HHSquidDemo.desktop
fi

