#!/bin/sh
if [ -d debian/tmp ]; then
	rm -Rf debian/tmp
fi
mkdir debian/tmp
svn export python debian/tmp/python
svn export Demos debian/tmp/Demos
svn export Docs debian/tmp/docmoose
svn export gui debian/tmp/gui
cp README debian/tmp/docmoose/

