######################################################################
# Automatically generated by qmake (2.00a) Tue Jul 31 11:22:10 2007
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DesktopPanel.h GuiHandler.h Main.h MooseQt.h Plot.h PlotWidget.h
SOURCES += DesktopPanel.cpp main.cpp Main.cpp Plot.cpp PlotWidget.cpp
