MOOSE: PoissonRng Class Reference
PoissonRng Class Reference
#include <PoissonRng.h>
Public Member Functions
PoissonRng ()
virtual ~PoissonRng ()
void setMean (double mean)
virtual void vReinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from RandGenerator
RandGenerator ()
virtual ~RandGenerator ()
double getMean () const
double getVariance () const
double getSample () const
void process (const Eref &e, ProcPtr info)
void reinit (const Eref &e, ProcPtr info)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from RandGenerator
static const Cinfo * initCinfo ()
Additional Inherited Members
Protected Attributes inherited from RandGenerator
Probability * rng_
double sample_
Constructor & Destructor Documentation
PoissonRng::PoissonRng ()
virtual PoissonRng::~PoissonRng () inline virtual
Member Function Documentation
const Cinfo * PoissonRng::initCinfo () static
References RandGenerator::getMean(), RandGenerator::initCinfo(), and setMean().
void PoissonRng::setMean (double mean)
Sets the mean. Since poisson distribution is defined in terms of the rate parameter or the mean, it is mandatory to set this before using the generator.
References RandGenerator::rng_, and Poisson::setMean().
Referenced by initCinfo().
void PoissonRng::vReinit (const Eref & e, ProcPtr p) virtual
reports error in case the parameter mean has not been set.
Reimplemented from RandGenerator.
References RandGenerator::rng_.
The documentation for this class was generated from the following files:
randnum/PoissonRng.h
randnum/PoissonRng.cpp