MOOSE: FuncTerm Class Reference
FuncTerm Class Reference
#include <FuncTerm.h>
Public Member Functions
FuncTerm ()
~FuncTerm ()
double operator() (const double *S, double t) const
const FuncTerm & operator= (const FuncTerm &other)
void evalPool (double *s, double t) const
void setReactantIndex (const vector< unsigned int > &mol)
const vector< unsigned int > & getReactantIndex () const
const string & getExpr () const
void setExpr (const string &e)
const unsigned int getTarget () const
void setTarget (unsigned int tgt)
Constructor & Destructor Documentation
FuncTerm::FuncTerm ()
References M_PI.
FuncTerm::~FuncTerm ()
Member Function Documentation
void FuncTerm::evalPool (double * s, double t) const
Referenced by GssaVoxelPools::updateDependentMathExpn().
const string & FuncTerm::getExpr () const
Referenced by FuncRate::getExpr().
const vector< unsigned int > & FuncTerm::getReactantIndex () const
Referenced by Gsolve::fillMathDep(), and FuncRate::getFuncArgIndex().
const unsigned int FuncTerm::getTarget () const
Referenced by FuncRate::copyWithVolScaling(), and FuncRate::getReactants().
double FuncTerm::operator() (const double * S, double t) const
This computes the value. The time t is an argument needed by some functions.
const FuncTerm & FuncTerm::operator= (const FuncTerm & other)
References setReactantIndex().
void FuncTerm::setExpr (const string & e)
References showError().
Referenced by Stoich::installAndUnschedFunc(), FuncRate::setExpr(), and testFuncTerm().
void FuncTerm::setReactantIndex (const vector< unsigned int > & mol)
This function finds the reactant indices in the vector S. It returns the number of indices found, which are the entries in molIndex.
Referenced by Stoich::installAndUnschedFunc(), operator=(), FuncRate::setFuncArgIndex(), and testFuncTerm().
void FuncTerm::setTarget (unsigned int tgt)
Referenced by FuncRate::FuncRate(), Stoich::installAndUnschedFunc(), and FuncRate::setReactants().
The documentation for this class was generated from the following files:
ksolve/FuncTerm.h
ksolve/FuncTerm.cpp