MOOSE: ObjId Class Reference
ObjId Class Reference
#include <ObjId.h>
Public Member Functions
ObjId ()
ObjId (Id i, unsigned int d, unsigned int f=0)
ObjId (Id i)
ObjId (const string &path)
string path () const
Eref eref () const
bool operator== (const ObjId &other) const
bool operator!= (const ObjId &other) const
bool operator< (const ObjId &other) const
bool isDataHere () const
bool isGlobal () const
Returns true if the Element is global.
bool isOffNode () const
Returns true if we need to go off-node for calling operations.
char * data () const
Element * element () const
bool bad () const
Public Attributes
Id id
unsigned int dataIndex
unsigned int fieldIndex
Friends
ostream & operator<< (ostream &s, const ObjId &i)
istream & operator>> (istream &s, ObjId &i)
Detailed Description
This class manages lookups for specific data entries in elements, in a node-independent manner. It is basically a composite of Id and DataIndex.
Constructor & Destructor Documentation
ObjId::ObjId () inline
Returns the root Id
ObjId::ObjId (Id i, unsigned int d, unsigned int f = 0) inline
Creates a ObjId using specified Id and DataIndex
ObjId::ObjId (Id i) inline
ObjId::ObjId (const string & path)
Creates an ObjId by reading the path string Returns bad on failure.
Member Function Documentation
bool ObjId::bad () const
True if the return value is bad: either returning a failure, or the DataIndex or FieldIndex is out of range. However, this is a node-local funtion so it can't report the FieldIndex status in all cases.
References BADINDEX, dataIndex, fieldIndex, Element::getNode(), Element::localDataStart(), Shell::myNode(), Element::numData(), and Element::numField().
Referenced by benchmarkMsg(), HSolve::deleteIncomingMessages(), testAssortedMsg(), testIntFireNetwork(), testMsgElementListing(), and testTreeTraversal().
char * ObjId::data () const
Returns data entry for this object
References dataIndex, element(), and fieldIndex.
Referenced by addToBuf(), dispatchBuffers(), Msg::getMsg(), main(), ReadKkit::read(), remoteFieldGetVec(), remoteGet(), remoteGetVec(), ZombieFunction::setSolver(), test2ArgSetVec(), testLookupSetGet(), testMsgField(), testSendSpike(), testSetGet(), testSetGetDouble(), testSetGetExtField(), testStrGet(), and ZombiePool::vSetSolver().
Element * ObjId::element () const
Returns Element part
Referenced by Shell::adopt(), SetGet::checkSet(), data(), Shell::doCreate(), Shell::doFind(), Shell::doMove(), eref(), OneToAllMsg::findOtherEnd(), OneToOneDataIndexMsg::findOtherEnd(), OneToOneMsg::findOtherEnd(), SingleMsg::findOtherEnd(), SparseMsg::findOtherEnd(), getCompt(), Shell::innerMove(), isDataHere(), isGlobal(), isOffNode(), GetOpFunc1< T, L, A >::op(), GetEpFunc1< T, L, A >::op(), Neutral::parent(), Neutral::path(), ReadCspace::printMol(), SetGet::strGet(), SetGet::strSet(), testGet(), testMsgField(), testSendSpike(), testSyncSynapseSize(), wildcardTestFunc(), and writeKkit().
Eref ObjId::eref () const
Returns the Eref matching itself.
References dataIndex, element(), and fieldIndex.
Referenced by Shell::adopt(), allChildren(), SetGet::checkSet(), Shell::destroy(), Shell::doCreate(), Shell::doFind(), Shell::doMove(), Field< A >::get(), LookupField< L, A >::get(), Field< A >::getVec(), Shell::innerAddMsg(), Shell::innerMove(), Neutral::isDescendant(), GetOpFunc1< T, L, A >::op(), GetEpFunc1< T, L, A >::op(), path(), Neutral::path(), SetGet0::set(), SetGet1< A >::set(), SetGet2< L, A >::set(), SetGet3< A1, A2, A3 >::set(), SetGet4< A1, A2, A3, A4 >::set(), SetGet5< A1, A2, A3, A4, A5 >::set(), SetGet6< A1, A2, A3, A4, A5, A6 >::set(), Neutral::setName(), SetGet1< A >::setVec(), SetGet2< L, A >::setVec(), singleLevelWildcard(), SetGet::strGet(), SetGet::strSet(), testGetMsg(), testObjIdToAndFromPath(), testSendSpike(), testShellAddMsg(), and testTable().
bool ObjId::isDataHere () const
True if the data is present on the current node. Always true for globals, which confuses the matter somewhat.
References dataIndex, element(), and Shell::myNode().
Referenced by SetGet::checkSet(), Field< A >::get(), and LookupField< L, A >::get().
bool ObjId::isGlobal () const
Returns true if the Element is global.
References element().
Referenced by isOffNode(), SetGet0::set(), SetGet1< A >::set(), SetGet2< L, A >::set(), SetGet3< A1, A2, A3 >::set(), SetGet4< A1, A2, A3, A4 >::set(), SetGet5< A1, A2, A3, A4, A5 >::set(), and SetGet6< A1, A2, A3, A4, A5, A6 >::set().
bool ObjId::isOffNode () const
Returns true if we need to go off-node for calling operations.
References dataIndex, element(), isGlobal(), Shell::myNode(), and Shell::numNodes().
Referenced by SetGet0::set(), SetGet1< A >::set(), SetGet2< L, A >::set(), SetGet3< A1, A2, A3 >::set(), SetGet4< A1, A2, A3, A4 >::set(), SetGet5< A1, A2, A3, A4, A5 >::set(), and SetGet6< A1, A2, A3, A4, A5, A6 >::set().
bool ObjId::operator!= (const ObjId & other) const
References dataIndex, fieldIndex, and id.
bool ObjId::operator< (const ObjId & other) const
For sorting
References dataIndex, fieldIndex, and id.
bool ObjId::operator== (const ObjId & other) const
For equality check
References dataIndex, fieldIndex, and id.
string ObjId::path () const
Returns the absolute path including all array indices.
References eref(), and Neutral::path().
Referenced by Shell::doCopy(), Shell::doCreate(), Shell::doMove(), Function::getExpr(), Field< A >::getVec(), Function::setExpr(), testObjIdToAndFromPath(), and testTreeTraversal().
Friends And Related Function Documentation
ostream& operator<< (ostream & s, const ObjId & i) friend
istream& operator>> (istream & s, ObjId & i) friend
Member Data Documentation
unsigned int ObjId::dataIndex
Referenced by allChildren(), bad(), SetGet::checkSet(), data(), Shell::doAddMsg(), Shell::doFind(), eref(), OneToAllMsg::findOtherEnd(), OneToOneDataIndexMsg::findOtherEnd(), OneToOneMsg::findOtherEnd(), SingleMsg::findOtherEnd(), DiagonalMsg::findOtherEnd(), SparseMsg::findOtherEnd(), innerCopyElements(), isDataHere(), isOffNode(), operator!=(), operator<(), operator<<(), operator==(), Neutral::path(), testObjIdToAndFromPath(), DiagonalMsg::~DiagonalMsg(), OneToAllMsg::~OneToAllMsg(), OneToOneDataIndexMsg::~OneToOneDataIndexMsg(), OneToOneMsg::~OneToOneMsg(), SingleMsg::~SingleMsg(), and SparseMsg::~SparseMsg().
unsigned int ObjId::fieldIndex
Referenced by bad(), SetGet::checkSet(), data(), Shell::doFind(), eref(), operator!=(), operator<(), operator<<(), operator==(), and testObjIdToAndFromPath().
Id ObjId::id
Here are the data values.
Referenced by ReadKkit::assignPoolCompartments(), ReadKkit::assignReacCompartments(), ReadKkit::buildChan(), ReadKkit::buildEnz(), ReadKkit::buildGraph(), ReadKkit::buildGroup(), ReadKkit::buildPlot(), ReadKkit::buildPool(), ReadKkit::buildReac(), ReadKkit::buildStim(), ReadKkit::buildTable(), SetGet::checkSet(), HSolve::deleteIncomingMessages(), Shell::destroy(), Shell::doAddMsg(), findModelParent(), DiagonalMsg::findOtherEnd(), getCompt(), Id::Id(), Shell::innerAddMsg(), Stoich::installEnzyme(), Stoich::installMMenz(), Stoich::installReaction(), operator!=(), operator<(), operator<<(), operator==(), operator>>(), Neutral::parent(), Neutral::path(), testObjIdToAndFromPath(), and testTreeTraversal().
The documentation for this class was generated from the following files:
basecode/ObjId.h
basecode/ObjId.cpp