MOOSE: OpFunc6Base< A1, A2, A3, A4, A5, A6 > Class Template Reference
OpFunc6Base< A1, A2, A3, A4, A5, A6 > Class Template Reference abstract
#include <OpFuncBase.h>
Public Member Functions
bool checkFinfo (const Finfo *s) const
virtual void op (const Eref &e, A1 arg1, A2 arg2, A3 arg3, A4 arg4, A5 arg5, A6 arg6) const =0
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
virtual ~OpFunc ()
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Member Function Documentation
template<class A1, class A2, class A3, class A4, class A5, class A6> bool OpFunc6Base< A1, A2, A3, A4, A5, A6 >::checkFinfo (const Finfo * s) const inline virtual
Implements OpFunc.
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > const OpFunc * OpFunc6Base< A1, A2, A3, A4, A5, A6 >::makeHopFunc (HopIndex hopIndex) const virtual
Implements OpFunc.
Referenced by SetGet6< A1, A2, A3, A4, A5, A6 >::set().
template<class A1, class A2, class A3, class A4, class A5, class A6> virtual void OpFunc6Base< A1, A2, A3, A4, A5, A6 >::op (const Eref & e, A1 arg1, A2 arg2, A3 arg3, A4 arg4, A5 arg5, A6 arg6) const pure virtual
Implemented in HopFunc6< A1, A2, A3, A4, A5, A6 >, EpFunc6< T, A1, A2, A3, A4, A5, A6 >, and OpFunc6< T, A1, A2, A3, A4, A5, A6 >.
Referenced by OpFunc6Base< A1, A2, A3, A4, A5, A6 >::opBuffer(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), and SetGet6< A1, A2, A3, A4, A5, A6 >::set().
template<class A1, class A2, class A3, class A4, class A5, class A6> void OpFunc6Base< A1, A2, A3, A4, A5, A6 >::opBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc by converting args.
Implements OpFunc.
References Conv< T >::buf2val(), and OpFunc6Base< A1, A2, A3, A4, A5, A6 >::op().
template<class A1, class A2, class A3, class A4, class A5, class A6> string OpFunc6Base< A1, A2, A3, A4, A5, A6 >::rttiType () const inline virtual
Implements OpFunc.
References Conv< T >::rttiType().
The documentation for this class was generated from the following files:
basecode/OpFuncBase.h
basecode/HopFunc.h