MOOSE: OpFunc Class Reference
OpFunc Class Reference abstract
#include <OpFuncBase.h>
Public Member Functions
OpFunc ()
virtual ~OpFunc ()
virtual bool checkFinfo (const Finfo *s) const =0
virtual string rttiType () const =0
virtual const OpFunc * makeHopFunc (HopIndex hopIndex) const =0
virtual void opBuffer (const Eref &e, double *buf) const =0
Executes the OpFunc by converting args.
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Static Public Member Functions
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Constructor & Destructor Documentation
OpFunc::OpFunc ()
virtual OpFunc::~OpFunc () inline virtual
Member Function Documentation
virtual bool OpFunc::checkFinfo (const Finfo * s) const pure virtual
Implemented in LookupGetOpFuncBase< L, A >, OpFunc6Base< A1, A2, A3, A4, A5, A6 >, OpFunc5Base< A1, A2, A3, A4, A5 >, OpFunc4Base< A1, A2, A3, A4 >, OpFunc3Base< A1, A2, A3 >, OpFunc2Base< A1, A2 >, OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< vector< A > * >, OpFunc1Base< ProcPtr >, and OpFunc0Base.
Referenced by SrcFinfo::addMsg(), and SrcFinfo::checkTarget().
const OpFunc * OpFunc::lookop (unsigned int opIndex) static
References opIndex().
virtual const OpFunc* OpFunc::makeHopFunc (HopIndex hopIndex) const pure virtual
Implemented in LookupGetOpFuncBase< L, A >, GetOpFuncBase< A >, OpFunc6Base< A1, A2, A3, A4, A5, A6 >, OpFunc5Base< A1, A2, A3, A4, A5 >, OpFunc4Base< A1, A2, A3, A4 >, OpFunc3Base< A1, A2, A3 >, OpFunc2Base< A1, A2 >, OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< vector< A > * >, OpFunc1Base< ProcPtr >, and OpFunc0Base.
Referenced by Element::putOffNodeTargetsInDigest().
virtual void OpFunc::opBuffer (const Eref & e, double * buf) const pure virtual
Executes the OpFunc by converting args.
Implemented in LookupGetOpFuncBase< L, A >, GetOpFuncBase< A >, OpFunc6Base< A1, A2, A3, A4, A5, A6 >, OpFunc5Base< A1, A2, A3, A4, A5 >, OpFunc4Base< A1, A2, A3, A4 >, OpFunc3Base< A1, A2, A3 >, OpFunc2Base< A1, A2 >, OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< vector< A > * >, OpFunc1Base< ProcPtr >, and OpFunc0Base.
unsigned int OpFunc::opIndex () const inline
Referenced by Field< A >::get(), Field< A >::getVec(), lookop(), SetGet0::set(), SetGet1< A >::set(), SetGet2< L, A >::set(), SetGet3< A1, A2, A3 >::set(), SetGet4< A1, A2, A3, A4 >::set(), SetGet5< A1, A2, A3, A4, A5 >::set(), SetGet6< A1, A2, A3, A4, A5, A6 >::set(), SetGet1< A >::setVec(), and SetGet2< L, A >::setVec().
virtual void OpFunc::opVecBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc for all data by converting a vector of args.
Reimplemented in OpFunc2Base< A1, A2 >, OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< vector< A > * >, and OpFunc1Base< ProcPtr >.
unsigned int OpFunc::rebuildOpIndex () static
cleans out the entire Ops vector. Returns size of orig vector.
Referenced by Cinfo::rebuildOpIndex().
virtual string OpFunc::rttiType () const pure virtual
Implemented in LookupGetOpFuncBase< L, A >, OpFunc6Base< A1, A2, A3, A4, A5, A6 >, OpFunc5Base< A1, A2, A3, A4, A5 >, OpFunc4Base< A1, A2, A3, A4 >, OpFunc3Base< A1, A2, A3 >, OpFunc2Base< A1, A2 >, OpFunc1Base< A >, OpFunc1Base< A * >, OpFunc1Base< vector< A > * >, OpFunc1Base< ProcPtr >, OpFunc0Base, and ProcOpFunc< T >.
Referenced by DestFinfo::rttiType().
bool OpFunc::setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Referenced by Cinfo::rebuildOpIndex().
The documentation for this class was generated from the following files:
basecode/OpFuncBase.h
basecode/OpFuncBase.cpp