MOOSE: Probability Class Reference
Probability Class Reference abstract
#include <Probability.h>
Public Member Functions
virtual ~Probability ()
virtual double getMean () const =0
virtual double getVariance () const =0
virtual double getNextSample () const =0
Detailed Description
Base class for implementing various probability distributions.
Constructor & Destructor Documentation
virtual Probability::~Probability () inline virtual
Member Function Documentation
virtual double Probability::getMean () const pure virtual
Implemented in Poisson, Exponential, Normal, Gamma, Binomial, and Uniform.
Referenced by RandGenerator::getMean().
virtual double Probability::getNextSample () const pure virtual
Implemented in Normal, Poisson, Exponential, Gamma, Binomial, and Uniform.
Referenced by RandGenerator::process().
virtual double Probability::getVariance () const pure virtual
Implemented in Poisson, Normal, Exponential, Gamma, Binomial, and Uniform.
Referenced by RandGenerator::getVariance().
The documentation for this class was generated from the following file:
randnum/Probability.h