MOOSE: ZombiePoolInterface Class Reference
ZombiePoolInterface Class Reference abstract
#include <ZombiePoolInterface.h>
Public Member Functions
ZombiePoolInterface ()
virtual void setNinit (const Eref &e, double val)=0
Set initial # of molecules in given pool and voxel. Bdry cond.
virtual double getNinit (const Eref &e) const =0
get initial # of molecules in given pool and voxel. Bdry cond.
virtual void setN (const Eref &e, double val)=0
Set # of molecules in given pool and voxel. Varies with time.
virtual double getN (const Eref &e) const =0
Get # of molecules in given pool and voxel. Varies with time.
virtual void setDiffConst (const Eref &e, double val)=0
Diffusion constant: Only one per pool, voxel number is ignored.
virtual double getDiffConst (const Eref &e) const =0
Diffusion constant: Only one per pool, voxel number is ignored.
virtual void setMotorConst (const Eref &e, double val)
virtual void setNumPools (unsigned int num)=0
Specifies number of pools (species) handled by system.
virtual unsigned int getNumPools () const =0
gets number of pools (species) handled by system.
virtual void setNumAllVoxels (unsigned int numVoxels)=0
Assign number of voxels (size of pools_ vector)
virtual unsigned int getNumLocalVoxels () const =0
Number of voxels here. pools_.size() == getNumLocalVoxels.
virtual VoxelPoolsBase * pools (unsigned int i)=0
Return a pointer to the specified VoxelPool.
virtual double volume (unsigned int i) const =0
Return volume of voxel i.
virtual void getBlock (vector< double > &values) const =0
virtual void setBlock (const vector< double > &values)=0
virtual void setStoich (Id stoich)=0
virtual void setDsolve (Id dsolve)=0
Assigns the diffusion solver. Used by the reac solvers.
virtual void setCompartment (Id compartment)
Assigns compartment.
Id getCompartment () const
void setupCrossSolverReacs (const map< Id, vector< Id > > &xr, Id otherStoich)
Sets up cross-solver reactions.
void setupCrossSolverReacVols (const vector< vector< Id > > &subCompts, const vector< vector< Id > > &prdCompts)
void filterCrossRateTerms (const vector< Id > &xreacs, const vector< pair< Id, Id > > &xrt)
virtual void updateRateTerms (unsigned int index=~0U)=0
virtual unsigned int getPoolIndex (const Eref &er) const =0
Return pool index, using Stoich ptr to do lookup.
void xComptIn (const Eref &e, Id srcZombiePoolInterface, vector< double > values)
void assignXferVoxels (unsigned int xferCompt)
void assignXferIndex (unsigned int numProxyMols, unsigned int xferCompt, const vector< vector< unsigned int > > &voxy)
void setupXfer (Id myZombiePoolInterface, Id otherZombiePoolInterface, unsigned int numProxyMols, const vector< VoxelJunction > &vj)
unsigned int assignProxyPools (const map< Id, vector< Id > > &xr, Id myZombiePoolInterface, Id otherZombiePoolInterface, Id otherComptId)
void matchJunctionVols (vector< double > &vols, Id otherComptId) const
Protected Attributes
Id stoich_
Id compartment_
Id of Chem compartment used to figure out volumes of voxels.
vector< XferInfo > xfer_
bool isBuilt_
Flag: True when solver setup has been completed.
Detailed Description
This pure virtual base class is for solvers that want to talk to the zombie pool. The Eref specifies both the pool identity and the voxel number within the pool.
Constructor & Destructor Documentation
ZombiePoolInterface::ZombiePoolInterface ()
Member Function Documentation
unsigned int ZombiePoolInterface::assignProxyPools (const map< Id, vector< Id > > & xr, Id myZombiePoolInterface, Id otherZombiePoolInterface, Id otherComptId)
Builds up the list of proxy pools on either side of the junction, and assigns to the XferInfo data structures for use during runtime.
References Eref::data(), Id::eref(), getPoolIndex(), stoich_, and xfer_.
Referenced by setupCrossSolverReacs().
void ZombiePoolInterface::assignXferIndex (unsigned int numProxyMols, unsigned int xferCompt, const vector< vector< unsigned int > > & voxy)
Figures out indexing of the array of transferred pool n's used to fill out proxies on each timestep.
References VoxelPoolsBase::addProxyTransferIndex(), and pools().
Referenced by setupXfer().
void ZombiePoolInterface::assignXferVoxels (unsigned int xferCompt)
Figures out which voxels are involved in cross-compt reactions. Stores in the appropriate xfer_ entry.
References getNumLocalVoxels(), VoxelPoolsBase::hasXfer(), pools(), and xfer_.
Referenced by setupXfer().
void ZombiePoolInterface::filterCrossRateTerms (const vector< Id > & xreacs, const vector< pair< Id, Id > > & xrt)
References VoxelPoolsBase::filterCrossRateTerms(), getNumLocalVoxels(), and pools().
Referenced by Stoich::filterXreacs().
virtual void ZombiePoolInterface::getBlock (vector< double > & values) const pure virtual
Gets block of data. The first 4 entries are passed in on the 'values' vector: the start voxel, numVoxels, start pool#, numPools. These are followed by numVoxels * numPools of data values which are filled in by the function. We assert that the entire requested block is present in this ZombiePoolInterface. The block is organized as an array of arrays of voxels; values[pool#][voxel#]
Note that numVoxels and numPools are the number in the current block, not the upper limit of the block. So values.size() == 4 + numPools * numVoxels.
Implemented in Ksolve, and Gsolve.
Referenced by Gsolve::process(), and Ksolve::process().
Id ZombiePoolInterface::getCompartment () const
References compartment_.
Referenced by Ksolve::initCinfo().
virtual double ZombiePoolInterface::getDiffConst (const Eref & e) const pure virtual
Diffusion constant: Only one per pool, voxel number is ignored.
Implemented in Gsolve, and Ksolve.
virtual double ZombiePoolInterface::getN (const Eref & e) const pure virtual
Get # of molecules in given pool and voxel. Varies with time.
Implemented in Gsolve, and Ksolve.
Referenced by ZombiePool::vGetN().
virtual double ZombiePoolInterface::getNinit (const Eref & e) const pure virtual
get initial # of molecules in given pool and voxel. Bdry cond.
Implemented in Gsolve, and Ksolve.
Referenced by ZombiePool::vGetNinit().
virtual unsigned int ZombiePoolInterface::getNumLocalVoxels () const pure virtual
Number of voxels here. pools_.size() == getNumLocalVoxels.
Implemented in Ksolve, and Gsolve.
Referenced by assignXferVoxels(), filterCrossRateTerms(), matchJunctionVols(), setupCrossSolverReacVols(), and setupXfer().
virtual unsigned int ZombiePoolInterface::getNumPools () const pure virtual
gets number of pools (species) handled by system.
Implemented in Ksolve, and Gsolve.
virtual unsigned int ZombiePoolInterface::getPoolIndex (const Eref & er) const pure virtual
Return pool index, using Stoich ptr to do lookup.
Implemented in Ksolve, and Gsolve.
Referenced by assignProxyPools().
void ZombiePoolInterface::matchJunctionVols (vector< double > & vols, Id otherComptId) const
This fills the vols vector with the volume of the abutting voxel on compt. If there are no abutting voxels on a given voxel then that entry of the vols vector is filled with a zero. There is exactly one vols entry for each voxel of the local compt.
References compartment_, Eref::data(), Id::eref(), getNumLocalVoxels(), ChemCompt::matchMeshEntries(), and volume().
Referenced by setupCrossSolverReacVols().
virtual VoxelPoolsBase* ZombiePoolInterface::pools (unsigned int i) pure virtual
Return a pointer to the specified VoxelPool.
Implemented in Ksolve, and Gsolve.
Referenced by assignXferIndex(), assignXferVoxels(), filterCrossRateTerms(), setCompartment(), setupCrossSolverReacVols(), and setupXfer().
virtual void ZombiePoolInterface::setBlock (const vector< double > & values) pure virtual
Sets block of data. The first 4 entries on the 'values' vector are the start voxel, numVoxels, start pool#, numPools. These are followed by numVoxels * numPools of data values.
Implemented in Ksolve, and Gsolve.
Referenced by Gsolve::process(), and Ksolve::process().
void ZombiePoolInterface::setCompartment (Id compartment) virtual
Assigns compartment.
Reimplemented in Gsolve.
References Element::cinfo(), compartment_, Id::element(), Cinfo::isA(), isBuilt_, pools(), setNumAllVoxels(), and VoxelPoolsBase::setVolume().
Referenced by Ksolve::initCinfo(), and Stoich::setElist().
virtual void ZombiePoolInterface::setDiffConst (const Eref & e, double val) pure virtual
Diffusion constant: Only one per pool, voxel number is ignored.
Implemented in Gsolve, and Ksolve.
Referenced by ZombiePool::vSetDiffConst().
virtual void ZombiePoolInterface::setDsolve (Id dsolve) pure virtual
Assigns the diffusion solver. Used by the reac solvers.
Implemented in Gsolve, and Ksolve.
Referenced by Stoich::setElist().
virtual void ZombiePoolInterface::setMotorConst (const Eref & e, double val) inline virtual
Motor constant: Only one per pool, voxel number is ignored. Used only in Dsolves, so here I put in a dummy.
Referenced by ZombiePool::vSetMotorConst().
virtual void ZombiePoolInterface::setN (const Eref & e, double val) pure virtual
Set # of molecules in given pool and voxel. Varies with time.
Implemented in Gsolve, and Ksolve.
Referenced by ZombiePool::vSetN().
virtual void ZombiePoolInterface::setNinit (const Eref & e, double val) pure virtual
Set initial # of molecules in given pool and voxel. Bdry cond.
Implemented in Gsolve, and Ksolve.
Referenced by ZombiePool::vSetNinit().
virtual void ZombiePoolInterface::setNumAllVoxels (unsigned int numVoxels) pure virtual
Assign number of voxels (size of pools_ vector)
Implemented in Ksolve, and Gsolve.
Referenced by setCompartment().
virtual void ZombiePoolInterface::setNumPools (unsigned int num) pure virtual
Specifies number of pools (species) handled by system.
Implemented in Ksolve, and Gsolve.
Referenced by Stoich::resizeArrays().
virtual void ZombiePoolInterface::setStoich (Id stoich) pure virtual
Informs the ZPI about the stoich, used during subsequent computations. Called to wrap up the model building. The Stoich does this call after it has set up its own path.
Implemented in Ksolve, and Gsolve.
Referenced by Stoich::setElist().
void ZombiePoolInterface::setupCrossSolverReacs (const map< Id, vector< Id > > & xr, Id otherStoich)
Sets up cross-solver reactions.
This function builds cross-solver reaction calculations. For the specified pair of stoichs (this->stoich_, otherStoich) it identifies interacting molecules, finds where the junctions are, sets up the info to build the data transfer vector, and sets up the transfer itself.
This sets up the volume scaling from cross reac terms
References assignProxyPools(), compartment_, Eref::data(), Shell::doAddMsg(), Id::eref(), Field< A >::get(), ChemCompt::matchMeshEntries(), setupXfer(), and stoich_.
Referenced by Stoich::buildXreacs().
void ZombiePoolInterface::setupCrossSolverReacVols (const vector< vector< Id > > & subCompts, const vector< vector< Id > > & prdCompts)
This function builds cross-solver reaction volume scaling.
References VoxelPoolsBase::backwardReacVolumeFactor(), Eref::data(), Id::eref(), VoxelPoolsBase::forwardReacVolumeFactor(), Stoich::getNumCoreRates(), getNumLocalVoxels(), Stoich::getNumRates(), matchJunctionVols(), pools(), VoxelPoolsBase::resetXreacScale(), and stoich_.
Referenced by Stoich::setElist(), and Stoich::setupCrossSolverReacVols().
void ZombiePoolInterface::setupXfer (Id myZombiePoolInterface, Id otherZombiePoolInterface, unsigned int numProxyMols, const vector< VoxelJunction > & vj)
This function sets up the information about the pool transfer for cross-compartment reactions. It consolidates the transfer into a distinct vector for each direction of the transfer between each coupled pair of ZombiePoolInterfaces. This one call sets up the information about transfer on both sides of the junction(s) between current ZombiePoolInterface and otherZombiePoolInterface.
VoxelJunction refers to a specific junction between compartments. It has the following relevant fields: first, second: VoxelIndex for the first and second compartments. firstVol, secondVol: VoxelVolume for the first and second compartments.
References VoxelPoolsBase::addProxyVoxy(), assignXferIndex(), assignXferVoxels(), compartment_, Eref::data(), Id::eref(), ChemCompt::getNumEntries(), getNumLocalVoxels(), pools(), and xfer_.
Referenced by setupCrossSolverReacs().
virtual void ZombiePoolInterface::updateRateTerms (unsigned int index = ~0U) pure virtual
Informs the solver that the rate terms or volumes have changed and that the parameters must be updated. The index specifies which rateTerm to change, and if it is ~0U it means update all of them.
Implemented in Ksolve, and Gsolve.
Referenced by Stoich::setElist(), Stoich::setEnzK1(), Stoich::setEnzK2(), Stoich::setEnzK3(), Stoich::setMMenzKcat(), Stoich::setMMenzKm(), Stoich::setReacKb(), and Stoich::setReacKf().
virtual double ZombiePoolInterface::volume (unsigned int i) const pure virtual
Return volume of voxel i.
Implemented in Ksolve, and Gsolve.
Referenced by matchJunctionVols().
void ZombiePoolInterface::xComptIn (const Eref & e, Id srcZombiePoolInterface, vector< double > values)
References xfer_.
Referenced by Gsolve::initCinfo(), and Ksolve::initCinfo().
Member Data Documentation
Id ZombiePoolInterface::compartment_ protected
Id of Chem compartment used to figure out volumes of voxels.
Referenced by Gsolve::getCompartment(), getCompartment(), matchJunctionVols(), Ksolve::print(), Gsolve::setCompartment(), setCompartment(), setupCrossSolverReacs(), and setupXfer().
bool ZombiePoolInterface::isBuilt_ protected
Flag: True when solver setup has been completed.
Referenced by Ksolve::process(), Ksolve::reinit(), setCompartment(), and Ksolve::setStoich().
Id ZombiePoolInterface::stoich_ protected
Stoich is the class that sets up the reaction system and manages the stoichiometry matrix
Referenced by assignProxyPools(), Gsolve::getStoich(), Ksolve::getStoich(), Ksolve::print(), Gsolve::setStoich(), Ksolve::setStoich(), setupCrossSolverReacs(), and setupCrossSolverReacVols().
vector< XferInfo > ZombiePoolInterface::xfer_ protected
All the data transfer information from current to other solvers. xfer_[otherKsolveIndex]
Referenced by assignProxyPools(), assignXferVoxels(), Gsolve::initProc(), Ksolve::initProc(), Gsolve::initReinit(), Ksolve::initReinit(), Ksolve::print(), Gsolve::process(), Ksolve::process(), Gsolve::reinit(), Ksolve::reinit(), setupXfer(), and xComptIn().
The documentation for this class was generated from the following files:
ksolve/ZombiePoolInterface.h
ksolve/ZombiePoolInterface.cpp