MOOSE: ReacBase Class Reference
ReacBase Class Reference abstract
#include <ReacBase.h>
Public Member Functions
ReacBase ()
virtual ~ReacBase ()
void setNumKf (const Eref &e, double v)
double getNumKf (const Eref &e) const
void setNumKb (const Eref &e, double v)
double getNumKb (const Eref &e) const
void setConcKf (const Eref &e, double v)
set Kf in concentration units
double getConcKf (const Eref &e) const
get Kf in concentration units
void setConcKb (const Eref &e, double v)
set Kb in concentration units
double getConcKb (const Eref &e) const
get Kb in concentration units
unsigned int getNumSub (const Eref &e) const
Get number of substrates.
unsigned int getNumPrd (const Eref &e) const
Get number of products.
virtual void vSetNumKf (const Eref &e, double v)=0
virtual double vGetNumKf (const Eref &e) const =0
virtual void vSetNumKb (const Eref &e, double v)=0
virtual double vGetNumKb (const Eref &e) const =0
virtual void vSetConcKf (const Eref &e, double v)=0
virtual double vGetConcKf (const Eref &e) const =0
virtual void vSetConcKb (const Eref &e, double v)=0
virtual double vGetConcKb (const Eref &e) const =0
virtual void setSolver (Id solver, Id orig)
Assign solver info.
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void sub (double v)
void prd (double v)
void remesh (const Eref &e)
virtual void vProcess (const Eref &e, ProcPtr p)
virtual void vReinit (const Eref &e, ProcPtr p)
virtual void vSub (double v)
virtual void vPrd (double v)
virtual void vRemesh (const Eref &e)
Static Public Member Functions
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Protected Attributes
double concKf_
double concKb_
Constructor & Destructor Documentation
ReacBase::ReacBase ()
ReacBase::~ReacBase () virtual
Member Function Documentation
double ReacBase::getConcKb (const Eref & e) const
get Kb in concentration units
References vGetConcKb().
Referenced by initCinfo(), and zombify().
double ReacBase::getConcKf (const Eref & e) const
get Kf in concentration units
References vGetConcKf().
Referenced by initCinfo(), and zombify().
double ReacBase::getNumKb (const Eref & e) const
References vGetNumKb().
Referenced by initCinfo().
double ReacBase::getNumKf (const Eref & e) const
References vGetNumKf().
Referenced by initCinfo().
unsigned int ReacBase::getNumPrd (const Eref & e) const
Get number of products.
References Eref::element(), and Element::getMsgAndFunc().
Referenced by initCinfo().
unsigned int ReacBase::getNumSub (const Eref & e) const
Get number of substrates.
References Eref::element(), and Element::getMsgAndFunc().
Referenced by initCinfo().
const Cinfo * ReacBase::initCinfo () static
References getConcKb(), getConcKf(), getNumKb(), getNumKf(), getNumPrd(), getNumSub(), Neutral::initCinfo(), prd(), process(), reinit(), setConcKb(), setConcKf(), setNumKb(), setNumKf(), and sub().
Referenced by findParentComptOfReac(), ZombieReac::initCinfo(), Reac::initCinfo(), and storeReacMsgs().
void ReacBase::prd (double v)
References vPrd().
Referenced by initCinfo(), and ZombieReac::setSolver().
void ReacBase::process (const Eref & e, ProcPtr p)
References vProcess().
Referenced by initCinfo().
void ReacBase::reinit (const Eref & e, ProcPtr p)
References vReinit().
Referenced by initCinfo().
void ReacBase::remesh (const Eref & e)
References vRemesh().
void ReacBase::setConcKb (const Eref & e, double v)
set Kb in concentration units
References vSetConcKb().
Referenced by initCinfo(), and zombify().
void ReacBase::setConcKf (const Eref & e, double v)
set Kf in concentration units
References vSetConcKf().
Referenced by initCinfo(), and zombify().
void ReacBase::setNumKb (const Eref & e, double v)
References vSetNumKb().
Referenced by initCinfo().
void ReacBase::setNumKf (const Eref & e, double v)
References vSetNumKf().
Referenced by initCinfo().
void ReacBase::setSolver (Id solver, Id orig) virtual
Assign solver info.
Reimplemented in ZombieReac.
Referenced by zombify().
void ReacBase::sub (double v)
References vSub().
Referenced by initCinfo(), and ZombieReac::setSolver().
virtual double ReacBase::vGetConcKb (const Eref & e) const pure virtual
Implemented in Reac, and ZombieReac.
Referenced by getConcKb().
virtual double ReacBase::vGetConcKf (const Eref & e) const pure virtual
Implemented in Reac, and ZombieReac.
Referenced by getConcKf().
virtual double ReacBase::vGetNumKb (const Eref & e) const pure virtual
Implemented in Reac, and ZombieReac.
Referenced by getNumKb().
virtual double ReacBase::vGetNumKf (const Eref & e) const pure virtual
Implemented in Reac, and ZombieReac.
Referenced by getNumKf().
void ReacBase::vPrd (double v) virtual
Reimplemented in Reac.
Referenced by prd().
void ReacBase::vProcess (const Eref & e, ProcPtr p) virtual
Reimplemented in Reac.
Referenced by process().
void ReacBase::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented in Reac.
Referenced by reinit().
void ReacBase::vRemesh (const Eref & e) virtual
Reimplemented in Reac.
Referenced by remesh().
virtual void ReacBase::vSetConcKb (const Eref & e, double v) pure virtual
Implemented in Reac, and ZombieReac.
Referenced by setConcKb().
virtual void ReacBase::vSetConcKf (const Eref & e, double v) pure virtual
Implemented in Reac, and ZombieReac.
Referenced by setConcKf().
virtual void ReacBase::vSetNumKb (const Eref & e, double v) pure virtual
Implemented in Reac, and ZombieReac.
Referenced by setNumKb().
virtual void ReacBase::vSetNumKf (const Eref & e, double v) pure virtual
Implemented in Reac, and ZombieReac.
Referenced by setNumKf().
void ReacBase::vSub (double v) virtual
Reimplemented in Reac.
Referenced by sub().
void ReacBase::zombify (Element * original, const Cinfo * zClass, Id solver) static
Zombification functions.
References Element::cinfo(), Eref::data(), getConcKb(), getConcKf(), Element::id(), Element::localDataStart(), Element::numLocalData(), setConcKb(), setConcKf(), setSolver(), and Element::zombieSwap().
Referenced by Stoich::unZombifyModel(), and Stoich::zombifyModel().
Member Data Documentation
double ReacBase::concKb_ protected
Referenced by ZombieReac::vGetConcKb(), Reac::vGetConcKb(), ZombieReac::vGetNumKb(), Reac::vGetNumKb(), Reac::vReinit(), Reac::vRemesh(), ZombieReac::vSetConcKb(), Reac::vSetConcKb(), Reac::vSetNumKb(), and ZombieReac::vSetNumKb().
double ReacBase::concKf_ protected
Referenced by ZombieReac::vGetConcKf(), Reac::vGetConcKf(), ZombieReac::vGetNumKf(), Reac::vGetNumKf(), Reac::vReinit(), Reac::vRemesh(), ZombieReac::vSetConcKf(), Reac::vSetConcKf(), Reac::vSetNumKf(), and ZombieReac::vSetNumKf().
The documentation for this class was generated from the following files:
kinetics/ReacBase.h
kinetics/ReacBase.cpp