MOOSE: ChanCommon Class Reference
ChanCommon Class Reference
#include <ChanCommon.h>
Public Member Functions
ChanCommon ()
~ChanCommon ()
void vSetGbar (const Eref &e, double Gbar)
double vGetGbar (const Eref &e) const
void vSetEk (const Eref &e, double Ek)
double vGetEk (const Eref &e) const
void vSetGk (const Eref &e, double Gk)
double vGetGk (const Eref &e) const
void vSetIk (const Eref &e, double Ic)
double vGetIk (const Eref &e) const
void vHandleVm (double Vm)
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double getVm () const
Utility function to access Vm.
double getGbar () const
Utility function to acces Gbar.
Public Member Functions inherited from ChanBase
ChanBase ()
~ChanBase ()
void setGbar (const Eref &e, double Gbar)
double getGbar (const Eref &e) const
void setEk (const Eref &e, double Ek)
double getEk (const Eref &e) const
void setGk (const Eref &e, double Gk)
double getGk (const Eref &e) const
void setIk (const Eref &e, double Ic)
double getIk (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
virtual void vProcess (const Eref &e, const ProcPtr info)=0
virtual void vReinit (const Eref &e, const ProcPtr info)=0
Static Public Member Functions
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo1< double > * permeability ()
static SrcFinfo2< double,
double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Protected Attributes
double Vm_
Vm_ is input variable from compartment, used for most rates.
Detailed Description
The ChanCommon.g handles the data fields for all ion channel classes in MOOSE, when they are using regular ee calculations rather than being zombified by the solver.
Constructor & Destructor Documentation
ChanCommon::ChanCommon ()
ChanCommon::~ChanCommon ()
Member Function Documentation
double ChanCommon::getGbar () const
Utility function to acces Gbar.
Referenced by SynChan::normalizeGbar().
double ChanCommon::getVm () const
Utility function to access Vm.
References Vm_.
static const Cinfo* ChanCommon::initCinfo () static
Specify the Class Info static variable for initialization.
void ChanCommon::sendProcessMsgs (const Eref & e, const ProcPtr info)
This function sends out the messages expected of a channel, after process. Used as a utility by various derived classes.
References ChanBase::channelOut(), ChanBase::IkOut(), and ChanBase::permeability().
Referenced by MgBlock::vProcess(), SynChan::vProcess(), Leakage::vProcess(), NMDAChan::vProcess(), MarkovChannel::vProcess(), HHChannel2D::vProcess(), and HHChannel::vProcess().
void ChanCommon::sendReinitMsgs (const Eref & e, const ProcPtr info)
References ChanBase::channelOut(), and ChanBase::permeability().
Referenced by SynChan::vReinit(), MgBlock::vReinit(), Leakage::vReinit(), NMDAChan::vReinit(), MarkovChannel::vReinit(), HHChannel2D::vReinit(), and HHChannel::vReinit().
void ChanCommon::updateIk ()
Utility function for a common computation using local variables
References Vm_.
Referenced by MgBlock::vProcess(), SynChan::vProcess(), NMDAChan::vProcess(), MarkovChannel::vProcess(), HHChannel2D::vProcess(), HHChannel::vProcess(), HHChannel2D::vReinit(), and HHChannel::vReinit().
double ChanCommon::vGetEk (const Eref & e) const virtual
Implements ChanBase.
double ChanCommon::vGetGbar (const Eref & e) const virtual
Implements ChanBase.
Referenced by HHChannel::vProcess(), and HHChannel::vReinit().
double ChanCommon::vGetGk (const Eref & e) const virtual
Implements ChanBase.
double ChanCommon::vGetIk (const Eref & e) const virtual
Implements ChanBase.
void ChanCommon::vHandleVm (double Vm) virtual
Assign the local Vm_ to the incoming Vm from the compartment
Implements ChanBase.
References Vm_.
void ChanCommon::vSetEk (const Eref & e, double Ek) virtual
Implements ChanBase.
void ChanCommon::vSetGbar (const Eref & e, double Gbar) virtual
Implements ChanBase.
Reimplemented in SynChan.
Referenced by SynChan::vSetGbar().
void ChanCommon::vSetGk (const Eref & e, double Gk) virtual
Implements ChanBase.
Referenced by HHChannel::vProcess(), and HHChannel::vReinit().
void ChanCommon::vSetIk (const Eref & e, double Ic) virtual
Ik is read-only for MOOSE, but we provide the set func for derived classes to update it.
Implements ChanBase.
Member Data Documentation
double ChanCommon::Vm_ protected
Vm_ is input variable from compartment, used for most rates.
Referenced by MarkovChannel::getVm(), getVm(), MarkovChannel::setVm(), updateIk(), vHandleVm(), MgBlock::vProcess(), NMDAChan::vProcess(), HHChannel::vProcess(), and HHChannel::vReinit().
The documentation for this class was generated from the following files:
biophysics/ChanCommon.h
biophysics/ChanCommon.cpp