MOOSE: TimeTable Class Reference
TimeTable Class Reference
#include <TimeTable.h>
Public Member Functions
TimeTable ()
~TimeTable ()
void setFilename (string filename)
string getFilename () const
void setMethod (int method)
int getMethod () const
double getState () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from TableBase
TableBase ()
vector< double > getVec () const
void setVec (vector< double > val)
double getOutputValue () const
void setOutputValue (double val)
double getY (unsigned int index) const
void linearTransform (double scale, double offset)
void xplot (string file, string plotname)
void plainPlot (string file)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
void loadCSV (string fname, int startLine, int colNum, char separator)
void compareXplot (string fname, string plotname, string op)
void compareVec (vector< double > other, string op)
void clearVec ()
double * lookupVec (unsigned int index)
void setVecSize (unsigned int num)
unsigned int getVecSize () const
double interpolate (double x, double xmin, double xmax) const
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from TableBase
static const Cinfo * initCinfo ()
Additional Inherited Members
Protected Member Functions inherited from TableBase
vector< double > & vec ()
Constructor & Destructor Documentation
TimeTable::TimeTable ()
TimeTable::~TimeTable ()
Member Function Documentation
string TimeTable::getFilename () const
Referenced by initCinfo().
int TimeTable::getMethod () const
Referenced by initCinfo().
double TimeTable::getState () const
Referenced by initCinfo().
const Cinfo * TimeTable::initCinfo () static
References getFilename(), getMethod(), getState(), TableBase::initCinfo(), process(), reinit(), setFilename(), and setMethod().
void TimeTable::process (const Eref & e, ProcPtr p)
The process function called by scheduler on every tick
References ProcInfo::currTime, and TableBase::vec().
Referenced by initCinfo().
void TimeTable::reinit (const Eref & e, ProcPtr p)
The reinit function called by scheduler for the reset
Referenced by initCinfo().
void TimeTable::setFilename (string filename)
References TableBase::vec().
Referenced by initCinfo().
void TimeTable::setMethod (int method)
Referenced by initCinfo().
The documentation for this class was generated from the following files:
builtins/TimeTable.h
builtins/TimeTable.cpp