MOOSE: SpineMesh Class Reference
SpineMesh Class Reference
#include <SpineMesh.h>
Public Member Functions
SpineMesh ()
SpineMesh (const SpineMesh &other)
~SpineMesh ()
void updateCoords ()
Id getCell () const
vector< unsigned int > getParentVoxel () const
Return Id of parent cell.
vector< unsigned int > getNeuronVoxel () const
vector< Id > getElecComptMap () const
unsigned int getMeshType (unsigned int fid) const
Virtual function to return MeshType of specified entry.
unsigned int getMeshDimensions (unsigned int fid) const
Virtual function to return dimensions of specified entry.
double getMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry.
vector< double > getCoordinates (unsigned int fid) const
Virtual function to return coords of mesh Entry.
vector< double > getDiffusionArea (unsigned int fid) const
Virtual function to return diffusion X-section area.
vector< double > getDiffusionScaling (unsigned int fid) const
Virtual function to return scale factor for diffusion. 1 here.
double extendedMeshEntryVolume (unsigned int fid) const
Vol of all mesh Entries including abutting diff-coupled voxels.
unsigned int innerGetNumEntries () const
void innerSetNumEntries (unsigned int n)
Inherited virtual func.
unsigned int innerGetDimensions () const
Returns # of dimensions, always 3 here. Inherited pure virt func.
double vGetEntireVolume () const
Inherited virtual func.
bool vSetVolumeNotRates (double volume)
Inherited virtual func.
void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
Virtual func to make a mesh with specified Volume and numEntries.
void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void handleSpineList (const Eref &e, Id cell, vector< Id > shaft, vector< Id > head, vector< unsigned int > parentVoxel)
void transmitChange (const Eref &e)
void buildStencil ()
void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchNeuroMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchCubeMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
void matchSpineMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
double nearest (double x, double y, double z, unsigned int &index) const
void indexToSpace (unsigned int index, double &x, double &y, double &z) const
const vector< double > & vGetVoxelVolume () const
Virtual func so that derived classes can pass voxel volume back.
const vector< double > & vGetVoxelMidpoint () const
Virtual func so that derived classes can return voxel midpoint.
const vector< double > & getVoxelArea () const
const vector< double > & getVoxelLength () const
const vector< SpineEntry > & spines () const
Public Member Functions inherited from MeshCompt
MeshCompt ()
~MeshCompt ()
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
void innerResetStencil ()
virtual func implemented here.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
vector< double > innerGetStencilRate (unsigned int row) const
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void setStencilSize (unsigned int numRows, unsigned int numCols)
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
Public Member Functions inherited from ChemCompt
ChemCompt ()
virtual ~ChemCompt ()
double getEntireVolume (const Eref &e) const
void setEntireVolume (const Eref &e, double volume)
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
unsigned int getDimensions () const
void setMethod (string method)
string getMethod () const
vector< double > getStencilRate (unsigned int row) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
void setVolumeNotRates (double volume)
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void resetStencil ()
unsigned int getNumEntries () const
void setNumEntries (unsigned int num)
MeshEntry * lookupEntry (unsigned int index)
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static SrcFinfo1< vector
< double > > * voxelVolOut ()
static const Cinfo * initCinfo ()
Detailed Description
The SpineMesh sets up the diffusion geometries for dendritic spines. It is filled by a message from a NeuroMesh that contains information about the matching voxel on the NeuroMesh, and the compartment Ids for the spine shaft and head. The SpineMesh can further generate a PSD mesh with the info for the PSD geometries. This assumes that the each spine is a single voxel: single diffusive compartment, well-stirred. The shaft is treated as zero volume diffusion barrier to the dendrite. The PSD is a separate compt with its own diffusion coupling to the spine head.
Constructor & Destructor Documentation
SpineMesh::SpineMesh ()
SpineMesh::SpineMesh (const SpineMesh & other)
SpineMesh::~SpineMesh ()
Member Function Documentation
void SpineMesh::buildStencil ()
References MeshCompt::innerResetStencil(), and MeshCompt::setStencilSize().
Referenced by updateCoords().
double SpineMesh::extendedMeshEntryVolume (unsigned int fid) const virtual
Vol of all mesh Entries including abutting diff-coupled voxels.
Virtual function to return volume of mesh Entry, including for diffusively coupled voxels from other solvers.
Reimplemented from MeshCompt.
References MeshCompt::extendedMeshEntryVolume(), and getMeshEntryVolume().
Id SpineMesh::getCell () const
Referenced by matchNeuroMeshEntries(), and PsdMesh::matchSpineMeshEntries().
vector< double > SpineMesh::getCoordinates (unsigned int fid) const virtual
Virtual function to return coords of mesh Entry.
Virtual function to return coords of mesh Entry. For SpineMesh, coords are x1y1z1 x2y2z2 x3y3z3 r0 r1
Implements ChemCompt.
vector< double > SpineMesh::getDiffusionArea (unsigned int fid) const virtual
Virtual function to return diffusion X-section area.
Virtual function to return diffusion X-section area for each neighbor.
Implements ChemCompt.
vector< double > SpineMesh::getDiffusionScaling (unsigned int fid) const virtual
Virtual function to return scale factor for diffusion. 1 here.
Virtual function to return scale factor for diffusion. I think all dendite tips need to return just one entry of 1.
Implements ChemCompt.
vector< Id > SpineMesh::getElecComptMap () const
Returns vector of Ids of electrical compts that map to respective voxels in SpineMesh
Referenced by initCinfo().
unsigned int SpineMesh::getMeshDimensions (unsigned int fid) const virtual
Virtual function to return dimensions of specified entry.
Implements ChemCompt.
double SpineMesh::getMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry.
Implements ChemCompt.
Referenced by extendedMeshEntryVolume(), handleSpineList(), and PsdMesh::matchSpineMeshEntries().
unsigned int SpineMesh::getMeshType (unsigned int fid) const virtual
Virtual function to return MeshType of specified entry.
Implements ChemCompt.
References CYL.
vector< unsigned int > SpineMesh::getNeuronVoxel () const
Returns index of voxel on NeuroMesh to which this spine is connected.
Referenced by initCinfo().
vector< unsigned int > SpineMesh::getParentVoxel () const virtual
Return Id of parent cell.
This function returns the diffusively connected parent voxel within the current (spine) mesh. Since each spine is treated as an independed voxel, there is no such voxel, so we return -1U for each spine. Note that there is a separate function that returns the parentVoxel referred to the NeuroMesh that this spine sits on.
Implements MeshCompt.
Referenced by initCinfo().
const vector< double > & SpineMesh::getVoxelArea () const virtual
Implements MeshCompt.
const vector< double > & SpineMesh::getVoxelLength () const virtual
Implements MeshCompt.
void SpineMesh::handleSpineList (const Eref & e, Id cell, vector< Id > shaft, vector< Id > head, vector< unsigned int > parentVoxel)
References getMeshEntryVolume(), Eref::id(), ChemCompt::lookupEntry(), MeshEntry::triggerRemesh(), updateCoords(), and Id::value().
Referenced by initCinfo().
void SpineMesh::indexToSpace (unsigned int index, double & x, double & y, double & z) const virtual
Converts specified index to xyz coords of middle of voxel Values out of range return original xyz
Implements ChemCompt.
References innerGetNumEntries().
const Cinfo * SpineMesh::initCinfo () static
References getElecComptMap(), getNeuronVoxel(), getParentVoxel(), handleSpineList(), and ChemCompt::initCinfo().
void SpineMesh::innerBuildDefaultMesh (const Eref & e, double volume, unsigned int numEntries) virtual
Virtual func to make a mesh with specified Volume and numEntries.
Not allowed.
Implements ChemCompt.
unsigned int SpineMesh::innerGetDimensions () const virtual
Returns # of dimensions, always 3 here. Inherited pure virt func.
Implements ChemCompt.
unsigned int SpineMesh::innerGetNumEntries () const virtual
Inherited virtual func. Returns number of MeshEntry in array
Implements ChemCompt.
Referenced by indexToSpace().
void SpineMesh::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) virtual
Implements ChemCompt.
void SpineMesh::innerSetNumEntries (unsigned int n) virtual
Inherited virtual func.
Inherited virtual func. Assigns number of MeshEntries. Doesn't do anything, we have to set spine # from geometry.
Implements ChemCompt.
void SpineMesh::matchCubeMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
References SpineEntry::matchCubeMeshEntriesToHead().
Referenced by matchMeshEntries().
void SpineMesh::matchMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const virtual
Returns the meshIndices (NOT spatial indices) of all adjacent mesh entry pairs on ether side of the (self, other) junction. meshIndices are the indices that look up entries in the vector of pools. spatialIndices are (iz * ny + iy) * nx + ix, that is, a linear conversion of cartesian spatial indices. So, for two touching cubes, the return vector is the paired meshIndices on either side of the plane of contact. If one mesh has a finer mesh than the other, or if there are more than one contact points from self to other (for example, at a corner), then we just have multiple pairs using the same meshIndex of the repeated voxel.
Implements ChemCompt.
References ChemCompt::flipRet(), matchCubeMeshEntries(), matchNeuroMeshEntries(), and PsdMesh::matchSpineMeshEntries().
void SpineMesh::matchNeuroMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
References getCell(), NeuroMesh::getCell(), and NeuroMesh::getMeshEntryVolume().
Referenced by matchMeshEntries(), and NeuroMesh::matchMeshEntries().
void SpineMesh::matchSpineMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const
double SpineMesh::nearest (double x, double y, double z, unsigned int & index) const virtual
This works a little different from other subclass versions of the function. It finds the index of the mesh entry whose centre is closest to the specified coords, and returns the distance to the centre. Doesn't worry about whether this distance is inside or outside cell.
Implements ChemCompt.
References a, d, Vec::distance(), and SpineEntry::mid().
const vector< SpineEntry > & SpineMesh::spines () const
void SpineMesh::transmitChange (const Eref & e)
void SpineMesh::updateCoords ()
Recomputes all local coordinate and meshing data following a change in any of the coord parameters
This assumes that lambda is the quantity to preserve, over numEntries. So when the compartment changes volume, numEntries changes too. Assumes that the soma node is at index 0.
References buildStencil().
Referenced by handleSpineList().
double SpineMesh::vGetEntireVolume () const virtual
Inherited virtual func.
Implements ChemCompt.
Referenced by vSetVolumeNotRates().
const vector< double > & SpineMesh::vGetVoxelMidpoint () const virtual
Virtual func so that derived classes can return voxel midpoint.
Implements ChemCompt.
const vector< double > & SpineMesh::vGetVoxelVolume () const virtual
Virtual func so that derived classes can pass voxel volume back.
Implements ChemCompt.
bool SpineMesh::vSetVolumeNotRates (double volume) virtual
Inherited virtual func.
Implements ChemCompt.
References vGetEntireVolume().
The documentation for this class was generated from the following files:
mesh/SpineMesh.h
mesh/SpineMesh.cpp