MOOSE: CplxEnzBase Class Reference
CplxEnzBase Class Reference abstract
#include <CplxEnzBase.h>
Public Member Functions
CplxEnzBase ()
virtual ~CplxEnzBase ()
void setK1 (const Eref &e, double v)
double getK1 (const Eref &e) const
void setK2 (const Eref &e, double v)
double getK2 (const Eref &e) const
void setRatio (const Eref &e, double v)
double getRatio (const Eref &e) const
void setConcK1 (const Eref &e, double v)
double getConcK1 (const Eref &e) const
virtual void vSetK1 (const Eref &e, double v)=0
virtual double vGetK1 (const Eref &e) const =0
virtual void vSetK2 (const Eref &e, double v)=0
virtual double vGetK2 (const Eref &e) const =0
virtual void vSetRatio (const Eref &e, double v)=0
virtual double vGetRatio (const Eref &e) const =0
virtual void vSetConcK1 (const Eref &e, double v)=0
virtual double vGetConcK1 (const Eref &e) const =0
void cplx (double n)
virtual void vCplx (double n)
Public Member Functions inherited from EnzBase
EnzBase ()
virtual ~EnzBase ()
void setKm (const Eref &e, double v)
double getKm (const Eref &e) const
void setNumKm (const Eref &e, double v)
double getNumKm (const Eref &e) const
void setKcat (const Eref &e, double v)
double getKcat (const Eref &e) const
unsigned int getNumSub (const Eref &e) const
virtual void vSetKm (const Eref &e, double v)=0
virtual double vGetKm (const Eref &e) const =0
virtual void vSetNumKm (const Eref &e, double v)=0
virtual double vGetNumKm (const Eref &e) const =0
virtual void vSetKcat (const Eref &e, double v)=0
virtual double vGetKcat (const Eref &e) const =0
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void sub (double n)
void enz (double n)
void prd (double n)
void remesh (const Eref &e)
virtual void vProcess (const Eref &e, ProcPtr p)
virtual void vReinit (const Eref &e, ProcPtr p)
virtual void vSub (double n)
virtual void vEnz (double n)
virtual void vRemesh (const Eref &e)
virtual void setSolver (Id solver, Id orig)
Assign solver info.
Static Public Member Functions
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from EnzBase
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Detailed Description
This class is for mass-action enzymes, in which there is an explict pool for the enzyme-substrate complex. It models the reaction E + S <===> E.S -—> E + P
Constructor & Destructor Documentation
CplxEnzBase::CplxEnzBase ()
CplxEnzBase::~CplxEnzBase () virtual
Member Function Documentation
void CplxEnzBase::cplx (double n)
References vCplx().
Referenced by initCinfo().
double CplxEnzBase::getConcK1 (const Eref & e) const
References vGetConcK1().
Referenced by initCinfo(), and zombify().
double CplxEnzBase::getK1 (const Eref & e) const
References vGetK1().
Referenced by initCinfo().
double CplxEnzBase::getK2 (const Eref & e) const
References vGetK2().
Referenced by initCinfo(), ZombieEnz::vGetKm(), ZombieEnz::vGetRatio(), ZombieEnz::vSetKm(), ZombieEnz::vSetNumKm(), ZombieEnz::vSetRatio(), and zombify().
double CplxEnzBase::getRatio (const Eref & e) const
References vGetRatio().
Referenced by initCinfo().
const Cinfo * CplxEnzBase::initCinfo () static
References cplx(), EnzBase::enz(), enzDest(), getConcK1(), getK1(), getK2(), EnzBase::getKcat(), getRatio(), EnzBase::initCinfo(), setConcK1(), setK1(), setK2(), EnzBase::setKcat(), and setRatio().
Referenced by getEnzCplx(), Enz::initCinfo(), ZombieEnz::initCinfo(), and storeCplxEnzMsgs().
void CplxEnzBase::setConcK1 (const Eref & e, double v)
References vSetConcK1().
Referenced by initCinfo(), ZombieEnz::vSetRatio(), and zombify().
void CplxEnzBase::setK1 (const Eref & e, double v)
References vSetK1().
Referenced by initCinfo().
void CplxEnzBase::setK2 (const Eref & e, double v)
References vSetK2().
Referenced by initCinfo(), and zombify().
void CplxEnzBase::setRatio (const Eref & e, double v)
References vSetRatio().
Referenced by initCinfo().
void CplxEnzBase::vCplx (double n) virtual
Reimplemented in Enz.
Referenced by cplx().
virtual double CplxEnzBase::vGetConcK1 (const Eref & e) const pure virtual
Implemented in Enz, and ZombieEnz.
Referenced by getConcK1().
virtual double CplxEnzBase::vGetK1 (const Eref & e) const pure virtual
Implemented in Enz, and ZombieEnz.
Referenced by getK1().
virtual double CplxEnzBase::vGetK2 (const Eref & e) const pure virtual
Implemented in Enz, and ZombieEnz.
Referenced by getK2().
virtual double CplxEnzBase::vGetRatio (const Eref & e) const pure virtual
Implemented in Enz, and ZombieEnz.
Referenced by getRatio().
virtual void CplxEnzBase::vSetConcK1 (const Eref & e, double v) pure virtual
Implemented in Enz, and ZombieEnz.
Referenced by setConcK1().
virtual void CplxEnzBase::vSetK1 (const Eref & e, double v) pure virtual
Implemented in Enz, and ZombieEnz.
Referenced by setK1().
virtual void CplxEnzBase::vSetK2 (const Eref & e, double v) pure virtual
Implemented in Enz, and ZombieEnz.
Referenced by setK2().
virtual void CplxEnzBase::vSetRatio (const Eref & e, double v) pure virtual
Implemented in Enz, and ZombieEnz.
Referenced by setRatio().
void CplxEnzBase::zombify (Element * orig, const Cinfo * zClass, Id solver) static
This function helps the conversion between CplxEnz subclasses, these are the ones that have an explicit enzyme-substrate complex molecule. Note that I use the ConcK1 terms because those are independent of the volume decomposition. K2 and kcat (ie., k3) only have time units.
References Element::cinfo(), Eref::data(), getConcK1(), getK2(), EnzBase::getKcat(), Element::id(), Element::localDataStart(), Element::numLocalData(), setConcK1(), setK2(), EnzBase::setKcat(), EnzBase::setSolver(), and Element::zombieSwap().
Referenced by Stoich::unZombifyModel(), and Stoich::zombifyModel().
The documentation for this class was generated from the following files:
kinetics/CplxEnzBase.h
kinetics/CplxEnzBase.cpp