MOOSE: HopFunc6< A1, A2, A3, A4, A5, A6 > Class Template Reference
HopFunc6< A1, A2, A3, A4, A5, A6 > Class Template Reference
#include <HopFunc.h>
Public Member Functions
HopFunc6 (HopIndex hopIndex)
void op (const Eref &e, A1 arg1, A2 arg2, A3 arg3, A4 arg4, A5 arg5, A6 arg6) const
Public Member Functions inherited from OpFunc6Base< A1, A2, A3, A4, A5, A6 >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
virtual ~OpFunc ()
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Constructor & Destructor Documentation
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > HopFunc6< A1, A2, A3, A4, A5, A6 >::HopFunc6 (HopIndex hopIndex) inline
Member Function Documentation
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > void HopFunc6< A1, A2, A3, A4, A5, A6 >::op (const Eref & e, A1 arg1, A2 arg2, A3 arg3, A4 arg4, A5 arg5, A6 arg6) const inline virtual
Implements OpFunc6Base< A1, A2, A3, A4, A5, A6 >.
References addToBuf(), dispatchBuffers(), and Conv< T >::val2buf().
The documentation for this class was generated from the following file:
basecode/HopFunc.h