MOOSE: ZombieEnz Class Reference
ZombieEnz Class Reference
#include <ZombieEnz.h>
Public Member Functions
ZombieEnz ()
~ZombieEnz ()
void vSetK1 (const Eref &e, double v)
double vGetK1 (const Eref &e) const
void vSetK2 (const Eref &e, double v)
double vGetK2 (const Eref &e) const
void vSetKcat (const Eref &e, double v)
double vGetKcat (const Eref &e) const
void vSetKm (const Eref &e, double v)
double vGetKm (const Eref &e) const
void vSetNumKm (const Eref &e, double v)
double vGetNumKm (const Eref &e) const
void vSetRatio (const Eref &e, double v)
double vGetRatio (const Eref &e) const
void vSetConcK1 (const Eref &e, double v)
double vGetConcK1 (const Eref &e) const
void setSolver (Id solver, Id orig)
Assign solver info.
Public Member Functions inherited from CplxEnzBase
CplxEnzBase ()
virtual ~CplxEnzBase ()
void setK1 (const Eref &e, double v)
double getK1 (const Eref &e) const
void setK2 (const Eref &e, double v)
double getK2 (const Eref &e) const
void setRatio (const Eref &e, double v)
double getRatio (const Eref &e) const
void setConcK1 (const Eref &e, double v)
double getConcK1 (const Eref &e) const
void cplx (double n)
virtual void vCplx (double n)
Public Member Functions inherited from EnzBase
EnzBase ()
virtual ~EnzBase ()
void setKm (const Eref &e, double v)
double getKm (const Eref &e) const
void setNumKm (const Eref &e, double v)
double getNumKm (const Eref &e) const
void setKcat (const Eref &e, double v)
double getKcat (const Eref &e) const
unsigned int getNumSub (const Eref &e) const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void sub (double n)
void enz (double n)
void prd (double n)
void remesh (const Eref &e)
virtual void vProcess (const Eref &e, ProcPtr p)
virtual void vReinit (const Eref &e, ProcPtr p)
virtual void vSub (double n)
virtual void vEnz (double n)
virtual void vRemesh (const Eref &e)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from CplxEnzBase
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from EnzBase
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
ZombieEnz::ZombieEnz ()
ZombieEnz::~ZombieEnz ()
Member Function Documentation
const Cinfo * ZombieEnz::initCinfo () static
References CplxEnzBase::initCinfo().
void ZombieEnz::setSolver (Id solver, Id orig) virtual
Assign solver info.
Reimplemented from EnzBase.
References Element::cinfo(), Eref::data(), Id::element(), Id::eref(), Cinfo::find(), Cinfo::findFinfo(), Element::getNeighbors(), Stoich::installEnzyme(), and Cinfo::isA().
double ZombieEnz::vGetConcK1 (const Eref & e) const virtual
Implements CplxEnzBase.
double ZombieEnz::vGetK1 (const Eref & e) const virtual
Implements CplxEnzBase.
References convertConcToNumRateUsingMesh().
double ZombieEnz::vGetK2 (const Eref & e) const virtual
Implements CplxEnzBase.
References Stoich::getEnzK2().
Referenced by vGetNumKm().
double ZombieEnz::vGetKcat (const Eref & e) const virtual
Implements EnzBase.
References Stoich::getEnzK3().
Referenced by vGetNumKm().
double ZombieEnz::vGetKm (const Eref & e) const virtual
Implements EnzBase.
References CplxEnzBase::getK2(), and EnzBase::getKcat().
double ZombieEnz::vGetNumKm (const Eref & e) const virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh(), vGetK2(), and vGetKcat().
double ZombieEnz::vGetRatio (const Eref & e) const virtual
Implements CplxEnzBase.
References CplxEnzBase::getK2(), and EnzBase::getKcat().
void ZombieEnz::vSetConcK1 (const Eref & e, double v) virtual
Implements CplxEnzBase.
References Stoich::setEnzK1().
void ZombieEnz::vSetK1 (const Eref & e, double v) virtual
Implements CplxEnzBase.
References convertConcToNumRateUsingMesh(), and Stoich::setEnzK1().
void ZombieEnz::vSetK2 (const Eref & e, double v) virtual
Implements CplxEnzBase.
References Stoich::setEnzK2().
void ZombieEnz::vSetKcat (const Eref & e, double v) virtual
Implements EnzBase.
References Stoich::setEnzK3().
void ZombieEnz::vSetKm (const Eref & e, double v) virtual
Implements EnzBase.
References CplxEnzBase::getK2(), EnzBase::getKcat(), and Stoich::setEnzK1().
void ZombieEnz::vSetNumKm (const Eref & e, double v) virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh(), CplxEnzBase::getK2(), EnzBase::getKcat(), and Stoich::setEnzK1().
void ZombieEnz::vSetRatio (const Eref & e, double v) virtual
Implements CplxEnzBase.
References CplxEnzBase::getK2(), EnzBase::getKcat(), EnzBase::getKm(), CplxEnzBase::setConcK1(), and Stoich::setEnzK2().
The documentation for this class was generated from the following files:
ksolve/ZombieEnz.h
ksolve/ZombieEnz.cpp