MOOSE: ZombieReac Class Reference
ZombieReac Class Reference
#include <ZombieReac.h>
Public Member Functions
ZombieReac ()
~ZombieReac ()
void vSetNumKf (const Eref &e, double v)
double vGetNumKf (const Eref &e) const
void vSetNumKb (const Eref &e, double v)
double vGetNumKb (const Eref &e) const
void vSetConcKf (const Eref &e, double v)
double vGetConcKf (const Eref &e) const
void vSetConcKb (const Eref &e, double v)
double vGetConcKb (const Eref &e) const
void setSolver (Id solver, Id orig)
Assign solver info.
Public Member Functions inherited from ReacBase
ReacBase ()
virtual ~ReacBase ()
void setNumKf (const Eref &e, double v)
double getNumKf (const Eref &e) const
void setNumKb (const Eref &e, double v)
double getNumKb (const Eref &e) const
void setConcKf (const Eref &e, double v)
set Kf in concentration units
double getConcKf (const Eref &e) const
get Kf in concentration units
void setConcKb (const Eref &e, double v)
set Kb in concentration units
double getConcKb (const Eref &e) const
get Kb in concentration units
unsigned int getNumSub (const Eref &e) const
Get number of substrates.
unsigned int getNumPrd (const Eref &e) const
Get number of products.
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void sub (double v)
void prd (double v)
void remesh (const Eref &e)
virtual void vProcess (const Eref &e, ProcPtr p)
virtual void vReinit (const Eref &e, ProcPtr p)
virtual void vSub (double v)
virtual void vPrd (double v)
virtual void vRemesh (const Eref &e)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ReacBase
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Additional Inherited Members
Protected Attributes inherited from ReacBase
double concKf_
double concKb_
Constructor & Destructor Documentation
ZombieReac::ZombieReac ()
ZombieReac::~ZombieReac ()
Member Function Documentation
const Cinfo * ZombieReac::initCinfo () static
References ReacBase::initCinfo().
void ZombieReac::setSolver (Id solver, Id orig) virtual
Assign solver info.
Reimplemented from ReacBase.
References Element::cinfo(), Eref::data(), Id::element(), Id::eref(), Element::getNeighbors(), Stoich::installReaction(), Cinfo::isA(), ReacBase::prd(), and ReacBase::sub().
double ZombieReac::vGetConcKb (const Eref & e) const virtual
Implements ReacBase.
References ReacBase::concKb_.
double ZombieReac::vGetConcKf (const Eref & e) const virtual
Implements ReacBase.
References ReacBase::concKf_.
double ZombieReac::vGetNumKb (const Eref & e) const virtual
Implements ReacBase.
References ReacBase::concKb_, and convertConcToNumRateUsingMesh().
double ZombieReac::vGetNumKf (const Eref & e) const virtual
Implements ReacBase.
References ReacBase::concKf_, and convertConcToNumRateUsingMesh().
void ZombieReac::vSetConcKb (const Eref & e, double v) virtual
Implements ReacBase.
References ReacBase::concKb_, and Stoich::setReacKb().
void ZombieReac::vSetConcKf (const Eref & e, double v) virtual
Implements ReacBase.
References ReacBase::concKf_, and Stoich::setReacKf().
void ZombieReac::vSetNumKb (const Eref & e, double v) virtual
Implements ReacBase.
References ReacBase::concKb_, convertConcToNumRateUsingMesh(), and Stoich::setReacKb().
void ZombieReac::vSetNumKf (const Eref & e, double v) virtual
Implements ReacBase.
References ReacBase::concKf_, convertConcToNumRateUsingMesh(), and Stoich::setReacKf().
The documentation for this class was generated from the following files:
ksolve/ZombieReac.h
ksolve/ZombieReac.cpp