MOOSE: FinfoWrapper Class Reference
FinfoWrapper Class Reference
#include <Finfo.h>
Public Member Functions
FinfoWrapper (const Finfo *other)
string getName () const
string docs () const
string type () const
vector< string > src () const
vector< string > dest () const
Constructor & Destructor Documentation
FinfoWrapper::FinfoWrapper (const Finfo * other) inline
Member Function Documentation
vector< string > FinfoWrapper::dest () const
Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function.
References Finfo::innerDest().
Referenced by Finfo::initCinfo(), and testFinfoFields().
string FinfoWrapper::docs () const
References Finfo::docs().
Referenced by Finfo::initCinfo(), and testFinfoFields().
string FinfoWrapper::getName () const
References Finfo::name().
Referenced by Finfo::initCinfo(), and testFinfoFields().
vector< string > FinfoWrapper::src () const
Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function.
References Finfo::innerSrc().
Referenced by Finfo::initCinfo(), and testFinfoFields().
string FinfoWrapper::type () const
References Finfo::rttiType().
Referenced by Finfo::initCinfo(), and testFinfoFields().
The documentation for this class was generated from the following files:
basecode/Finfo.h
basecode/Finfo.cpp