MOOSE: UniformRng Class Reference
UniformRng Class Reference
#include <UniformRng.h>
Public Member Functions
UniformRng ()
virtual ~UniformRng ()
double getMin () const
double getMax () const
void setMin (double min)
void setMax (double max)
virtual void vReinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from RandGenerator
RandGenerator ()
virtual ~RandGenerator ()
double getMean () const
double getVariance () const
double getSample () const
void process (const Eref &e, ProcPtr info)
void reinit (const Eref &e, ProcPtr info)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from RandGenerator
static const Cinfo * initCinfo ()
Additional Inherited Members
Protected Attributes inherited from RandGenerator
Probability * rng_
double sample_
Constructor & Destructor Documentation
UniformRng::UniformRng ()
References RandGenerator::rng_.
virtual UniformRng::~UniformRng () inline virtual
Member Function Documentation
double UniformRng::getMax () const
References Uniform::getMax(), and RandGenerator::rng_.
Referenced by initCinfo().
double UniformRng::getMin () const
References Uniform::getMin(), and RandGenerator::rng_.
Referenced by initCinfo().
const Cinfo * UniformRng::initCinfo () static
References getMax(), getMin(), RandGenerator::initCinfo(), setMax(), and setMin().
void UniformRng::setMax (double max)
References RandGenerator::rng_, and Uniform::setMax().
Referenced by initCinfo().
void UniformRng::setMin (double min)
References RandGenerator::rng_, and Uniform::setMin().
Referenced by initCinfo().
void UniformRng::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented from RandGenerator.
The documentation for this class was generated from the following files:
randnum/UniformRng.h
randnum/UniformRng.cpp