MOOSE: BufPool Class Reference
BufPool Class Reference
#include <BufPool.h>
Public Member Functions
BufPool ()
~BufPool ()
void vSetN (const Eref &e, double v)
The 'get' functions are simply inherited from Pool.
void vSetNinit (const Eref &e, double v)
void vSetConc (const Eref &e, double v)
void vSetConcInit (const Eref &e, double v)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from Pool
Pool ()
~Pool ()
void vSetN (const Eref &e, double v)
double vGetN (const Eref &e) const
void vSetNinit (const Eref &e, double v)
double vGetNinit (const Eref &e) const
void vSetDiffConst (const Eref &e, double v)
double vGetDiffConst (const Eref &e) const
void vSetMotorConst (const Eref &e, double v)
Dummy MotorConst field for most Pool subclasses.
double vGetMotorConst (const Eref &e) const
void vSetConc (const Eref &e, double v)
double vGetConc (const Eref &e) const
void vSetConcInit (const Eref &e, double v)
void vSetVolume (const Eref &e, double v)
double vGetVolume (const Eref &e) const
void vSetSpecies (const Eref &e, SpeciesId v)
SpeciesId vGetSpecies (const Eref &e) const
void vHandleMolWt (const Eref &e, double v)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vReac (double A, double B)
void increment (double val)
void decrement (double val)
Public Member Functions inherited from PoolBase
PoolBase ()
virtual ~PoolBase ()
void setN (const Eref &e, double v)
double getN (const Eref &e) const
void setNinit (const Eref &e, double v)
double getNinit (const Eref &e) const
void setDiffConst (const Eref &e, double v)
double getDiffConst (const Eref &e) const
void setMotorConst (const Eref &e, double v)
double getMotorConst (const Eref &e) const
void setConc (const Eref &e, double v)
double getConc (const Eref &e) const
void setConcInit (const Eref &e, double v)
double getConcInit (const Eref &e) const
void setVolume (const Eref &e, double v)
double getVolume (const Eref &e) const
void setSpecies (const Eref &e, SpeciesId v)
SpeciesId getSpecies (const Eref &e) const
virtual void vSetSolver (Id ksolve, Id dsolve)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void reac (double A, double B)
void handleMolWt (const Eref &e, double v)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from Pool
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from PoolBase
static void zombify (Element *original, const Cinfo *zClass, Id ksolve, Id dsolve)
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
BufPool::BufPool ()
BufPool::~BufPool ()
Member Function Documentation
const Cinfo * BufPool::initCinfo () static
References Pool::initCinfo().
Referenced by ReadKkit::buildSumTotal(), and ReadKkit::setupSlaveMsg().
void BufPool::vProcess (const Eref & e, ProcPtr p) virtual
Reimplemented from PoolBase.
References Pool::vReinit().
void BufPool::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented from PoolBase.
References Pool::vReinit().
void BufPool::vSetConc (const Eref & e, double v) virtual
Implements PoolBase.
References lookupVolumeFromMesh(), NA, and vSetN().
Referenced by vSetConcInit().
void BufPool::vSetConcInit (const Eref & e, double v) virtual
Implements PoolBase.
References vSetConc().
void BufPool::vSetN (const Eref & e, double v) virtual
The 'get' functions are simply inherited from Pool.
Implements PoolBase.
References Pool::vSetN(), and Pool::vSetNinit().
Referenced by vSetConc(), and vSetNinit().
void BufPool::vSetNinit (const Eref & e, double v) virtual
Implements PoolBase.
References vSetN().
The documentation for this class was generated from the following files:
kinetics/BufPool.h
kinetics/BufPool.cpp