MOOSE: ElementValueFinfo< T, F > Class Template Reference
ElementValueFinfo< T, F > Class Template Reference
#include <ElementValueFinfo.h>
Public Member Functions
~ElementValueFinfo ()
ElementValueFinfo (const string &name, const string &doc, void(T::*setFunc)(const Eref &, F), F(T::*getFunc)(const Eref &) const)
void registerFinfo (Cinfo *c)
bool strSet (const Eref &tgt, const string &field, const string &arg) const
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
string rttiType () const
Public Member Functions inherited from ValueFinfoBase
~ValueFinfoBase ()
ValueFinfoBase (const string &name, const string &doc)
DestFinfo * getFinfo () const
vector< string > innerDest () const
Public Member Functions inherited from Finfo
Finfo (const string &name, const string &doc)
virtual ~Finfo ()
const string & name () const
const string & docs () const
Returns documentation string.
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual bool checkTarget (const Finfo *target) const
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual vector< string > innerSrc () const
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Protected Attributes inherited from ValueFinfoBase
DestFinfo * set_
DestFinfo * get_
Detailed Description
template<class T, class F>
class ElementValueFinfo< T, F >
This variant of ValueFinfo provides facilities to set and get values of fields that require information about the managing Element
Constructor & Destructor Documentation
template<class T, class F> ElementValueFinfo< T, F >::~ElementValueFinfo () inline
References ValueFinfoBase::get_, and ValueFinfoBase::set_.
template<class T, class F> ElementValueFinfo< T, F >::ElementValueFinfo (const string & name, const string & doc, void(T::*)(const Eref &, F) setFunc, F(T::*)(const Eref &) const getFunc) inline
References ValueFinfoBase::get_, Finfo::name(), and ValueFinfoBase::set_.
Member Function Documentation
template<class T, class F> void ElementValueFinfo< T, F >::registerFinfo (Cinfo * c) inline virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
References ValueFinfoBase::get_, Cinfo::registerFinfo(), and ValueFinfoBase::set_.
template<class T, class F> string ElementValueFinfo< T, F >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
References Conv< T >::rttiType().
template<class T, class F> bool ElementValueFinfo< T, F >::strGet (const Eref & tgt, const string & field, string & returnValue) const inline virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
References Field< A >::innerStrGet(), and Eref::objId().
template<class T, class F> bool ElementValueFinfo< T, F >::strSet (const Eref & tgt, const string & field, const string & arg) const inline virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
References Field< A >::innerStrSet(), and Eref::objId().
The documentation for this class was generated from the following file:
basecode/ElementValueFinfo.h