MOOSE: ReadKkit Class Reference
ReadKkit Class Reference
#include <ReadKkit.h>
Public Types
enum ParseMode { DATA, INIT, COMMENT, LINE_CONTINUE }
Public Member Functions
ReadKkit ()
double getMaxTime () const
double getPlotDt () const
double getDefaultVol () const
string getBasePath () const
unsigned int getVersion () const
bool getMoveOntoCompartment () const
void setMoveOntoCompartment (bool v)
void innerRead (ifstream &fin)
ParseMode readInit (const string &line)
Id read (const string &filename, const string &cellname, Id parent, const string &solverClass="Stoich")
void readData (const string &line)
void undump (const vector< string > &args)
void run ()
void dumpPlots (const string &filename)
Id buildCompartment (const vector< string > &args)
Id buildPool (const vector< string > &args)
Id buildReac (const vector< string > &args)
Id buildEnz (const vector< string > &args)
Id buildPlot (const vector< string > &args)
Id buildTable (const vector< string > &args)
unsigned int loadTab (const vector< string > &args)
Id buildGroup (const vector< string > &args)
Id buildText (const vector< string > &args)
Id buildGraph (const vector< string > &args)
Id buildGeometry (const vector< string > &args)
Id buildStim (const vector< string > &args)
Id buildChan (const vector< string > &args)
Id buildInfo (Id parent, map< string, int > &m, const vector< string > &args)
void buildSumTotal (const string &src, const string &dest)
Id findSumTotSrc (const string &src)
void addmsg (const vector< string > &args)
void setupSlaveMsg (const string &src, const string &dest)
void innerAddMsg (const string &src, const map< string, Id > &m1, const string &srcMsg, const string &dest, const map< string, Id > &m2, const string &destMsg, bool isBackward=0)
void call (const vector< string > &args)
void objdump (const vector< string > &args)
void textload (const vector< string > &args)
void separateVols (Id pool, double vol)
void assignPoolCompartments ()
void assignReacCompartments ()
void assignEnzCompartments ()
void assignMMenzCompartments ()
void convertParametersToConcUnits ()
void convertPoolAmountToConcUnits ()
Convert pool amounts. Initially given in n, but scaling issue.
void convertReacRatesToConcUnits ()
Convert Reac rates, initially in n units.
void convertMMenzRatesToConcUnits ()
void convertEnzRatesToConcUnits ()
string pathTail (const string &path, string &head) const
string cleanPath (const string &path) const
Detailed Description
Loads in a kkit.g model. It makes a separate compartment for each distinct volume it finds in the system. The largest volume gets set to /model/kinetics. The next volume is in /model/compartment_1. The next volume is in /model/compartment_2. And so on. Has two options for handling compartments and solvers. By default, it puts the entire reaction system on /kinetics and makes just one solver. If the moveOntoCompartments_ flag is set it will put each model entity onto the appropriate compartment. It will create separate solvers for each compartment.
Member Enumeration Documentation
enum ReadKkit::ParseMode
Enumerator
DATA
INIT
COMMENT
LINE_CONTINUE
Constructor & Destructor Documentation
ReadKkit::ReadKkit ()
Member Function Documentation
void ReadKkit::addmsg (const vector< string > & args)
References buildSumTotal(), cleanPath(), Shell::doAddMsg(), innerAddMsg(), pathTail(), and setupSlaveMsg().
Referenced by readData().
void ReadKkit::assignEnzCompartments ()
Goes through all Enzs and connects them up to each of the compartments in which one or more of their reactants resides. Thus, if any of these compartments changes volume, the Enz will be informed.
Referenced by read().
void ReadKkit::assignMMenzCompartments ()
Goes through all MMenzs and connects them up to each of the compartments in which one or more of their reactants resides. Thus, if any of these compartments changes volume, the MMenz will be informed.
Referenced by read().
void ReadKkit::assignPoolCompartments ()
References Neutral::child(), Shell::doCreate(), Shell::doMove(), Id::eref(), findVolOrder(), getCompt(), ObjId::id, and SetGet1< A >::set().
Referenced by read().
void ReadKkit::assignReacCompartments ()
Goes through all Reacs and connects them up to each of the compartments in which one or more of their reactants resides. Thus, if any of these compartments changes volume, the Reac will be informed.
References Shell::doMove(), findParentComptOfReac(), getCompt(), and ObjId::id.
Referenced by read().
Id ReadKkit::buildChan (const vector< string > & args)
Build a Kchan entry in simulation. For now a dummy Neutral.
References cleanPath(), Shell::doCreate(), Shell::doFind(), ObjId::id, and pathTail().
Referenced by undump().
Id ReadKkit::buildCompartment (const vector< string > & args)
Id ReadKkit::buildEnz (const vector< string > & args)
vsf is vol scale factor, which is what GENESIS stores in 'vol' field n = vsf * conc(uM) Also, n = (conc (uM) / 1e6) * NA * vol so, vol = 1e6 * vsf / NA
References buildInfo(), cleanPath(), Shell::doAddMsg(), Shell::doCreate(), Shell::doFind(), ObjId::id, pathTail(), separateVols(), and Field< A >::set().
Referenced by undump().
Id ReadKkit::buildGeometry (const vector< string > & args)
Referenced by undump().
Id ReadKkit::buildGraph (const vector< string > & args)
References cleanPath(), Shell::doCreate(), Shell::doFind(), ObjId::id, and pathTail().
Referenced by undump().
Id ReadKkit::buildGroup (const vector< string > & args)
References buildInfo(), cleanPath(), Shell::doCreate(), Shell::doFind(), ObjId::id, and pathTail().
Referenced by undump().
Id ReadKkit::buildInfo (Id parent, map< string, int > & m, const vector< string > & args)
References Shell::doCreate(), Field< A >::set(), and y.
Referenced by buildEnz(), buildGroup(), buildPool(), buildReac(), and buildTable().
Id ReadKkit::buildPlot (const vector< string > & args)
References cleanPath(), Shell::doCreate(), Shell::doFind(), ObjId::id, and pathTail().
Referenced by undump().
Id ReadKkit::buildPool (const vector< string > & args)
There is a problem with this conversion, because of the discrepancy of the correct NA and the version (6e23) used in kkit. I take the concentration as authoritative, not the # of molecules. This is because I use conc units for the rates as well, and to use n for pools and conc for reactions will always introduce errors. This is still not a great solution, because, for example, simulations involving receptor traffic are originally framed in terms of number of receptors, not conc.
vsf is vol scale factor, which is what GENESIS stores in 'vol' field n = vsf * conc(uM) Also, n = (conc (uM) / 1e6) * NA * vol so, vol = 1e6 * vsf / NA
References buildInfo(), cleanPath(), Shell::doCreate(), Shell::doFind(), ObjId::id, pathTail(), separateVols(), and Field< A >::set().
Referenced by undump().
Id ReadKkit::buildReac (const vector< string > & args)
References buildInfo(), cleanPath(), Shell::doCreate(), Shell::doFind(), ObjId::id, pathTail(), and Field< A >::set().
Referenced by undump().
Id ReadKkit::buildStim (const vector< string > & args)
Build a Stim entry in simulation, i.e., a PulseGen
References cleanPath(), Shell::doCreate(), Shell::doFind(), ObjId::id, pathTail(), and Field< A >::set().
Referenced by undump().
void ReadKkit::buildSumTotal (const string & src, const string & dest)
References Neutral::child(), Shell::doAddMsg(), Shell::doCreate(), Id::element(), findSumTotSrc(), Field< A >::get(), BufPool::initCinfo(), Field< A >::set(), Id::value(), and Element::zombieSwap().
Referenced by addmsg().
Id ReadKkit::buildTable (const vector< string > & args)
References buildInfo(), cleanPath(), Shell::doCreate(), Shell::doFind(), ObjId::id, pathTail(), Field< A >::set(), TAB_IO, TAB_LOOP, and TAB_ONCE.
Referenced by undump().
Id ReadKkit::buildText (const vector< string > & args)
Referenced by undump().
void ReadKkit::call (const vector< string > & args)
call /kinetics/foo/notes LOAD notes_string_here
References cleanPath(), and Field< A >::set().
Referenced by readData().
string ReadKkit::cleanPath (const string & path) const
Utility function. Cleans up path strings. In most cases, it replaces things with underscores. Replaces square braces with underscores. Replaces '*' with 'p' as it is usually there to indicate phosphorylation Replaces '-' with underscore Replaces '@' with underscore Replaces ' ' with underscore
References c.
Referenced by addmsg(), buildChan(), buildEnz(), buildGraph(), buildGroup(), buildPlot(), buildPool(), buildReac(), buildStim(), buildTable(), and call().
void ReadKkit::convertEnzRatesToConcUnits ()
Convert regular Enz rates. Binding step k1 has similar issues as reac rates. k2 and k3 are both in units of 1/time, so OK.
References Field< A >::get(), NA, and Field< A >::set().
Referenced by convertParametersToConcUnits().
void ReadKkit::convertMMenzRatesToConcUnits ()
Convert MMEnz rates. Km should be in conc units. Actually rates stored as k1, k2, k3 in num units, so this has to be computed and then converted.
References Field< A >::get(), NA, and Field< A >::set().
Referenced by convertParametersToConcUnits().
void ReadKkit::convertParametersToConcUnits ()
We have a slight problem because MOOSE has a more precise value for NA than does kkit. Also, at the time the model is loaded, the volume relationships are unknown. So we need to fix up conc units of all pools reacs post-facto. Here we assume that the conc units from Kkit are meant to be OK, so they override the #/cell (lower case k) units. So we convert all the Kfs and Kbs in the entire system after the model has been created, once we know the order of each reac.
References convertEnzRatesToConcUnits(), convertMMenzRatesToConcUnits(), convertPoolAmountToConcUnits(), and convertReacRatesToConcUnits().
Referenced by read().
void ReadKkit::convertPoolAmountToConcUnits ()
Convert pool amounts. Initially given in n, but scaling issue.
References Field< A >::get(), NA, and Field< A >::set().
Referenced by convertParametersToConcUnits().
void ReadKkit::convertReacRatesToConcUnits ()
Convert Reac rates, initially in n units.
References Field< A >::get(), NA, and Field< A >::set().
Referenced by convertParametersToConcUnits().
void ReadKkit::dumpPlots (const string & filename)
References wildcardFind().
Referenced by testReadKkit().
Id ReadKkit::findSumTotSrc (const string & src)
Finds the source pool for a SumTot. It also deals with cases where the source is an enz-substrate complex
References pathTail().
Referenced by buildSumTotal().
string ReadKkit::getBasePath () const
double ReadKkit::getDefaultVol () const
double ReadKkit::getMaxTime () const
bool ReadKkit::getMoveOntoCompartment () const
double ReadKkit::getPlotDt () const
unsigned int ReadKkit::getVersion () const
void ReadKkit::innerAddMsg (const string & src, const map< string, Id > & m1, const string & srcMsg, const string & dest, const map< string, Id > & m2, const string & destMsg, bool isBackward = 0)
References Shell::doAddMsg().
Referenced by addmsg(), and setupSlaveMsg().
void ReadKkit::innerRead (ifstream & fin)
References COMMENT, DATA, INIT, readData(), readInit(), and trim().
Referenced by read().
unsigned int ReadKkit::loadTab (const vector< string > & args)
References Element::cinfo(), Id::element(), Field< A >::get(), Cinfo::isA(), and Field< A >::set().
Referenced by readData().
void ReadKkit::objdump (const vector< string > & args)
References assignArgs().
Referenced by readData().
string ReadKkit::pathTail (const string & path, string & head) const
Splits up kkit path into head and tail portions, tail is returned. Note that this prepends the basePath to the head.
Referenced by addmsg(), buildChan(), buildEnz(), buildGraph(), buildGroup(), buildPlot(), buildPool(), buildReac(), buildStim(), buildTable(), and findSumTotSrc().
Id ReadKkit::read (const string & filename, const string & cellname, Id parent, const string & solverClass = "Stoich")
The readcell function implements the old GENESIS cellreader functionality. Although it is really a parser operation, I put it here in Kinetics because the cell format is independent of parser and is likely to remain a legacy for a while.
References assignEnzCompartments(), assignMMenzCompartments(), assignPoolCompartments(), assignReacCompartments(), convertParametersToConcUnits(), ObjId::data(), Shell::doCreate(), Shell::doReinit(), innerRead(), makeStandardElements(), Id::path(), Field< A >::set(), and setMethod().
Referenced by Shell::doLoadModel(), and testReadKkit().
void ReadKkit::readData (const string & line)
References addmsg(), call(), chopLine(), loadTab(), objdump(), textload(), and undump().
Referenced by innerRead().
ReadKkit::ParseMode ReadKkit::readInit (const string & line)
References chopLine(), DATA, and INIT.
Referenced by innerRead().
void ReadKkit::run ()
This function sets up the kkit model for a run using the GSL, which means numerical integration using the GSL, all the plots specified by the kkit file, and the timestep for plots as specified by the kkit file.
References Shell::doReinit(), Shell::doSetClock(), and Shell::doStart().
Referenced by testReadKkit().
void ReadKkit::separateVols (Id pool, double vol)
Referenced by buildEnz(), and buildPool().
void ReadKkit::setMoveOntoCompartment (bool v)
void ReadKkit::setupSlaveMsg (const string & src, const string & dest)
References Element::cinfo(), Id::element(), Field< A >::get(), BufPool::initCinfo(), innerAddMsg(), Cinfo::isA(), Field< A >::set(), SetGet2< A1, A2 >::set(), and Element::zombieSwap().
Referenced by addmsg().
void ReadKkit::textload (const vector< string > & args)
Referenced by readData().
void ReadKkit::undump (const vector< string > & args)
References buildChan(), buildEnz(), buildGeometry(), buildGraph(), buildGroup(), buildPlot(), buildPool(), buildReac(), buildStim(), buildTable(), and buildText().
Referenced by readData().
The documentation for this class was generated from the following files:
kinetics/ReadKkit.h
kinetics/ReadKkit.cpp