MOOSE: OpFunc4Base< A1, A2, A3, A4 > Class Template Reference
OpFunc4Base< A1, A2, A3, A4 > Class Template Reference abstract
#include <OpFuncBase.h>
Public Member Functions
bool checkFinfo (const Finfo *s) const
virtual void op (const Eref &e, A1 arg1, A2 arg2, A3 arg3, A4 arg4) const =0
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
virtual ~OpFunc ()
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Member Function Documentation
template<class A1, class A2, class A3, class A4> bool OpFunc4Base< A1, A2, A3, A4 >::checkFinfo (const Finfo * s) const inline virtual
Implements OpFunc.
template<class A1 , class A2 , class A3 , class A4 > const OpFunc * OpFunc4Base< A1, A2, A3, A4 >::makeHopFunc (HopIndex hopIndex) const virtual
Implements OpFunc.
Referenced by SetGet4< A1, A2, A3, A4 >::set().
template<class A1, class A2, class A3, class A4> virtual void OpFunc4Base< A1, A2, A3, A4 >::op (const Eref & e, A1 arg1, A2 arg2, A3 arg3, A4 arg4) const pure virtual
Implemented in HopFunc4< A1, A2, A3, A4 >, EpFunc4< T, A1, A2, A3, A4 >, and OpFunc4< T, A1, A2, A3, A4 >.
Referenced by OpFunc4Base< A1, A2, A3, A4 >::opBuffer(), SrcFinfo4< T1, T2, T3, T4 >::send(), and SetGet4< A1, A2, A3, A4 >::set().
template<class A1, class A2, class A3, class A4> void OpFunc4Base< A1, A2, A3, A4 >::opBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc by converting args.
Implements OpFunc.
References Conv< T >::buf2val(), and OpFunc4Base< A1, A2, A3, A4 >::op().
template<class A1, class A2, class A3, class A4> string OpFunc4Base< A1, A2, A3, A4 >::rttiType () const inline virtual
Implements OpFunc.
References Conv< T >::rttiType().
The documentation for this class was generated from the following files:
basecode/OpFuncBase.h
basecode/HopFunc.h