MOOSE: Pool Class Reference
Pool Class Reference
#include <Pool.h>
Public Member Functions
Pool ()
~Pool ()
void vSetN (const Eref &e, double v)
double vGetN (const Eref &e) const
void vSetNinit (const Eref &e, double v)
double vGetNinit (const Eref &e) const
void vSetDiffConst (const Eref &e, double v)
double vGetDiffConst (const Eref &e) const
void vSetMotorConst (const Eref &e, double v)
Dummy MotorConst field for most Pool subclasses.
double vGetMotorConst (const Eref &e) const
void vSetConc (const Eref &e, double v)
double vGetConc (const Eref &e) const
void vSetConcInit (const Eref &e, double v)
void vSetVolume (const Eref &e, double v)
double vGetVolume (const Eref &e) const
void vSetSpecies (const Eref &e, SpeciesId v)
SpeciesId vGetSpecies (const Eref &e) const
void vHandleMolWt (const Eref &e, double v)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vReac (double A, double B)
void increment (double val)
void decrement (double val)
Public Member Functions inherited from PoolBase
PoolBase ()
virtual ~PoolBase ()
void setN (const Eref &e, double v)
double getN (const Eref &e) const
void setNinit (const Eref &e, double v)
double getNinit (const Eref &e) const
void setDiffConst (const Eref &e, double v)
double getDiffConst (const Eref &e) const
void setMotorConst (const Eref &e, double v)
double getMotorConst (const Eref &e) const
void setConc (const Eref &e, double v)
double getConc (const Eref &e) const
void setConcInit (const Eref &e, double v)
double getConcInit (const Eref &e) const
void setVolume (const Eref &e, double v)
double getVolume (const Eref &e) const
void setSpecies (const Eref &e, SpeciesId v)
SpeciesId getSpecies (const Eref &e) const
virtual void vSetSolver (Id ksolve, Id dsolve)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void reac (double A, double B)
void handleMolWt (const Eref &e, double v)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from PoolBase
static void zombify (Element *original, const Cinfo *zClass, Id ksolve, Id dsolve)
static const Cinfo * initCinfo ()
Detailed Description
The Pool class is a molecular pool. This is a set of molecules of a given species, in a uniform chemical context. Note that the same species might be present in other compartments, or be handled by other solvers.
Constructor & Destructor Documentation
Pool::Pool ()
Pool::~Pool ()
Member Function Documentation
void Pool::decrement (double val)
Referenced by initCinfo().
void Pool::increment (double val)
Referenced by initCinfo().
const Cinfo * Pool::initCinfo () static
References decrement(), increment(), and PoolBase::initCinfo().
Referenced by BufPool::initCinfo().
double Pool::vGetConc (const Eref & e) const virtual
Implements PoolBase.
References lookupVolumeFromMesh(), and NA.
double Pool::vGetDiffConst (const Eref & e) const virtual
Implements PoolBase.
double Pool::vGetMotorConst (const Eref & e) const virtual
Reimplemented from PoolBase.
double Pool::vGetN (const Eref & e) const virtual
Implements PoolBase.
double Pool::vGetNinit (const Eref & e) const virtual
Implements PoolBase.
SpeciesId Pool::vGetSpecies (const Eref & e) const virtual
Implements PoolBase.
double Pool::vGetVolume (const Eref & e) const virtual
Implements PoolBase.
References lookupVolumeFromMesh().
void Pool::vHandleMolWt (const Eref & e, double v) virtual
Reimplemented from PoolBase.
void Pool::vProcess (const Eref & e, ProcPtr p) virtual
Reimplemented from PoolBase.
References ProcInfo::dt, EPSILON, and SrcFinfo1< T >::send().
void Pool::vReac (double A, double B) virtual
Reimplemented from PoolBase.
void Pool::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented from PoolBase.
References PoolBase::getNinit(), and SrcFinfo1< T >::send().
Referenced by BufPool::vProcess(), and BufPool::vReinit().
void Pool::vSetConc (const Eref & e, double v) virtual
Implements PoolBase.
References lookupVolumeFromMesh(), and NA.
void Pool::vSetConcInit (const Eref & e, double v) virtual
Implements PoolBase.
References lookupVolumeFromMesh(), and NA.
void Pool::vSetDiffConst (const Eref & e, double v) virtual
Implements PoolBase.
void Pool::vSetMotorConst (const Eref & e, double v) virtual
Dummy MotorConst field for most Pool subclasses.
Reimplemented from PoolBase.
void Pool::vSetN (const Eref & e, double v) virtual
Implements PoolBase.
Referenced by BufPool::vSetN().
void Pool::vSetNinit (const Eref & e, double v) virtual
Implements PoolBase.
Referenced by BufPool::vSetN().
void Pool::vSetSpecies (const Eref & e, SpeciesId v) virtual
Implements PoolBase.
void Pool::vSetVolume (const Eref & e, double v) virtual
Volume is usually volume, but we also permit areal density This is obtained by looking up the corresponding spatial mesh entry in the parent compartment. If the message isn't set then it defaults to 1.0.
Implements PoolBase.
The documentation for this class was generated from the following files:
kinetics/Pool.h
kinetics/Pool.cpp