MOOSE: StimulusTable Class Reference
StimulusTable Class Reference
#include <StimulusTable.h>
Public Member Functions
StimulusTable ()
void setStartTime (double v)
double getStartTime () const
void setStopTime (double v)
double getStopTime () const
void setLoopTime (double v)
double getLoopTime () const
void setStepSize (double v)
double getStepSize () const
void setStepPosition (double v)
double getStepPosition () const
void setDoLoop (bool v)
bool getDoLoop () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from TableBase
TableBase ()
vector< double > getVec () const
void setVec (vector< double > val)
double getOutputValue () const
void setOutputValue (double val)
double getY (unsigned int index) const
void linearTransform (double scale, double offset)
void xplot (string file, string plotname)
void plainPlot (string file)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
void loadCSV (string fname, int startLine, int colNum, char separator)
void compareXplot (string fname, string plotname, string op)
void compareVec (vector< double > other, string op)
void clearVec ()
double * lookupVec (unsigned int index)
void setVecSize (unsigned int num)
unsigned int getVecSize () const
double interpolate (double x, double xmin, double xmax) const
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from TableBase
static const Cinfo * initCinfo ()
Additional Inherited Members
Protected Member Functions inherited from TableBase
vector< double > & vec ()
Detailed Description
Receives and records inputs. Handles plot and spiking data in batch mode.
Constructor & Destructor Documentation
StimulusTable::StimulusTable ()
Member Function Documentation
bool StimulusTable::getDoLoop () const
Referenced by initCinfo().
double StimulusTable::getLoopTime () const
Referenced by initCinfo().
double StimulusTable::getStartTime () const
Referenced by initCinfo().
double StimulusTable::getStepPosition () const
Referenced by initCinfo().
double StimulusTable::getStepSize () const
Referenced by initCinfo().
double StimulusTable::getStopTime () const
Referenced by initCinfo().
const Cinfo * StimulusTable::initCinfo () static
References getDoLoop(), getLoopTime(), getStartTime(), getStepPosition(), getStepSize(), getStopTime(), TableBase::initCinfo(), process(), reinit(), setDoLoop(), setLoopTime(), setStartTime(), setStepPosition(), setStepSize(), and setStopTime().
Referenced by storeStimulusTableMsgs().
void StimulusTable::process (const Eref & e, ProcPtr p)
References ProcInfo::currTime, TableBase::interpolate(), TableBase::setOutputValue(), and y.
Referenced by initCinfo().
void StimulusTable::reinit (const Eref & e, ProcPtr p)
References TableBase::interpolate(), TableBase::setOutputValue(), and y.
Referenced by initCinfo().
void StimulusTable::setDoLoop (bool v)
Referenced by initCinfo().
void StimulusTable::setLoopTime (double v)
Referenced by initCinfo().
void StimulusTable::setStartTime (double v)
Referenced by initCinfo().
void StimulusTable::setStepPosition (double v)
Referenced by initCinfo().
void StimulusTable::setStepSize (double v)
Referenced by initCinfo().
void StimulusTable::setStopTime (double v)
References doubleEq().
Referenced by initCinfo().
The documentation for this class was generated from the following files:
builtins/StimulusTable.h
builtins/StimulusTable.cpp