MOOSE: KinSparseMatrix Class Reference
KinSparseMatrix Class Reference
#include <KinSparseMatrix.h>
Public Member Functions
double computeRowRate (unsigned int row, const vector< double > &v) const
void getGillespieDependence (unsigned int row, vector< unsigned int > &cols) const
void fireReac (unsigned int reacIndex, vector< double > &S) const
void truncateRow (unsigned int maxColumnIndex)
vector< int > matrixEntry () const
Here we expose the sparse matrix for MOOSE use.
vector< unsigned int > colIndex () const
vector< unsigned int > rowStart () const
Public Member Functions inherited from SparseMatrix< int >
SparseMatrix ()
SparseMatrix (unsigned int nrows, unsigned int ncolumns)
unsigned int nRows () const
unsigned int nColumns () const
unsigned int nEntries () const
void setSize (unsigned int nrows, unsigned int ncolumns)
void set (unsigned int row, unsigned int column, intvalue)
void unset (unsigned int row, unsigned int column)
int get (unsigned int row, unsigned int column) const
unsigned int getRow (unsigned int row, const int **entry, const unsigned int **colIndex) const
unsigned int getRow (unsigned int row, vector< int > &e, vector< unsigned int > &c) const
unsigned int getColumn (unsigned int col, vector< int > &entry, vector< unsigned int > &rowIndex) const
void rowOperation (unsigned int row, unary_function< int, void > &f)
void addRow (unsigned int rowNum, const vector< int > &row)
void addRow (unsigned int rowNum, const vector< int > &entry, const vector< unsigned int > &colIndexArg)
void clear ()
void transpose ()
void reorderColumns (const vector< unsigned int > &colMap)
void tripletFill (const vector< unsigned int > &row, const vector< unsigned int > &col, const vector< int > &z)
void pairFill (const vector< unsigned int > &row, const vector< unsigned int > &col, intvalue)
void printTriplet (const vector< Triplet< int > > &t)
void print () const
void printInternal () const
Additional Inherited Members
Protected Attributes inherited from SparseMatrix< int >
unsigned int nrows_
unsigned int ncolumns_
vector< int > N_
vector< unsigned int > colIndex_
Non-zero entries in the SparseMatrix.
vector< unsigned int > rowStart_
Start index in the N_ and colIndex_ vectors, of each row.
Member Function Documentation
vector< unsigned int > KinSparseMatrix::colIndex () const
Referenced by Stoich::getColIndex().
double KinSparseMatrix::computeRowRate (unsigned int row, const vector< double > & v) const
Returns all non-zero column indices, for the specified row. This gives reac #s in orig matrix, and molecule #s in the transposed matrix Not needed. The getRow function does all this, more efficiently. int getRowIndices(unsigned int row, vector< unsigned int >& indices); Returns the dot product of the specified row with the vector v. v corresponds to the vector of reaction rates. v must have nColumns entries.
Returns the dot product of the specified row with the vector v. v corresponds to the vector of reaction rates. v must have nColumns entries.
Referenced by VoxelPools::updateRates().
void KinSparseMatrix::fireReac (unsigned int reacIndex, vector< double > & S) const
Fires a stochastic reaction: It undergoes a single transition This operation updates the mol concs due to the reacn.
This too operates on the transposed matrix, because we need to get all the molecules for a given reac: a column in the original N matrix.
Referenced by GssaVoxelPools::advance().
void KinSparseMatrix::getGillespieDependence (unsigned int row, vector< unsigned int > & deps) const
Does a special self-product of the specified row. Output is the set of nonzero indices in the product abs(Rij) * neg(Rjk) for the specified index i, where neg(val) is true only if val < 0.
Has to operate on transposed matrix row argument refers to reac# in this transformed situation. Fills up 'deps' with reac::s that depend on the row argument. Does NOT ensure that list is unique.
Referenced by Gsolve::rebuildGssaSystem().
vector< int > KinSparseMatrix::matrixEntry () const
Here we expose the sparse matrix for MOOSE use.
Referenced by Stoich::getMatrixEntry().
vector< unsigned int > KinSparseMatrix::rowStart () const
Referenced by Stoich::getRowStart().
void KinSparseMatrix::truncateRow (unsigned int maxColumnIndex)
This function generates a new internal list of rowEnds, such that they are all less than the maxColumnIndex. It is used because in fireReac we don't want to update all the molecules, only those that are variable.
Referenced by Gsolve::rebuildGssaSystem().
The documentation for this class was generated from the following files:
ksolve/KinSparseMatrix.h
ksolve/KinSparseMatrix.cpp