MOOSE: ZombieBufPool Class Reference
ZombieBufPool Class Reference
#include <ZombieBufPool.h>
Public Member Functions
ZombieBufPool ()
~ZombieBufPool ()
void vSetN (const Eref &e, double v)
The 'get' functions are simply inherited from ZombiePool.
void vSetNinit (const Eref &e, double v)
void vSetConc (const Eref &e, double v)
void vSetConcInit (const Eref &e, double v)
Public Member Functions inherited from ZombiePool
ZombiePool ()
~ZombiePool ()
void vSetN (const Eref &e, double v)
double vGetN (const Eref &e) const
void vSetNinit (const Eref &e, double v)
double vGetNinit (const Eref &e) const
void vSetDiffConst (const Eref &e, double v)
double vGetDiffConst (const Eref &e) const
void vSetConc (const Eref &e, double v)
double vGetConc (const Eref &e) const
void vSetConcInit (const Eref &e, double v)
void vSetVolume (const Eref &e, double v)
double vGetVolume (const Eref &e) const
void vSetSpecies (const Eref &e, unsigned int v)
unsigned int vGetSpecies (const Eref &e) const
void vSetSolver (Id ksolve, Id dsolve)
void vSetMotorConst (const Eref &e, double v)
Dummy MotorConst field for most Pool subclasses.
double vGetMotorConst (const Eref &e) const
Public Member Functions inherited from PoolBase
PoolBase ()
virtual ~PoolBase ()
void setN (const Eref &e, double v)
double getN (const Eref &e) const
void setNinit (const Eref &e, double v)
double getNinit (const Eref &e) const
void setDiffConst (const Eref &e, double v)
double getDiffConst (const Eref &e) const
void setMotorConst (const Eref &e, double v)
double getMotorConst (const Eref &e) const
void setConc (const Eref &e, double v)
double getConc (const Eref &e) const
void setConcInit (const Eref &e, double v)
double getConcInit (const Eref &e) const
void setVolume (const Eref &e, double v)
double getVolume (const Eref &e) const
void setSpecies (const Eref &e, SpeciesId v)
SpeciesId getSpecies (const Eref &e) const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void reac (double A, double B)
void handleMolWt (const Eref &e, double v)
virtual void vProcess (const Eref &e, ProcPtr p)
virtual void vReinit (const Eref &e, ProcPtr p)
virtual void vReac (double A, double B)
virtual void vHandleMolWt (const Eref &e, double v)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ZombiePool
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from PoolBase
static void zombify (Element *original, const Cinfo *zClass, Id ksolve, Id dsolve)
static const Cinfo * initCinfo ()
Additional Inherited Members
Protected Attributes inherited from ZombiePool
ZombiePoolInterface * dsolve_
ZombiePoolInterface * ksolve_
double diffConst_
double motorConst_
Constructor & Destructor Documentation
ZombieBufPool::ZombieBufPool ()
ZombieBufPool::~ZombieBufPool ()
Member Function Documentation
const Cinfo * ZombieBufPool::initCinfo () static
References ZombiePool::initCinfo().
void ZombieBufPool::vSetConc (const Eref & e, double v) virtual
Implements PoolBase.
References lookupVolumeFromMesh(), NA, and vSetN().
Referenced by vSetConcInit().
void ZombieBufPool::vSetConcInit (const Eref & e, double v) virtual
Implements PoolBase.
References vSetConc().
void ZombieBufPool::vSetN (const Eref & e, double v) virtual
The 'get' functions are simply inherited from ZombiePool.
Implements PoolBase.
References ZombiePool::vSetN(), and ZombiePool::vSetNinit().
Referenced by vSetConc(), and vSetNinit().
void ZombieBufPool::vSetNinit (const Eref & e, double v) virtual
Implements PoolBase.
References vSetN().
The documentation for this class was generated from the following files:
ksolve/ZombieBufPool.h
ksolve/ZombieBufPool.cpp