MOOSE: MeshCompt Class Reference
MeshCompt Class Reference abstract
#include <MeshCompt.h>
Public Member Functions
MeshCompt ()
~MeshCompt ()
double extendedMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry, including.
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
void innerResetStencil ()
virtual func implemented here.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
vector< double > innerGetStencilRate (unsigned int row) const
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void setStencilSize (unsigned int numRows, unsigned int numCols)
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
virtual vector< unsigned int > getParentVoxel () const =0
virtual const vector< double > & getVoxelArea () const =0
virtual const vector< double > & getVoxelLength () const =0
Public Member Functions inherited from ChemCompt
ChemCompt ()
virtual ~ChemCompt ()
double getEntireVolume (const Eref &e) const
virtual double vGetEntireVolume () const =0
void setEntireVolume (const Eref &e, double volume)
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
unsigned int getDimensions () const
virtual unsigned int innerGetDimensions () const =0
void setMethod (string method)
string getMethod () const
vector< double > getStencilRate (unsigned int row) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
virtual const vector< double > & vGetVoxelVolume () const =0
Virtual func so that derived classes can pass voxel volume back.
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
virtual const vector< double > & vGetVoxelMidpoint () const =0
Virtual func so that derived classes can return voxel midpoint.
void setVolumeNotRates (double volume)
virtual bool vSetVolumeNotRates (double volume)=0
Virtual function for actually doing this.
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
virtual void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)=0
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
virtual void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)=0
void resetStencil ()
unsigned int getNumEntries () const
virtual unsigned int innerGetNumEntries () const =0
void setNumEntries (unsigned int num)
virtual void innerSetNumEntries (unsigned int n)=0
MeshEntry * lookupEntry (unsigned int index)
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
virtual void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const =0
virtual double nearest (double x, double y, double z, unsigned int &index) const =0
virtual void indexToSpace (unsigned int index, double &x, double &y, double &z) const =0
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
virtual unsigned int getMeshType (unsigned int fid) const =0
Virtual function to return MeshType of specified entry.
virtual unsigned int getMeshDimensions (unsigned int fid) const =0
Virtual function to return dimensions of specified entry.
virtual double getMeshEntryVolume (unsigned int fid) const =0
Virtual function to return volume of mesh Entry.
virtual vector< double > getCoordinates (unsigned int fid) const =0
Virtual function to return coords of mesh Entry.
virtual vector< double > getDiffusionArea (unsigned int fid) const =0
Virtual function to return diffusion X-section area per neighbor.
virtual vector< double > getDiffusionScaling (unsigned int fid) const =0
Virtual function to return scale factor for diffusion. 1 here.
Additional Inherited Members
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static SrcFinfo1< vector
< double > > * voxelVolOut ()
static const Cinfo * initCinfo ()
Detailed Description
The MeshCompt represents the base class for all compartments which are set up as a meshes. These include CubeMesh, CylMesh and NeuroMesh. The MeshCompt handles the stencil that is the core of all the meshes. The stencil specifies which compartments diffuse into each other, and by how much.
Constructor & Destructor Documentation
MeshCompt::MeshCompt ()
MeshCompt::~MeshCompt ()
Member Function Documentation
void MeshCompt::addRow (unsigned int index, const vector< double > & entry, const vector< unsigned int > & colIndex)
References SparseMatrix< T >::addRow().
Referenced by CylMesh::buildStencil(), NeuroMesh::buildStencil(), and CubeMesh::buildStencil().
void MeshCompt::clearExtendedMeshEntryVolume () virtual
Inherited virtual function to clear the vector of MeshEntryVolume.
Implements ChemCompt.
double MeshCompt::extendedMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry, including.
Utility function to return volume of any voxel including those diffusively coupled and aubtting the present volume.
Implements ChemCompt.
Reimplemented in NeuroMesh, SpineMesh, and PsdMesh.
Referenced by PsdMesh::extendedMeshEntryVolume(), CylMesh::extendedMeshEntryVolume(), SpineMesh::extendedMeshEntryVolume(), CubeMesh::extendedMeshEntryVolume(), and NeuroMesh::extendedMeshEntryVolume().
void MeshCompt::extendStencil (const ChemCompt * other, const vector< VoxelJunction > & vj) virtual
Add boundary voxels to stencil for cross-solver junctions.
extendStencil adds voxels to the current stencil m_, to build up a monolithic stencil that also handles the entries just past all the boundaries. This function may be called many times to deal with the addition of multiple junctions. Before the first of these calls, the m_ matrix should be set to the coreStencil_.
Organizes vj by voxel, that is, by row.
Implements ChemCompt.
References SparseMatrix< T >::addRow(), c, SparseMatrix< T >::clear(), ChemCompt::getMeshEntryVolume(), SparseMatrix< T >::getRow(), SparseMatrix< T >::nRows(), and SparseMatrix< T >::setSize().
Referenced by testCubeMeshExtendStencil().
vector< unsigned int > MeshCompt::getNeighbors (unsigned int fid) const virtual
Looks up stencil to return vector of indices of coupled voxels.
Virtual function to return info on Entries connected to this one.
Implements ChemCompt.
References SparseMatrix< T >::getRow().
Referenced by NeuroMesh::getDiffusionArea(), and testCubeMesh().
virtual vector< unsigned int > MeshCompt::getParentVoxel () const pure virtual
Implemented in CubeMesh, NeuroMesh, CylMesh, PsdMesh, and SpineMesh.
const SparseMatrix< double > & MeshCompt::getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
unsigned int MeshCompt::getStencilRow (unsigned int meshIndex, const double ** entry, const unsigned int ** colIndex) const virtual
Derived function to return SparseMatrix-style row info for specified mesh entry.
Implements ChemCompt.
References SparseMatrix< T >::getRow().
Referenced by testCubeMeshExtendStencil().
virtual const vector< double >& MeshCompt::getVoxelArea () const pure virtual
Implemented in CubeMesh, SpineMesh, NeuroMesh, CylMesh, and PsdMesh.
virtual const vector< double >& MeshCompt::getVoxelLength () const pure virtual
Implemented in CubeMesh, SpineMesh, NeuroMesh, CylMesh, and PsdMesh.
vector< double > MeshCompt::innerGetStencilRate (unsigned int row) const virtual
Looks up stencil to return vector of diffusion coupling to neighbor voxels.
Implements ChemCompt.
References SparseMatrix< T >::getRow().
void MeshCompt::innerResetStencil () virtual
virtual func implemented here.
Implements ChemCompt.
Referenced by CylMesh::buildStencil(), PsdMesh::buildStencil(), SpineMesh::buildStencil(), NeuroMesh::buildStencil(), and CubeMesh::buildStencil().
void MeshCompt::setStencilSize (unsigned int numRows, unsigned int numCols)
References SparseMatrix< T >::clear(), and SparseMatrix< T >::setSize().
Referenced by CylMesh::buildStencil(), PsdMesh::buildStencil(), SpineMesh::buildStencil(), NeuroMesh::buildStencil(), and CubeMesh::buildStencil().
The documentation for this class was generated from the following files:
mesh/MeshCompt.h
mesh/MeshCompt.cpp