MOOSE: DiagonalMsg Class Reference
DiagonalMsg Class Reference
#include <DiagonalMsg.h>
Public Member Functions
DiagonalMsg (Element *e1, Element *e2, unsigned int msgIndex)
~DiagonalMsg ()
Eref firstTgt (const Eref &src) const
void sources (vector< vector< Eref > > &v) const
void targets (vector< vector< Eref > > &v) const
Id managerId () const
ObjId findOtherEnd (ObjId end) const
Msg * copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const
void setStride (int stride)
int getStride () const
Public Member Functions inherited from Msg
Msg (ObjId mid, Element *e1, Element *e2)
Constructor.
virtual ~Msg ()
Destructor.
Element * e1 () const
Element * e2 () const
Id getE1 () const
Id getE2 () const
vector< string > getSrcFieldsOnE1 () const
vector< string > getDestFieldsOnE2 () const
vector< string > getSrcFieldsOnE2 () const
vector< string > getDestFieldsOnE1 () const
ObjId mid () const
ObjId getAdjacent (ObjId) const
bool isForward (const Element *src) const
Static Public Member Functions
static unsigned int numMsg ()
Msg lookup functions.
static char * lookupMsg (unsigned int index)
Static function for Msg access.
static const Cinfo * initCinfo ()
Setup function for Element-style access to Msg fields.
Static Public Member Functions inherited from Msg
static void deleteMsg (ObjId mid)
static const Msg * getMsg (ObjId m)
static const Cinfo * initCinfo ()
static unsigned int initMsgManagers ()
static void clearAllMsgs ()
static const Msg * lastMsg ()
static bool isLastTrump ()
True when MOOSE has been terminated and is being cleaned up.
Friends
unsigned int Msg::initMsgManagers ()
Additional Inherited Members
Protected Attributes inherited from Msg
ObjId mid_
Element * e1_
Index of this Msg on the msg_ vector.
Element * e2_
Element 1 attached to Msg.
Static Protected Attributes inherited from Msg
static Id msgManagerId_
Element 2 attached to Msg.
static bool lastTrump_ = false
Flag to indicate termination of program.
Detailed Description
Connects up a series of data entries onto a matching series in a target Element. Inspects each entry, and uses the 'stride_' field to determine which should be its target.
* Suppose we have a stride of +1. Then
* Src:      1   2   3   4   n
* Dest: 2   3   4   5   n+1
*
* Suppose we have a stride of -2. Then
* Src:      1   2   3   4   n
* Dest: -   -   1   2   n-2
*
Constructor & Destructor Documentation
DiagonalMsg::DiagonalMsg (Element * e1, Element * e2, unsigned int msgIndex)
Referenced by copy().
DiagonalMsg::~DiagonalMsg ()
References ObjId::dataIndex, and Msg::mid_.
Member Function Documentation
Msg * DiagonalMsg::copy (Id origSrc, Id newSrc, Id newTgt, FuncId fid, unsigned int b, unsigned int n) const virtual
Make a copy of this Msg. The original msg was on origSrc. The new Msg should go from newSrc to newTgt, and have the function fid, on bindIndex b. The copy may have to be a higher-order Msg type to handle arrays if n > 1. Note that n is not the number of msgs, but the multiplier by which numData will be scaled.
Implements Msg.
References Element::addMsgAndFunc(), DiagonalMsg(), Msg::e1(), Msg::e2(), Id::element(), Msg::mid(), and setStride().
ObjId DiagonalMsg::findOtherEnd (ObjId) const virtual
Find the other end of this Msg. In most cases this is a straightforward return of e1 or e2, plus perhaps a DataId. But in some complex msgs we need to figure out DataIds that match with the target. In many-to-one cases we just return the first entry. If no Element match, return ObjId(Id(), DataId::bad()) If Element e matches but not DataId, return ObjId(e.id(), DataId::bad())
Implements Msg.
References BADINDEX, ObjId::dataIndex, Msg::e1(), Msg::e2(), Id::element(), Element::id(), ObjId::id, and Element::numData().
Eref DiagonalMsg::firstTgt (const Eref & src) const virtual
Obtain the first target Eref for the specified Src Eref It is really meant only to work with messages with a single target ObjId for each given src, typically OneToOne.
Implements Msg.
References Eref::dataIndex(), Msg::e1_, Msg::e2_, and Eref::element().
int DiagonalMsg::getStride () const
The stride is the increment to the src DataId that gives the dest DataId. It can be positive or negative, but bounds checking takes place and it does not wrap around. This function reads the stride.
Referenced by initCinfo().
const Cinfo * DiagonalMsg::initCinfo () static
Setup function for Element-style access to Msg fields.
References getStride(), Msg::initCinfo(), and setStride().
Referenced by Msg::initMsgManagers().
char * DiagonalMsg::lookupMsg (unsigned int index) static
Static function for Msg access.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
Id DiagonalMsg::managerId () const
unsigned int DiagonalMsg::numMsg () static
Msg lookup functions.
Static function for Msg access.
Referenced by Msg::clearAllMsgs(), and Msg::initMsgManagers().
void DiagonalMsg::setStride (int stride)
The stride is the increment to the src DataId that gives the dest DataId. It can be positive or negative, but bounds checking takes place and it does not wrap around. This function assigns the stride.
References Msg::e1(), Msg::e2(), and Element::markRewired().
Referenced by copy(), initCinfo(), and testFibonacci().
void DiagonalMsg::sources (vector< vector< Eref > > & v) const virtual
Return all the sources of e2 from e1, that is, all the msgs coming into specified entries on e2 from e1.
ALLDATA used when the sources include all data entries on a source. Indexing is v[dataId in range e2.numData][src list]
Implements Msg.
References Msg::e1_, Msg::e2_, and Element::numData().
void DiagonalMsg::targets (vector< vector< Eref > > & v) const virtual
Return all the targets of e1 on e2, that is, all the msgs going from specified entries on e1 to e2. ALLDATA used when the targets include all data entries on a target. Indexing is v[dataId in range e1.numData][tgt list]
Implements Msg.
References Msg::e1_, Msg::e2_, and Element::numData().
Friends And Related Function Documentation
unsigned int Msg::initMsgManagers () friend
The documentation for this class was generated from the following files:
msg/DiagonalMsg.h
msg/DiagonalMsg.cpp