MOOSE: ReadOnlyElementValueFinfo< T, F > Class Template Reference
ReadOnlyElementValueFinfo< T, F > Class Template Reference
#include <ElementValueFinfo.h>
Public Member Functions
~ReadOnlyElementValueFinfo ()
ReadOnlyElementValueFinfo (const string &name, const string &doc, F(T::*getFunc)(const Eref &e) const)
void registerFinfo (Cinfo *c)
bool strSet (const Eref &tgt, const string &field, const string &arg) const
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
string rttiType () const
Public Member Functions inherited from ValueFinfoBase
~ValueFinfoBase ()
ValueFinfoBase (const string &name, const string &doc)
DestFinfo * getFinfo () const
vector< string > innerDest () const
Public Member Functions inherited from Finfo
Finfo (const string &name, const string &doc)
virtual ~Finfo ()
const string & name () const
const string & docs () const
Returns documentation string.
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual bool checkTarget (const Finfo *target) const
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual vector< string > innerSrc () const
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Protected Attributes inherited from ValueFinfoBase
DestFinfo * set_
DestFinfo * get_
Constructor & Destructor Documentation
template<class T, class F> ReadOnlyElementValueFinfo< T, F >::~ReadOnlyElementValueFinfo () inline
References ValueFinfoBase::get_.
template<class T, class F> ReadOnlyElementValueFinfo< T, F >::ReadOnlyElementValueFinfo (const string & name, const string & doc, F(T::*)(const Eref &e) const getFunc) inline
References ValueFinfoBase::get_, and Finfo::name().
Member Function Documentation
template<class T, class F> void ReadOnlyElementValueFinfo< T, F >::registerFinfo (Cinfo * c) inline virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
References ValueFinfoBase::get_, and Cinfo::registerFinfo().
template<class T, class F> string ReadOnlyElementValueFinfo< T, F >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
References Conv< T >::rttiType().
template<class T, class F> bool ReadOnlyElementValueFinfo< T, F >::strGet (const Eref & tgt, const string & field, string & returnValue) const inline virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
References Field< A >::innerStrGet(), and Eref::objId().
template<class T, class F> bool ReadOnlyElementValueFinfo< T, F >::strSet (const Eref & tgt, const string & field, const string & arg) const inline virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
The documentation for this class was generated from the following file:
basecode/ElementValueFinfo.h