MOOSE: ExponentialRng Class Reference
ExponentialRng Class Reference
#include <ExponentialRng.h>
Public Member Functions
ExponentialRng ()
double getMean () const
void setMean (double mean)
int getMethod () const
void setMethod (int method)
virtual void vReinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from RandGenerator
RandGenerator ()
virtual ~RandGenerator ()
double getMean () const
double getVariance () const
double getSample () const
void process (const Eref &e, ProcPtr info)
void reinit (const Eref &e, ProcPtr info)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from RandGenerator
static const Cinfo * initCinfo ()
Additional Inherited Members
Protected Attributes inherited from RandGenerator
Probability * rng_
double sample_
Detailed Description
This is MOOSE wrapper for Exponentially distributed random number generator class, Exponential. The default
Constructor & Destructor Documentation
ExponentialRng::ExponentialRng ()
References RANDOM_MINIMIZATION.
Member Function Documentation
double ExponentialRng::getMean () const
Replaces the same method in base class. Returns the mean as stored in this object independent of the actual generator object.
Referenced by initCinfo().
int ExponentialRng::getMethod () const
Returns the algorithm used for sample generation. 0 for logarithmic method. 1 for random minimization method.
Referenced by initCinfo().
const Cinfo * ExponentialRng::initCinfo () static
References getMean(), getMethod(), RandGenerator::initCinfo(), setMean(), and setMethod().
void ExponentialRng::setMean (double mean)
Sets the mean. Since exponential distribution is defined in terms of this parameter, it is stored locally independent of the instantiation of the internal generator object.
References RandGenerator::rng_.
Referenced by initCinfo().
void ExponentialRng::setMethod (int method)
Sets the algorithm used for sample generation. 0 for logarithmic method. 1 for random minimization method. Default is random minimization.
References LOGARITHMIC, RANDOM_MINIMIZATION, and RandGenerator::rng_.
Referenced by initCinfo().
void ExponentialRng::vReinit (const Eref & e, ProcPtr p) virtual
Reports error in case the parameter mean has not been set.
Reimplemented from RandGenerator.
References RandGenerator::rng_.
The documentation for this class was generated from the following files:
randnum/ExponentialRng.h
randnum/ExponentialRng.cpp