MOOSE: Uniform Class Reference
Uniform Class Reference
#include <Uniform.h>
Public Member Functions
Uniform ()
Uniform (double min, double max)
double getMean () const
double getVariance () const
double getNextSample () const
double getMin () const
double getMax () const
void setMin (double min)
void setMax (double max)
Public Member Functions inherited from Probability
virtual ~Probability ()
Constructor & Destructor Documentation
Uniform::Uniform ()
Uniform::Uniform (double min, double max)
Member Function Documentation
double Uniform::getMax () const
Referenced by UniformRng::getMax().
double Uniform::getMean () const virtual
Implements Probability.
double Uniform::getMin () const
Referenced by UniformRng::getMin().
double Uniform::getNextSample () const virtual
Implements Probability.
References mtrand().
double Uniform::getVariance () const virtual
Implements Probability.
void Uniform::setMax (double max)
Referenced by UniformRng::setMax().
void Uniform::setMin (double min)
Referenced by UniformRng::setMin().
The documentation for this class was generated from the following files:
randnum/Uniform.h
randnum/Uniform.cpp