MOOSE: moose::CompartmentDataHolder Class Reference
moose::CompartmentDataHolder Class Reference
#include <CompartmentDataHolder.h>
Public Member Functions
CompartmentDataHolder ()
void readData (const CompartmentBase *c, const Eref &e)
void writeData (CompartmentBase *c, const Eref &e)
Constructor & Destructor Documentation
CompartmentDataHolder::CompartmentDataHolder ()
Member Function Documentation
void CompartmentDataHolder::readData (const CompartmentBase * c, const Eref & e)
References moose::CompartmentBase::getCm(), moose::CompartmentBase::getDiameter(), moose::CompartmentBase::getEm(), moose::CompartmentBase::getInitVm(), moose::CompartmentBase::getInject(), moose::CompartmentBase::getLength(), moose::CompartmentBase::getRa(), moose::CompartmentBase::getRm(), moose::CompartmentBase::getX(), moose::CompartmentBase::getX0(), moose::CompartmentBase::getY(), moose::CompartmentBase::getY0(), moose::CompartmentBase::getZ(), and moose::CompartmentBase::getZ0().
void CompartmentDataHolder::writeData (CompartmentBase * c, const Eref & e)
References moose::CompartmentBase::setCm(), moose::CompartmentBase::setDiameter(), moose::CompartmentBase::setEm(), moose::CompartmentBase::setInitVm(), moose::CompartmentBase::setInject(), moose::CompartmentBase::setLength(), moose::CompartmentBase::setRa(), moose::CompartmentBase::setRm(), moose::CompartmentBase::setX(), moose::CompartmentBase::setX0(), moose::CompartmentBase::setY(), moose::CompartmentBase::setY0(), moose::CompartmentBase::setZ(), and moose::CompartmentBase::setZ0().
The documentation for this class was generated from the following files:
biophysics/CompartmentDataHolder.h
biophysics/CompartmentDataHolder.cpp