MOOSE: ZombieMMenz Class Reference
ZombieMMenz Class Reference
#include <ZombieMMenz.h>
Public Member Functions
ZombieMMenz ()
void vSetKm (const Eref &e, double v)
double vGetKm (const Eref &e) const
void vSetNumKm (const Eref &e, double v)
double vGetNumKm (const Eref &e) const
void vSetKcat (const Eref &e, double v)
double vGetKcat (const Eref &e) const
void setSolver (Id solver, Id orig)
Public Member Functions inherited from EnzBase
EnzBase ()
virtual ~EnzBase ()
void setKm (const Eref &e, double v)
double getKm (const Eref &e) const
void setNumKm (const Eref &e, double v)
double getNumKm (const Eref &e) const
void setKcat (const Eref &e, double v)
double getKcat (const Eref &e) const
unsigned int getNumSub (const Eref &e) const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void sub (double n)
void enz (double n)
void prd (double n)
void remesh (const Eref &e)
virtual void vProcess (const Eref &e, ProcPtr p)
virtual void vReinit (const Eref &e, ProcPtr p)
virtual void vSub (double n)
virtual void vEnz (double n)
virtual void vRemesh (const Eref &e)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from EnzBase
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Detailed Description
This class represents the Michaelis-Menten type enzyme, obeying the equation V = kcat.[Etot].[S]/(Km + [S])
Constructor & Destructor Documentation
ZombieMMenz::ZombieMMenz ()
Member Function Documentation
const Cinfo * ZombieMMenz::initCinfo () static
References EnzBase::initCinfo().
void ZombieMMenz::setSolver (Id solver, Id orig) virtual
Does ZombieMMenz specific functions during conversion to zombie virtual func overrides default.
Now set up the RateTerm
Reimplemented from EnzBase.
References Element::cinfo(), Eref::data(), Id::element(), Id::eref(), Cinfo::findFinfo(), Element::getNeighbors(), EnzBase::initCinfo(), and Cinfo::isA().
double ZombieMMenz::vGetKcat (const Eref & e) const virtual
Implements EnzBase.
References Stoich::getMMenzKcat().
double ZombieMMenz::vGetKm (const Eref & e) const virtual
Implements EnzBase.
double ZombieMMenz::vGetNumKm (const Eref & e) const virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh().
void ZombieMMenz::vSetKcat (const Eref & e, double v) virtual
Implements EnzBase.
References Stoich::setMMenzKcat().
void ZombieMMenz::vSetKm (const Eref & e, double v) virtual
Implements EnzBase.
References Stoich::setMMenzKm().
void ZombieMMenz::vSetNumKm (const Eref & e, double v) virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh(), and Stoich::setMMenzKm().
The documentation for this class was generated from the following files:
ksolve/ZombieMMenz.h
ksolve/ZombieMMenz.cpp