MOOSE: IntFire Class Reference
IntFire Class Reference
#include <IntFire.h>
Public Member Functions
IntFire ()
IntFire (double thresh, double tau)
void innerAddSpike (unsigned int synIndex, double time)
void setVm (double v)
double getVm () const
void setTau (double v)
double getTau () const
void setThresh (double v)
double getThresh () const
void setRefractoryPeriod (double v)
double getRefractoryPeriod () const
void activation (double v)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Static Public Member Functions
static const Cinfo * initCinfo ()
Friends
void testStandaloneIntFire ()
void testSynapse ()
Constructor & Destructor Documentation
IntFire::IntFire ()
IntFire::IntFire (double thresh, double tau)
Member Function Documentation
void IntFire::activation (double v)
Referenced by initCinfo().
double IntFire::getRefractoryPeriod () const
Referenced by initCinfo().
double IntFire::getTau () const
Referenced by initCinfo().
double IntFire::getThresh () const
Referenced by initCinfo().
double IntFire::getVm () const
Referenced by initCinfo().
const Cinfo * IntFire::initCinfo () static
References activation(), getRefractoryPeriod(), getTau(), getThresh(), getVm(), Neutral::initCinfo(), process(), reinit(), setRefractoryPeriod(), setTau(), setThresh(), and setVm().
Referenced by testCinfoFields(), testFinfoFields(), testSendSpike(), testSetGetDouble(), and testSparseMsg().
void IntFire::innerAddSpike (unsigned int synIndex, double time)
Overrides base class function. Inserts an event into the pendingEvents queue for spikes.
void IntFire::process (const Eref & e, ProcPtr p)
References ProcInfo::currTime, Eref::dataIndex(), and ProcInfo::dt.
Referenced by initCinfo().
void IntFire::reinit (const Eref & e, ProcPtr p)
Referenced by initCinfo().
void IntFire::setRefractoryPeriod (double v)
Referenced by initCinfo().
void IntFire::setTau (double v)
Referenced by initCinfo().
void IntFire::setThresh (double v)
Referenced by initCinfo().
void IntFire::setVm (double v)
Referenced by initCinfo().
Friends And Related Function Documentation
void testStandaloneIntFire () friend
void testSynapse () friend
The documentation for this class was generated from the following files:
biophysics/IntFire.h
biophysics/IntFire.cpp