MOOSE: RandSpike Class Reference
RandSpike Class Reference
#include <RandSpike.h>
Public Member Functions
RandSpike ()
void setRate (double rate)
double getRate () const
void setRefractT (double val)
double getRefractT () const
bool getFired () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Static Public Member Functions
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
RandSpike::RandSpike ()
Member Function Documentation
bool RandSpike::getFired () const
Referenced by initCinfo().
double RandSpike::getRate () const
Referenced by initCinfo().
double RandSpike::getRefractT () const
Referenced by initCinfo().
const Cinfo * RandSpike::initCinfo () static
References getFired(), getRate(), getRefractT(), Neutral::initCinfo(), process(), reinit(), setRate(), and setRefractT().
void RandSpike::process (const Eref & e, ProcPtr p)
References ProcInfo::currTime, ProcInfo::dt, and mtrand().
Referenced by initCinfo().
void RandSpike::reinit (const Eref & e, ProcPtr p)
References mtrand().
Referenced by initCinfo().
void RandSpike::setRate (double rate)
Referenced by initCinfo().
void RandSpike::setRefractT (double val)
Referenced by initCinfo().
The documentation for this class was generated from the following files:
biophysics/RandSpike.h
biophysics/RandSpike.cpp