MOOSE: HSolve Class Reference
HSolve Class Reference
#include <HSolve.h>
Public Member Functions
HSolve ()
void process (const Eref &hsolve, ProcPtr p)
void reinit (const Eref &hsolve, ProcPtr p)
void setSeed (Id seed)
Id getSeed () const
void setPath (const Eref &e, string path)
string getPath (const Eref &e) const
void setDt (double dt)
double getDt () const
void setCaAdvance (int caAdvance)
int getCaAdvance () const
void setVDiv (int vDiv)
int getVDiv () const
void setVMin (double vMin)
double getVMin () const
void setVMax (double vMax)
double getVMax () const
void setCaDiv (int caDiv)
int getCaDiv () const
void setCaMin (double caMin)
double getCaMin () const
void setCaMax (double caMax)
double getCaMax () const
double getInitVm (Id id) const
void setInitVm (Id id, double value)
double getVm (Id id) const
void setVm (Id id, double value)
double getCm (Id id) const
void setCm (Id id, double value)
double getEm (Id id) const
void setEm (Id id, double value)
double getRm (Id id) const
void setRm (Id id, double value)
double getRa (Id id) const
void setRa (Id id, double value)
double getIm (Id id) const
double getIa (Id id) const
double getInject (Id id) const
void setInject (Id id, double value)
void addInject (Id id, double value)
void addGkEk (Id id, double v1, double v2)
Interface to compartments.
void setPowers (Id id, double Xpower, double Ypower, double Zpower)
Interface to channels.
int getInstant (Id id) const
void setInstant (Id id, int instant)
double getHHChannelGbar (Id id) const
void setHHChannelGbar (Id id, double value)
double getEk (Id id) const
void setEk (Id id, double value)
double getGk (Id id) const
void setGk (Id id, double value)
double getIk (Id id) const
double getX (Id id) const
void setX (Id id, double value)
double getY (Id id) const
void setY (Id id, double value)
double getZ (Id id) const
void setZ (Id id, double value)
double getCa (Id id) const
Interface to CaConc.
void setCa (Id id, double Ca)
void iCa (Id id, double iCa)
double getCaBasal (Id id) const
void setCaBasal (Id id, double CaBasal)
void setTauB (Id id, double tau, double B)
double getCaCeiling (Id id) const
void setCaCeiling (Id id, double floor)
double getCaFloor (Id id) const
void setCaFloor (Id id, double floor)
Public Member Functions inherited from HSolveActive
HSolveActive ()
void setup (Id seed, double dt)
void step (ProcPtr info)
Equivalent to process.
void reinit (ProcPtr info)
Public Member Functions inherited from HSolvePassive
void setup (Id seed, double dt)
void solve ()
Public Member Functions inherited from HinesMatrix
HinesMatrix ()
void setup (const vector< TreeNodeStruct > &tree, double dt)
unsigned int getSize () const
double getA (unsigned int row, unsigned int col) const
double getB (unsigned int row) const
double getVMid (unsigned int row) const
Static Public Member Functions
static const Cinfo * initCinfo ()
Interface to external channels.
static const std::set< string > & handledClasses ()
static void deleteIncomingMessages (Element *orig, const string finfo)
Additional Inherited Members
Protected Types inherited from HinesMatrix
typedef vector< double >::iterator vdIterator
Protected Member Functions inherited from HSolvePassive
void updateMatrix ()
void forwardEliminate ()
void backwardSubstitute ()
Protected Attributes inherited from HSolveActive
int caAdvance_
double vMin_
double vMax_
int vDiv_
double caMin_
double caMax_
int caDiv_
vector< CurrentStruct > current_
Channel current.
vector< double > state_
Fraction of gates open.
vector< ChannelStruct > channel_
to compartment: chan2compt
vector< SpikeGenStruct > spikegen_
vector< SynChanStruct > synchan_
vector< CaConcStruct > caConc_
Ca pool info.
vector< double > ca_
Ca conc in each pool.
vector< double > caActivation_
calcium pool
vector< double * > caTarget_
LookupTable vTable_
LookupTable caTable_
vector< bool > gCaDepend_
depend on Ca conc?
vector< unsigned int > caCount_
each compartment
vector< int > caDependIndex_
depdt channel depend upon?
vector< LookupColumn > column_
to lookup for this species
vector< LookupRow > caRowCompt_
vector< LookupRow * > caRow_
vector< int > channelCount_
compartment
vector< currentVecIter > currentBoundary_
vector< unsigned int > chan2compt_
vector< unsigned int > chan2state_
a state index
vector< double > externalCurrent_
vector< Id > caConcId_
Used for localIndex-ing.
vector< Id > channelId_
Used for localIndex-ing.
vector< Id > gateId_
Used for localIndex-ing.
vector< unsigned int > outVm_
vector< unsigned int > outCa_
Protected Attributes inherited from HSolvePassive
vector< CompartmentStruct > compartment_
vector< Id > compartmentId_
vector< double > V_
vector< TreeNodeStruct > tree_
map< unsigned int, InjectStruct > inject_
Protected Attributes inherited from HinesMatrix
unsigned int nCompt_
double dt_
vector< JunctionStruct > junction_
vector< double > HS_
vector< double > HJ_
vector< double > HJCopy_
vector< double > VMid_
middle of a time step.
vector< vdIterator > operand_
vector< vdIterator > backOperand_
int stage_
reached. Used in getA.
Detailed Description
HSolve adapts the integrator HSolveActive into a MOOSE class.
Constructor & Destructor Documentation
HSolve::HSolve ()
Member Function Documentation
void HSolve::addGkEk (Id id, double v1, double v2)
Interface to compartments.
References HSolveActive::externalCurrent_.
void HSolve::addInject (Id id, double value)
References HSolvePassive::inject_, and HinesMatrix::nCompt_.
void HSolve::deleteIncomingMessages (Element * orig, const string finfo) static
Delete messages coming into this particular element if its class that is handled by HSolve
Utility function to delete incoming messages on orig. To be used in zombifying elements.
References ObjId::bad(), Element::cinfo(), Msg::deleteMsg(), Id::element(), Element::findCaller(), Cinfo::findFinfo(), Msg::findOtherEnd(), DestFinfo::getFid(), Msg::getMsg(), handledClasses(), Element::id(), ObjId::id, and Cinfo::name().
double HSolve::getCa (Id id) const
Interface to CaConc.
References HSolveActive::ca_, and HSolveActive::caConc_.
Referenced by ZombieCaConc::vGetCa().
int HSolve::getCaAdvance () const
References HSolveActive::caAdvance_.
Referenced by initCinfo().
double HSolve::getCaBasal (Id id) const
References HSolveActive::caConc_.
Referenced by ZombieCaConc::vGetCaBasal().
double HSolve::getCaCeiling (Id id) const
References HSolveActive::caConc_.
Referenced by ZombieCaConc::vGetCeiling().
int HSolve::getCaDiv () const
References HSolveActive::caDiv_.
Referenced by initCinfo().
double HSolve::getCaFloor (Id id) const
References HSolveActive::caConc_.
Referenced by ZombieCaConc::vGetFloor().
double HSolve::getCaMax () const
References HSolveActive::caMax_.
Referenced by initCinfo().
double HSolve::getCaMin () const
References HSolveActive::caMin_.
Referenced by initCinfo().
double HSolve::getCm (Id id) const
References HSolvePassive::tree_.
double HSolve::getDt () const
Referenced by initCinfo().
double HSolve::getEk (Id id) const
References HSolveActive::current_.
Referenced by ZombieHHChannel::vGetEk().
double HSolve::getEm (Id id) const
References HSolvePassive::tree_.
double HSolve::getGk (Id id) const
References HSolveActive::current_.
Referenced by ZombieHHChannel::vGetGk().
double HSolve::getHHChannelGbar (Id id) const
References HSolveActive::channel_.
Referenced by ZombieHHChannel::vGetGbar().
double HSolve::getIa (Id id) const
double HSolve::getIk (Id id) const
References HSolveActive::chan2compt_, HSolveActive::current_, and HSolvePassive::V_.
Referenced by ZombieHHChannel::vGetIk().
double HSolve::getIm (Id id) const
References HSolvePassive::compartment_, HSolveActive::current_, HSolveActive::currentBoundary_, HinesMatrix::nCompt_, HSolvePassive::tree_, and HSolvePassive::V_.
double HSolve::getInitVm (Id id) const
References HSolvePassive::tree_.
double HSolve::getInject (Id id) const
References HSolvePassive::inject_, and HinesMatrix::nCompt_.
int HSolve::getInstant (Id id) const
References HSolveActive::channel_.
Referenced by ZombieHHChannel::vGetInstant().
string HSolve::getPath (const Eref & e) const
Path to the compartments
Referenced by initCinfo().
double HSolve::getRa (Id id) const
References HSolvePassive::tree_.
double HSolve::getRm (Id id) const
References HSolvePassive::tree_.
Id HSolve::getSeed () const
For searching for compartments: seed is the starting compt.
Referenced by initCinfo().
int HSolve::getVDiv () const
References HSolveActive::vDiv_.
Referenced by initCinfo().
double HSolve::getVm (Id id) const
References HSolvePassive::V_.
double HSolve::getVMax () const
References HSolveActive::vMax_.
Referenced by initCinfo().
double HSolve::getVMin () const
References HSolveActive::vMin_.
Referenced by initCinfo().
double HSolve::getX (Id id) const
References HSolveActive::chan2state_, HSolveActive::channel_, and HSolveActive::state_.
Referenced by ZombieHHChannel::vGetX().
double HSolve::getY (Id id) const
References HSolveActive::chan2state_, HSolveActive::channel_, and HSolveActive::state_.
Referenced by ZombieHHChannel::vGetY().
double HSolve::getZ (Id id) const
References HSolveActive::chan2state_, HSolveActive::channel_, and HSolveActive::state_.
Referenced by ZombieHHChannel::vGetZ().
const set< string > & HSolve::handledClasses () static
Returns the set of classes "handled" by HSolve
Referenced by deleteIncomingMessages().
void HSolve::iCa (Id id, double iCa)
References HSolveActive::caActivation_, and HSolveActive::caConc_.
Referenced by ZombieCaConc::vCurrent().
const Cinfo * HSolve::initCinfo () static
Interface to external channels.
References getCaAdvance(), getCaDiv(), getCaMax(), getCaMin(), getDt(), getPath(), getSeed(), getVDiv(), getVMax(), getVMin(), Neutral::initCinfo(), process(), reinit(), setCaAdvance(), setCaDiv(), setCaMax(), setCaMin(), setDt(), setPath(), setSeed(), setVDiv(), setVMax(), and setVMin().
void HSolve::process (const Eref & hsolve, ProcPtr p)
References HSolveActive::step().
Referenced by initCinfo().
void HSolve::reinit (const Eref & hsolve, ProcPtr p)
References ProcInfo::dt, and HSolveActive::reinit().
Referenced by initCinfo().
void HSolve::setCa (Id id, double Ca)
References HSolveActive::ca_, and HSolveActive::caConc_.
Referenced by ZombieCaConc::vSetCa(), and ZombieCaConc::vSetCaBasal().
void HSolve::setCaAdvance (int caAdvance)
References HSolveActive::caAdvance_.
Referenced by initCinfo().
void HSolve::setCaBasal (Id id, double CaBasal)
References HSolveActive::caConc_.
void HSolve::setCaCeiling (Id id, double floor)
References HSolveActive::caConc_.
Referenced by ZombieCaConc::vSetCeiling().
void HSolve::setCaDiv (int caDiv)
References HSolveActive::caDiv_.
Referenced by initCinfo().
void HSolve::setCaFloor (Id id, double floor)
References HSolveActive::caConc_.
Referenced by ZombieCaConc::vSetFloor().
void HSolve::setCaMax (double caMax)
References HSolveActive::caMax_.
Referenced by initCinfo().
void HSolve::setCaMin (double caMin)
References HSolveActive::caMin_.
Referenced by initCinfo().
void HSolve::setCm (Id id, double value)
References HSolvePassive::tree_.
void HSolve::setDt (double dt)
Referenced by initCinfo().
void HSolve::setEk (Id id, double value)
References HSolveActive::current_.
Referenced by ZombieHHChannel::vSetEk().
void HSolve::setEm (Id id, double value)
References HSolvePassive::tree_.
void HSolve::setGk (Id id, double value)
References HSolveActive::current_.
Referenced by ZombieHHChannel::vSetGk().
void HSolve::setHHChannelGbar (Id id, double value)
References HSolveActive::channel_.
Referenced by ZombieHHChannel::vSetGbar().
void HSolve::setInitVm (Id id, double value)
References HSolvePassive::tree_.
void HSolve::setInject (Id id, double value)
References HSolvePassive::inject_, and HinesMatrix::nCompt_.
void HSolve::setInstant (Id id, int instant)
References HSolveActive::channel_.
Referenced by ZombieHHChannel::vSetInstant().
void HSolve::setPath (const Eref & e, string path)
Referenced by initCinfo().
void HSolve::setPowers (Id id, double Xpower, double Ypower, double Zpower)
Interface to channels.
References HSolveActive::channel_.
Referenced by ZombieHHChannel::vSetXpower(), ZombieHHChannel::vSetYpower(), and ZombieHHChannel::vSetZpower().
void HSolve::setRa (Id id, double value)
References HSolvePassive::tree_.
void HSolve::setRm (Id id, double value)
References HSolvePassive::tree_.
void HSolve::setSeed (Id seed)
References Element::cinfo(), Id::element(), Cinfo::isA(), and Id::path().
Referenced by initCinfo().
void HSolve::setTauB (Id id, double tau, double B)
References HSolveActive::caConc_.
Referenced by ZombieCaConc::vSetB(), and ZombieCaConc::vSetTau().
void HSolve::setVDiv (int vDiv)
References HSolveActive::vDiv_.
Referenced by initCinfo().
void HSolve::setVm (Id id, double value)
References HSolvePassive::V_.
void HSolve::setVMax (double vMax)
References HSolveActive::vMax_.
Referenced by initCinfo().
void HSolve::setVMin (double vMin)
References HSolveActive::vMin_.
Referenced by initCinfo().
void HSolve::setX (Id id, double value)
References HSolveActive::chan2state_, HSolveActive::channel_, and HSolveActive::state_.
Referenced by ZombieHHChannel::vSetX().
void HSolve::setY (Id id, double value)
References HSolveActive::chan2state_, HSolveActive::channel_, and HSolveActive::state_.
Referenced by ZombieHHChannel::vSetY().
void HSolve::setZ (Id id, double value)
References HSolveActive::chan2state_, HSolveActive::channel_, and HSolveActive::state_.
Referenced by ZombieHHChannel::vSetZ().
The documentation for this class was generated from the following files:
hsolve/HSolve.h
hsolve/HSolve.cpp
hsolve/HSolveInterface.cpp