MOOSE: moose::VClamp Class Reference
moose::VClamp Class Reference
#include <VClamp.h>
Public Member Functions
VClamp ()
~VClamp ()
void setCommand (double v)
double getCommand () const
void setVin (double v)
double getVin () const
double getCurrent () const
void setMode (unsigned int mode)
unsigned int getMode () const
void setTi (double value)
double getTi () const
void setTd (double value)
double getTd () const
void setTau (double value)
double getTau () const
void setGain (double value)
double getGain () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Static Public Member Functions
static const Cinfo * initCinfo ()
static SrcFinfo1< double > * currentOut ()
Protected Attributes
double vIn_
double command_
double current_
unsigned int mode_
double ti_
double td_
double Kp_
double tau_
double tdByDt_
double dtByTi_
double tauByDt_
double e_
double e1_
double e2_
double v1_
double cmdIn_
double oldCmdIn_
double expt_
Constructor & Destructor Documentation
VClamp::VClamp ()
VClamp::~VClamp ()
Member Function Documentation
SrcFinfo1< double > * VClamp::currentOut () static
Referenced by initCinfo(), process(), and reinit().
double VClamp::getCommand () const
References command_.
Referenced by initCinfo().
double VClamp::getCurrent () const
References current_.
Referenced by initCinfo().
double VClamp::getGain () const
References Kp_.
Referenced by initCinfo().
unsigned int VClamp::getMode () const
References mode_.
Referenced by initCinfo().
double VClamp::getTau () const
References tau_.
Referenced by initCinfo().
double VClamp::getTd () const
References td_.
Referenced by initCinfo().
double VClamp::getTi () const
References ti_.
Referenced by initCinfo().
double VClamp::getVin () const
References vIn_.
Referenced by initCinfo().
const Cinfo * VClamp::initCinfo () static
References currentOut(), getCommand(), getCurrent(), getGain(), getMode(), getTau(), getTd(), getTi(), getVin(), Neutral::initCinfo(), process(), reinit(), setCommand(), setGain(), setMode(), setTau(), setTd(), setTi(), and setVin().
void VClamp::process (const Eref & e, ProcPtr p)
References cmdIn_, command_, current_, currentOut(), dtByTi_, e1_, e2_, e_, expt_, Kp_, mode_, oldCmdIn_, tau_, tauByDt_, td_, tdByDt_, ti_, v1_, and vIn_.
Referenced by initCinfo().
void VClamp::reinit (const Eref & e, ProcPtr p)
References cmdIn_, command_, currentOut(), ProcInfo::dt, dtByTi_, e1_, e2_, e_, Eref::element(), expt_, Field< A >::get(), Element::getNeighbors(), Kp_, oldCmdIn_, tau_, tauByDt_, td_, tdByDt_, ti_, v1_, and vIn_.
Referenced by initCinfo().
void VClamp::setCommand (double v)
References cmdIn_.
Referenced by initCinfo().
void VClamp::setGain (double value)
References Kp_.
Referenced by initCinfo().
void VClamp::setMode (unsigned int mode)
References mode_.
Referenced by initCinfo().
void VClamp::setTau (double value)
References tau_.
Referenced by initCinfo().
void VClamp::setTd (double value)
References td_.
Referenced by initCinfo().
void VClamp::setTi (double value)
References ti_.
Referenced by initCinfo().
void VClamp::setVin (double v)
References vIn_.
Referenced by initCinfo().
Member Data Documentation
double moose::VClamp::cmdIn_ protected
Referenced by process(), reinit(), and setCommand().
double moose::VClamp::command_ protected
Referenced by getCommand(), process(), and reinit().
double moose::VClamp::current_ protected
Referenced by getCurrent(), and process().
double moose::VClamp::dtByTi_ protected
Referenced by process(), and reinit().
double moose::VClamp::e1_ protected
Referenced by process(), and reinit().
double moose::VClamp::e2_ protected
Referenced by process(), and reinit().
double moose::VClamp::e_ protected
Referenced by process(), and reinit().
double moose::VClamp::expt_ protected
Referenced by process(), and reinit().
double moose::VClamp::Kp_ protected
Referenced by getGain(), process(), reinit(), and setGain().
unsigned int moose::VClamp::mode_ protected
Referenced by getMode(), process(), and setMode().
double moose::VClamp::oldCmdIn_ protected
Referenced by process(), and reinit().
double moose::VClamp::tau_ protected
Referenced by getTau(), process(), reinit(), and setTau().
double moose::VClamp::tauByDt_ protected
Referenced by process(), and reinit().
double moose::VClamp::td_ protected
Referenced by getTd(), process(), reinit(), and setTd().
double moose::VClamp::tdByDt_ protected
Referenced by process(), and reinit().
double moose::VClamp::ti_ protected
Referenced by getTi(), process(), reinit(), and setTi().
double moose::VClamp::v1_ protected
Referenced by process(), and reinit().
double moose::VClamp::vIn_ protected
Referenced by getVin(), process(), reinit(), and setVin().
The documentation for this class was generated from the following files:
biophysics/VClamp.h
biophysics/VClamp.cpp