MOOSE: ReadCell Class Reference
ReadCell Class Reference
#include <ReadCell.h>
Public Member Functions
ReadCell ()
Id read (const string &filename, const string &cellname, Id parent)
Detailed Description
The ReadCell class implements the old GENESIS cellreader functionality.
ReadCell is partially implemented but works for most common uses and will evolve to some further point.
One significant semantic difference from the GENESIS version is that in MOOSE ReadCell can accept values of globals defined in the script, but will NOT alter the script global values.
Constructor & Destructor Documentation
ReadCell::ReadCell ()
References Id::element(), Element::getName(), and Id::path().
Member Function Documentation
Id ReadCell::read (const string & filename, const string & cellname, Id parent)
The readcell function implements the old GENESIS cellreader functionality.
References Shell::doCreate(), and MooseGlobal.
Referenced by Shell::doLoadModel().
The documentation for this class was generated from the following files:
biophysics/ReadCell.h
biophysics/ReadCell.cpp