MOOSE: MMenz Class Reference
MMenz Class Reference
#include <MMenz.h>
Public Member Functions
MMenz ()
virtual ~MMenz ()
void vSetKm (const Eref &e, double v)
double vGetKm (const Eref &e) const
void vSetNumKm (const Eref &e, double v)
double vGetNumKm (const Eref &e) const
void vSetKcat (const Eref &e, double v)
double vGetKcat (const Eref &e) const
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vSub (double n)
void vEnz (double n)
void vRemesh (const Eref &e)
Public Member Functions inherited from EnzBase
EnzBase ()
virtual ~EnzBase ()
void setKm (const Eref &e, double v)
double getKm (const Eref &e) const
void setNumKm (const Eref &e, double v)
double getNumKm (const Eref &e) const
void setKcat (const Eref &e, double v)
double getKcat (const Eref &e) const
unsigned int getNumSub (const Eref &e) const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void sub (double n)
void enz (double n)
void prd (double n)
void remesh (const Eref &e)
virtual void setSolver (Id solver, Id orig)
Assign solver info.
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from EnzBase
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Detailed Description
This class represents the Michaelis-Menten type enzyme, obeying the equation V = kcat.[Etot].[S]/(Km + [S])
Constructor & Destructor Documentation
MMenz::MMenz ()
MMenz::~MMenz () virtual
Member Function Documentation
const Cinfo * MMenz::initCinfo () static
References EnzBase::initCinfo().
void MMenz::vEnz (double n) virtual
Reimplemented from EnzBase.
Referenced by testMMenz().
double MMenz::vGetKcat (const Eref & e) const virtual
Implements EnzBase.
Referenced by testMMenz().
double MMenz::vGetKm (const Eref & e) const virtual
Implements EnzBase.
Referenced by testMMenz().
double MMenz::vGetNumKm (const Eref & e) const virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh().
void MMenz::vProcess (const Eref & e, ProcPtr p) virtual
Reimplemented from EnzBase.
References SrcFinfo2< T1, T2 >::send().
Referenced by testMMenz().
void MMenz::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented from EnzBase.
Referenced by testMMenz().
void MMenz::vRemesh (const Eref & e) virtual
Reimplemented from EnzBase.
References convertConcToNumRateUsingMesh().
void MMenz::vSetKcat (const Eref & e, double v) virtual
Implements EnzBase.
Referenced by testMMenz().
void MMenz::vSetKm (const Eref & e, double v) virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh().
Referenced by testMMenz().
void MMenz::vSetNumKm (const Eref & e, double v) virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh().
void MMenz::vSub (double n) virtual
Reimplemented from EnzBase.
Referenced by testMMenz().
The documentation for this class was generated from the following files:
kinetics/MMenz.h
kinetics/MMenz.cpp