MOOSE: SpikeGen Class Reference
SpikeGen Class Reference
#include <SpikeGen.h>
Public Member Functions
SpikeGen ()
void setThreshold (double threshold)
double getThreshold () const
void setRefractT (double val)
double getRefractT () const
bool getFired () const
void setEdgeTriggered (bool yes)
bool getEdgeTriggered () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void handleVm (double val)
Static Public Member Functions
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
SpikeGen::SpikeGen ()
Member Function Documentation
bool SpikeGen::getEdgeTriggered () const
Referenced by initCinfo().
bool SpikeGen::getFired () const
Referenced by initCinfo().
double SpikeGen::getRefractT () const
Referenced by initCinfo().
double SpikeGen::getThreshold () const
Referenced by initCinfo().
void SpikeGen::handleVm (double val)
Referenced by initCinfo(), and SpikeGenStruct::send().
const Cinfo * SpikeGen::initCinfo () static
References getEdgeTriggered(), getFired(), getRefractT(), getThreshold(), handleVm(), Neutral::initCinfo(), process(), reinit(), setEdgeTriggered(), setRefractT(), and setThreshold().
void SpikeGen::process (const Eref & e, ProcPtr p)
References ProcInfo::currTime, and ProcInfo::dt.
Referenced by initCinfo(), and SpikeGenStruct::send().
void SpikeGen::reinit (const Eref & e, ProcPtr p)
Referenced by initCinfo(), and SpikeGenStruct::reinit().
void SpikeGen::setEdgeTriggered (bool yes)
Referenced by initCinfo().
void SpikeGen::setRefractT (double val)
Referenced by initCinfo().
void SpikeGen::setThreshold (double threshold)
Referenced by initCinfo().
The documentation for this class was generated from the following files:
biophysics/SpikeGen.h
biophysics/SpikeGen.cpp