MOOSE: GapJunction Class Reference
GapJunction Class Reference
#include <GapJunction.h>
Public Member Functions
GapJunction ()
~GapJunction ()
void setVm1 (double Vm)
void setVm2 (double Vm)
void setGk (double g)
double getGk () const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
double Vm1_
double Vm2_
double Gk_
Constructor & Destructor Documentation
GapJunction::GapJunction ()
GapJunction::~GapJunction ()
Member Function Documentation
double GapJunction::getGk () const
References Gk_.
Referenced by initCinfo().
const Cinfo * GapJunction::initCinfo () static
Initializes the class info.
References getGk(), Neutral::initCinfo(), process(), reinit(), setGk(), setVm1(), and setVm2().
void GapJunction::process (const Eref & e, ProcPtr p)
The process function does the object updating and sends out messages to channels, nernsts, and so on.
References Gk_, Vm1_, and Vm2_.
Referenced by initCinfo().
void GapJunction::reinit (const Eref & e, ProcPtr p)
The reinit function reinitializes all fields.
References Vm1_, and Vm2_.
Referenced by initCinfo().
void GapJunction::setGk (double g)
References Gk_.
Referenced by initCinfo().
void GapJunction::setVm1 (double Vm)
References Vm1_.
Referenced by initCinfo().
void GapJunction::setVm2 (double Vm)
References Vm2_.
Referenced by initCinfo().
Member Data Documentation
double GapJunction::Gk_ protected
Referenced by getGk(), process(), and setGk().
double GapJunction::Vm1_ protected
Referenced by process(), reinit(), and setVm1().
double GapJunction::Vm2_ protected
Referenced by process(), reinit(), and setVm2().
The documentation for this class was generated from the following files:
biophysics/GapJunction.h
biophysics/GapJunction.cpp