MOOSE: Vec Class Reference
Vec Class Reference
#include <Vec.h>
Public Member Functions
Vec (double a0, double a1, double a2)
Vec ()
double length () const
double distance (const Vec &other) const
double dotProduct (const Vec &other) const
Vec crossProduct (const Vec &other) const
void unitLength ()
Rescales vector so it has unit length.
void orthogonalAxes (Vec &u, Vec &v) const
Generates vectors u and v to form a mutually orthogonal system.
double a0 () const
double a1 () const
double a2 () const
Vec pointOnLine (const Vec &end, double k)
bool operator== (const Vec &other) const
Vec operator- (const Vec &other) const
Constructor & Destructor Documentation
Vec::Vec (double a0, double a1, double a2)
Vec::Vec () inline
Referenced by crossProduct(), operator-(), orthogonalAxes(), and pointOnLine().
Member Function Documentation
double Vec::a0 () const inline
Referenced by fillPointsOnCircle(), NeuroMesh::indexToSpace(), CylBase::matchCubeMeshEntries(), and CylMesh::matchCubeMeshEntries().
double Vec::a1 () const inline
Referenced by fillPointsOnCircle(), NeuroMesh::indexToSpace(), CylBase::matchCubeMeshEntries(), and CylMesh::matchCubeMeshEntries().
double Vec::a2 () const inline
Referenced by fillPointsOnCircle(), NeuroMesh::indexToSpace(), CylBase::matchCubeMeshEntries(), and CylMesh::matchCubeMeshEntries().
Vec Vec::crossProduct (const Vec & other) const
References Vec().
Referenced by orthogonalAxes(), and testVec().
double Vec::distance (const Vec & other) const
Referenced by CylBase::nearest(), PsdMesh::nearest(), and SpineMesh::nearest().
double Vec::dotProduct (const Vec & other) const
Referenced by testVec().
double Vec::length () const
Referenced by orthogonalAxes(), and unitLength().
Vec Vec::operator- (const Vec & other) const
References Vec().
bool Vec::operator== (const Vec & other) const
References doubleEq().
void Vec::orthogonalAxes (Vec & u, Vec & v) const
Generates vectors u and v to form a mutually orthogonal system.
References crossProduct(), doubleApprox(), doubleEq(), length(), unitLength(), and Vec().
Referenced by CylBase::matchCubeMeshEntries(), CylMesh::matchCubeMeshEntries(), and testVec().
Vec Vec::pointOnLine (const Vec & end, double k)
Returns a point on the line from self to 'end', a fraction k from the 'self'. r = self + k.(end - self)
References Vec().
Referenced by CylBase::nearest().
void Vec::unitLength ()
Rescales vector so it has unit length.
References length().
Referenced by orthogonalAxes().
The documentation for this class was generated from the following files:
utility/Vec.h
utility/Vec.cpp