MOOSE: SrcFinfo5< T1, T2, T3, T4, T5 > Class Template Reference
SrcFinfo5< T1, T2, T3, T4, T5 > Class Template Reference
#include <SrcFinfo.h>
Public Member Functions
~SrcFinfo5 ()
SrcFinfo5 (const string &name, const string &doc)
void send (const Eref &e, const T1 &arg1, const T2 &arg2, const T3 &arg3, const T4 &arg4, const T5 &arg5) const
void sendBuffer (const Eref &e, double *buf) const
string rttiType () const
Public Member Functions inherited from SrcFinfo
SrcFinfo (const string &name, const string &doc)
~SrcFinfo ()
void registerFinfo (Cinfo *c)
bool strSet (const Eref &tgt, const string &field, const string &arg) const
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
BindIndex getBindIndex () const
void setBindIndex (BindIndex b)
bool checkTarget (const Finfo *target) const
bool addMsg (const Finfo *target, ObjId mid, Element *src) const
Public Member Functions inherited from Finfo
Finfo (const string &name, const string &doc)
virtual ~Finfo ()
const string & name () const
const string & docs () const
Returns documentation string.
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual vector< string > innerSrc () const
virtual vector< string > innerDest () const
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Static Public Attributes inherited from SrcFinfo
static const BindIndex BadBindIndex = 65535
Constructor & Destructor Documentation
template<class T1, class T2, class T3, class T4, class T5> SrcFinfo5< T1, T2, T3, T4, T5 >::~SrcFinfo5 () inline
template<class T1, class T2, class T3, class T4, class T5> SrcFinfo5< T1, T2, T3, T4, T5 >::SrcFinfo5 (const string & name, const string & doc) inline
Member Function Documentation
template<class T1, class T2, class T3, class T4, class T5> string SrcFinfo5< T1, T2, T3, T4, T5 >::rttiType () const inline virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
References Conv< T >::rttiType().
template<class T1, class T2, class T3, class T4, class T5> void SrcFinfo5< T1, T2, T3, T4, T5 >::send (const Eref & e, const T1 & arg1, const T2 & arg2, const T3 & arg3, const T4 & arg4, const T5 & arg5) const inline
References ALLDATA, Eref::element(), SrcFinfo::getBindIndex(), Element::localDataStart(), Eref::msgDigest(), Element::numData(), and OpFunc5Base< A1, A2, A3, A4, A5 >::op().
Referenced by SrcFinfo5< T1, T2, T3, T4, T5 >::sendBuffer().
template<class T1, class T2, class T3, class T4, class T5> void SrcFinfo5< T1, T2, T3, T4, T5 >::sendBuffer (const Eref & e, double * buf) const inline virtual
Sends contents of buffer on to msg targets Buffer has a header with the TgtInfo.
Implements SrcFinfo.
References Conv< T >::buf2val(), and SrcFinfo5< T1, T2, T3, T4, T5 >::send().
The documentation for this class was generated from the following file:
basecode/SrcFinfo.h