MOOSE: DataElement Class Reference
DataElement Class Reference
#include <DataElement.h>
Public Member Functions
DataElement (Id id, const Cinfo *c, const string &name, unsigned int numData=1)
DataElement (Id id, const Element *orig, unsigned int n, unsigned int startEntry)
~DataElement ()
unsigned int numLocalData () const
Defined only in derived classes: unsigned int numData() const;.
unsigned int numField (unsigned int rawIndex) const
Define only in derived classes: getNode(unsigned int dataIndex) const;.
unsigned int totNumLocalField () const
bool hasFields () const
Do not define getNode() or rawIndex() funcs, those are derived.
char * data (unsigned int rawIndex, unsigned int fieldIndex=0) const
void resize (unsigned int newNumData)
void resizeField (unsigned int rawIndex, unsigned int newNumField)
void zombieSwap (const Cinfo *newCinfo)
Virtual func.
Public Member Functions inherited from Element
Element (Id id, const Cinfo *c, const string &name)
virtual ~Element ()
virtual Element * copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const =0
const string & getName () const
void setName (const string &val)
virtual unsigned int numData () const =0
Returns number of data entries across all nodes.
virtual unsigned int localDataStart () const =0
Returns index of first data entry on this node.
virtual unsigned int getNode (unsigned int dataIndex) const =0
Returns node number of specified dataIndex.
virtual unsigned int startDataIndex (unsigned int nodeNum) const =0
Returns start dataIndex on specified node.
virtual unsigned int rawIndex (unsigned int dataIndex) const =0
Id id () const
virtual bool isGlobal () const =0
True if there is a copy of every dataEntry on all nodes.
virtual unsigned int getNumOnNode (unsigned int node) const =0
int getTick () const
void setTick (int t)
void innerSetTick (unsigned int tick)
void addMsg (ObjId mid)
void dropMsg (ObjId mid)
void clearBinding (BindIndex b)
void addMsgAndFunc (ObjId mid, FuncId fid, BindIndex bindIndex)
const vector< MsgFuncBinding > * getMsgAndFunc (BindIndex b) const
bool hasMsgs (BindIndex b) const
void showFields () const
void showMsg () const
void digestMessages ()
void putTargetsInDigest (unsigned int srcNum, const MsgFuncBinding &mfb, const FuncOrder &fo, vector< vector< bool > > &targetNodes)
void putOffNodeTargetsInDigest (unsigned int srcNum, vector< vector< bool > > &targetNodes)
const Cinfo * cinfo () const
void markAsDoomed ()
bool isDoomed () const
void markRewired ()
void printMsgDigest (unsigned int srcIndex, unsigned int dataIndex) const
void dropAllMsgsFromSrc (Id src)
const vector< MsgDigest > & msgDigest (unsigned int index)
unsigned int findBinding (MsgFuncBinding b) const
const vector< ObjId > & msgIn () const
ObjId findCaller (FuncId fid) const
unsigned int getInputMsgs (vector< ObjId > &caller, FuncId fid) const
unsigned int getNeighbors (vector< Id > &ret, const Finfo *finfo) const
unsigned int getFieldsOfOutgoingMsg (ObjId mid, vector< pair< BindIndex, FuncId > > &ret) const
unsigned int getMsgTargetAndFunctions (DataId srcDataId, const SrcFinfo *finfo, vector< ObjId > &tgt, vector< string > &func) const
vector< ObjId > getMsgTargets (DataId srcDataId, const SrcFinfo *finfo) const
void clearAllMsgs ()
Used upon ending of MOOSE session, to rapidly clear out messages.
void replaceCinfo (const Cinfo *newCinfo)
Support function for zombieSwap, replaces Cinfo.
Additional Inherited Members
Static Public Member Functions inherited from Element
static void destroyElementTree (const vector< Id > &tree)
Detailed Description
This is the base class for managing the data in the MOOSE interface. Elaborates on base class for how it handles destruction. Subclasses of this handle special node decomposition. This does basic data management with raw indices.
Constructor & Destructor Documentation
DataElement::DataElement (Id id, const Cinfo * c, const string & name, unsigned int numData = 1)
This is the main constructor, used by Shell::innerCreate which makes most Elements. Also used to create base Elements to init the simulator in main.cpp. Id is the Id of the new Element Cinfo is the class name is its name numData is the number of data entries, defaults to a singleton. The isGlobal flag specifies whether the created objects should be replicated on all nodes, or partitioned without replication.
DataElement::DataElement (Id id, const Element * orig, unsigned int n, unsigned int startEntry)
This constructor copies over the original n times. It is used for doing all copies, in Shell::innerCopyElements.
References Element::cinfo(), DinfoBase::copyData(), Element::data(), Cinfo::dinfo(), Element::numData(), and DinfoBase::sizeIncrement().
DataElement::~DataElement ()
Virtual Destructor
References Element::cinfo(), DinfoBase::destroyData(), and Cinfo::dinfo().
Member Function Documentation
char * DataElement::data (unsigned int rawIndex, unsigned int fieldIndex = 0) const virtual
Inherited virtual. Looks up specified field data entry. On regular objects just returns the data entry specified by the rawIndex. On FieldElements like synapses, does a second lookup on the field index. Note that the index is NOT a DataIndex: it is instead the raw index of the data on the current node. Index is also NOT the character offset, but the index to the data array in whatever type the data may be.
The DataIndex has to be filtered through the nodeMap to find a) if the entry is here, and b) what its raw index is.
Returns 0 if either index is out of range.
Implements Element.
bool DataElement::hasFields () const inline virtual
Do not define getNode() or rawIndex() funcs, those are derived.
Inherited virtual True if this is a FieldElement having an array of fields on each data entry. Clearly not true for the base Element.
Implements Element.
unsigned int DataElement::numField (unsigned int rawIndex) const virtual
Define only in derived classes: getNode(unsigned int dataIndex) const;.
Inherited virtual. Returns number of field entries for specified data
Implements Element.
unsigned int DataElement::numLocalData () const virtual
Defined only in derived classes: unsigned int numData() const;.
copyElement function is defined only in derived classes.Inherited virtual. Returns number of data entries on this node
Implements Element.
Referenced by LocalDataElement::getNode(), GlobalDataElement::getNumOnNode(), and GlobalDataElement::numData().
void DataElement::resize (unsigned int newNumLocalData) virtual
Inherited virtual. Changes the total number of data entries on Element in entire simulation. Not permitted for FieldElements since they are just fields on the data.
virtual func, overridden. Here we resize the local data. This function would be called by derived classes to do their own data management as per node decomposition.
Implements Element.
Reimplemented in LocalDataElement.
References Element::cinfo(), DinfoBase::copyData(), DinfoBase::destroyData(), and Cinfo::dinfo().
Referenced by LocalDataElement::resize().
void DataElement::resizeField (unsigned int rawIndex, unsigned int newNumField) inline virtual
Inherited virtual. Changes the number of fields on the specified data entry. Doesn't do anything for the regular Element.
Implements Element.
unsigned int DataElement::totNumLocalField () const virtual
Inherited virtual: Returns number of field entries on current node, same as numLocalData().
Implements Element.
void DataElement::zombieSwap (const Cinfo * newCinfo) virtual
Virtual func.
Reimplemented from Element.
References DinfoBase::allocData(), Element::cinfo(), DinfoBase::destroyData(), Cinfo::dinfo(), Element::replaceCinfo(), DinfoBase::sizeIncrement(), and Element::zombieSwap().
The documentation for this class was generated from the following files:
basecode/DataElement.h
basecode/DataElement.cpp