MOOSE: LocalDataElement Class Reference
LocalDataElement Class Reference
#include <LocalDataElement.h>
Public Member Functions
LocalDataElement (Id id, const Cinfo *c, const string &name, unsigned int numData=1)
LocalDataElement (Id id, const Element *orig, unsigned int n)
~LocalDataElement ()
Element * copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const
unsigned int numData () const
Inherited virtual. Returns number of data entries over all nodes.
unsigned int localDataStart () const
Inherited virtual. Returns index of first entry on this node.
unsigned int getNode (unsigned int dataId) const
Inherited virtual. Returns node location of specified object.
unsigned int startDataIndex (unsigned int node) const
Inherited virtual. Returns start DataIndex on specified node.
unsigned int rawIndex (unsigned int dataId) const
Converts dataId to index on current node.
bool isGlobal () const
Inherited virtual. Reports if this is Global, which it isn't.
unsigned int getNumOnNode (unsigned int node) const
Inherited virtual.
void resize (unsigned int newNumData)
unsigned int setDataSize (unsigned int numData)
Public Member Functions inherited from DataElement
DataElement (Id id, const Cinfo *c, const string &name, unsigned int numData=1)
DataElement (Id id, const Element *orig, unsigned int n, unsigned int startEntry)
~DataElement ()
unsigned int numLocalData () const
Defined only in derived classes: unsigned int numData() const;.
unsigned int numField (unsigned int rawIndex) const
Define only in derived classes: getNode(unsigned int dataIndex) const;.
unsigned int totNumLocalField () const
bool hasFields () const
Do not define getNode() or rawIndex() funcs, those are derived.
char * data (unsigned int rawIndex, unsigned int fieldIndex=0) const
void resizeField (unsigned int rawIndex, unsigned int newNumField)
void zombieSwap (const Cinfo *newCinfo)
Virtual func.
Public Member Functions inherited from Element
Element (Id id, const Cinfo *c, const string &name)
virtual ~Element ()
const string & getName () const
void setName (const string &val)
Id id () const
int getTick () const
void setTick (int t)
void innerSetTick (unsigned int tick)
void addMsg (ObjId mid)
void dropMsg (ObjId mid)
void clearBinding (BindIndex b)
void addMsgAndFunc (ObjId mid, FuncId fid, BindIndex bindIndex)
const vector< MsgFuncBinding > * getMsgAndFunc (BindIndex b) const
bool hasMsgs (BindIndex b) const
void showFields () const
void showMsg () const
void digestMessages ()
void putTargetsInDigest (unsigned int srcNum, const MsgFuncBinding &mfb, const FuncOrder &fo, vector< vector< bool > > &targetNodes)
void putOffNodeTargetsInDigest (unsigned int srcNum, vector< vector< bool > > &targetNodes)
const Cinfo * cinfo () const
void markAsDoomed ()
bool isDoomed () const
void markRewired ()
void printMsgDigest (unsigned int srcIndex, unsigned int dataIndex) const
void dropAllMsgsFromSrc (Id src)
const vector< MsgDigest > & msgDigest (unsigned int index)
unsigned int findBinding (MsgFuncBinding b) const
const vector< ObjId > & msgIn () const
ObjId findCaller (FuncId fid) const
unsigned int getInputMsgs (vector< ObjId > &caller, FuncId fid) const
unsigned int getNeighbors (vector< Id > &ret, const Finfo *finfo) const
unsigned int getFieldsOfOutgoingMsg (ObjId mid, vector< pair< BindIndex, FuncId > > &ret) const
unsigned int getMsgTargetAndFunctions (DataId srcDataId, const SrcFinfo *finfo, vector< ObjId > &tgt, vector< string > &func) const
vector< ObjId > getMsgTargets (DataId srcDataId, const SrcFinfo *finfo) const
void clearAllMsgs ()
Used upon ending of MOOSE session, to rapidly clear out messages.
void replaceCinfo (const Cinfo *newCinfo)
Support function for zombieSwap, replaces Cinfo.
Additional Inherited Members
Static Public Member Functions inherited from Element
static void destroyElementTree (const vector< Id > &tree)
Detailed Description
This is the class for handling the local portion of a data element that is distributed over many nodes. Does block-wise partitioning between nodes.
Constructor & Destructor Documentation
LocalDataElement::LocalDataElement (Id id, const Cinfo * c, const string & name, unsigned int numData = 1)
This is the main constructor, used by Shell::innerCreate which makes most Elements. Also used to create base Elements to init the simulator in main.cpp. Id is the Id of the new Element Cinfo is the class name is its name numData is the number of data entries, defaults to a singleton.
Referenced by copyElement().
LocalDataElement::LocalDataElement (Id id, const Element * orig, unsigned int n)
This constructor copies over the original n times. It is used for doing all copies, in Shell::innerCopyElements.
LocalDataElement::~LocalDataElement ()
Virtual Destructor
Member Function Documentation
Element * LocalDataElement::copyElement (Id newParent, Id newId, unsigned int n, bool toGlobal) const virtual
Virtual copier. Makes a copy of self.
Implements Element.
References LocalDataElement().
unsigned int LocalDataElement::getNode (unsigned int dataId) const virtual
Inherited virtual. Returns node location of specified object.
Implements Element.
References ALLDATA, Shell::myNode(), and DataElement::numLocalData().
unsigned int LocalDataElement::getNumOnNode (unsigned int node) const virtual
Inherited virtual.
Implements Element.
References numData().
bool LocalDataElement::isGlobal () const inline virtual
Inherited virtual. Reports if this is Global, which it isn't.
Implements Element.
unsigned int LocalDataElement::localDataStart () const virtual
Inherited virtual. Returns index of first entry on this node.
Implements Element.
unsigned int LocalDataElement::numData () const virtual
Inherited virtual. Returns number of data entries over all nodes.
Implements Element.
Referenced by getNumOnNode(), and setDataSize().
unsigned int LocalDataElement::rawIndex (unsigned int dataId) const virtual
Converts dataId to index on current node.
Implements Element.
void LocalDataElement::resize (unsigned int newNumData) virtual
the data() function is inherited from DataElement and used as is. Inherited virtual. Changes the total number of data entries on Element in entire simulation. Not permitted for FieldElements since they are just fields on the data.
Reimplemented from DataElement.
References DataElement::resize(), and setDataSize().
unsigned int LocalDataElement::setDataSize (unsigned int numData)
References Shell::myNode(), numData(), and Shell::numNodes().
Referenced by resize().
unsigned int LocalDataElement::startDataIndex (unsigned int node) const virtual
Inherited virtual. Returns start DataIndex on specified node.
Inherited virtual. Returns start DataId on specified node.
Implements Element.
The documentation for this class was generated from the following files:
basecode/LocalDataElement.h
basecode/LocalDataElement.cpp