MOOSE: NMDAChan Class Reference
NMDAChan Class Reference
#include <NMDAChan.h>
Public Member Functions
NMDAChan ()
~NMDAChan ()
void setKMg_A (double Gbar)
double getKMg_A () const
void setKMg_B (double Ek)
double getKMg_B () const
void setCMg (double CMg)
double getCMg () const
void setTemperature (double temperature)
double getTemperature () const
void setExtCa (double conc)
double getExtCa () const
Set external conc.
void setIntCa (double conc)
double getIntCa () const
Set external conc.
double getICa () const
void setPermeability (double permeability)
double getPermeability () const
void setIntCaScale (double v)
double getIntCaScale () const
void setIntCaOffset (double v)
double getIntCaOffset () const
void setCondFraction (double v)
double getCondFraction () const
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void assignIntCa (double v)
Public Member Functions inherited from SynChan
SynChan ()
~SynChan ()
void setTau1 (double tau1)
double getTau1 () const
void setTau2 (double tau2)
double getTau2 () const
void setNormalizeWeights (bool value)
bool getNormalizeWeights () const
void vSetGbar (const Eref &e, double Gbar)
void normalizeGbar ()
double calcGk ()
Update alpha function terms for synaptic channel.
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void activation (double val)
void modulator (double val)
Public Member Functions inherited from ChanCommon
ChanCommon ()
~ChanCommon ()
double vGetGbar (const Eref &e) const
void vSetEk (const Eref &e, double Ek)
double vGetEk (const Eref &e) const
void vSetGk (const Eref &e, double Gk)
double vGetGk (const Eref &e) const
void vSetIk (const Eref &e, double Ic)
double vGetIk (const Eref &e) const
void vHandleVm (double Vm)
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double getVm () const
Utility function to access Vm.
double getGbar () const
Utility function to acces Gbar.
Public Member Functions inherited from ChanBase
ChanBase ()
~ChanBase ()
void setGbar (const Eref &e, double Gbar)
double getGbar (const Eref &e) const
void setEk (const Eref &e, double Ek)
double getEk (const Eref &e) const
void setGk (const Eref &e, double Gk)
double getGk (const Eref &e) const
void setIk (const Eref &e, double Ic)
double getIk (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from SynChan
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo1< double > * permeability ()
static SrcFinfo2< double,
double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Additional Inherited Members
Protected Attributes inherited from SynChan
double tau1_
double tau2_
int normalizeWeights_
double xconst1_
double yconst1_
double xconst2_
double yconst2_
double norm_
double activation_
double modulation_
double X_
double Y_
double dt_
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Detailed Description
The NMDAChan incorporates calculations for Mg block, Nernst potential and/or GHK estimates for the fraction of current carried by Ca. These can also be done by messaging but it is messy and slow, so I've lumped them. Also I've assumed that we're only dealing with the GHK equation for Ca. This is not so good considering that other ions also go through the channel.
Constructor & Destructor Documentation
NMDAChan::NMDAChan ()
NMDAChan::~NMDAChan ()
Member Function Documentation
void NMDAChan::assignIntCa (double v)
Referenced by initCinfo().
double NMDAChan::getCMg () const
Referenced by initCinfo().
double NMDAChan::getCondFraction () const
Referenced by initCinfo().
double NMDAChan::getExtCa () const
Set external conc.
Referenced by initCinfo().
double NMDAChan::getICa () const
Referenced by initCinfo().
double NMDAChan::getIntCa () const
Set external conc.
Referenced by initCinfo().
double NMDAChan::getIntCaOffset () const
Referenced by initCinfo().
double NMDAChan::getIntCaScale () const
Referenced by initCinfo().
double NMDAChan::getKMg_A () const
Referenced by initCinfo().
double NMDAChan::getKMg_B () const
Referenced by initCinfo().
double NMDAChan::getPermeability () const
double NMDAChan::getTemperature () const
Referenced by initCinfo().
const Cinfo * NMDAChan::initCinfo () static
References assignIntCa(), getCMg(), getCondFraction(), getExtCa(), ChanBase::getGbar(), getICa(), getIntCa(), getIntCaOffset(), getIntCaScale(), getKMg_A(), getKMg_B(), getTemperature(), ICaOut(), SynChan::initCinfo(), ChanBase::permeability(), setCMg(), setCondFraction(), setExtCa(), ChanBase::setGbar(), setIntCa(), setIntCaOffset(), setIntCaScale(), setKMg_A(), setKMg_B(), and setTemperature().
void NMDAChan::setCMg (double CMg)
References EPSILON.
Referenced by initCinfo().
void NMDAChan::setCondFraction (double v)
Referenced by initCinfo().
void NMDAChan::setExtCa (double conc)
References EPSILON.
Referenced by initCinfo().
void NMDAChan::setIntCa (double conc)
Referenced by initCinfo().
void NMDAChan::setIntCaOffset (double v)
Referenced by initCinfo().
void NMDAChan::setIntCaScale (double v)
Referenced by initCinfo().
void NMDAChan::setKMg_A (double Gbar)
References EPSILON.
Referenced by initCinfo().
void NMDAChan::setKMg_B (double Ek)
References EPSILON.
Referenced by initCinfo().
void NMDAChan::setPermeability (double permeability)
void NMDAChan::setTemperature (double temperature)
References EPSILON, FaradayConst, and GasConst.
Referenced by initCinfo().
void NMDAChan::vProcess (const Eref & e, ProcPtr info) virtual
Note the implicit mapping between permeability and conductance. From the GENESIS source code: A thought about the units, by EDS 6/95 (based on Hille 92): Units: p in M/s EF/RT and z are dimensionless F in C/mol Cin and Cout in mM==mol/m^3 Then Ik is really in units of C/s/m^2==A/m^2, so we compute a current density. As we replace in practice p by Gbar, which has already been scaled for surface, we get rid of the density factor.
Implements ChanBase.
References SynChan::calcGk(), ICaOut(), ChanCommon::sendProcessMsgs(), ChanBase::setGk(), ChanCommon::updateIk(), and ChanCommon::Vm_.
void NMDAChan::vReinit (const Eref & e, ProcPtr p) virtual
Implements ChanBase.
References EPSILON, ICaOut(), ChanCommon::sendReinitMsgs(), and SynChan::vReinit().
The documentation for this class was generated from the following files:
biophysics/NMDAChan.h
biophysics/NMDAChan.cpp