MOOSE: Normal Class Reference
Normal Class Reference
#include <Normal.h>
Public Member Functions
Normal (double mean=0.0, double variance=1.0, NormalGenerator algorithm=ALIAS)
double getMean () const
void setMean (double value)
double getVariance () const
void setVariance (double value)
NormalGenerator getMethod (void)
void setMethod (NormalGenerator method)
double getNextSample () const
Public Member Functions inherited from Probability
virtual ~Probability ()
Constructor & Destructor Documentation
Normal::Normal (double mean = 0.0, double variance = 1.0, NormalGenerator algorithm = ALIAS)
References ALIAS, BOX_MUELLER, and ZIGGURAT.
Member Function Documentation
double Normal::getMean () const virtual
Implements Probability.
NormalGenerator Normal::getMethod (void)
Referenced by NormalRng::getMethod(), and NormalRng::setMethod().
double Normal::getNextSample () const virtual
Implements Probability.
double Normal::getVariance () const virtual
Implements Probability.
void Normal::setMean (double value)
Referenced by NormalRng::setMean().
void Normal::setMethod (NormalGenerator method)
References ALIAS, BOX_MUELLER, and ZIGGURAT.
Referenced by NormalRng::setMethod().
void Normal::setVariance (double value)
Referenced by NormalRng::setVariance().
The documentation for this class was generated from the following files:
randnum/Normal.h
randnum/Normal.cpp