MOOSE: MarkovSolverBase Class Reference
MarkovSolverBase Class Reference
#include <MarkovSolverBase.h>
Public Member Functions
MarkovSolverBase ()
virtual ~MarkovSolverBase ()
Matrix getQ () const
Vector getState () const
Vector getInitialState () const
void setInitialState (Vector)
void setXmin (double)
double getXmin () const
void setXmax (double)
double getXmax () const
void setXdivs (unsigned int)
unsigned int getXdivs () const
double getInvDx () const
void setYmin (double)
double getYmin () const
void setYmax (double)
double getYmax () const
void setYdivs (unsigned int)
unsigned int getYdivs () const
double getInvDy () const
void innerFillupTable (vector< unsigned int >, string, unsigned int, unsigned int)
void fillupTable ()
virtual Matrix * computeMatrixExponential ()
Vector * bilinearInterpolate () const
Vector * linearInterpolate () const
void computeState ()
void reinit (const Eref &, ProcPtr)
void process (const Eref &, ProcPtr)
void handleVm (double)
void handleLigandConc (double)
void init (Id, double)
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
Matrix * Q_
Constructor & Destructor Documentation
MarkovSolverBase::MarkovSolverBase ()
MarkovSolverBase::~MarkovSolverBase () virtual
References Q_.
Member Function Documentation
Vector * MarkovSolverBase::bilinearInterpolate () const
References vecMatMul(), and vecVecScalAdd().
Referenced by computeState().
Matrix * MarkovSolverBase::computeMatrixExponential () virtual
Reimplemented in MarkovSolver.
Referenced by fillupTable().
void MarkovSolverBase::computeState ()
References MarkovRateTable::areAllRates1d(), MarkovRateTable::areAnyRates2d(), MarkovRateTable::areAnyRatesLigandDep(), MarkovRateTable::areAnyRatesVoltageDep(), bilinearInterpolate(), and linearInterpolate().
Referenced by process().
void MarkovSolverBase::fillupTable ()
References MarkovRateTable::areAllRates1d(), MarkovRateTable::areAllRatesConstant(), MarkovRateTable::areAllRatesLigandDep(), MarkovRateTable::areAllRatesVoltageDep(), MarkovRateTable::areAnyRates2d(), MarkovRateTable::areAnyRatesLigandDep(), MarkovRateTable::areAnyRatesVoltageDep(), computeMatrixExponential(), MarkovRateTable::getListOf1dRates(), MarkovRateTable::getListOf2dRates(), MarkovRateTable::getListOfConstantRates(), MarkovRateTable::getListOfLigandRates(), MarkovRateTable::getListOfVoltageRates(), and innerFillupTable().
Referenced by init().
Vector MarkovSolverBase::getInitialState () const
Referenced by initCinfo().
double MarkovSolverBase::getInvDx () const
Referenced by initCinfo().
double MarkovSolverBase::getInvDy () const
Referenced by initCinfo().
Matrix MarkovSolverBase::getQ () const
References Q_.
Referenced by initCinfo().
Vector MarkovSolverBase::getState () const
Referenced by initCinfo().
unsigned int MarkovSolverBase::getXdivs () const
Referenced by initCinfo().
double MarkovSolverBase::getXmax () const
Referenced by initCinfo().
double MarkovSolverBase::getXmin () const
Referenced by initCinfo().
unsigned int MarkovSolverBase::getYdivs () const
Referenced by initCinfo().
double MarkovSolverBase::getYmax () const
Referenced by initCinfo().
double MarkovSolverBase::getYmin () const
Referenced by initCinfo().
void MarkovSolverBase::handleLigandConc (double ligandConc)
Referenced by initCinfo().
void MarkovSolverBase::handleVm (double Vm)
Referenced by initCinfo().
void MarkovSolverBase::init (Id rateTableId, double dt)
References MarkovRateTable::areAllRates1d(), MarkovRateTable::areAllRatesLigandDep(), MarkovRateTable::areAllRatesVoltageDep(), MarkovRateTable::areAnyRates2d(), MarkovRateTable::areAnyRatesLigandDep(), MarkovRateTable::areAnyRatesVoltageDep(), Eref::data(), Id::eref(), fillupTable(), MarkovRateTable::getSize(), matAlloc(), Q_, and resize().
Referenced by initCinfo().
const Cinfo * MarkovSolverBase::initCinfo () static
References getInitialState(), getInvDx(), getInvDy(), getQ(), getState(), getXdivs(), getXmax(), getXmin(), getYdivs(), getYmax(), getYmin(), handleLigandConc(), handleVm(), init(), Neutral::initCinfo(), process(), reinit(), setInitialState(), setXdivs(), setXmax(), setXmin(), setYdivs(), setYmax(), setYmin(), and stateOut().
Referenced by MarkovSolver::initCinfo().
void MarkovSolverBase::innerFillupTable (vector< unsigned int > , string , unsigned int, unsigned int)
References MarkovRateTable::lookup1dIndex(), MarkovRateTable::lookup1dValue(), MarkovRateTable::lookup2dIndex(), and Q_.
Referenced by fillupTable().
Vector * MarkovSolverBase::linearInterpolate () const
References MarkovRateTable::areAllRatesVoltageDep(), vecMatMul(), and vecVecScalAdd().
Referenced by computeState().
void MarkovSolverBase::process (const Eref & e, ProcPtr p)
References computeState(), and stateOut().
Referenced by initCinfo(), and MarkovSolver::process().
void MarkovSolverBase::reinit (const Eref & e, ProcPtr p)
References stateOut().
Referenced by initCinfo(), and MarkovSolver::reinit().
void MarkovSolverBase::setInitialState (Vector state)
Referenced by initCinfo().
void MarkovSolverBase::setXdivs (unsigned int xDivs)
Referenced by initCinfo().
void MarkovSolverBase::setXmax (double xMax)
Referenced by initCinfo().
void MarkovSolverBase::setXmin (double xMin)
Referenced by initCinfo().
void MarkovSolverBase::setYdivs (unsigned int yDivs)
Referenced by initCinfo().
void MarkovSolverBase::setYmax (double yMax)
Referenced by initCinfo().
void MarkovSolverBase::setYmin (double yMin)
Referenced by initCinfo().
Member Data Documentation
Matrix* MarkovSolverBase::Q_ protected
Referenced by MarkovSolver::computeMatrixExponential(), getQ(), init(), innerFillupTable(), and ~MarkovSolverBase().
The documentation for this class was generated from the following files:
biophysics/MarkovSolverBase.h
biophysics/MarkovSolverBase.cpp