MOOSE: FuncOrder Class Reference
FuncOrder Class Reference
#include <FuncOrder.h>
Public Member Functions
FuncOrder ()
const OpFunc * func () const
unsigned int index () const
void set (const OpFunc *func, unsigned int index)
bool operator< (const FuncOrder &other) const
Detailed Description
Utility function for sorting by function pointer. Used in Element::msgDigest
Constructor & Destructor Documentation
FuncOrder::FuncOrder () inline
Member Function Documentation
const OpFunc* FuncOrder::func () const inline
Referenced by Element::putTargetsInDigest(), and set().
unsigned int FuncOrder::index () const inline
Referenced by set().
bool FuncOrder::operator< (const FuncOrder & other) const inline
void FuncOrder::set (const OpFunc * func, unsigned int index) inline
References func(), and index().
The documentation for this class was generated from the following file:
basecode/FuncOrder.h