MOOSE: Arith Class Reference
Arith Class Reference
#include <Arith.h>
Public Member Functions
Arith ()
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void addSpike (unsigned int synIndex, const double time)
void setFunction (string v)
string getFunction () const
void setOutput (double v)
double getOutput () const
void setIdentifiedArg (unsigned int i, double val)
double getIdentifiedArg (unsigned int i) const
void arg1 (double v)
void arg2 (double v)
void arg3 (double v)
void arg1x2 (double arg1, double arg2)
double getArg1 () const
Static Public Member Functions
static const Cinfo * initCinfo ()
Friends
void testCopyMsgOps ()
void testTicks ()
Constructor & Destructor Documentation
Arith::Arith ()
Member Function Documentation
void Arith::addSpike (unsigned int synIndex, const double time)
Inserts an event into the pendingEvents queue for spikes.
void Arith::arg1 (double v)
Referenced by initCinfo(), testArith(), and testFibonacci().
void Arith::arg1x2 (double arg1, double arg2)
Referenced by initCinfo().
void Arith::arg2 (double v)
Referenced by initCinfo(), testArith(), and testFibonacci().
void Arith::arg3 (double v)
Referenced by initCinfo().
double Arith::getArg1 () const
Referenced by initCinfo(), and testLookupSetGet().
string Arith::getFunction () const
Referenced by initCinfo().
double Arith::getIdentifiedArg (unsigned int i) const
Referenced by initCinfo(), and testLookupSetGet().
double Arith::getOutput () const
Referenced by initCinfo(), testArith(), testFibonacci(), and testLookupSetGet().
const Cinfo * Arith::initCinfo () static
References arg1(), arg1x2(), arg2(), arg3(), getArg1(), getFunction(), getIdentifiedArg(), getOutput(), Neutral::initCinfo(), process(), reinit(), setFunction(), setIdentifiedArg(), and setOutput().
Referenced by test2ArgSetVec(), testArith(), testAssortedMsg(), testCreateMsg(), testFibonacci(), testGet(), testIsA(), testLookupSetGet(), testMsgField(), testSendMsg(), testSetGet(), testSetGetExtField(), testStrGet(), and testStrSet().
void Arith::process (const Eref & e, ProcPtr p)
References Eref::element(), Element::getName(), and Eref::objId().
Referenced by initCinfo(), and testArith().
void Arith::reinit (const Eref & e, ProcPtr p)
Referenced by initCinfo().
void Arith::setFunction (string v)
Referenced by initCinfo().
void Arith::setIdentifiedArg (unsigned int i, double val)
Referenced by initCinfo(), and testLookupSetGet().
void Arith::setOutput (double v)
Referenced by initCinfo().
Friends And Related Function Documentation
void testCopyMsgOps () friend
void testTicks () friend
The documentation for this class was generated from the following files:
builtins/Arith.h
builtins/Arith.cpp