MOOSE: PulseGen Class Reference
PulseGen Class Reference
#include <PulseGen.h>
Public Member Functions
PulseGen ()
~PulseGen ()
void setFirstDelay (double value)
double getFirstDelay () const
void setFirstWidth (double value)
double getFirstWidth () const
void setFirstLevel (double value)
double getFirstLevel () const
void setSecondDelay (double value)
double getSecondDelay () const
void setSecondWidth (double value)
double getSecondWidth () const
void setSecondLevel (double value)
double getSecondLevel () const
void setBaseLevel (double value)
double getBaseLevel () const
void setTrigMode (unsigned int value)
unsigned int getTrigMode () const
double getOutput () const
double getTrigTime () const
int getPreviousInput () const
void setCount (unsigned int count)
unsigned int getCount () const
void setLevel (unsigned int pulseNo, double level)
void setWidth (unsigned int pulseNo, double width)
void setDelay (unsigned int pulseNo, double delay)
double getWidth (unsigned int index) const
double getDelay (unsigned int index) const
double getLevel (unsigned int index) const
void input (double input)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
vector< double > delay_
vector< double > level_
vector< double > width_
double output_
double baseLevel_
double trigTime_
unsigned int trigMode_
bool secondPulse_
int prevInput_
int input_
Detailed Description
PulseGen acts as a pulse generator. It generates square pulses of specified duration and amplitude. Two consecutive pulses are separated by specified delay.
Constructor & Destructor Documentation
PulseGen::PulseGen ()
References baseLevel_, delay_, level_, output_, prevInput_, trigMode_, trigTime_, and width_.
PulseGen::~PulseGen ()
Member Function Documentation
double PulseGen::getBaseLevel () const
References baseLevel_.
Referenced by initCinfo().
unsigned int PulseGen::getCount () const
References level_.
Referenced by initCinfo().
double PulseGen::getDelay (unsigned int index) const
References delay_.
Referenced by initCinfo().
double PulseGen::getFirstDelay () const
References delay_.
Referenced by initCinfo().
double PulseGen::getFirstLevel () const
References level_.
Referenced by initCinfo().
double PulseGen::getFirstWidth () const
References width_.
Referenced by initCinfo().
double PulseGen::getLevel (unsigned int index) const
References level_.
Referenced by initCinfo().
double PulseGen::getOutput () const
References output_.
Referenced by initCinfo().
int PulseGen::getPreviousInput () const
References prevInput_.
double PulseGen::getSecondDelay () const
References delay_.
Referenced by initCinfo().
double PulseGen::getSecondLevel () const
References level_.
Referenced by initCinfo().
double PulseGen::getSecondWidth () const
References width_.
Referenced by initCinfo().
unsigned int PulseGen::getTrigMode () const
References trigMode_.
Referenced by initCinfo().
double PulseGen::getTrigTime () const
double PulseGen::getWidth (unsigned int index) const
References width_.
Referenced by initCinfo().
const Cinfo * PulseGen::initCinfo () static
References getBaseLevel(), getCount(), getDelay(), getFirstDelay(), getFirstLevel(), getFirstWidth(), getLevel(), getOutput(), getSecondDelay(), getSecondLevel(), getSecondWidth(), getTrigMode(), getWidth(), Neutral::initCinfo(), input(), process(), reinit(), setBaseLevel(), setCount(), setDelay(), setFirstDelay(), setFirstLevel(), setFirstWidth(), setLevel(), setSecondDelay(), setSecondLevel(), setSecondWidth(), setTrigMode(), and setWidth().
void PulseGen::input (double input)
References input_.
Referenced by initCinfo().
void PulseGen::process (const Eref & e, ProcPtr p)
References baseLevel_, ProcInfo::currTime, delay_, input_, level_, output_, prevInput_, trigMode_, trigTime_, and width_.
Referenced by initCinfo().
void PulseGen::reinit (const Eref & e, ProcPtr p)
References baseLevel_, input_, output_, prevInput_, and trigTime_.
Referenced by initCinfo().
void PulseGen::setBaseLevel (double value)
References baseLevel_.
Referenced by initCinfo().
void PulseGen::setCount (unsigned int count)
References delay_, level_, and width_.
Referenced by initCinfo().
void PulseGen::setDelay (unsigned int pulseNo, double delay)
References delay_.
Referenced by initCinfo().
void PulseGen::setFirstDelay (double value)
References delay_.
Referenced by initCinfo().
void PulseGen::setFirstLevel (double value)
References level_.
Referenced by initCinfo().
void PulseGen::setFirstWidth (double value)
References width_.
Referenced by initCinfo().
void PulseGen::setLevel (unsigned int pulseNo, double level)
References level_.
Referenced by initCinfo().
void PulseGen::setSecondDelay (double value)
References delay_.
Referenced by initCinfo().
void PulseGen::setSecondLevel (double value)
References level_.
Referenced by initCinfo().
void PulseGen::setSecondWidth (double value)
References width_.
Referenced by initCinfo().
void PulseGen::setTrigMode (unsigned int value)
References trigMode_.
Referenced by initCinfo().
void PulseGen::setWidth (unsigned int pulseNo, double width)
References width_.
Referenced by initCinfo().
Member Data Documentation
double PulseGen::baseLevel_ protected
Referenced by getBaseLevel(), process(), PulseGen(), reinit(), and setBaseLevel().
vector<double> PulseGen::delay_ protected
Referenced by getDelay(), getFirstDelay(), getSecondDelay(), process(), PulseGen(), setCount(), setDelay(), setFirstDelay(), and setSecondDelay().
int PulseGen::input_ protected
Referenced by input(), process(), and reinit().
vector<double> PulseGen::level_ protected
Referenced by getCount(), getFirstLevel(), getLevel(), getSecondLevel(), process(), PulseGen(), setCount(), setFirstLevel(), setLevel(), and setSecondLevel().
double PulseGen::output_ protected
Referenced by getOutput(), process(), PulseGen(), and reinit().
int PulseGen::prevInput_ protected
Referenced by getPreviousInput(), process(), PulseGen(), and reinit().
bool PulseGen::secondPulse_ protected
unsigned int PulseGen::trigMode_ protected
Referenced by getTrigMode(), process(), PulseGen(), and setTrigMode().
double PulseGen::trigTime_ protected
Referenced by process(), PulseGen(), and reinit().
vector<double> PulseGen::width_ protected
Referenced by getFirstWidth(), getSecondWidth(), getWidth(), process(), PulseGen(), setCount(), setFirstWidth(), setSecondWidth(), and setWidth().
The documentation for this class was generated from the following files:
device/PulseGen.h
device/PulseGen.cpp