MOOSE: GetOpFunc< T, A > Class Template Reference
GetOpFunc< T, A > Class Template Reference
#include <OpFunc.h>
Public Member Functions
GetOpFunc (A(T::*func)() const)
void op (const Eref &e, vector< A > *ret) const
A returnOp (const Eref &e) const
Public Member Functions inherited from GetOpFuncBase< A >
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
Public Member Functions inherited from OpFunc1Base< vector< A > * >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
virtual void opVec (const Eref &e, const vector< vector< A > * > &arg, const OpFunc1Base< vector< A > * > *op) const
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
virtual ~OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T, class A>
class GetOpFunc< T, A >
This specialized OpFunc is for returning a single field value It generates an opFunc that takes a single argument, a reference to a vector into which the return value should be appended. It manages the 'get' function that retrieves the return value. Note that the 'get' function must be blocking in case the request goes off node.
Constructor & Destructor Documentation
template<class T, class A> GetOpFunc< T, A >::GetOpFunc (A(T::*)() const func) inline
Member Function Documentation
template<class T, class A> void GetOpFunc< T, A >::op (const Eref & e, vector< A > * ret) const inline virtual
Implements OpFunc1Base< vector< A > * >.
References GetOpFunc< T, A >::returnOp().
Referenced by localGet().
template<class T, class A> A GetOpFunc< T, A >::returnOp (const Eref & e) const inline virtual
Implements GetOpFuncBase< A >.
References Eref::data().
Referenced by GetOpFunc< T, A >::op().
The documentation for this class was generated from the following file:
basecode/OpFunc.h