MOOSE: GetOpFuncBase< A > Class Template Reference
GetOpFuncBase< A > Class Template Reference abstract
#include <OpFuncBase.h>
Public Member Functions
virtual A returnOp (const Eref &e) const =0
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
Public Member Functions inherited from OpFunc1Base< vector< A > * >
bool checkFinfo (const Finfo *s) const
virtual void op (const Eref &e, vector< A > *arg) const =0
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
virtual void opVec (const Eref &e, const vector< vector< A > * > &arg, const OpFunc1Base< vector< A > * > *op) const
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
virtual ~OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class A>
class GetOpFuncBase< A >
This is the base class for all GetOpFuncs.
Member Function Documentation
template<class A > const OpFunc * GetOpFuncBase< A >::makeHopFunc (HopIndex hopIndex) const virtual
Deferred specification of function from OpFunc1Base, so it is after the declaration of the HopFunc class to which it refers.
Implements OpFunc.
Referenced by Field< A >::get(), and Field< A >::getVec().
template<class A> void GetOpFuncBase< A >::opBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc by converting args.
Implements OpFunc.
References GetOpFuncBase< A >::returnOp(), Conv< T >::size(), and Conv< T >::val2buf().
template<class A> virtual A GetOpFuncBase< A >::returnOp (const Eref & e) const pure virtual
Implemented in GetEpFunc< T, A >, and GetOpFunc< T, A >.
Referenced by Field< A >::get(), GetHopFunc< A >::getLocalFieldVec(), GetHopFunc< A >::getLocalVec(), and GetOpFuncBase< A >::opBuffer().
The documentation for this class was generated from the following files:
basecode/OpFuncBase.h
basecode/HopFunc.h