MOOSE: GammaRng Class Reference
GammaRng Class Reference
#include <GammaRng.h>
Public Member Functions
GammaRng ()
virtual ~GammaRng ()
double getAlpha () const
double getTheta () const
void setAlpha (double alpha)
void setTheta (double theta)
virtual void vReinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from RandGenerator
RandGenerator ()
virtual ~RandGenerator ()
double getMean () const
double getVariance () const
double getSample () const
void process (const Eref &e, ProcPtr info)
void reinit (const Eref &e, ProcPtr info)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from RandGenerator
static const Cinfo * initCinfo ()
Additional Inherited Members
Protected Attributes inherited from RandGenerator
Probability * rng_
double sample_
Detailed Description
This is MOOSE wrapper for Gammaly distributed random number generator class, Gamma. The default
Constructor & Destructor Documentation
GammaRng::GammaRng ()
virtual GammaRng::~GammaRng () inline virtual
Member Function Documentation
double GammaRng::getAlpha () const
returns the shape parameter.
Referenced by initCinfo().
double GammaRng::getTheta () const
returns the scale parameter.
Referenced by initCinfo().
const Cinfo * GammaRng::initCinfo () static
References getAlpha(), getTheta(), RandGenerator::initCinfo(), setAlpha(), and setTheta().
void GammaRng::setAlpha (double alpha)
Sets parameter alpha. Also known as the shape parameter.
References Gamma::getAlpha(), and RandGenerator::rng_.
Referenced by initCinfo().
void GammaRng::setTheta (double theta)
Sets parameter theta. Also known as the scale parameter.
References Gamma::getTheta(), and RandGenerator::rng_.
Referenced by initCinfo().
void GammaRng::vReinit (const Eref & e, ProcPtr p) virtual
reports error if parameters have not been set properly.
Reimplemented from RandGenerator.
References RandGenerator::rng_.
The documentation for this class was generated from the following files:
randnum/GammaRng.h
randnum/GammaRng.cpp