MOOSE: ReadCspace Class Reference
ReadCspace Class Reference
#include <ReadCspace.h>
Public Member Functions
ReadCspace ()
void printHeader ()
void printFooter ()
void printMol (Id id, double conc, double concinit, double vol)
void printReac (Id id, double kf, double kb)
void printEnz (Id id, Id cplx, double k1, double k2, double k3)
Id readModelString (const string &model, const string &modelname, Id pa, const string &solverClass)
void makePlots (double plotdt)
void build (const char *name)
void expandEnzyme (const char *name, int e, int s, int p, int p2=0)
void expandReaction (const char *name, int nm1)
void deployParameters ()
void testReadModel ()
void makeMolecule (char name)
Constructor & Destructor Documentation
ReadCspace::ReadCspace ()
Member Function Documentation
void ReadCspace::build (const char * name)
References expandEnzyme(), expandReaction(), and makeMolecule().
Referenced by readModelString().
void ReadCspace::deployParameters ()
References Neutral::children(), and Field< A >::set().
Referenced by readModelString().
void ReadCspace::expandEnzyme (const char * name, int e, int s, int p, int p2 = 0)
References Eref::data(), Shell::doAddMsg(), Shell::doCreate(), and Id::eref().
Referenced by build().
void ReadCspace::expandReaction (const char * name, int nm1)
References Eref::data(), Shell::doAddMsg(), Shell::doCreate(), and Id::eref().
Referenced by build().
void ReadCspace::makeMolecule (char name)
References Eref::data(), Shell::doCreate(), and Id::eref().
Referenced by build().
void ReadCspace::makePlots (double plotdt)
References Neutral::children(), Eref::data(), Shell::doAddMsg(), Shell::doCreate(), Id::eref(), Cinfo::isA(), and Id::path().
Referenced by Shell::doLoadModel().
void ReadCspace::printEnz (Id id, Id cplx, double k1, double k2, double k3)
void ReadCspace::printFooter ()
void ReadCspace::printHeader ()
void ReadCspace::printMol (Id id, double conc, double concinit, double vol)
References Element::cinfo(), ObjId::element(), Element::getName(), Cinfo::isA(), and Neutral::parent().
void ReadCspace::printReac (Id id, double kf, double kb)
Id ReadCspace::readModelString (const string & model, const string & modelname, Id pa, const string & solverClass)
References build(), deployParameters(), makeStandardElements(), Id::path(), and Field< A >::set().
Referenced by Shell::doLoadModel(), and testReadModel().
void ReadCspace::testReadModel ()
References Eref::data(), Shell::doDelete(), doubleEq(), Id::eref(), Field< A >::get(), Id::path(), and readModelString().
Referenced by testReadCspace().
The documentation for this class was generated from the following files:
kinetics/ReadCspace.h
kinetics/ReadCspace.cpp