MOOSE: Variable Class Reference
Variable Class Reference
#include <Variable.h>
Public Member Functions
Variable ()
Variable (const Variable &rhs)
virtual ~Variable ()
void setValue (double v)
void epSetValue (const Eref &e, double v)
double getValue () const
void addMsgCallback (const Eref &e, const string &finfoName, ObjId msg, unsigned int msgLookup)
Static Public Member Functions
static const Cinfo * initCinfo ()
Public Attributes
double value
Detailed Description
This class is used as FieldElement in Function. It is used as named variable of type double.
Constructor & Destructor Documentation
Variable::Variable () inline
Variable::Variable (const Variable & rhs) inline
virtual Variable::~Variable () inline virtual
Member Function Documentation
void Variable::addMsgCallback (const Eref & e, const string & finfoName, ObjId msg, unsigned int msgLookup)
void Variable::epSetValue (const Eref & e, double v) inline
References value.
Referenced by initCinfo().
double Variable::getValue () const inline
References value.
Referenced by initCinfo().
const Cinfo * Variable::initCinfo () static
References epSetValue(), getValue(), Neutral::initCinfo(), setValue(), and value.
Referenced by Function::initCinfo().
void Variable::setValue (double v) inline
References value.
Referenced by initCinfo().
Member Data Documentation
double Variable::value
Referenced by epSetValue(), getValue(), initCinfo(), and setValue().
The documentation for this class was generated from the following files:
builtins/Variable.h
builtins/Variable.cpp