MOOSE: SpikeStats Class Reference
SpikeStats Class Reference
#include <SpikeStats.h>
Public Member Functions
SpikeStats ()
void addSpike (DataId synIndex, const double time)
void setThreshold (double thresh)
double getThreshold () const
void addSpike (double v)
void Vm (double v)
void vProcess (const Eref &e, ProcPtr p)
Virtual func for handling process calls.
void vReinit (const Eref &e, ProcPtr p)
Public Member Functions inherited from Stats
Stats ()
double getMean () const
double getSdev () const
double getSum () const
unsigned int getNum () const
double getWmean () const
double getWsdev () const
double getWsum () const
unsigned int getWnum () const
void setWindowLength (unsigned int len)
unsigned int getWindowLength () const
void input (double v)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void doWindowCalculation () const
void innerWindowCalculation ()
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from Stats
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
SpikeStats::SpikeStats ()
Member Function Documentation
void SpikeStats::addSpike (DataId synIndex, const double time)
Inserts an event into the pendingEvents queue for spikes.
Referenced by initCinfo().
void SpikeStats::addSpike (double v)
double SpikeStats::getThreshold () const
Referenced by initCinfo().
const Cinfo * SpikeStats::initCinfo () static
References addSpike(), getThreshold(), Stats::initCinfo(), setThreshold(), and Vm().
void SpikeStats::setThreshold (double thresh)
Referenced by initCinfo().
void SpikeStats::Vm (double v)
Referenced by initCinfo().
void SpikeStats::vProcess (const Eref & e, ProcPtr p) virtual
Virtual func for handling process calls.
Reimplemented from Stats.
References ProcInfo::dt, and Stats::input().
void SpikeStats::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented from Stats.
References Stats::vReinit().
The documentation for this class was generated from the following files:
builtins/SpikeStats.h
builtins/SpikeStats.cpp