MOOSE: Annotator Class Reference
Annotator Class Reference
#include <Annotator.h>
Public Member Functions
Annotator ()
double getX () const
void setX (double v)
double getY () const
void setY (double v)
double getZ () const
void setZ (double v)
string getNotes () const
void setNotes (string v)
string getColor () const
void setColor (string v)
string getTextColor () const
void setTextColor (string v)
string getIcon () const
void setIcon (string v)
string getSolver () const
void setSolver (string v)
double getRuntime () const
void setRuntime (double v)
string getdirpath () const
void setdirpath (string v)
string getmodeltype () const
void setmodeltype (string v)
Static Public Member Functions
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
Annotator::Annotator ()
Member Function Documentation
string Annotator::getColor () const
Referenced by initCinfo().
string Annotator::getdirpath () const
Referenced by initCinfo().
string Annotator::getIcon () const
Referenced by initCinfo().
string Annotator::getmodeltype () const
Referenced by initCinfo().
string Annotator::getNotes () const
Referenced by initCinfo().
double Annotator::getRuntime () const
Referenced by initCinfo().
string Annotator::getSolver () const
Referenced by initCinfo().
string Annotator::getTextColor () const
Referenced by initCinfo().
double Annotator::getX () const
Referenced by initCinfo().
double Annotator::getY () const
Referenced by initCinfo().
double Annotator::getZ () const
Referenced by initCinfo().
const Cinfo * Annotator::initCinfo () static
References getColor(), getdirpath(), getIcon(), getmodeltype(), getNotes(), getRuntime(), getSolver(), getTextColor(), getX(), getY(), getZ(), Neutral::initCinfo(), setColor(), setdirpath(), setIcon(), setmodeltype(), setNotes(), setRuntime(), setSolver(), setTextColor(), setX(), setY(), setZ(), and y.
void Annotator::setColor (string v)
Referenced by initCinfo().
void Annotator::setdirpath (string v)
Referenced by initCinfo().
void Annotator::setIcon (string v)
Referenced by initCinfo().
void Annotator::setmodeltype (string v)
Referenced by initCinfo().
void Annotator::setNotes (string v)
Referenced by initCinfo().
void Annotator::setRuntime (double v)
Referenced by initCinfo().
void Annotator::setSolver (string v)
Referenced by initCinfo().
void Annotator::setTextColor (string v)
Referenced by initCinfo().
void Annotator::setX (double v)
Referenced by initCinfo().
void Annotator::setY (double v)
Referenced by initCinfo().
void Annotator::setZ (double v)
Referenced by initCinfo().
The documentation for this class was generated from the following files:
utility/Annotator.h
utility/Annotator.cpp