MOOSE: ZombieHHChannel Class Reference
ZombieHHChannel Class Reference
#include <ZombieHHChannel.h>
Public Member Functions
ZombieHHChannel ()
void vSetGbar (const Eref &e, double Gbar)
double vGetGbar (const Eref &e) const
void vSetGk (const Eref &e, double Gk)
double vGetGk (const Eref &e) const
void vSetEk (const Eref &e, double Ek)
double vGetEk (const Eref &e) const
void vSetIk (const Eref &e, double Ik)
double vGetIk (const Eref &e) const
void vSetXpower (const Eref &e, double Xpower)
void vSetYpower (const Eref &e, double Ypower)
void vSetZpower (const Eref &e, double Zpower)
void vSetInstant (const Eref &e, int instant)
int vGetInstant (const Eref &e) const
void vSetX (const Eref &e, double X)
double vGetX (const Eref &e) const
void vSetY (const Eref &e, double Y)
double vGetY (const Eref &e) const
void vSetZ (const Eref &e, double Z)
double vGetZ (const Eref &e) const
void vSetUseConcentration (const Eref &e, int value)
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vHandleConc (const Eref &e, double value)
void vCreateGate (const Eref &e, string name)
void vHandleVm (double Vm)
HHGate * vGetXgate (unsigned int i) const
HHGate * vGetYgate (unsigned int i) const
HHGate * vGetZgate (unsigned int i) const
void vSetSolver (const Eref &e, Id hsolve)
Public Member Functions inherited from HHChannelBase
HHChannelBase ()
~HHChannelBase ()
void setXpower (const Eref &e, double Xpower)
double getXpower (const Eref &e) const
void setYpower (const Eref &e, double Ypower)
double getYpower (const Eref &e) const
void setZpower (const Eref &e, double Zpower)
double getZpower (const Eref &e) const
void setInstant (const Eref &e, int Instant)
int getInstant (const Eref &e) const
void setX (const Eref &e, double X)
double getX (const Eref &e) const
void setY (const Eref &e, double Y)
double getY (const Eref &e) const
void setZ (const Eref &e, double Z)
double getZ (const Eref &e) const
void setUseConcentration (const Eref &e, int value)
int getUseConcentration (const Eref &e) const
void handleConc (const Eref &e, double conc)
HHGate * getXgate (unsigned int i)
HHGate * getYgate (unsigned int i)
HHGate * getZgate (unsigned int i)
void setNumGates (unsigned int num)
unsigned int getNumXgates () const
unsigned int getNumYgates () const
Returns 1 if Y gate present, otherwise 0.
unsigned int getNumZgates () const
Returns 1 if Z gate present, otherwise 0.
void createGate (const Eref &e, string gateType)
virtual void vCreateGate (const Eref &e, string gateType)=0
Public Member Functions inherited from ChanBase
ChanBase ()
~ChanBase ()
void setGbar (const Eref &e, double Gbar)
double getGbar (const Eref &e) const
void setEk (const Eref &e, double Ek)
double getEk (const Eref &e) const
void setGk (const Eref &e, double Gk)
double getGk (const Eref &e) const
void setIk (const Eref &e, double Ic)
double getIk (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from HHChannelBase
static double power1 (double x, double p)
static double power2 (double x, double p)
static double power3 (double x, double p)
static double power4 (double x, double p)
static double powerN (double x, double p)
static PFDD selectPower (double power)
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChanBase
static SrcFinfo1< double > * permeability ()
static SrcFinfo2< double,
double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Additional Inherited Members
Protected Attributes inherited from HHChannelBase
double Xpower_
Exponent for X gate.
double Ypower_
Exponent for Y gate.
double Zpower_
Exponent for Z gate.
bool useConcentration_
Flag for use of conc for input to Z gate calculations.
Detailed Description
Zombie object that lets HSolve do its calculations, while letting the user interact with this object as if it were the original object.
ZombieHHChannel derives directly from Neutral, unlike the regular HHChannel which derives from ChanBase. ChanBase handles fields like Gbar, Gk, Ek, Ik, which are common to HHChannel, SynChan, etc. On the other hand, these fields are stored separately for HHChannel and SynChan in the HSolver. Hence we cannot have a ZombieChanBase which does, for example: hsolve_->setGk(id, Gk); Instead we must have ZombieHHChannel and ZombieSynChan which do: hsolve_->setHHChannelGk(id, Gk); and: hsolve_->setSynChanGk(id, Gk); respectively.
Constructor & Destructor Documentation
ZombieHHChannel::ZombieHHChannel ()
Member Function Documentation
const Cinfo * ZombieHHChannel::initCinfo () static
References HHChannelBase::initCinfo().
void ZombieHHChannel::vCreateGate (const Eref & e, string name)
double ZombieHHChannel::vGetEk (const Eref & e) const virtual
Implements ChanBase.
References HSolve::getEk(), and Eref::id().
double ZombieHHChannel::vGetGbar (const Eref & e) const virtual
Implements ChanBase.
References HSolve::getHHChannelGbar(), and Eref::id().
double ZombieHHChannel::vGetGk (const Eref & e) const virtual
Implements ChanBase.
References HSolve::getGk(), and Eref::id().
double ZombieHHChannel::vGetIk (const Eref & e) const virtual
Implements ChanBase.
References HSolve::getIk(), and Eref::id().
int ZombieHHChannel::vGetInstant (const Eref & e) const virtual
Implements HHChannelBase.
References HSolve::getInstant(), and Eref::id().
double ZombieHHChannel::vGetX (const Eref & e) const virtual
Implements HHChannelBase.
References HSolve::getX(), and Eref::id().
HHGate * ZombieHHChannel::vGetXgate (unsigned int i) const virtual
Access function used for the X gate. The index is ignored.
Implements HHChannelBase.
double ZombieHHChannel::vGetY (const Eref & e) const virtual
Implements HHChannelBase.
References HSolve::getY(), and Eref::id().
HHGate * ZombieHHChannel::vGetYgate (unsigned int i) const virtual
Access function used for the Y gate. The index is ignored.
Implements HHChannelBase.
double ZombieHHChannel::vGetZ (const Eref & e) const virtual
Implements HHChannelBase.
References HSolve::getZ(), and Eref::id().
HHGate * ZombieHHChannel::vGetZgate (unsigned int i) const virtual
Access function used for the Z gate. The index is ignored.
Implements HHChannelBase.
void ZombieHHChannel::vHandleConc (const Eref & e, double value) virtual
Implements HHChannelBase.
void ZombieHHChannel::vHandleVm (double Vm) virtual
Implements ChanBase.
void ZombieHHChannel::vProcess (const Eref & e, ProcPtr p) virtual
Implements ChanBase.
void ZombieHHChannel::vReinit (const Eref & e, ProcPtr p) virtual
Implements ChanBase.
void ZombieHHChannel::vSetEk (const Eref & e, double Ek) virtual
Implements ChanBase.
References Eref::id(), and HSolve::setEk().
void ZombieHHChannel::vSetGbar (const Eref & e, double Gbar) virtual
Implements ChanBase.
References Eref::id(), and HSolve::setHHChannelGbar().
void ZombieHHChannel::vSetGk (const Eref & e, double Gk) virtual
Implements ChanBase.
References Eref::id(), and HSolve::setGk().
void ZombieHHChannel::vSetIk (const Eref & e, double Ik) virtual
Implements ChanBase.
void ZombieHHChannel::vSetInstant (const Eref & e, int instant) virtual
Implements HHChannelBase.
References Eref::id(), and HSolve::setInstant().
void ZombieHHChannel::vSetSolver (const Eref & e, Id hsolve) virtual
Reimplemented from HHChannelBase.
References Element::cinfo(), Eref::data(), Id::element(), Id::eref(), Cinfo::isA(), and Id::path().
void ZombieHHChannel::vSetUseConcentration (const Eref & e, int value) virtual
Not trivial to change Ca-dependence once HSolve has been set up, and unlikely that one would want to change this field after setup, so keeping this field read-only.
Implements HHChannelBase.
void ZombieHHChannel::vSetX (const Eref & e, double X) virtual
Implements HHChannelBase.
References Eref::id(), and HSolve::setX().
void ZombieHHChannel::vSetXpower (const Eref & e, double Xpower) virtual
Implements HHChannelBase.
References Eref::id(), HSolve::setPowers(), HHChannelBase::Xpower_, HHChannelBase::Ypower_, and HHChannelBase::Zpower_.
void ZombieHHChannel::vSetY (const Eref & e, double Y) virtual
Implements HHChannelBase.
References Eref::id(), and HSolve::setY().
void ZombieHHChannel::vSetYpower (const Eref & e, double Ypower) virtual
Implements HHChannelBase.
References Eref::id(), HSolve::setPowers(), HHChannelBase::Xpower_, HHChannelBase::Ypower_, and HHChannelBase::Zpower_.
void ZombieHHChannel::vSetZ (const Eref & e, double Z) virtual
Implements HHChannelBase.
References Eref::id(), and HSolve::setZ().
void ZombieHHChannel::vSetZpower (const Eref & e, double Zpower) virtual
Implements HHChannelBase.
References Eref::id(), HSolve::setPowers(), HHChannelBase::Xpower_, HHChannelBase::Ypower_, and HHChannelBase::Zpower_.
The documentation for this class was generated from the following files:
hsolve/ZombieHHChannel.h
hsolve/ZombieHHChannel.cpp