MOOSE: DestFinfo Class Reference
DestFinfo Class Reference
#include <DestFinfo.h>
Public Member Functions
~DestFinfo ()
DestFinfo (const string &name, const string &doc, OpFunc *func)
void registerFinfo (Cinfo *c)
bool strSet (const Eref &tgt, const string &field, const string &arg) const
bool strGet (const Eref &tgt, const string &field, string &returnValue) const
const OpFunc * getOpFunc () const
FuncId getFid () const
string rttiType () const
Public Member Functions inherited from Finfo
Finfo (const string &name, const string &doc)
virtual ~Finfo ()
const string & name () const
const string & docs () const
Returns documentation string.
virtual void postCreationFunc (Id newId, Element *newElm) const
virtual bool checkTarget (const Finfo *target) const
virtual bool addMsg (const Finfo *target, ObjId mid, Element *src) const
virtual vector< string > innerSrc () const
virtual vector< string > innerDest () const
Additional Inherited Members
Static Public Member Functions inherited from Finfo
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
DestFinfo::~DestFinfo ()
DestFinfo::DestFinfo (const string & name, const string & doc, OpFunc * func)
Member Function Documentation
FuncId DestFinfo::getFid () const
Referenced by SrcFinfo::addMsg(), SetGet::checkSet(), Neutral::child(), Neutral::children(), HSolve::deleteIncomingMessages(), Cinfo::destFinfoName(), Shell::dropClockMsgs(), Shell::innerMove(), insertSharedMsgs(), Neutral::isDescendant(), Neutral::parent(), Neutral::path(), Cinfo::reportFids(), testMsgField(), and testSendMsg().
const OpFunc * DestFinfo::getOpFunc () const
Referenced by SrcFinfo::addMsg(), SetGet::checkSet(), SrcFinfo::checkTarget(), and localGet().
void DestFinfo::registerFinfo (Cinfo * c) virtual
Returns string-ified form to handle template expectations for name field string getName() const; Assign function Ids, bindIndex and so on.
Implements Finfo.
References Cinfo::baseCinfo(), Cinfo::findFinfo(), Finfo::name(), Cinfo::overrideFunc(), and Cinfo::registerOpFunc().
string DestFinfo::rttiType () const virtual
Returns the documentation string for the Finfo string docs() const; Returns the RTTI type string for the finfo by referring to an internal virtual function. string type() const; Returns the list of subsidiary SrcFinfos. Used in Shared Finfos, empty otherwise. Goes via internal virtual function. vector< string > src() const; Returns the list of subsidiary destFinfos. Used in SharedFinfos and ValueFinfos, empty otherwise. Goes via internal virtual function. vector< string > dest() const; Returns an RTTI type string for this Finfo.
Reimplemented from Finfo.
References OpFunc::rttiType().
bool DestFinfo::strGet (const Eref & tgt, const string & field, string & returnValue) const virtual
Function to return value of field into a string argument. Returns true on success. Normally called only from SetGet::strGet.
Implements Finfo.
bool DestFinfo::strSet (const Eref & tgt, const string & field, const string & arg) const virtual
Function to set this field using a string argument. Returns true on success. Normally called only from SetGet::strSet.
Implements Finfo.
The documentation for this class was generated from the following files:
basecode/DestFinfo.h
basecode/DestFinfo.cpp