MOOSE: DifShell Class Reference
DifShell Class Reference
#include <DifShell.h>
Public Member Functions
DifShell ()
double getC () const
C is a read-only field.
void setCeq (double Ceq)
double getCeq () const
void setD (double D)
double getD () const
void setValence (double valence)
double getValence () const
void setLeak (double leak)
double getLeak () const
void setShapeMode (unsigned int shapeMode)
unsigned int getShapeMode () const
void setLength (double length)
double getLength () const
void setDiameter (double diameter)
double getDiameter () const
void setThickness (double thickness)
double getThickness () const
void setVolume (double volume)
double getVolume () const
void setOuterArea (double outerArea)
double getOuterArea () const
void setInnerArea (double innerArea)
double getInnerArea () const
void reinit_0 (const Eref &e, ProcPtr p)
void process_0 (const Eref &e, ProcPtr p)
void process_1 (const Eref &e, ProcPtr p)
void reinit_1 (const Eref &e, ProcPtr p)
void buffer (double kf, double kb, double bFree, double bBound)
void fluxFromOut (double outerC, double outerThickness)
void fluxFromIn (double innerC, double innerThickness)
void influx (double I)
void outflux (double I)
void fInflux (double I, double fraction)
void fOutflux (double I, double fraction)
void storeInflux (double flux)
void storeOutflux (double flux)
void tauPump (double kP, double Ceq)
void eqTauPump (double kP)
void mmPump (double vMax, double Kd)
void hillPump (double vMax, double Kd, unsigned int hill)
Static Public Member Functions
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
DifShell::DifShell ()
Member Function Documentation
void DifShell::buffer (double kf, double kb, double bFree, double bBound)
Referenced by initCinfo().
void DifShell::eqTauPump (double kP)
Referenced by initCinfo().
void DifShell::fInflux (double I, double fraction)
Referenced by initCinfo().
void DifShell::fluxFromIn (double innerC, double innerThickness)
Referenced by initCinfo().
void DifShell::fluxFromOut (double outerC, double outerThickness)
Referenced by initCinfo().
void DifShell::fOutflux (double I, double fraction)
Referenced by initCinfo().
double DifShell::getC () const
C is a read-only field.
Referenced by initCinfo().
double DifShell::getCeq () const
Referenced by initCinfo().
double DifShell::getD () const
Referenced by initCinfo().
double DifShell::getDiameter () const
Referenced by initCinfo().
double DifShell::getInnerArea () const
Referenced by initCinfo().
double DifShell::getLeak () const
Referenced by initCinfo().
double DifShell::getLength () const
Referenced by initCinfo().
double DifShell::getOuterArea () const
Referenced by initCinfo().
unsigned int DifShell::getShapeMode () const
Referenced by initCinfo().
double DifShell::getThickness () const
Referenced by initCinfo().
double DifShell::getValence () const
Referenced by initCinfo().
double DifShell::getVolume () const
Referenced by initCinfo().
void DifShell::hillPump (double vMax, double Kd, unsigned int hill)
Referenced by initCinfo().
void DifShell::influx (double I)
Referenced by initCinfo().
const Cinfo * DifShell::initCinfo () static
References buffer(), eqTauPump(), fInflux(), fluxFromIn(), fluxFromOut(), fOutflux(), getC(), getCeq(), getD(), getDiameter(), getInnerArea(), getLeak(), getLength(), getOuterArea(), getShapeMode(), getThickness(), getValence(), getVolume(), hillPump(), influx(), Neutral::initCinfo(), mmPump(), outflux(), process_0(), process_1(), reinit_0(), reinit_1(), setCeq(), setD(), setDiameter(), setInnerArea(), setLeak(), setLength(), setOuterArea(), setShapeMode(), setThickness(), setValence(), setVolume(), storeInflux(), storeOutflux(), and tauPump().
void DifShell::mmPump (double vMax, double Kd)
Referenced by initCinfo().
void DifShell::outflux (double I)
Referenced by initCinfo().
void DifShell::process_0 (const Eref & e, ProcPtr p)
Referenced by initCinfo().
void DifShell::process_1 (const Eref & e, ProcPtr p)
Referenced by initCinfo().
void DifShell::reinit_0 (const Eref & e, ProcPtr p)
Referenced by initCinfo().
void DifShell::reinit_1 (const Eref & e, ProcPtr p)
Referenced by initCinfo().
void DifShell::setCeq (double Ceq)
Referenced by initCinfo().
void DifShell::setD (double D)
Referenced by initCinfo().
void DifShell::setDiameter (double diameter)
Referenced by initCinfo().
void DifShell::setInnerArea (double innerArea)
Referenced by initCinfo().
void DifShell::setLeak (double leak)
Referenced by initCinfo().
void DifShell::setLength (double length)
Referenced by initCinfo().
void DifShell::setOuterArea (double outerArea)
Referenced by initCinfo().
void DifShell::setShapeMode (unsigned int shapeMode)
Referenced by initCinfo().
void DifShell::setThickness (double thickness)
Referenced by initCinfo().
void DifShell::setValence (double valence)
Referenced by initCinfo().
void DifShell::setVolume (double volume)
Referenced by initCinfo().
void DifShell::storeInflux (double flux)
Referenced by initCinfo().
void DifShell::storeOutflux (double flux)
Referenced by initCinfo().
void DifShell::tauPump (double kP, double Ceq)
Referenced by initCinfo().
The documentation for this class was generated from the following files:
biophysics/DifShell.h
biophysics/DifShell.cpp