MOOSE: LookupGetOpFuncBase< L, A > Class Template Reference
LookupGetOpFuncBase< L, A > Class Template Reference abstract
#include <OpFuncBase.h>
Public Member Functions
bool checkFinfo (const Finfo *s) const
virtual void op (const Eref &e, L index, ObjId recipient, FuncId fid) const =0
virtual A returnOp (const Eref &e, const L &index) const =0
const OpFunc * makeHopFunc (HopIndex hopIndex) const
const OpFunc * makeHopFunc (HopIndex hopIndex, const L &index) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
virtual ~OpFunc ()
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class L, class A>
class LookupGetOpFuncBase< L, A >
This is the base class for all LookupGetOpFuncs.
Member Function Documentation
template<class L, class A> bool LookupGetOpFuncBase< L, A >::checkFinfo (const Finfo * s) const inline virtual
Implements OpFunc.
template<class L, class A> const OpFunc* LookupGetOpFuncBase< L, A >::makeHopFunc (HopIndex hopIndex) const inline virtual
Implements OpFunc.
template<class L, class A> const OpFunc* LookupGetOpFuncBase< L, A >::makeHopFunc (HopIndex hopIndex, const L & index) const inline
template<class L, class A> virtual void LookupGetOpFuncBase< L, A >::op (const Eref & e, L index, ObjId recipient, FuncId fid) const pure virtual
Implemented in GetEpFunc1< T, L, A >, and GetOpFunc1< T, L, A >.
template<class L, class A> void LookupGetOpFuncBase< L, A >::opBuffer (const Eref & e, double * buf) const inline virtual
Executes the OpFunc by converting args.
Implements OpFunc.
template<class L, class A> virtual A LookupGetOpFuncBase< L, A >::returnOp (const Eref & e, const L & index) const pure virtual
Implemented in GetEpFunc1< T, L, A >, and GetOpFunc1< T, L, A >.
Referenced by LookupField< L, A >::get(), and LookupField< L, A >::getVec().
template<class L, class A> string LookupGetOpFuncBase< L, A >::rttiType () const inline virtual
Implements OpFunc.
References Conv< T >::rttiType().
The documentation for this class was generated from the following file:
basecode/OpFuncBase.h