MOOSE: Eref Class Reference
Eref Class Reference
#include <Eref.h>
Public Member Functions
Eref ()
Eref (Element *e, unsigned int index, unsigned int field=0)
char * data () const
Element * element () const
unsigned int dataIndex () const
unsigned int fieldIndex () const
ObjId objId () const
Id id () const
const vector< MsgDigest > & msgDigest (unsigned int bindIndex) const
bool isDataHere () const
unsigned int getNode () const
Friends
ostream & operator<< (ostream &s, const Eref &e)
Constructor & Destructor Documentation
Eref::Eref ()
Eref::Eref (Element * e, unsigned int index, unsigned int field = 0)
Member Function Documentation
char * Eref::data () const
Returns data entry.
References Element::data(), isDataHere(), and Element::rawIndex().
Referenced by ZombiePoolInterface::assignProxyPools(), benchmarkMsg(), checkArg1(), SteadyState::classifyState(), Shell::cleanSimulation(), Shell::destroy(), ReadCspace::expandEnzyme(), ReadCspace::expandReaction(), getEpFuncData(), MarkovSolverBase::init(), init(), isDoingReinit(), Shell::isRunning(), Shell::launchParser(), makeCompt(), ReadCspace::makeMolecule(), ReadCspace::makePlots(), makeReacTest(), makeStandardElements(), ZombiePoolInterface::matchJunctionVols(), OpFunc0< T >::op(), OpFunc1< T, A >::op(), OpFunc2< T, A1, A2 >::op(), EpFunc0< T >::op(), OpFunc3< T, A1, A2, A3 >::op(), EpFunc1< T, ProcPtr >::op(), OpFunc4< T, A1, A2, A3, A4 >::op(), EpFunc2< T, A1, A2 >::op(), OpFunc5< T, A1, A2, A3, A4, A5 >::op(), EpFunc3< T, A1, A2, A3 >::op(), OpFunc6< T, A1, A2, A3, A4, A5, A6 >::op(), EpFunc4< T, A1, A2, A3, A4 >::op(), EpFunc5< T, A1, A2, A3, A4, A5 >::op(), EpFunc6< T, A1, A2, A3, A4, A5, A6 >::op(), HSolveUtils::rates(), SpikeGenStruct::reinit(), Clock::reportClock(), GetOpFunc< T, A >::returnOp(), GetOpFunc1< T, L, A >::returnOp(), GetEpFunc1< T, L, A >::returnOp(), SpikeGenStruct::send(), Ksolve::setDsolve(), Stoich::setDsolve(), Stoich::setElist(), MarkovRateTable::setInt2dChildTable(), Stoich::setKsolve(), ZombieReac::setSolver(), ZombieMMenz::setSolver(), ZombieEnz::setSolver(), Gsolve::setStoich(), SteadyState::setStoich(), Ksolve::setStoich(), ZombiePoolInterface::setupCrossSolverReacs(), ZombiePoolInterface::setupCrossSolverReacVols(), ZombiePoolInterface::setupXfer(), MarkovRateTable::setVtChildTable(), testAssortedMsg(), testBuildStoich(), testChildren(), testClock(), testClockMessaging(), testCopy(), testCopyFieldElement(), testCopyMsgOps(), testDescendant(), testFibonacci(), testFilterOffNodeTargets(), testFindModelParent(), testGetMsg(), testGetMsgs(), testInterNodeOps(), testIntFireNetwork(), testMMenz(), testMMenzProcess(), testMove(), testMpiFibonacci(), testMsgElementListing(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), testReadKkit(), ReadCspace::testReadModel(), testReMesh(), testRunGsolve(), testRunKsolve(), testSendSpike(), testSetupReac(), testSharedMsg(), testShellAddMsg(), testShellParserCreateDelete(), testShellParserQuit(), testShellParserStart(), testShellSetGet(), testStats(), testSyncSynapseSize(), testTable(), testTreeTraversal(), testTwoReacGetNeighbors(), testVolScaling(), testWildcard(), verifyKids(), ZombieCaConc::vSetSolver(), ZombieHHChannel::vSetSolver(), ZombieCompartment::vSetSolver(), ZombieFunction::zombify(), ReacBase::zombify(), CplxEnzBase::zombify(), EnzBase::zombify(), CaConcBase::zombify(), PoolBase::zombify(), HHChannelBase::zombify(), and moose::CompartmentBase::zombify().
unsigned int Eref::dataIndex () const inline
Returns data index, for now typecast to unsigned int.
Referenced by Neutral::child(), Neutral::children(), HopFunc1< A >::dataOpVec(), filterOffNodeTargets(), OneToOneMsg::firstTgt(), OneToOneDataIndexMsg::firstTgt(), DiagonalMsg::firstTgt(), SparseMsg::firstTgt(), GetHopFunc< A >::getLocalFieldVec(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), Neutral::getNumField(), MeshEntry::getVolume(), Gsolve::getVoxelIndex(), Ksolve::getVoxelIndex(), HopFunc1< A >::localFieldOpVec(), lookupVolumeFromMesh(), OpFunc1Base< ProcPtr >::opVecBuffer(), IntFire::process(), MeshEntry::reinit(), Adaptor::reinit(), ChemCompt::setEntireVolume(), Neutral::setNumField(), and testSendMsg().
Element* Eref::element () const inline
Returns Element part
Referenced by Neutral::buildTree(), Neutral::child(), Neutral::children(), convertConcToNumRateUsingMesh(), convertConcToNumRateUsingVol(), HopFunc1< A >::dataOpVec(), Neutral::destroy(), filterOffNodeTargets(), OneToAllMsg::firstTgt(), SingleMsg::firstTgt(), OneToOneDataIndexMsg::firstTgt(), OneToOneMsg::firstTgt(), DiagonalMsg::firstTgt(), SparseMsg::firstTgt(), Neutral::getClass(), Neutral::getDestFields(), Neutral::getDt(), Neutral::getIncomingMsgs(), GetHopFunc< A >::getLocalFieldVec(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), GetHopFunc< A >::getMultiNodeVec(), Neutral::getName(), Neutral::getNeighbors(), Neutral::getNumData(), Neutral::getNumField(), ReacBase::getNumPrd(), EnzBase::getNumSub(), ReacBase::getNumSub(), Neutral::getOutgoingMsgs(), getReactantVols(), Neutral::getSourceFields(), Neutral::getTick(), Neutral::getValueFields(), Neutral::isDescendant(), HopFunc1< A >::localFieldOpVec(), localGet(), GetHopFunc< A >::opGetVec(), HopFunc1< A >::opVec(), HopFunc2< A1, A2 >::opVec(), OpFunc1Base< ProcPtr >::opVecBuffer(), OpFunc2Base< A1, A2 >::opVecBuffer(), Neutral::path(), Arith::process(), moose::VClamp::reinit(), Adaptor::reinit(), SrcFinfo0::send(), SrcFinfo2< T1, T2 >::send(), SrcFinfo3< T1, T2, T3 >::send(), SrcFinfo4< T1, T2, T3, T4 >::send(), SrcFinfo5< T1, T2, T3, T4, T5 >::send(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), SrcFinfo2< T1, T2 >::sendTo(), NeuroMesh::separateOutSpines(), ChemCompt::setEntireVolume(), Gsolve::setN(), Neutral::setName(), Gsolve::setNinit(), Neutral::setNumData(), Neutral::setNumField(), Neutral::setTick(), testCreateMsg(), testFibonacci(), testMsgField(), testSendMsg(), testShellAddMsg(), HHChannel2D::vReinit(), and HHChannel::vReinit().
unsigned int Eref::fieldIndex () const inline
Returns field index, for now typecast to unsigned int. This is really an extra bit of baggage used here not for immediate lookup, but to pass to EpFuncs that know how to use this for lookup.
Referenced by MeshEntry::getCoordinates(), MeshEntry::getDiffusionArea(), MeshEntry::getDiffusionScaling(), MeshEntry::getDimensions(), MeshEntry::getMeshType(), MeshEntry::getNeighbors(), and Neutral::path().
unsigned int Eref::getNode () const
Returns node upon which specified data entry resides . If this is a GlobalElement then it returns the local node.
References Element::getNode().
Referenced by filterOffNodeTargets(), HopFunc1< A >::localFieldOpVec(), GetHopFunc< A >::opGetVec(), and HopFunc1< A >::opVec().
Id Eref::id () const
Returns the Id corresponding to the Eref. Loses information.
References Element::id().
Referenced by HHChannel2D::createGate(), HHChannel2D::destroyGate(), HHChannel::destroyGate(), Neutral::getMsgDestFunctions(), Neutral::getMsgDests(), Neutral::getNeighbors(), Gsolve::getPoolIndex(), Ksolve::getPoolIndex(), Stoich::getR1(), Stoich::getR1offset1(), Stoich::getR1offset2(), Stoich::getR2(), PsdMesh::handlePsdList(), SpineMesh::handleSpineList(), Gsolve::initProc(), Ksolve::initProc(), Gsolve::initReinit(), Ksolve::initReinit(), lookupVolumeFromMesh(), Cell::reinit(), HHGate::setAlpha(), HHGate::setBeta(), HHGate::setDivs(), Stoich::setElist(), Stoich::setEnzK1(), Stoich::setEnzK2(), Stoich::setEnzK3(), Stoich::setFunctionExpr(), HHGate::setMax(), HHGate::setMin(), HHGate::setMinfinity(), Stoich::setMMenzKcat(), Stoich::setMMenzKm(), Neutral::setName(), Stoich::setReacKb(), Stoich::setReacKf(), HHGate::setTableA(), HHGate::setTableB(), HHGate::setTau(), HHGate::setupAlpha(), HHGate::setupGate(), HHGate::setupTau(), HHGate::setUseInterpolation(), HHChannel::vCreateGate(), ZombieCaConc::vCurrent(), ZombieCaConc::vGetCa(), ZombieCaConc::vGetCaBasal(), ZombieCaConc::vGetCeiling(), ZombieCompartment::vGetCm(), ZombieHHChannel::vGetEk(), ZombieCompartment::vGetEm(), ZombieCaConc::vGetFloor(), ZombieHHChannel::vGetGbar(), ZombieHHChannel::vGetGk(), ZombieHHChannel::vGetIk(), ZombieCompartment::vGetIm(), ZombieCompartment::vGetInitVm(), ZombieCompartment::vGetInject(), ZombieHHChannel::vGetInstant(), ZombieCompartment::vGetRa(), ZombieCompartment::vGetRm(), ZombieCompartment::vGetVm(), ZombieHHChannel::vGetX(), ZombieHHChannel::vGetY(), ZombieHHChannel::vGetZ(), ZombieCompartment::vHandleChannel(), ZombieCompartment::vInjectMsg(), RandGenerator::vReinit(), ZombieCaConc::vSetB(), ZombieCaConc::vSetCa(), ZombieCaConc::vSetCaBasal(), ZombieCaConc::vSetCeiling(), ZombieCompartment::vSetCm(), ZombieHHChannel::vSetEk(), ZombieCompartment::vSetEm(), ZombieCaConc::vSetFloor(), ZombieHHChannel::vSetGbar(), ZombieHHChannel::vSetGk(), ZombieCompartment::vSetInitVm(), ZombieCompartment::vSetInject(), ZombieHHChannel::vSetInstant(), ZombieCompartment::vSetRa(), ZombieCompartment::vSetRm(), ZombieCaConc::vSetTau(), ZombieCompartment::vSetVm(), ZombieHHChannel::vSetX(), ZombieHHChannel::vSetXpower(), ZombieHHChannel::vSetY(), ZombieHHChannel::vSetYpower(), ZombieHHChannel::vSetZ(), ZombieHHChannel::vSetZpower(), and Stoich::zombifyModel().
bool Eref::isDataHere () const
True if the data are on the current node
References Element::getNode(), and Shell::myNode().
Referenced by data(), Neutral::getNumField(), Neutral::setNumField(), OneToOneMsg::sources(), and OneToOneMsg::targets().
const vector< MsgDigest > & Eref::msgDigest (unsigned int bindIndex) const
Returns the digested version of the specified msgsrc. If the message has changed, this call triggers the digestion operation.
References Element::cinfo(), Element::msgDigest(), and Cinfo::numBindIndex().
Referenced by Element::getMsgTargets(), SrcFinfo0::send(), SrcFinfo1< T >::send(), SrcFinfo2< T1, T2 >::send(), SrcFinfo3< T1, T2, T3 >::send(), SrcFinfo4< T1, T2, T3, T4 >::send(), SrcFinfo5< T1, T2, T3, T4, T5 >::send(), SrcFinfo6< T1, T2, T3, T4, T5, T6 >::send(), SrcFinfo1< T >::sendTo(), SrcFinfo2< T1, T2 >::sendTo(), and SrcFinfo1< T >::sendVec().
ObjId Eref::objId () const
Returns the ObjId corresponding to the Eref. All info is kept.
References Element::id().
Referenced by Neutral::child(), Neutral::destroy(), Function::getExpr(), Neutral::getObjId(), Neutral::isDescendant(), Neutral::parent(), Neutral::path(), Arith::process(), Function::setExpr(), ElementValueFinfo< T, F >::strGet(), LookupElementValueFinfo< T, L, F >::strGet(), ValueFinfo< T, F >::strGet(), LookupValueFinfo< T, L, F >::strGet(), ReadOnlyElementValueFinfo< T, F >::strGet(), ReadOnlyLookupElementValueFinfo< T, L, F >::strGet(), ReadOnlyValueFinfo< T, F >::strGet(), ReadOnlyLookupValueFinfo< T, L, F >::strGet(), ElementValueFinfo< T, F >::strSet(), LookupElementValueFinfo< T, L, F >::strSet(), LookupValueFinfo< T, L, F >::strSet(), ValueFinfo< T, F >::strSet(), and testGetMsg().
Friends And Related Function Documentation
ostream& operator<< (ostream & s, const Eref & e) friend
The documentation for this class was generated from the following files:
basecode/Eref.h
basecode/Eref.cpp