MOOSE: EnzBase Class Reference
EnzBase Class Reference abstract
#include <EnzBase.h>
Public Member Functions
EnzBase ()
virtual ~EnzBase ()
void setKm (const Eref &e, double v)
double getKm (const Eref &e) const
void setNumKm (const Eref &e, double v)
double getNumKm (const Eref &e) const
void setKcat (const Eref &e, double v)
double getKcat (const Eref &e) const
unsigned int getNumSub (const Eref &e) const
virtual void vSetKm (const Eref &e, double v)=0
virtual double vGetKm (const Eref &e) const =0
virtual void vSetNumKm (const Eref &e, double v)=0
virtual double vGetNumKm (const Eref &e) const =0
virtual void vSetKcat (const Eref &e, double v)=0
virtual double vGetKcat (const Eref &e) const =0
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void sub (double n)
void enz (double n)
void prd (double n)
void remesh (const Eref &e)
virtual void vProcess (const Eref &e, ProcPtr p)
virtual void vReinit (const Eref &e, ProcPtr p)
virtual void vSub (double n)
virtual void vEnz (double n)
virtual void vRemesh (const Eref &e)
virtual void setSolver (Id solver, Id orig)
Assign solver info.
Static Public Member Functions
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Detailed Description
This class is the base class for enzymes, both the classical Michaelis- Menten form and the form with explicit enz-substrate complexes that MOOSE prefers.
Constructor & Destructor Documentation
EnzBase::EnzBase ()
EnzBase::~EnzBase () virtual
Member Function Documentation
void EnzBase::enz (double n)
References vEnz().
Referenced by CplxEnzBase::initCinfo(), and initCinfo().
double EnzBase::getKcat (const Eref & e) const
References vGetKcat().
Referenced by CplxEnzBase::initCinfo(), initCinfo(), ZombieEnz::vGetKm(), ZombieEnz::vGetRatio(), ZombieEnz::vSetKm(), ZombieEnz::vSetNumKm(), ZombieEnz::vSetRatio(), CplxEnzBase::zombify(), and zombify().
double EnzBase::getKm (const Eref & e) const
References vGetKm().
Referenced by initCinfo(), ZombieEnz::vSetRatio(), and zombify().
double EnzBase::getNumKm (const Eref & e) const
References vGetNumKm().
Referenced by initCinfo().
unsigned int EnzBase::getNumSub (const Eref & e) const
References Eref::element(), and Element::getMsgAndFunc().
Referenced by initCinfo().
const Cinfo * EnzBase::initCinfo () static
References enz(), enzDest(), getKcat(), getKm(), getNumKm(), getNumSub(), Neutral::initCinfo(), prd(), process(), reinit(), remesh(), setKcat(), setKm(), setNumKm(), and sub().
Referenced by enzDest(), findMeshOfEnz(), getEnzMol(), MMenz::initCinfo(), ZombieMMenz::initCinfo(), CplxEnzBase::initCinfo(), ZombieMMenz::setSolver(), storeCplxEnzMsgs(), and storeMMenzMsgs().
void EnzBase::prd (double n)
Referenced by initCinfo().
void EnzBase::process (const Eref & e, ProcPtr p)
References vProcess().
Referenced by initCinfo().
void EnzBase::reinit (const Eref & e, ProcPtr p)
References vReinit().
Referenced by initCinfo().
void EnzBase::remesh (const Eref & e)
References vRemesh().
Referenced by initCinfo().
void EnzBase::setKcat (const Eref & e, double v)
References vSetKcat().
Referenced by CplxEnzBase::initCinfo(), initCinfo(), CplxEnzBase::zombify(), and zombify().
void EnzBase::setKm (const Eref & e, double v)
References vSetKm().
Referenced by initCinfo(), Enz::vRemesh(), and zombify().
void EnzBase::setNumKm (const Eref & e, double v)
References vSetNumKm().
Referenced by initCinfo().
void EnzBase::setSolver (Id solver, Id orig) virtual
Assign solver info.
Reimplemented in ZombieEnz, and ZombieMMenz.
Referenced by CplxEnzBase::zombify(), and zombify().
void EnzBase::sub (double n)
References vSub().
Referenced by initCinfo().
void EnzBase::vEnz (double n) virtual
Reimplemented in Enz, and MMenz.
Referenced by enz().
virtual double EnzBase::vGetKcat (const Eref & e) const pure virtual
Implemented in MMenz, ZombieMMenz, ZombieEnz, and Enz.
Referenced by getKcat().
virtual double EnzBase::vGetKm (const Eref & e) const pure virtual
Implemented in ZombieEnz, MMenz, ZombieMMenz, and Enz.
Referenced by getKm().
virtual double EnzBase::vGetNumKm (const Eref & e) const pure virtual
Implemented in ZombieEnz, MMenz, ZombieMMenz, and Enz.
Referenced by getNumKm().
void EnzBase::vProcess (const Eref & e, ProcPtr p) virtual
Reimplemented in Enz, and MMenz.
Referenced by process().
void EnzBase::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented in Enz, and MMenz.
Referenced by reinit().
void EnzBase::vRemesh (const Eref & e) virtual
Reimplemented in Enz, and MMenz.
Referenced by remesh().
virtual void EnzBase::vSetKcat (const Eref & e, double v) pure virtual
Implemented in MMenz, ZombieMMenz, ZombieEnz, and Enz.
Referenced by setKcat().
virtual void EnzBase::vSetKm (const Eref & e, double v) pure virtual
Implemented in ZombieEnz, MMenz, ZombieMMenz, and Enz.
Referenced by setKm().
virtual void EnzBase::vSetNumKm (const Eref & e, double v) pure virtual
Implemented in ZombieEnz, MMenz, ZombieMMenz, and Enz.
Referenced by setNumKm().
void EnzBase::vSub (double n) virtual
Reimplemented in Enz, and MMenz.
Referenced by sub().
void EnzBase::zombify (Element * orig, const Cinfo * zClass, Id solver) static
This function helps the conversion between Enzyme subclasses. Note that we may need a second zombify function to convert to and from explicit enz classes because there is information lost if we go right down to the EnzBase. Specifically, EnzBase only knows about two parameters, the Km and kcat. Explicit enzymes also need to know a k2, or equivalently a ratio between kcat and k2. But in principle this function allows conversion between the two cases.
References Element::cinfo(), Eref::data(), getKcat(), getKm(), Element::id(), Element::localDataStart(), Element::numLocalData(), setKcat(), setKm(), setSolver(), and Element::zombieSwap().
Referenced by Stoich::unZombifyModel(), and Stoich::zombifyModel().
The documentation for this class was generated from the following files:
kinetics/EnzBase.h
kinetics/EnzBase.cpp