MOOSE: MgBlock Class Reference
MgBlock Class Reference
#include <MgBlock.h>
Public Member Functions
MgBlock ()
void setKMg_A (double Gbar)
double getKMg_A () const
void setKMg_B (double Ek)
double getKMg_B () const
void setCMg (double CMg)
double getCMg () const
void setZk (double Zk)
double getZk () const
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void origChannel (const Eref &e, double Gk, double Ek)
Public Member Functions inherited from ChanCommon
ChanCommon ()
~ChanCommon ()
void vSetGbar (const Eref &e, double Gbar)
double vGetGbar (const Eref &e) const
void vSetEk (const Eref &e, double Ek)
double vGetEk (const Eref &e) const
void vSetGk (const Eref &e, double Gk)
double vGetGk (const Eref &e) const
void vSetIk (const Eref &e, double Ic)
double vGetIk (const Eref &e) const
void vHandleVm (double Vm)
void sendProcessMsgs (const Eref &e, const ProcPtr info)
void sendReinitMsgs (const Eref &e, const ProcPtr info)
void updateIk ()
double getVm () const
Utility function to access Vm.
double getGbar () const
Utility function to acces Gbar.
Public Member Functions inherited from ChanBase
ChanBase ()
~ChanBase ()
void setGbar (const Eref &e, double Gbar)
double getGbar (const Eref &e) const
void setEk (const Eref &e, double Ek)
double getEk (const Eref &e) const
void setGk (const Eref &e, double Gk)
double getGk (const Eref &e) const
void setIk (const Eref &e, double Ic)
double getIk (const Eref &e) const
void handleVm (double Vm)
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChanCommon
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Static Public Member Functions inherited from ChanBase
static SrcFinfo1< double > * permeability ()
static SrcFinfo2< double,
double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Additional Inherited Members
Protected Attributes inherited from ChanCommon
double Vm_
Vm_ is input variable from compartment, used for most rates.
Constructor & Destructor Documentation
MgBlock::MgBlock ()
Member Function Documentation
double MgBlock::getCMg () const
Referenced by initCinfo().
double MgBlock::getKMg_A () const
Referenced by initCinfo().
double MgBlock::getKMg_B () const
Referenced by initCinfo().
double MgBlock::getZk () const
Referenced by initCinfo().
const Cinfo * MgBlock::initCinfo () static
References getCMg(), getKMg_A(), getKMg_B(), getZk(), ChanBase::initCinfo(), origChannel(), setCMg(), setKMg_A(), setKMg_B(), and setZk().
void MgBlock::origChannel (const Eref & e, double Gk, double Ek)
Assign the local Vm_ to the incoming Vm from the compartment
References ChanBase::setEk().
Referenced by initCinfo().
void MgBlock::setCMg (double CMg)
References EPSILON.
Referenced by initCinfo().
void MgBlock::setKMg_A (double Gbar)
References EPSILON.
Referenced by initCinfo().
void MgBlock::setKMg_B (double Ek)
References EPSILON.
Referenced by initCinfo().
void MgBlock::setZk (double Zk)
Referenced by initCinfo().
void MgBlock::vProcess (const Eref & e, ProcPtr p) virtual
processFunc handles the update and calculations every clock tick. It first sends the request for evaluation of the gate variables to the respective gate objects and recieves their response immediately through a return message. This is done so that many channel instances can share the same gate lookup tables, but do so cleanly. Such messages should never go to a remote node. Then the function does its own little calculations to send back to the parent compartment through regular messages.
Implements ChanBase.
References ChanCommon::sendProcessMsgs(), ChanBase::setGk(), ChanCommon::updateIk(), and ChanCommon::Vm_.
void MgBlock::vReinit (const Eref & e, ProcPtr p) virtual
Reinitializes the values for the channel. This involves computing the steady-state value for the channel gates using the provided Vm from the parent compartment. It involves a similar cycle through the gates and then updates to the parent compartment as for the processFunc.
Implements ChanBase.
References EPSILON, and ChanCommon::sendReinitMsgs().
The documentation for this class was generated from the following files:
biophysics/MgBlock.h
biophysics/MgBlock.cpp