MOOSE: Enz Class Reference
Enz Class Reference
#include <Enz.h>
Public Member Functions
Enz ()
~Enz ()
void vSetKm (const Eref &e, double v)
double vGetKm (const Eref &e) const
void vSetNumKm (const Eref &e, double v)
double vGetNumKm (const Eref &e) const
void vSetKcat (const Eref &e, double v)
double vGetKcat (const Eref &e) const
void vSetK1 (const Eref &e, double v)
double vGetK1 (const Eref &e) const
void vSetK2 (const Eref &e, double v)
double vGetK2 (const Eref &e) const
void vSetRatio (const Eref &e, double v)
double vGetRatio (const Eref &e) const
void vSetConcK1 (const Eref &e, double v)
double vGetConcK1 (const Eref &e) const
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vSub (double n)
void vEnz (double n)
void vPrd (double n)
void vCplx (double n)
void vRemesh (const Eref &e)
Public Member Functions inherited from CplxEnzBase
CplxEnzBase ()
virtual ~CplxEnzBase ()
void setK1 (const Eref &e, double v)
double getK1 (const Eref &e) const
void setK2 (const Eref &e, double v)
double getK2 (const Eref &e) const
void setRatio (const Eref &e, double v)
double getRatio (const Eref &e) const
void setConcK1 (const Eref &e, double v)
double getConcK1 (const Eref &e) const
void cplx (double n)
Public Member Functions inherited from EnzBase
EnzBase ()
virtual ~EnzBase ()
void setKm (const Eref &e, double v)
double getKm (const Eref &e) const
void setNumKm (const Eref &e, double v)
double getNumKm (const Eref &e) const
void setKcat (const Eref &e, double v)
double getKcat (const Eref &e) const
unsigned int getNumSub (const Eref &e) const
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void sub (double n)
void enz (double n)
void prd (double n)
void remesh (const Eref &e)
virtual void setSolver (Id solver, Id orig)
Assign solver info.
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from CplxEnzBase
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from EnzBase
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
Enz::Enz ()
Enz::~Enz ()
Member Function Documentation
const Cinfo * Enz::initCinfo () static
References CplxEnzBase::initCinfo().
void Enz::vCplx (double n) virtual
Reimplemented from CplxEnzBase.
void Enz::vEnz (double n) virtual
Reimplemented from EnzBase.
double Enz::vGetConcK1 (const Eref & e) const virtual
Implements CplxEnzBase.
References EPSILON.
double Enz::vGetK1 (const Eref & e) const virtual
Implements CplxEnzBase.
double Enz::vGetK2 (const Eref & e) const virtual
Implements CplxEnzBase.
double Enz::vGetKcat (const Eref & e) const virtual
Implements EnzBase.
double Enz::vGetKm (const Eref & e) const virtual
Implements EnzBase.
double Enz::vGetNumKm (const Eref & e) const virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh().
double Enz::vGetRatio (const Eref & e) const virtual
Implements CplxEnzBase.
void Enz::vPrd (double n)
void Enz::vProcess (const Eref & e, ProcPtr p) virtual
Reimplemented from EnzBase.
References SrcFinfo2< T1, T2 >::send().
void Enz::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented from EnzBase.
void Enz::vRemesh (const Eref & e) virtual
Reimplemented from EnzBase.
References EnzBase::setKm().
void Enz::vSetConcK1 (const Eref & e, double v) virtual
Implements CplxEnzBase.
References convertConcToNumRateUsingMesh(), and EPSILON.
void Enz::vSetK1 (const Eref & e, double v) virtual
Implements CplxEnzBase.
References convertConcToNumRateUsingMesh().
void Enz::vSetK2 (const Eref & e, double v) virtual
Implements CplxEnzBase.
References vSetKm().
void Enz::vSetKcat (const Eref & e, double v) virtual
Implements EnzBase.
References vSetKm().
void Enz::vSetKm (const Eref & e, double v) virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh().
Referenced by vSetK2(), and vSetKcat().
void Enz::vSetNumKm (const Eref & e, double v) virtual
Implements EnzBase.
References convertConcToNumRateUsingMesh().
void Enz::vSetRatio (const Eref & e, double v) virtual
Implements CplxEnzBase.
References convertConcToNumRateUsingMesh().
void Enz::vSub (double n) virtual
Reimplemented from EnzBase.
The documentation for this class was generated from the following files:
kinetics/Enz.h
kinetics/Enz.cpp