MOOSE: GetHopFunc< A > Class Template Reference
GetHopFunc< A > Class Template Reference
#include <HopFunc.h>
Public Member Functions
GetHopFunc (HopIndex hopIndex)
void op (const Eref &e, A *ret) const
void getLocalFieldVec (const Eref &er, vector< A > &ret, const GetOpFuncBase< A > *op) const
void getRemoteFieldVec (const Eref &e, vector< A > &ret, const GetOpFuncBase< A > *op) const
void getLocalVec (Element *elm, vector< A > &ret, const GetOpFuncBase< A > *op) const
void getMultiNodeVec (const Eref &e, vector< A > &ret, const GetOpFuncBase< A > *op) const
void opGetVec (const Eref &e, vector< A > &ret, const GetOpFuncBase< A > *op) const
Public Member Functions inherited from OpFunc1Base< A * >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
virtual void opVec (const Eref &e, const vector< A * > &arg, const OpFunc1Base< A * > *op) const
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
virtual ~OpFunc ()
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Constructor & Destructor Documentation
template<class A> GetHopFunc< A >::GetHopFunc (HopIndex hopIndex) inline
Member Function Documentation
template<class A> void GetHopFunc< A >::getLocalFieldVec (const Eref & er, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
References Eref::dataIndex(), Eref::element(), Element::localDataStart(), Element::numField(), q, and GetOpFuncBase< A >::returnOp().
Referenced by GetHopFunc< A >::opGetVec().
template<class A> void GetHopFunc< A >::getLocalVec (Element * elm, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
References Element::localDataStart(), Element::numLocalData(), and GetOpFuncBase< A >::returnOp().
Referenced by GetHopFunc< A >::getMultiNodeVec(), and GetHopFunc< A >::opGetVec().
template<class A> void GetHopFunc< A >::getMultiNodeVec (const Eref & e, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
References HopIndex::bindIndex(), Eref::element(), GetHopFunc< A >::getLocalVec(), mooseMyNode(), mooseNumNodes(), and remoteGetVec().
Referenced by GetHopFunc< A >::opGetVec().
template<class A> void GetHopFunc< A >::getRemoteFieldVec (const Eref & e, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
References HopIndex::bindIndex(), and remoteFieldGetVec().
Referenced by GetHopFunc< A >::opGetVec().
template<class A> void GetHopFunc< A >::op (const Eref & e, A * ret) const inline virtual
Implements OpFunc1Base< A * >.
References HopIndex::bindIndex(), Conv< T >::buf2val(), and remoteGet().
template<class A> void GetHopFunc< A >::opGetVec (const Eref & e, vector< A > & ret, const GetOpFuncBase< A > * op) const inline
References Eref::element(), GetHopFunc< A >::getLocalFieldVec(), GetHopFunc< A >::getLocalVec(), GetHopFunc< A >::getMultiNodeVec(), Eref::getNode(), GetHopFunc< A >::getRemoteFieldVec(), Element::hasFields(), Element::isGlobal(), mooseMyNode(), mooseNumNodes(), and Element::numData().
Referenced by Field< A >::getVec().
The documentation for this class was generated from the following file:
basecode/HopFunc.h