MOOSE: PIDController Class Reference
PIDController Class Reference
#include <PIDController.h>
Public Member Functions
PIDController ()
void setCommand (double command)
double getCommand () const
void setSensed (double sensed)
double getSensed () const
double getOutput () const
void setGain (double gain)
double getGain () const
void setTauI (double tau_i)
double getTauI () const
void setTauD (double tau_d)
double getTauD () const
void setSaturation (double saturation)
double getSaturation () const
double getError () const
double getEIntegral () const
double getEDerivative () const
double getEPrevious () const
void process (const Eref &e, ProcPtr process)
void reinit (const Eref &e, ProcPtr process)
Static Public Member Functions
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
PIDController::PIDController ()
Member Function Documentation
double PIDController::getCommand () const
Referenced by initCinfo().
double PIDController::getEDerivative () const
Referenced by initCinfo().
double PIDController::getEIntegral () const
Referenced by initCinfo().
double PIDController::getEPrevious () const
Referenced by initCinfo().
double PIDController::getError () const
Referenced by initCinfo().
double PIDController::getGain () const
Referenced by initCinfo().
double PIDController::getOutput () const
Referenced by initCinfo().
double PIDController::getSaturation () const
Referenced by initCinfo().
double PIDController::getSensed () const
Referenced by initCinfo().
double PIDController::getTauD () const
Referenced by initCinfo().
double PIDController::getTauI () const
Referenced by initCinfo().
const Cinfo * PIDController::initCinfo () static
References getCommand(), getEDerivative(), getEIntegral(), getEPrevious(), getError(), getGain(), getOutput(), getSaturation(), getSensed(), getTauD(), getTauI(), Neutral::initCinfo(), process(), reinit(), setCommand(), setGain(), setSaturation(), setSensed(), setTauD(), and setTauI().
void PIDController::process (const Eref & e, ProcPtr process)
References ProcInfo::dt.
Referenced by initCinfo().
void PIDController::reinit (const Eref & e, ProcPtr process)
References ProcInfo::dt.
Referenced by initCinfo().
void PIDController::setCommand (double command)
Referenced by initCinfo().
void PIDController::setGain (double gain)
Referenced by initCinfo().
void PIDController::setSaturation (double saturation)
Referenced by initCinfo().
void PIDController::setSensed (double sensed)
Referenced by initCinfo().
void PIDController::setTauD (double tau_d)
Referenced by initCinfo().
void PIDController::setTauI (double tau_i)
Referenced by initCinfo().
The documentation for this class was generated from the following files:
device/PIDController.h
device/PIDController.cpp