MOOSE: VectorTable Class Reference
VectorTable Class Reference
#include <VectorTable.h>
Public Member Functions
VectorTable ()
double lookupByValue (double) const
double lookupByIndex (unsigned int) const
vector< double > getTable () const
void setTable (vector< double >)
unsigned int getDiv () const
void setDiv (unsigned int)
double getMin () const
void setMin (double)
double getMax () const
void setMax (double)
double getInvDx () const
bool tableIsEmpty () const
Static Public Member Functions
static const Cinfo * initCinfo ()
Friends
istream & operator>> (istream &, VectorTable &)
Constructor & Destructor Documentation
VectorTable::VectorTable ()
Member Function Documentation
unsigned int VectorTable::getDiv () const
Referenced by initCinfo().
double VectorTable::getInvDx () const
Referenced by initCinfo().
double VectorTable::getMax () const
Referenced by initCinfo().
double VectorTable::getMin () const
Referenced by initCinfo().
vector< double > VectorTable::getTable () const
Referenced by initCinfo().
const Cinfo * VectorTable::initCinfo () static
References getDiv(), getInvDx(), getMax(), getMin(), getTable(), Neutral::initCinfo(), lookupByIndex(), lookupByValue(), setDiv(), setMax(), setMin(), and setTable().
double VectorTable::lookupByIndex (unsigned int index) const
References tableIsEmpty().
Referenced by initCinfo().
double VectorTable::lookupByValue (double x) const
References doubleEq().
Referenced by initCinfo().
void VectorTable::setDiv (unsigned int xDivs)
Referenced by initCinfo(), and MarkovRateTable::setConstantRate().
void VectorTable::setMax (double xMax)
Referenced by initCinfo(), and MarkovRateTable::setConstantRate().
void VectorTable::setMin (double xMin)
Referenced by initCinfo(), and MarkovRateTable::setConstantRate().
void VectorTable::setTable (vector< double > table)
Referenced by initCinfo(), and MarkovRateTable::setConstantRate().
bool VectorTable::tableIsEmpty () const
Referenced by lookupByIndex().
Friends And Related Function Documentation
istream& operator>> (istream & , VectorTable &) friend
The documentation for this class was generated from the following files:
biophysics/VectorTable.h
biophysics/VectorTable.cpp