MOOSE: CylMesh Class Reference
CylMesh Class Reference
#include <CylMesh.h>
Public Member Functions
CylMesh ()
~CylMesh ()
void updateCoords (const Eref &e, const vector< double > &childConcs)
void setX0 (const Eref &e, double v)
double getX0 (const Eref &e) const
void setY0 (const Eref &e, double v)
double getY0 (const Eref &e) const
void setZ0 (const Eref &e, double v)
double getZ0 (const Eref &e) const
void setR0 (const Eref &e, double v)
double getR0 (const Eref &e) const
void setX1 (const Eref &e, double v)
double getX1 (const Eref &e) const
void setY1 (const Eref &e, double v)
double getY1 (const Eref &e) const
void setZ1 (const Eref &e, double v)
double getZ1 (const Eref &e) const
void setR1 (const Eref &e, double v)
double getR1 (const Eref &e) const
void innerSetCoords (const Eref &e, const vector< double > &v)
void setCoords (const Eref &e, vector< double > v)
vector< double > getCoords (const Eref &e) const
void setDiffLength (const Eref &e, double v)
double getDiffLength (const Eref &e) const
double getTotLength () const
unsigned int innerGetDimensions () const
unsigned int getMeshType (unsigned int fid) const
Virtual function to return MeshType of specified entry.
unsigned int getMeshDimensions (unsigned int fid) const
Virtual function to return dimensions of specified entry.
double getMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry.
vector< double > getCoordinates (unsigned int fid) const
Virtual function to return coords of mesh Entry.
vector< double > getDiffusionArea (unsigned int fid) const
Virtual function to return diffusion X-section area.
vector< double > getDiffusionScaling (unsigned int fid) const
Virtual function to return scale factor for diffusion. 1 here.
double extendedMeshEntryVolume (unsigned int fid) const
Volume of mesh Entry including abutting diff-coupled voxels.
unsigned int innerGetNumEntries () const
void innerSetNumEntries (unsigned int n)
Inherited virtual func.
vector< unsigned int > getParentVoxel () const
Inherited virtual, do nothing for now.
const vector< double > & vGetVoxelVolume () const
Virtual func so that derived classes can pass voxel volume back.
const vector< double > & vGetVoxelMidpoint () const
Virtual func so that derived classes can return voxel midpoint.
const vector< double > & getVoxelArea () const
const vector< double > & getVoxelLength () const
double vGetEntireVolume () const
Inherited virtual. Returns entire volume of compartment.
bool vSetVolumeNotRates (double volume)
Inherited virtual. Resizes len and dia of each voxel.
void innerBuildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
Virtual func to make a mesh with specified Volume and numEntries.
void innerHandleRequestMeshStats (const Eref &e, const SrcFinfo2< unsigned int, vector< double > > *meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
void innerHandleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void transmitChange (const Eref &e)
void buildStencil ()
void matchMeshEntries (const ChemCompt *other, vector< VoxelJunction > &ret) const
double nearest (double x, double y, double z, unsigned int &index) const
double nearest (double x, double y, double z, double &linePos, double &r) const
void indexToSpace (unsigned int index, double &x, double &y, double &z) const
void matchCylMeshEntries (const CylMesh *other, vector< VoxelJunction > &ret) const
void matchCubeMeshEntries (const CubeMesh *other, vector< VoxelJunction > &ret) const
void matchNeuroMeshEntries (const NeuroMesh *other, vector< VoxelJunction > &ret) const
double selectGridVolume (double h) const
Public Member Functions inherited from MeshCompt
MeshCompt ()
~MeshCompt ()
double extendedMeshEntryVolume (unsigned int fid) const
Virtual function to return volume of mesh Entry, including.
void clearExtendedMeshEntryVolume ()
Inherited virtual function to clear the vector of MeshEntryVolume.
void innerResetStencil ()
virtual func implemented here.
unsigned int getStencilRow (unsigned int meshIndex, const double **entry, const unsigned int **colIndex) const
const SparseMatrix< double > & getStencil () const
Returns entire sparse matrix of mesh. Used by diffusion solver.
vector< unsigned int > getNeighbors (unsigned int fid) const
Looks up stencil to return vector of indices of coupled voxels.
vector< double > innerGetStencilRate (unsigned int row) const
void addRow (unsigned int index, const vector< double > &entry, const vector< unsigned int > &colIndex)
void setStencilSize (unsigned int numRows, unsigned int numCols)
void extendStencil (const ChemCompt *other, const vector< VoxelJunction > &vj)
Add boundary voxels to stencil for cross-solver junctions.
Public Member Functions inherited from ChemCompt
ChemCompt ()
virtual ~ChemCompt ()
double getEntireVolume (const Eref &e) const
void setEntireVolume (const Eref &e, double volume)
double getOneVoxelVolume (const Eref &e, unsigned int voxel) const
unsigned int getDimensions () const
void setMethod (string method)
string getMethod () const
vector< double > getStencilRate (unsigned int row) const
vector< unsigned int > getStencilIndex (unsigned int row) const
vector< double > getVoxelVolume () const
Returns vector of all voxel volumes in compartment.
vector< double > getVoxelMidpoint () const
Returns vector of all voxel midpoints in compartment.
void setVolumeNotRates (double volume)
void buildDefaultMesh (const Eref &e, double volume, unsigned int numEntries)
void handleNodeInfo (const Eref &e, unsigned int numNodes, unsigned int numThreads)
void resetStencil ()
unsigned int getNumEntries () const
void setNumEntries (unsigned int num)
MeshEntry * lookupEntry (unsigned int index)
void getChildConcs (const Eref &e, vector< double > &childConcs) const
unsigned int setChildConcs (const Eref &e, const vector< double > &childConcs, unsigned int start) const
void buildJunction (ChemCompt *other, vector< VoxelJunction > &ret)
void flipRet (vector< VoxelJunction > &ret) const
Utility function for swapping first and second in VoxelJunctions.
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChemCompt
static double distance (double x, double y, double z)
static SrcFinfo1< vector
< double > > * voxelVolOut ()
static const Cinfo * initCinfo ()
Detailed Description
The CylMesh represents a chemically identified compartment shaped like an extended cylinder. This is psuedo-1 dimension: Only the axial dimension is considered for diffusion and subdivisions. Typically used in modelling small segments of dendrite
Constructor & Destructor Documentation
CylMesh::CylMesh ()
CylMesh::~CylMesh ()
Member Function Documentation
void CylMesh::buildStencil ()
References MeshCompt::addRow(), MeshCompt::innerResetStencil(), PI, and MeshCompt::setStencilSize().
Referenced by innerSetNumEntries(), and updateCoords().
double CylMesh::extendedMeshEntryVolume (unsigned int fid) const virtual
Volume of mesh Entry including abutting diff-coupled voxels.
Virtual function to return volume of mesh Entry, including for diffusively coupled voxels from other solvers.
Implements ChemCompt.
References MeshCompt::extendedMeshEntryVolume(), and getMeshEntryVolume().
vector< double > CylMesh::getCoordinates (unsigned int fid) const virtual
Virtual function to return coords of mesh Entry.
Virtual function to return coords of mesh Entry. For Cylindrical mesh, coords are x1y1z1 x2y2z2 r0 r1 phi0 phi1
Implements ChemCompt.
vector< double > CylMesh::getCoords (const Eref & e) const
Referenced by initCinfo().
double CylMesh::getDiffLength (const Eref & e) const
Referenced by initCinfo().
vector< double > CylMesh::getDiffusionArea (unsigned int fid) const virtual
Virtual function to return diffusion X-section area.
Virtual function to return diffusion X-section area for each neighbor.
Implements ChemCompt.
References PI.
vector< double > CylMesh::getDiffusionScaling (unsigned int fid) const virtual
Virtual function to return scale factor for diffusion. 1 here.
Implements ChemCompt.
unsigned int CylMesh::getMeshDimensions (unsigned int fid) const virtual
Virtual function to return dimensions of specified entry.
Implements ChemCompt.
double CylMesh::getMeshEntryVolume (unsigned int fid) const virtual
Virtual function to return volume of mesh Entry.
diffLength = length constant for diffusive spread len = length of each mesh entry totLen = total length of cylinder diffLength = k * r^2 Each entry has the same number of diffLengths, L = len/diffLength. Thinner entries have shorter diffLength. This gives a moderately nasty quadratic. However, as len(i) is prop to diffLength(i), and diffLength(i) is prop to r(i)^2 and the cyl-mesh is assumed a gently sloping cone we get len(i) is prop to (r0 + slope.x)^2 and ignoring the 2nd-order term we have len(i) is approx proportional to x position.
dr/dx = (r1-r0)/len ri = r0 + i * dr/dx r(i+1)-ri = (r1-r0)/numEntries len = k * r^2 we get k from integ_r0,r1(len.dr) = totLen So k.r^3/3 | r0, r1 = totLen => k/3 * (r1^3 - r0^3) = totLen => k = 3 * totLen / (r1^3 - r0^3); This is bad if r1 == r0, and is generally unpleasant.
Simple definition of rSlope: rSlope is measured per meshEntry, not per length: rSlope = (r1 - r0) / numEntries; Let's just compute len0 from r0 and diffLength. len0/diffLength = 2 * r0 / (r0 + r1) so len0 = diffLength * 2 * r0 / (r0 + r1) and dlen/dx = lenSlope = diffLength * rSlope * 2/(r0 + r1)
Drop the following calculations: // dlen/dx = dr/dx * dlen/dr = ((r1-r0)/len) * 2k.r // To linearize, let 2r = r0 + r1. // so dlen/dx = ((r1-r0)/len) * k * (r0 + r1) // len(i) = len0 + i * dlen/dx // len0 = totLen/numEntries - (numEntries/2) * dlen/dx
Implements ChemCompt.
Referenced by extendedMeshEntryVolume(), vGetEntireVolume(), and vGetVoxelVolume().
unsigned int CylMesh::getMeshType (unsigned int fid) const virtual
Virtual function to return MeshType of specified entry.
Implements ChemCompt.
References CYL, and SPHERE_SHELL_SEG.
vector< unsigned int > CylMesh::getParentVoxel () const virtual
Inherited virtual, do nothing for now.
Implements MeshCompt.
double CylMesh::getR0 (const Eref & e) const
Referenced by initCinfo().
double CylMesh::getR1 (const Eref & e) const
Referenced by initCinfo().
double CylMesh::getTotLength () const
Referenced by initCinfo().
const vector< double > & CylMesh::getVoxelArea () const virtual
Implements MeshCompt.
References PI.
const vector< double > & CylMesh::getVoxelLength () const virtual
Implements MeshCompt.
double CylMesh::getX0 (const Eref & e) const
Referenced by initCinfo().
double CylMesh::getX1 (const Eref & e) const
Referenced by initCinfo().
double CylMesh::getY0 (const Eref & e) const
Referenced by initCinfo().
double CylMesh::getY1 (const Eref & e) const
Referenced by initCinfo().
double CylMesh::getZ0 (const Eref & e) const
Referenced by initCinfo().
double CylMesh::getZ1 (const Eref & e) const
Referenced by initCinfo().
void CylMesh::indexToSpace (unsigned int index, double & x, double & y, double & z) const virtual
Converts specified index to xyz coords of middle of voxel Values out of range return original xyz
Implements ChemCompt.
const Cinfo * CylMesh::initCinfo () static
References getCoords(), getDiffLength(), getR0(), getR1(), getTotLength(), getX0(), getX1(), getY0(), getY1(), getZ0(), getZ1(), ChemCompt::initCinfo(), innerGetNumEntries(), setCoords(), setDiffLength(), setR0(), setR1(), setX0(), setX1(), setY0(), setY1(), setZ0(), and setZ1().
void CylMesh::innerBuildDefaultMesh (const Eref & e, double volume, unsigned int numEntries) virtual
Virtual func to make a mesh with specified Volume and numEntries.
Single voxel cylinder with diameter = length. vol = volume = pi.r^2.len. So len = 2r, volume = pi*r^2*2r = 2pi*r^3 so r = (volume/2pi)^(1/3)
Implements ChemCompt.
References PI, and setCoords().
unsigned int CylMesh::innerGetDimensions () const virtual
Implements ChemCompt.
unsigned int CylMesh::innerGetNumEntries () const virtual
Inherited virtual func. Returns number of MeshEntry in array
Implements ChemCompt.
Referenced by initCinfo().
void CylMesh::innerHandleNodeInfo (const Eref & e, unsigned int numNodes, unsigned int numThreads) virtual
Implements ChemCompt.
void CylMesh::innerHandleRequestMeshStats (const Eref & e, const SrcFinfo2< unsigned int, vector< double > > * meshStatsFinfo)
More inherited virtual funcs: request comes in for mesh stats.
References vGetEntireVolume().
void CylMesh::innerSetCoords (const Eref & e, const vector< double > & v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by setCoords().
void CylMesh::innerSetNumEntries (unsigned int n) virtual
Inherited virtual func.
Inherited virtual func. Assigns number of MeshEntries.
Implements ChemCompt.
References buildStencil().
void CylMesh::matchCubeMeshEntries (const CubeMesh * other, vector< VoxelJunction > & ret) const
References a, Vec::a0(), Vec::a1(), Vec::a2(), EPSILON, fillPointsOnCircle(), CubeMesh::getDx(), ChemCompt::getNumEntries(), Vec::orthogonalAxes(), and selectGridVolume().
Referenced by matchMeshEntries().
void CylMesh::matchCylMeshEntries (const CylMesh * other, vector< VoxelJunction > & ret) const
References ChemCompt::distance(), EPSILON, and PI.
Referenced by matchMeshEntries().
void CylMesh::matchMeshEntries (const ChemCompt * other, vector< VoxelJunction > & ret) const virtual
Returns the meshIndices (NOT spatial indices) of all adjacent mesh entry pairs on ether side of the (self, other) junction. meshIndices are the indices that look up entries in the vector of pools. spatialIndices are (iz * ny + iy) * nx + ix, that is, a linear conversion of cartesian spatial indices. So, for two touching cubes, the return vector is the paired meshIndices on either side of the plane of contact. If one mesh has a finer mesh than the other, or if there are more than one contact points from self to other (for example, at a corner), then we just have multiple pairs using the same meshIndex of the repeated voxel.
Implements ChemCompt.
References matchCubeMeshEntries(), matchCylMeshEntries(), and matchNeuroMeshEntries().
void CylMesh::matchNeuroMeshEntries (const NeuroMesh * other, vector< VoxelJunction > & ret) const
Referenced by matchMeshEntries().
double CylMesh::nearest (double x, double y, double z, unsigned int & index) const virtual
Returns distance and index of nearest mesh entry. Computes each mesh entry position as its geometric centre. If the current location is not inside a valid mesh entry, distance returned is negative.
Implements ChemCompt.
double CylMesh::nearest (double x, double y, double z, double & linePos, double & r) const
References ChemCompt::distance().
double CylMesh::selectGridVolume (double h) const
Referenced by matchCubeMeshEntries().
void CylMesh::setCoords (const Eref & e, vector< double > v)
References innerSetCoords(), and transmitChange().
Referenced by initCinfo(), and innerBuildDefaultMesh().
void CylMesh::setDiffLength (const Eref & e, double v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by initCinfo().
void CylMesh::setR0 (const Eref & e, double v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by initCinfo().
void CylMesh::setR1 (const Eref & e, double v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by initCinfo().
void CylMesh::setX0 (const Eref & e, double v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by initCinfo().
void CylMesh::setX1 (const Eref & e, double v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by initCinfo().
void CylMesh::setY0 (const Eref & e, double v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by initCinfo().
void CylMesh::setY1 (const Eref & e, double v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by initCinfo().
void CylMesh::setZ0 (const Eref & e, double v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by initCinfo().
void CylMesh::setZ1 (const Eref & e, double v)
References ChemCompt::getChildConcs(), and updateCoords().
Referenced by initCinfo().
void CylMesh::transmitChange (const Eref & e)
Referenced by setCoords().
void CylMesh::updateCoords (const Eref & e, const vector< double > & concs)
Recomputes all local coordinate and meshing data following a change in any of the coord parameters
This assumes that diffLength is the quantity to preserve, over numEntries. So when the compartment changes volume, numEntries changes. diffLength will be fine-tuned to be a clean multiple.
References buildStencil(), doubleEq(), and ChemCompt::setChildConcs().
Referenced by innerSetCoords(), setDiffLength(), setR0(), setR1(), setX0(), setX1(), setY0(), setY1(), setZ0(), and setZ1().
double CylMesh::vGetEntireVolume () const virtual
Inherited virtual. Returns entire volume of compartment.
Implements ChemCompt.
References getMeshEntryVolume().
Referenced by innerHandleRequestMeshStats(), and vSetVolumeNotRates().
const vector< double > & CylMesh::vGetVoxelMidpoint () const virtual
Virtual func so that derived classes can return voxel midpoint.
Implements ChemCompt.
const vector< double > & CylMesh::vGetVoxelVolume () const virtual
Virtual func so that derived classes can pass voxel volume back.
Implements ChemCompt.
References getMeshEntryVolume().
bool CylMesh::vSetVolumeNotRates (double volume) virtual
Inherited virtual. Resizes len and dia of each voxel.
Implements ChemCompt.
References vGetEntireVolume().
The documentation for this class was generated from the following files:
mesh/CylMesh.h
mesh/CylMesh.cpp