MOOSE: HHChannelBase Class Reference
HHChannelBase Class Reference abstract
#include <HHChannelBase.h>
Public Member Functions
HHChannelBase ()
~HHChannelBase ()
void setXpower (const Eref &e, double Xpower)
double getXpower (const Eref &e) const
void setYpower (const Eref &e, double Ypower)
double getYpower (const Eref &e) const
void setZpower (const Eref &e, double Zpower)
double getZpower (const Eref &e) const
void setInstant (const Eref &e, int Instant)
int getInstant (const Eref &e) const
void setX (const Eref &e, double X)
double getX (const Eref &e) const
void setY (const Eref &e, double Y)
double getY (const Eref &e) const
void setZ (const Eref &e, double Z)
double getZ (const Eref &e) const
void setUseConcentration (const Eref &e, int value)
int getUseConcentration (const Eref &e) const
void handleConc (const Eref &e, double conc)
HHGate * getXgate (unsigned int i)
HHGate * getYgate (unsigned int i)
HHGate * getZgate (unsigned int i)
void setNumGates (unsigned int num)
unsigned int getNumXgates () const
unsigned int getNumYgates () const
Returns 1 if Y gate present, otherwise 0.
unsigned int getNumZgates () const
Returns 1 if Z gate present, otherwise 0.
void createGate (const Eref &e, string gateType)
virtual void vSetXpower (const Eref &e, double Xpower)=0
virtual void vSetYpower (const Eref &e, double Ypower)=0
virtual void vSetZpower (const Eref &e, double Zpower)=0
virtual void vSetInstant (const Eref &e, int Instant)=0
virtual int vGetInstant (const Eref &e) const =0
virtual void vSetX (const Eref &e, double X)=0
virtual double vGetX (const Eref &e) const =0
virtual void vSetY (const Eref &e, double Y)=0
virtual double vGetY (const Eref &e) const =0
virtual void vSetZ (const Eref &e, double Z)=0
virtual double vGetZ (const Eref &e) const =0
virtual void vSetUseConcentration (const Eref &e, int value)=0
virtual void vHandleConc (const Eref &e, double conc)=0
virtual HHGate * vGetXgate (unsigned int i) const =0
virtual HHGate * vGetYgate (unsigned int i) const =0
virtual HHGate * vGetZgate (unsigned int i) const =0
virtual void vCreateGate (const Eref &e, string gateType)=0
virtual void vSetSolver (const Eref &e, Id hsolve)
Public Member Functions inherited from ChanBase
ChanBase ()
~ChanBase ()
void setGbar (const Eref &e, double Gbar)
virtual void vSetGbar (const Eref &e, double Gbar)=0
double getGbar (const Eref &e) const
virtual double vGetGbar (const Eref &e) const =0
void setEk (const Eref &e, double Ek)
virtual void vSetEk (const Eref &e, double Ek)=0
double getEk (const Eref &e) const
virtual double vGetEk (const Eref &e) const =0
void setGk (const Eref &e, double Gk)
virtual void vSetGk (const Eref &e, double Gk)=0
double getGk (const Eref &e) const
virtual double vGetGk (const Eref &e) const =0
void setIk (const Eref &e, double Ic)
virtual void vSetIk (const Eref &e, double Ik)=0
double getIk (const Eref &e) const
virtual double vGetIk (const Eref &e) const =0
void handleVm (double Vm)
virtual void vHandleVm (double Vm)=0
void process (const Eref &e, const ProcPtr info)
void reinit (const Eref &e, const ProcPtr info)
virtual void vProcess (const Eref &e, const ProcPtr info)=0
virtual void vReinit (const Eref &e, const ProcPtr info)=0
Static Public Member Functions
static double power1 (double x, double p)
static double power2 (double x, double p)
static double power3 (double x, double p)
static double power4 (double x, double p)
static double powerN (double x, double p)
static PFDD selectPower (double power)
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ChanBase
static SrcFinfo1< double > * permeability ()
static SrcFinfo2< double,
double > * channelOut ()
static SrcFinfo1< double > * IkOut ()
static const Cinfo * initCinfo ()
Specify the Class Info static variable for initialization.
Protected Attributes
double Xpower_
Exponent for X gate.
double Ypower_
Exponent for Y gate.
double Zpower_
Exponent for Z gate.
bool useConcentration_
Flag for use of conc for input to Z gate calculations.
Detailed Description
The HHChannelBase is the base class for defining Hodgkin-Huxley type channels, specifically dealing with derivatives used in the HSolver. This is derived from the ChanBase rather than the ChanCommon, since the Zombie classes used in the HSolver will not use the ChanCommon fields.
Constructor & Destructor Documentation
HHChannelBase::HHChannelBase ()
HHChannelBase::~HHChannelBase ()
Member Function Documentation
void HHChannelBase::createGate (const Eref & e, string gateType)
Function for safely creating each gate, identified by strings as X, Y and Z. Will only work on a new channel, not on a copy. The idea is that the gates are always referred to the original 'library' channel, and their contents cannot be touched except by the original.
References vCreateGate().
Referenced by initCinfo(), and HHChannel::setGatePower().
int HHChannelBase::getInstant (const Eref & e) const
References vGetInstant().
Referenced by initCinfo().
unsigned int HHChannelBase::getNumXgates () const
Access function for the number of Xgates. Gives 1 if present, otherwise 0.
References vGetXgate().
Referenced by initCinfo().
unsigned int HHChannelBase::getNumYgates () const
Returns 1 if Y gate present, otherwise 0.
References vGetYgate().
Referenced by initCinfo().
unsigned int HHChannelBase::getNumZgates () const
Returns 1 if Z gate present, otherwise 0.
References vGetZgate().
Referenced by initCinfo().
int HHChannelBase::getUseConcentration (const Eref & e) const
References useConcentration_.
Referenced by initCinfo(), and zombify().
double HHChannelBase::getX (const Eref & e) const
References vGetX().
Referenced by initCinfo().
HHGate * HHChannelBase::getXgate (unsigned int i)
Access function used for the X gate. The index is ignored.
References vGetXgate().
Referenced by initCinfo().
double HHChannelBase::getXpower (const Eref & e) const
References Xpower_.
Referenced by initCinfo(), and zombify().
double HHChannelBase::getY (const Eref & e) const
References vGetY().
Referenced by initCinfo().
HHGate * HHChannelBase::getYgate (unsigned int i)
Access function used for the Y gate. The index is ignored.
References vGetYgate().
Referenced by initCinfo().
double HHChannelBase::getYpower (const Eref & e) const
References Ypower_.
Referenced by initCinfo(), and zombify().
double HHChannelBase::getZ (const Eref & e) const
References vGetZ().
Referenced by initCinfo().
HHGate * HHChannelBase::getZgate (unsigned int i)
Access function used for the Z gate. The index is ignored.
References vGetZgate().
Referenced by initCinfo().
double HHChannelBase::getZpower (const Eref & e) const
References Zpower_.
Referenced by initCinfo(), and zombify().
void HHChannelBase::handleConc (const Eref & e, double conc)
Assign the local conc_ to the incoming conc from the concentration calculations for the compartment. Typically the message source will be a CaConc object, but there are other options for computing the conc.
References vHandleConc().
Referenced by initCinfo().
const Cinfo * HHChannelBase::initCinfo () static
References createGate(), getInstant(), getNumXgates(), getNumYgates(), getNumZgates(), getUseConcentration(), getX(), getXgate(), getXpower(), getY(), getYgate(), getYpower(), getZ(), getZgate(), getZpower(), handleConc(), ChanBase::initCinfo(), HHGate::initCinfo(), setInstant(), setNumGates(), setUseConcentration(), setX(), setXpower(), setY(), setYpower(), setZ(), and setZpower().
Referenced by ZombieHHChannel::initCinfo(), and HHChannel::initCinfo().
static double HHChannelBase::power1 (double x, double p) inline static
Referenced by selectPower().
static double HHChannelBase::power2 (double x, double p) inline static
Referenced by power4(), and selectPower().
static double HHChannelBase::power3 (double x, double p) inline static
Referenced by selectPower().
static double HHChannelBase::power4 (double x, double p) inline static
References power2().
Referenced by selectPower().
double HHChannelBase::powerN (double x, double p) static
Referenced by selectPower().
PFDD HHChannelBase::selectPower (double power) static
References doubleEq(), power1(), power2(), power3(), power4(), and powerN().
Referenced by HHChannel::vSetXpower(), HHChannel::vSetYpower(), and HHChannel::vSetZpower().
void HHChannelBase::setInstant (const Eref & e, int Instant)
References vSetInstant().
Referenced by initCinfo().
void HHChannelBase::setNumGates (unsigned int num)
Dummy assignment function for the number of gates.
Referenced by initCinfo().
void HHChannelBase::setUseConcentration (const Eref & e, int value)
References useConcentration_, and vSetUseConcentration().
Referenced by initCinfo().
void HHChannelBase::setX (const Eref & e, double X)
References vSetX().
Referenced by initCinfo().
void HHChannelBase::setXpower (const Eref & e, double power)
Assigns the Xpower for this gate. If the gate exists and has only this element for input, then change the gate value. If the gate exists and has multiple parents, then make a new gate. If the gate does not exist, make a new gate
References checkPower(), and vSetXpower().
Referenced by initCinfo().
void HHChannelBase::setY (const Eref & e, double Y)
References vSetY().
Referenced by initCinfo().
void HHChannelBase::setYpower (const Eref & e, double Ypower)
References checkPower(), and vSetYpower().
Referenced by initCinfo().
void HHChannelBase::setZ (const Eref & e, double Z)
References vSetZ().
Referenced by initCinfo().
void HHChannelBase::setZpower (const Eref & e, double Zpower)
References checkPower(), and vSetZpower().
Referenced by initCinfo().
virtual void HHChannelBase::vCreateGate (const Eref & e, string gateType) pure virtual
Implemented in HHChannel.
Referenced by createGate().
virtual int HHChannelBase::vGetInstant (const Eref & e) const pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by getInstant().
virtual double HHChannelBase::vGetX (const Eref & e) const pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by getX().
virtual HHGate* HHChannelBase::vGetXgate (unsigned int i) const pure virtual
Implemented in HHChannel, and ZombieHHChannel.
Referenced by getNumXgates(), and getXgate().
virtual double HHChannelBase::vGetY (const Eref & e) const pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by getY().
virtual HHGate* HHChannelBase::vGetYgate (unsigned int i) const pure virtual
Implemented in HHChannel, and ZombieHHChannel.
Referenced by getNumYgates(), and getYgate().
virtual double HHChannelBase::vGetZ (const Eref & e) const pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by getZ().
virtual HHGate* HHChannelBase::vGetZgate (unsigned int i) const pure virtual
Implemented in HHChannel, and ZombieHHChannel.
Referenced by getNumZgates(), and getZgate().
virtual void HHChannelBase::vHandleConc (const Eref & e, double conc) pure virtual
Implemented in HHChannel, and ZombieHHChannel.
Referenced by handleConc().
virtual void HHChannelBase::vSetInstant (const Eref & e, int Instant) pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by setInstant().
void HHChannelBase::vSetSolver (const Eref & e, Id hsolve) virtual
Reimplemented in ZombieHHChannel.
Referenced by zombify().
virtual void HHChannelBase::vSetUseConcentration (const Eref & e, int value) pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by setUseConcentration().
virtual void HHChannelBase::vSetX (const Eref & e, double X) pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by setX().
virtual void HHChannelBase::vSetXpower (const Eref & e, double Xpower) pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by setXpower(), and zombify().
virtual void HHChannelBase::vSetY (const Eref & e, double Y) pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by setY().
virtual void HHChannelBase::vSetYpower (const Eref & e, double Ypower) pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by setYpower(), and zombify().
virtual void HHChannelBase::vSetZ (const Eref & e, double Z) pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by setZ().
virtual void HHChannelBase::vSetZpower (const Eref & e, double Zpower) pure virtual
Implemented in ZombieHHChannel, and HHChannel.
Referenced by setZpower(), and zombify().
void HHChannelBase::zombify (Element * orig, const Cinfo * zClass, Id hsolve) static
References Element::cinfo(), Eref::data(), getUseConcentration(), getXpower(), getYpower(), getZpower(), Element::localDataStart(), Element::numLocalData(), ChanBase::vGetEk(), ChanBase::vGetGbar(), ChanBase::vSetEk(), ChanBase::vSetGbar(), vSetSolver(), vSetXpower(), vSetYpower(), vSetZpower(), and Element::zombieSwap().
Member Data Documentation
bool HHChannelBase::useConcentration_ protected
Flag for use of conc for input to Z gate calculations.
Referenced by getUseConcentration(), setUseConcentration(), HHChannel::vProcess(), HHChannel::vReinit(), and HHChannel::vSetZpower().
double HHChannelBase::Xpower_ protected
Exponent for X gate.
Referenced by getXpower(), HHChannel::vProcess(), HHChannel::vReinit(), HHChannel::vSetXpower(), ZombieHHChannel::vSetXpower(), ZombieHHChannel::vSetYpower(), and ZombieHHChannel::vSetZpower().
double HHChannelBase::Ypower_ protected
Exponent for Y gate.
Referenced by getYpower(), HHChannel::vProcess(), HHChannel::vReinit(), ZombieHHChannel::vSetXpower(), HHChannel::vSetYpower(), ZombieHHChannel::vSetYpower(), and ZombieHHChannel::vSetZpower().
double HHChannelBase::Zpower_ protected
Exponent for Z gate.
Referenced by getZpower(), HHChannel::vProcess(), HHChannel::vReinit(), ZombieHHChannel::vSetXpower(), ZombieHHChannel::vSetYpower(), HHChannel::vSetZpower(), and ZombieHHChannel::vSetZpower().
The documentation for this class was generated from the following files:
biophysics/HHChannelBase.h
biophysics/HHChannelBase.cpp