MOOSE: GetEpFunc1< T, L, A > Class Template Reference
GetEpFunc1< T, L, A > Class Template Reference
#include <EpFunc.h>
Public Member Functions
GetEpFunc1 (A(T::*func)(const Eref &e, L) const)
void op (const Eref &e, L index, ObjId recipient, FuncId fid) const
A returnOp (const Eref &e, const L &index) const
Public Member Functions inherited from LookupGetOpFuncBase< L, A >
bool checkFinfo (const Finfo *s) const
const OpFunc * makeHopFunc (HopIndex hopIndex) const
const OpFunc * makeHopFunc (HopIndex hopIndex, const L &index) const
void opBuffer (const Eref &e, double *buf) const
Executes the OpFunc by converting args.
string rttiType () const
Public Member Functions inherited from OpFunc
OpFunc ()
virtual ~OpFunc ()
virtual void opVecBuffer (const Eref &e, double *buf) const
Executes the OpFunc for all data by converting a vector of args.
unsigned int opIndex () const
bool setIndex (unsigned int i)
Used when rebuilding the Fid->OpFunc mapping.
Additional Inherited Members
Static Public Member Functions inherited from OpFunc
static const OpFunc * lookop (unsigned int opIndex)
static unsigned int rebuildOpIndex ()
cleans out the entire Ops vector. Returns size of orig vector.
Detailed Description
template<class T, class L, class A>
class GetEpFunc1< T, L, A >
This specialized EpFunc is for returning a single field value, but the field lookup requires an index argument as well. Unlike the regular GetOpFunc, this variant takes the Eref and Qinfo. It generates an opFunc that takes a single argument: FuncId of the function on the object that requested the value. The EpFunc then sends back a message with the info.
Constructor & Destructor Documentation
template<class T , class L , class A > GetEpFunc1< T, L, A >::GetEpFunc1 (A(T::*)(const Eref &e, L) const func) inline
Member Function Documentation
template<class T , class L , class A > void GetEpFunc1< T, L, A >::op (const Eref & e, L index, ObjId recipient, FuncId fid) const inline virtual
Implements LookupGetOpFuncBase< L, A >.
References Element::cinfo(), ObjId::element(), ObjId::eref(), Cinfo::getOpFunc(), OpFunc1Base< A >::op(), and GetEpFunc1< T, L, A >::returnOp().
template<class T , class L , class A > A GetEpFunc1< T, L, A >::returnOp (const Eref & e, const L & index) const inline virtual
Implements LookupGetOpFuncBase< L, A >.
References Eref::data().
Referenced by GetEpFunc1< T, L, A >::op().
The documentation for this class was generated from the following file:
basecode/EpFunc.h