MOOSE: TableBase Class Reference
TableBase Class Reference
#include <TableBase.h>
Public Member Functions
TableBase ()
vector< double > getVec () const
void setVec (vector< double > val)
double getOutputValue () const
void setOutputValue (double val)
double getY (unsigned int index) const
void linearTransform (double scale, double offset)
void xplot (string file, string plotname)
void plainPlot (string file)
void loadXplot (string fname, string plotname)
void loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
void loadCSV (string fname, int startLine, int colNum, char separator)
void compareXplot (string fname, string plotname, string op)
void compareVec (vector< double > other, string op)
void clearVec ()
double * lookupVec (unsigned int index)
void setVecSize (unsigned int num)
unsigned int getVecSize () const
double interpolate (double x, double xmin, double xmax) const
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Member Functions
vector< double > & vec ()
Detailed Description
Base class for table operations. Provides basics for looking up table and interpolation, but no process or messaging. Derived classes deal with these.
Constructor & Destructor Documentation
TableBase::TableBase ()
Member Function Documentation
void TableBase::clearVec ()
Referenced by initCinfo().
void TableBase::compareVec (vector< double > other, string op)
References getRMSDiff(), getRMSRatio(), and headop().
Referenced by initCinfo().
void TableBase::compareXplot (string fname, string plotname, string op)
References getRMSDiff(), getRMSRatio(), headop(), and innerLoadXplot().
Referenced by initCinfo().
double TableBase::getOutputValue () const
Referenced by initCinfo().
vector< double > TableBase::getVec () const
Referenced by initCinfo().
unsigned int TableBase::getVecSize () const
Referenced by initCinfo().
double TableBase::getY (unsigned int index) const
Referenced by initCinfo().
const Cinfo * TableBase::initCinfo () static
References clearVec(), compareVec(), compareXplot(), getOutputValue(), getVec(), getVecSize(), getY(), Neutral::initCinfo(), linearTransform(), loadCSV(), loadXplot(), loadXplotRange(), plainPlot(), setVec(), vec(), xplot(), and y.
Referenced by TimeTable::initCinfo(), Table::initCinfo(), StimulusTable::initCinfo(), and Interpol::initCinfo().
double TableBase::interpolate (double x, double xmin, double xmax) const
References y.
Referenced by StimulusTable::process(), Interpol::process(), and StimulusTable::reinit().
void TableBase::linearTransform (double scale, double offset)
Referenced by initCinfo().
void TableBase::loadCSV (string fname, int startLine, int colNum, char separator)
Referenced by initCinfo().
void TableBase::loadXplot (string fname, string plotname)
References innerLoadXplot().
Referenced by initCinfo().
void TableBase::loadXplotRange (string fname, string plotname, unsigned int start, unsigned int end)
References innerLoadXplot().
Referenced by initCinfo().
double* TableBase::lookupVec (unsigned int index)
void TableBase::plainPlot (string file)
Referenced by initCinfo().
void TableBase::setOutputValue (double val)
Referenced by StimulusTable::process(), and StimulusTable::reinit().
void TableBase::setVec (vector< double > val)
Referenced by initCinfo().
void TableBase::setVecSize (unsigned int num)
vector< double > & TableBase::vec () protected
Referenced by initCinfo(), Table::input(), TimeTable::process(), Table::process(), Table::reinit(), TimeTable::setFilename(), and Table::spike().
void TableBase::xplot (string file, string plotname)
Referenced by initCinfo().
The documentation for this class was generated from the following files:
builtins/TableBase.h
builtins/TableBase.cpp