MOOSE: Mstring Class Reference
Mstring Class Reference
#include <Mstring.h>
Public Member Functions
Mstring ()
Mstring (string other)
void setThis (string v)
string getThis () const
Static Public Member Functions
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
Mstring::Mstring ()
Mstring::Mstring (string other)
Member Function Documentation
string Mstring::getThis () const
Referenced by initCinfo().
const Cinfo * Mstring::initCinfo () static
References getThis(), Neutral::initCinfo(), and setThis().
void Mstring::setThis (string v)
Referenced by initCinfo().
The documentation for this class was generated from the following files:
builtins/Mstring.h
builtins/Mstring.cpp