MOOSE: SetGet3< A1, A2, A3 > Class Template Reference
SetGet3< A1, A2, A3 > Class Template Reference
#include <SetGet.h>
Public Member Functions
SetGet3 ()
Public Member Functions inherited from SetGet
SetGet ()
virtual ~SetGet ()
virtual bool checkOpClass (const OpFunc *op) const =0
Static Public Member Functions
static bool set (const ObjId &dest, const string &field, A1 arg1, A2 arg2, A3 arg3)
static bool innerStrSet (const ObjId &dest, const string &field, const string &val)
Static Public Member Functions inherited from SetGet
static const OpFunc * checkSet (const string &field, ObjId &tgt, FuncId &fid)
static bool strGet (const ObjId &tgt, const string &field, string &ret)
static bool strSet (const ObjId &dest, const string &field, const string &val)
static const vector< double * > * dispatchGet (const ObjId &tgt, FuncId tgtFid, const double *arg, unsigned int size)
Sends out request for data, and awaits its return.
Detailed Description
template<class A1, class A2, class A3>
class SetGet3< A1, A2, A3 >
SetGet3 handles 3-argument Sets. It does not deal with Gets.
Constructor & Destructor Documentation
template<class A1 , class A2 , class A3 > SetGet3< A1, A2, A3 >::SetGet3 () inline
Member Function Documentation
template<class A1 , class A2 , class A3 > static bool SetGet3< A1, A2, A3 >::innerStrSet (const ObjId & dest, const string & field, const string & val) inline static
Blocking call using string conversion. As yet we don't have 2 arg conversion from a single string. So this is a dummy
References SetGet3< A1, A2, A3 >::set(), and Conv< T >::str2val().
template<class A1 , class A2 , class A3 > static bool SetGet3< A1, A2, A3 >::set (const ObjId & dest, const string & field, A1 arg1, A2 arg2, A3 arg3) inline static
Blocking, typed 'Set' call
References SetGet::checkSet(), ObjId::eref(), ObjId::isGlobal(), ObjId::isOffNode(), OpFunc3Base< A1, A2, A3 >::makeHopFunc(), MooseSetHop, OpFunc3Base< A1, A2, A3 >::op(), and OpFunc::opIndex().
Referenced by SetGet3< A1, A2, A3 >::innerStrSet(), testAssortedMsg(), testCopyMsgOps(), and testShellAddMsg().
The documentation for this class was generated from the following file:
basecode/SetGet.h