MOOSE: DinfoBase Class Reference
DinfoBase Class Reference abstract
#include <Dinfo.h>
Public Member Functions
DinfoBase ()
DinfoBase (bool isOneZombie)
virtual ~DinfoBase ()
virtual char * allocData (unsigned int numData) const =0
virtual void destroyData (char *d) const =0
virtual unsigned int size () const =0
virtual unsigned int sizeIncrement () const =0
virtual char * copyData (const char *orig, unsigned int origEntries, unsigned int copyEntries, unsigned int startEntry) const =0
virtual void assignData (char *copy, unsigned int copyEntries, const char *orig, unsigned int origEntries) const =0
virtual bool isA (const DinfoBase *other) const =0
bool isOneZombie () const
Constructor & Destructor Documentation
DinfoBase::DinfoBase () inline
DinfoBase::DinfoBase (bool isOneZombie) inline
virtual DinfoBase::~DinfoBase () inline virtual
Member Function Documentation
virtual char* DinfoBase::allocData (unsigned int numData) const pure virtual
Implemented in Dinfo< D >.
Referenced by DataElement::zombieSwap().
virtual void DinfoBase::assignData (char * copy, unsigned int copyEntries, const char * orig, unsigned int origEntries) const pure virtual
Assigns data contents from 'orig' over to 'copy'. Tiles the origEntries onto the copyEntries. So if there are fewer origEntries, the orig data contents are repeated till the copy is full.
Implemented in Dinfo< D >.
Referenced by buildFinfoElement(), and Cinfo::makeCinfoElements().
virtual char* DinfoBase::copyData (const char * orig, unsigned int origEntries, unsigned int copyEntries, unsigned int startEntry) const pure virtual
Return a newly allocated copy of the original data, repeated copyEntries times. Orig data untouched. Analogous to copying a vector into a bigger one. Repeat the original data as many times as possible.
Implemented in Dinfo< D >.
Referenced by DataElement::DataElement(), and DataElement::resize().
virtual void DinfoBase::destroyData (char * d) const pure virtual
Implemented in Dinfo< D >.
Referenced by DataElement::resize(), DataElement::zombieSwap(), and DataElement::~DataElement().
virtual bool DinfoBase::isA (const DinfoBase * other) const pure virtual
Implemented in Dinfo< D >.
bool DinfoBase::isOneZombie () const inline
Referenced by Dinfo< D >::assignData(), and Dinfo< D >::copyData().
virtual unsigned int DinfoBase::size () const pure virtual
Implemented in ZeroSizeDinfo< D >, and Dinfo< D >.
virtual unsigned int DinfoBase::sizeIncrement () const pure virtual
Implemented in ZeroSizeDinfo< D >, and Dinfo< D >.
Referenced by DataElement::DataElement(), and DataElement::zombieSwap().
The documentation for this class was generated from the following file:
basecode/Dinfo.h