MOOSE: RandGenerator Class Reference
RandGenerator Class Reference
#include <RandGenerator.h>
Public Member Functions
RandGenerator ()
virtual ~RandGenerator ()
double getMean () const
double getVariance () const
double getSample () const
void process (const Eref &e, ProcPtr info)
void reinit (const Eref &e, ProcPtr info)
virtual void vReinit (const Eref &e, ProcPtr info)
Static Public Member Functions
static const Cinfo * initCinfo ()
Protected Attributes
Probability * rng_
double sample_
Detailed Description
This class is a moose interface to underlying random number generators (which is an instance of Probability class).
Constructor & Destructor Documentation
RandGenerator::RandGenerator ()
References rng_, and sample_.
RandGenerator::~RandGenerator () virtual
References rng_.
Member Function Documentation
double RandGenerator::getMean () const
References Probability::getMean(), and rng_.
Referenced by PoissonRng::initCinfo(), NormalRng::initCinfo(), and initCinfo().
double RandGenerator::getSample () const
References sample_.
Referenced by initCinfo().
double RandGenerator::getVariance () const
References Probability::getVariance(), and rng_.
Referenced by NormalRng::initCinfo(), and initCinfo().
const Cinfo * RandGenerator::initCinfo () static
References getMean(), getSample(), getVariance(), Neutral::initCinfo(), process(), and reinit().
Referenced by PoissonRng::initCinfo(), UniformRng::initCinfo(), BinomialRng::initCinfo(), ExponentialRng::initCinfo(), NormalRng::initCinfo(), and GammaRng::initCinfo().
void RandGenerator::process (const Eref & e, ProcPtr info)
References Probability::getNextSample(), rng_, and sample_.
Referenced by initCinfo().
void RandGenerator::reinit (const Eref & e, ProcPtr info)
References vReinit().
Referenced by initCinfo().
void RandGenerator::vReinit (const Eref & e, ProcPtr info) virtual
Reimplemented in GammaRng, NormalRng, ExponentialRng, BinomialRng, UniformRng, and PoissonRng.
References Eref::id(), and Id::path().
Referenced by reinit().
Member Data Documentation
Probability* RandGenerator::rng_ protected
Referenced by UniformRng::getMax(), getMean(), NormalRng::getMethod(), UniformRng::getMin(), getVariance(), NormalRng::NormalRng(), process(), RandGenerator(), GammaRng::setAlpha(), UniformRng::setMax(), PoissonRng::setMean(), NormalRng::setMean(), ExponentialRng::setMean(), NormalRng::setMethod(), ExponentialRng::setMethod(), UniformRng::setMin(), BinomialRng::setN(), BinomialRng::setP(), GammaRng::setTheta(), NormalRng::setVariance(), UniformRng::UniformRng(), PoissonRng::vReinit(), BinomialRng::vReinit(), ExponentialRng::vReinit(), GammaRng::vReinit(), and ~RandGenerator().
double RandGenerator::sample_ protected
Referenced by getSample(), process(), and RandGenerator().
The documentation for this class was generated from the following files:
randnum/RandGenerator.h
randnum/RandGenerator.cpp