MOOSE: FuncRate Class Reference
FuncRate Class Reference
#include <FuncRateTerm.h>
Public Member Functions
FuncRate (double k, unsigned int targetPoolIndex)
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
unsigned int getReactants (vector< unsigned int > &molIndex) const
void setReactants (const vector< unsigned int > &molIndex)
const vector< unsigned int > & getFuncArgIndex ()
void setFuncArgIndex (const vector< unsigned int > &mol)
void setExpr (const string &s)
const string & getExpr () const
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
Public Member Functions inherited from ExternReac
double operator() (const double *S) const
Computes the rate. The argument is the molecule array.
void setRates (double k1, double k2)
void setR1 (double k1)
Used by Zombie to assign rate terms.
void setR2 (double k2)
Used by Zombie to assign rate terms.
double getR1 () const
Used by Zombie to return rate terms.
double getR2 () const
Used by Zombie to return rate terms.
unsigned int getReactants (vector< unsigned int > &molIndex) const
void rescaleVolume (short comptIndex, const vector< short > &compartmentLookup, double ratio)
RateTerm * copyWithVolScaling (double vol, double sub, double prd) const
Public Member Functions inherited from RateTerm
RateTerm ()
virtual ~RateTerm ()
Protected Attributes
FuncTerm func_
double k_
double funcVolPower_
Additional Inherited Members
Static Public Attributes inherited from RateTerm
static const double EPSILON = 1.0e-6
Detailed Description
This FuncRate manages a one-way reaction whose rate is determined by a Function. It has no substrates, just controls the rate of change of a target molecule.
dtarget/dt = func(x0, x1, x2..., t)
The values x0, x1, x2 are expected to be concentrations so that they do not depend on volume.
Constructor & Destructor Documentation
FuncRate::FuncRate (double k, unsigned int targetPoolIndex) inline
References func_, and FuncTerm::setTarget().
Referenced by copyWithVolScaling().
Member Function Documentation
RateTerm* FuncRate::copyWithVolScaling (double vol, double sub, double prd) const inline virtual
Duplicates rate term and then applies volume scaling. Arguments are volume of reference voxel, product of vol/refVol for all substrates: applied to R1 product of vol/refVol for all products: applied to R2
Note that unless the reaction is cross-compartment, the vol/refVol will be one.
Implements RateTerm.
Reimplemented in FuncReac.
References func_, FuncRate(), funcVolPower_, FuncTerm::getTarget(), k_, and NA.
const string& FuncRate::getExpr () const inline
References func_, and FuncTerm::getExpr().
const vector< unsigned int >& FuncRate::getFuncArgIndex () inline
References func_, and FuncTerm::getReactantIndex().
unsigned int FuncRate::getReactants (vector< unsigned int > & molIndex) const inline virtual
This function finds the reactant indices in the vector S. It returns the number of substrates found, which are the first entries in molIndex. The products are the remaining ones. Note that it does NOT find products for unidirectional reactions, which is a bit of a problem.
Implements RateTerm.
Reimplemented in FuncReac.
References func_, and FuncTerm::getTarget().
double FuncRate::operator() (const double * S) const inline virtual
Computes the rate. The argument is the molecule array.
Implements RateTerm.
Reimplemented in FuncReac.
References func_.
void FuncRate::setExpr (const string & s) inline
References func_, and FuncTerm::setExpr().
Referenced by Stoich::installAndUnschedFuncReac(), and Stoich::setFunctionExpr().
void FuncRate::setFuncArgIndex (const vector< unsigned int > & mol) inline
References func_, and FuncTerm::setReactantIndex().
Referenced by Stoich::installAndUnschedFuncReac().
void FuncRate::setReactants (const vector< unsigned int > & molIndex) inline
References func_, and FuncTerm::setTarget().
Member Data Documentation
FuncTerm FuncRate::func_ protected
Referenced by copyWithVolScaling(), FuncReac::copyWithVolScaling(), FuncRate(), getExpr(), getFuncArgIndex(), getReactants(), operator()(), FuncReac::operator()(), setExpr(), setFuncArgIndex(), and setReactants().
double FuncRate::funcVolPower_ protected
Referenced by copyWithVolScaling(), and FuncReac::copyWithVolScaling().
double FuncRate::k_ protected
Referenced by copyWithVolScaling(), FuncReac::copyWithVolScaling(), and FuncReac::rescaleVolume().
The documentation for this class was generated from the following file:
ksolve/FuncRateTerm.h