MOOSE: Reac Class Reference
Reac Class Reference
#include <Reac.h>
Public Member Functions
Reac ()
void vSetNumKf (const Eref &e, double v)
double vGetNumKf (const Eref &e) const
void vSetNumKb (const Eref &e, double v)
double vGetNumKb (const Eref &e) const
void vSetConcKf (const Eref &e, double v)
set Kf in concentration units
double vGetConcKf (const Eref &e) const
vGet Kf in concentration units
void vSetConcKb (const Eref &e, double v)
set Kb in concentration units
double vGetConcKb (const Eref &e) const
get Kb in concentration units
void vProcess (const Eref &e, ProcPtr p)
void vReinit (const Eref &e, ProcPtr p)
void vSub (double v)
void vPrd (double v)
void vRemesh (const Eref &e)
Public Member Functions inherited from ReacBase
ReacBase ()
virtual ~ReacBase ()
void setNumKf (const Eref &e, double v)
double getNumKf (const Eref &e) const
void setNumKb (const Eref &e, double v)
double getNumKb (const Eref &e) const
void setConcKf (const Eref &e, double v)
set Kf in concentration units
double getConcKf (const Eref &e) const
get Kf in concentration units
void setConcKb (const Eref &e, double v)
set Kb in concentration units
double getConcKb (const Eref &e) const
get Kb in concentration units
unsigned int getNumSub (const Eref &e) const
Get number of substrates.
unsigned int getNumPrd (const Eref &e) const
Get number of products.
virtual void setSolver (Id solver, Id orig)
Assign solver info.
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void sub (double v)
void prd (double v)
void remesh (const Eref &e)
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from ReacBase
static void zombify (Element *original, const Cinfo *zClass, Id solver)
static const Cinfo * initCinfo ()
Additional Inherited Members
Protected Attributes inherited from ReacBase
double concKf_
double concKb_
Constructor & Destructor Documentation
Reac::Reac ()
Member Function Documentation
const Cinfo * Reac::initCinfo () static
References ReacBase::initCinfo().
Referenced by testTwoReacGetNeighbors().
double Reac::vGetConcKb (const Eref & e) const virtual
get Kb in concentration units
Implements ReacBase.
References ReacBase::concKb_.
double Reac::vGetConcKf (const Eref & e) const virtual
vGet Kf in concentration units
Implements ReacBase.
References ReacBase::concKf_.
double Reac::vGetNumKb (const Eref & e) const virtual
Implements ReacBase.
References ReacBase::concKb_, and convertConcToNumRateUsingMesh().
double Reac::vGetNumKf (const Eref & e) const virtual
Implements ReacBase.
References ReacBase::concKf_, and convertConcToNumRateUsingMesh().
void Reac::vPrd (double v) virtual
Reimplemented from ReacBase.
void Reac::vProcess (const Eref & e, ProcPtr p) virtual
Reimplemented from ReacBase.
References SrcFinfo2< T1, T2 >::send().
void Reac::vReinit (const Eref & e, ProcPtr p) virtual
Reimplemented from ReacBase.
References ReacBase::concKb_, ReacBase::concKf_, and convertConcToNumRateUsingMesh().
void Reac::vRemesh (const Eref & e) virtual
Reimplemented from ReacBase.
References ReacBase::concKb_, ReacBase::concKf_, and convertConcToNumRateUsingMesh().
void Reac::vSetConcKb (const Eref & e, double v) virtual
set Kb in concentration units
Implements ReacBase.
References ReacBase::concKb_, and convertConcToNumRateUsingMesh().
void Reac::vSetConcKf (const Eref & e, double v) virtual
set Kf in concentration units
Implements ReacBase.
References ReacBase::concKf_, and convertConcToNumRateUsingMesh().
void Reac::vSetNumKb (const Eref & e, double v) virtual
Implements ReacBase.
References ReacBase::concKb_, and convertConcToNumRateUsingMesh().
void Reac::vSetNumKf (const Eref & e, double v) virtual
Implements ReacBase.
References ReacBase::concKf_, and convertConcToNumRateUsingMesh().
void Reac::vSub (double v) virtual
Reimplemented from ReacBase.
The documentation for this class was generated from the following files:
kinetics/Reac.h
kinetics/Reac.cpp