MOOSE: CaConc Class Reference
CaConc Class Reference
#include <CaConc.h>
Public Member Functions
CaConc ()
void vReinit (const Eref &, ProcPtr info)
void vProcess (const Eref &, ProcPtr info)
void vCurrent (const Eref &e, double I)
void vCurrentFraction (const Eref &e, double I, double fraction)
void vIncrease (const Eref &e, double I)
void vDecrease (const Eref &e, double I)
void vSetCa (const Eref &e, double val)
double vGetCa (const Eref &e) const
void vSetCaBasal (const Eref &e, double val)
double vGetCaBasal (const Eref &e) const
void vSetTau (const Eref &e, double val)
double vGetTau (const Eref &e) const
void vSetB (const Eref &e, double val)
double vGetB (const Eref &e) const
void vSetCeiling (const Eref &e, double val)
double vGetCeiling (const Eref &e) const
void vSetFloor (const Eref &e, double val)
double vGetFloor (const Eref &e) const
Public Member Functions inherited from CaConcBase
CaConcBase ()
void reinit (const Eref &, ProcPtr info)
void process (const Eref &, ProcPtr info)
void current (const Eref &e, double I)
void currentFraction (const Eref &e, double I, double fraction)
void increase (const Eref &e, double I)
void decrease (const Eref &e, double I)
void setCa (const Eref &e, double val)
double getCa (const Eref &e) const
void setCaBasal (const Eref &e, double val)
double getCaBasal (const Eref &e) const
void setTau (const Eref &e, double val)
double getTau (const Eref &e) const
void setB (const Eref &e, double val)
double getB (const Eref &e) const
void setCeiling (const Eref &e, double val)
double getCeiling (const Eref &e) const
void setFloor (const Eref &e, double val)
double getFloor (const Eref &e) const
void setThickness (const Eref &e, double val)
double getThickness (const Eref &e) const
virtual void vSetSolver (const Eref &e, Id hsolve)
Used to set up the solver. Dummy for regular classes.
Static Public Member Functions
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from CaConcBase
static void zombify (Element *orig, const Cinfo *zClass, Id hsolve)
static SrcFinfo1< double > * concOut ()
static const Cinfo * initCinfo ()
Detailed Description
The CaConc object manages calcium dynamics in a single compartment without diffusion. It uses a simple exponential return of Ca to baseline, with influxes from ion channels. It solves the equation: dC/dt = B*Ik - C/tau where Ca = Ca_base + C.
From the GENESIS notes: In SI units, where concentration is moles/m^3 (milli-moles/liter) and current is in amperes, theory gives B = 5.2e-6/(shell volume). In practice, B is a parameter to be fitted or estimated from experiment, as buffering, non-uniform distribution of Ca, etc., will modify this value. If thick = 0, the readcell routine calculates B by dividing the "density" parameter in the cell parameter file by the volume of the compartment. Otherwise, it scales as a true shell, with the volume of a shell having thickness thick. A negative value of the "density" parameter may be used to indicate that it should be taken as an absolute value of B, without scaling.
Constructor & Destructor Documentation
CaConc::CaConc ()
Member Function Documentation
const Cinfo * CaConc::initCinfo () static
References CaConcBase::initCinfo().
void CaConc::vCurrent (const Eref & e, double I) virtual
Implements CaConcBase.
void CaConc::vCurrentFraction (const Eref & e, double I, double fraction) virtual
Implements CaConcBase.
void CaConc::vDecrease (const Eref & e, double I) virtual
Implements CaConcBase.
double CaConc::vGetB (const Eref & e) const virtual
Implements CaConcBase.
double CaConc::vGetCa (const Eref & e) const virtual
Implements CaConcBase.
double CaConc::vGetCaBasal (const Eref & e) const virtual
Implements CaConcBase.
double CaConc::vGetCeiling (const Eref & e) const virtual
Implements CaConcBase.
double CaConc::vGetFloor (const Eref & e) const virtual
Implements CaConcBase.
double CaConc::vGetTau (const Eref & e) const virtual
Implements CaConcBase.
void CaConc::vIncrease (const Eref & e, double I) virtual
Implements CaConcBase.
void CaConc::vProcess (const Eref & e, ProcPtr info) virtual
Implements CaConcBase.
References CaConcBase::concOut(), and ProcInfo::dt.
void CaConc::vReinit (const Eref & e, ProcPtr info) virtual
Implements CaConcBase.
References CaConcBase::concOut().
void CaConc::vSetB (const Eref & e, double val) virtual
Implements CaConcBase.
void CaConc::vSetCa (const Eref & e, double val) virtual
Implements CaConcBase.
void CaConc::vSetCaBasal (const Eref & e, double val) virtual
Implements CaConcBase.
void CaConc::vSetCeiling (const Eref & e, double val) virtual
Implements CaConcBase.
void CaConc::vSetFloor (const Eref & e, double val) virtual
Implements CaConcBase.
void CaConc::vSetTau (const Eref & e, double val) virtual
Implements CaConcBase.
The documentation for this class was generated from the following files:
biophysics/CaConc.h
biophysics/CaConc.cpp