MOOSE: VoxelPools Class Reference
VoxelPools Class Reference
#include <VoxelPools.h>
Public Member Functions
VoxelPools ()
virtual ~VoxelPools ()
void reinit (double dt)
void setStoich (Stoich *stoich, const OdeSystem *ode)
void advance (const ProcInfo *p)
Do the numerical integration. Advance the simulation.
void setInitDt (double dt)
Set initial timestep to use by the solver.
void setVolumeAndDependencies (double vol)
Handles volume change and subsequent cascading updates.
void updateAllRateTerms (const vector< RateTerm * > &rates, unsigned int numCoreRates)
Updates all the rate constants from the reference rates vector.
void updateRateTerms (const vector< RateTerm * > &rates, unsigned int numCoreRates, unsigned int index)
void updateRates (const double *s, double *yprime) const
void updateReacVelocities (const double *s, vector< double > &v) const
void print () const
Used for debugging.
Public Member Functions inherited from VoxelPoolsBase
VoxelPoolsBase ()
virtual ~VoxelPoolsBase ()
void resizeArrays (unsigned int totNumPools)
Allocate # of pools.
unsigned int size () const
const double * S () const
vector< double > & Svec ()
Returns a handle to the mol # vector.
double * varS ()
const double * Sinit () const
double * varSinit ()
void reinit ()
void setVolume (double vol)
Just assigns the volume without any cascading to other values.
double getVolume () const
Return the volume of the voxel.
void setN (unsigned int i, double v)
double getN (unsigned int) const
void setNinit (unsigned int, double v)
double getNinit (unsigned int) const
void setDiffConst (unsigned int, double v)
double getDiffConst (unsigned int) const
void filterCrossRateTerms (const vector< Id > &offSolverReacs, const vector< pair< Id, Id > > &offSolverReacCompts)
void xferIn (const vector< unsigned int > &poolIndex, const vector< double > &values, const vector< double > &lastValues, unsigned int voxelIndex)
void xferInOnlyProxies (const vector< unsigned int > &poolIndex, const vector< double > &values, unsigned int numProxyPools, unsigned int voxelIndex)
void xferOut (unsigned int voxelIndex, vector< double > &values, const vector< unsigned int > &poolIndex)
Assembles data values for sending out for x-compt reacs.
void addProxyVoxy (unsigned int comptIndex, Id comptId, unsigned int voxel)
Adds the index of a voxel to which proxy data should go.
void addProxyTransferIndex (unsigned int comptIndex, unsigned int transferIndex)
bool hasXfer (unsigned int comptIndex) const
True when this voxel has data to be transferred.
bool isVoxelJunctionPresent (Id i1, Id i2) const
void resetXreacScale (unsigned int size)
void forwardReacVolumeFactor (unsigned int i, double volume)
void backwardReacVolumeFactor (unsigned int i, double volume)
double getXreacScaleSubstrates (unsigned int i) const
double getXreacScaleProducts (unsigned int i) const
void print () const
Debugging utility.
Static Public Member Functions
static int gslFunc (double t, const double *y, double *dydt, void *params)
This is the function which evaluates the rates.
Additional Inherited Members
Protected Attributes inherited from VoxelPoolsBase
const Stoich * stoichPtr_
vector< RateTerm * > rates_
Detailed Description
This is the class for handling reac-diff voxels used for deterministic computations.
Constructor & Destructor Documentation
VoxelPools::VoxelPools ()
VoxelPools::~VoxelPools () virtual
References VoxelPoolsBase::rates_.
Member Function Documentation
void VoxelPools::advance (const ProcInfo * p)
Do the numerical integration. Advance the simulation.
References ProcInfo::currTime, ProcInfo::dt, and VoxelPoolsBase::varS().
int VoxelPools::gslFunc (double t, const double * y, double * dydt, void * params) static
This is the function which evaluates the rates.
References q, VoxelPoolsBase::stoichPtr_, Stoich::updateFuncs(), updateRates(), and y.
Referenced by Ksolve::setStoich().
void VoxelPools::print () const
Used for debugging.
For debugging: Print contents of voxel pool.
Changes cross rate terms to zero if there is no junction void filterCrossRateTerms(const vector< pair< Id, Id > >& vec);
References Stoich::getNumCoreRates(), VoxelPoolsBase::print(), VoxelPoolsBase::rates_, and VoxelPoolsBase::stoichPtr_.
void VoxelPools::reinit (double dt)
References VoxelPoolsBase::reinit().
void VoxelPools::setInitDt (double dt)
Set initial timestep to use by the solver.
void VoxelPools::setStoich (Stoich * stoich, const OdeSystem * ode)
setStoich: Assigns the ODE system and Stoich. Stoich may be modified to create a new RateTerm vector in case the volume of this VoxelPools is new.
References OdeSystem::epsAbs, OdeSystem::epsRel, OdeSystem::initStepSize, VoxelPoolsBase::reinit(), and VoxelPoolsBase::stoichPtr_.
Referenced by SteadyState::setStoich().
void VoxelPools::setVolumeAndDependencies (double vol) virtual
Handles volume change and subsequent cascading updates.
Handle volume updates. Inherited Virtual func.
Reimplemented from VoxelPoolsBase.
References Stoich::getNumCoreRates(), Stoich::getRateTerms(), Stoich::setupCrossSolverReacVols(), VoxelPoolsBase::setVolumeAndDependencies(), VoxelPoolsBase::stoichPtr_, and updateAllRateTerms().
void VoxelPools::updateAllRateTerms (const vector< RateTerm * > & rates, unsigned int numCoreRates) virtual
Updates all the rate constants from the reference rates vector.
Implements VoxelPoolsBase.
References VoxelPoolsBase::getVolume(), VoxelPoolsBase::getXreacScaleProducts(), VoxelPoolsBase::getXreacScaleSubstrates(), and VoxelPoolsBase::rates_.
Referenced by SteadyState::setStoich(), and setVolumeAndDependencies().
void VoxelPools::updateRates (const double * s, double * yprime) const
Core computation function. Updates the reaction velocities vector yprime given the current mol 'n' vector s.
References KinSparseMatrix::computeRowRate(), Stoich::getNumAllPools(), Stoich::getNumBufPools(), Stoich::getNumProxyPools(), Stoich::getNumVarPools(), Stoich::getStoichiometryMatrix(), N, SparseMatrix< T >::nColumns(), SparseMatrix< T >::nRows(), VoxelPoolsBase::rates_, and VoxelPoolsBase::stoichPtr_.
Referenced by SteadyState::classifyState(), and gslFunc().
void VoxelPools::updateRateTerms (const vector< RateTerm * > & rates, unsigned int numCoreRates, unsigned int index) virtual
updateRateTerms updates the rate consts of a belonging to the specified index on the rates vector. It does recaling and assigning using values from the internal rates vector.
Implements VoxelPoolsBase.
References VoxelPoolsBase::getVolume(), VoxelPoolsBase::getXreacScaleProducts(), VoxelPoolsBase::getXreacScaleSubstrates(), and VoxelPoolsBase::rates_.
void VoxelPools::updateReacVelocities (const double * s, vector< double > & v) const
updateReacVelocities computes the velocity v of each reaction from the vector s of pool #s. This is a utility function for programs like SteadyState that need to analyze velocity.
updateReacVelocities computes the velocity v of each reaction. This is a utility function for programs like SteadyState that need to analyze velocity.
References Stoich::getStoichiometryMatrix(), N, SparseMatrix< T >::nColumns(), VoxelPoolsBase::rates_, and VoxelPoolsBase::stoichPtr_.
The documentation for this class was generated from the following files:
ksolve/VoxelPools.h
ksolve/VoxelPools.cpp