MOOSE: MarkovGslSolver Class Reference
MarkovGslSolver Class Reference
#include <MarkovGslSolver.h>
Public Member Functions
MarkovGslSolver ()
~MarkovGslSolver ()
bool getIsInitialized () const
string getMethod () const
void setMethod (string method)
double getRelativeAccuracy () const
void setRelativeAccuracy (double value)
double getAbsoluteAccuracy () const
void setAbsoluteAccuracy (double value)
double getInternalDt () const
void setInternalDt (double value)
void process (const Eref &e, ProcPtr info)
void reinit (const Eref &e, ProcPtr info)
void init (vector< double >)
void handleQ (vector< vector< double > >)
Static Public Member Functions
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
MarkovGslSolver::MarkovGslSolver ()
MarkovGslSolver::~MarkovGslSolver ()
Member Function Documentation
double MarkovGslSolver::getAbsoluteAccuracy () const
Referenced by initCinfo().
double MarkovGslSolver::getInternalDt () const
Referenced by initCinfo().
bool MarkovGslSolver::getIsInitialized () const
Referenced by initCinfo().
string MarkovGslSolver::getMethod () const
Referenced by initCinfo().
double MarkovGslSolver::getRelativeAccuracy () const
Referenced by initCinfo().
void MarkovGslSolver::handleQ (vector< vector< double > >)
Referenced by initCinfo().
void MarkovGslSolver::init (vector< double > initialState)
References resize().
Referenced by initCinfo().
const Cinfo * MarkovGslSolver::initCinfo () static
References getAbsoluteAccuracy(), getInternalDt(), getIsInitialized(), getMethod(), getRelativeAccuracy(), handleQ(), init(), Neutral::initCinfo(), process(), reinit(), setAbsoluteAccuracy(), setInternalDt(), setMethod(), setRelativeAccuracy(), and stateOut().
void MarkovGslSolver::process (const Eref & e, ProcPtr info)
References ProcInfo::currTime, ProcInfo::dt, and stateOut().
Referenced by initCinfo().
void MarkovGslSolver::reinit (const Eref & e, ProcPtr info)
References stateOut().
Referenced by initCinfo().
void MarkovGslSolver::setAbsoluteAccuracy (double value)
Referenced by initCinfo().
void MarkovGslSolver::setInternalDt (double value)
Referenced by initCinfo().
void MarkovGslSolver::setMethod (string method)
Referenced by initCinfo().
void MarkovGslSolver::setRelativeAccuracy (double value)
Referenced by initCinfo().
The documentation for this class was generated from the following files:
biophysics/MarkovGslSolver.h
biophysics/MarkovGslSolver.cpp