MOOSE: ZombieFunction Class Reference
ZombieFunction Class Reference
#include <ZombieFunction.h>
Public Member Functions
ZombieFunction ()
~ZombieFunction ()
void setExpr (const Eref &e, string val)
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
void setSolver (Id solver, Id orig)
Public Member Functions inherited from Function
Function ()
Function (const Function &rhs)
~Function ()
void setExpr (const Eref &e, string expr)
string getExpr (const Eref &e) const
vector< string > getVars () const
void setVarValues (vector< string > vars, vector< double > vals)
void setVar (unsigned int index, double value)
Variable * getVar (unsigned int ii)
double getValue () const
double getRate () const
void setMode (unsigned int mode)
unsigned int getMode () const
void setNumVar (unsigned int num)
unsigned int getNumVar () const
void setConst (string name, double value)
double getConst (string name) const
void setIndependent (string index)
string getIndependent () const
vector< double > getY () const
double getDerivative () const
Function & operator= (const Function rhs)
unsigned int addVar ()
void process (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Static Public Member Functions
static void zombify (Element *orig, const Cinfo *zClass, Id ksolve, Id dsolve)
static const Cinfo * initCinfo ()
Static Public Member Functions inherited from Function
static const Cinfo * initCinfo ()
Additional Inherited Members
Static Public Attributes inherited from Function
static const int VARMAX
Protected Member Functions inherited from Function
void _clearBuffer ()
void _showError (mu::Parser::exception_type &e) const
Protected Attributes inherited from Function
bool _valid
unsigned int _numVar
double _lastValue
double _value
double _rate
unsigned int _mode
vector< Variable * > _varbuf
vector< double * > _pullbuf
map< string, double * > _constbuf
string _independent
mu::Parser _parser
char * _stoich
Constructor & Destructor Documentation
ZombieFunction::ZombieFunction ()
ZombieFunction::~ZombieFunction ()
Member Function Documentation
const Cinfo * ZombieFunction::initCinfo () static
References Function::getExpr(), Function::initCinfo(), process(), reinit(), and setExpr().
Referenced by zombify().
void ZombieFunction::process (const Eref & e, ProcPtr p)
Referenced by initCinfo().
void ZombieFunction::reinit (const Eref & e, ProcPtr p)
Referenced by initCinfo().
void ZombieFunction::setExpr (const Eref & e, string val)
References Function::_stoich, Function::setExpr(), and Stoich::setFunctionExpr().
Referenced by initCinfo().
void ZombieFunction::setSolver (Id solver, Id orig)
References Function::_stoich, Element::cinfo(), ObjId::data(), Id::element(), Field< A >::get(), Cinfo::isA(), and Cinfo::name().
Referenced by zombify().
void ZombieFunction::zombify (Element * orig, const Cinfo * zClass, Id ksolve, Id dsolve) static
References Element::cinfo(), Eref::data(), initCinfo(), Function::initCinfo(), Element::numLocalData(), Element::replaceCinfo(), and setSolver().
The documentation for this class was generated from the following files:
ksolve/ZombieFunction.h
ksolve/ZombieFunction.cpp