MOOSE: HHGate2D Class Reference
HHGate2D Class Reference
#include <HHGate2D.h>
Public Member Functions
HHGate2D ()
HHGate2D (Id originalChanId, Id originalGateId)
double lookupA (vector< double > v) const
double lookupB (vector< double > v) const
void lookupBoth (double v, double c, double *A, double *B) const
bool checkOriginal (Id id, const string &field) const
bool isOriginalChannel (Id id) const
bool isOriginalGate (Id id) const
Id originalChannelId () const
vector< vector< double > > getTableA (const Eref &e) const
void setTableA (const Eref &e, vector< vector< double > > value)
vector< vector< double > > getTableB (const Eref &e) const
void setTableB (const Eref &e, vector< vector< double > > value)
double getXminA (const Eref &e) const
void setXminA (const Eref &e, double value)
double getXmaxA (const Eref &e) const
void setXmaxA (const Eref &e, double value)
unsigned int getXdivsA (const Eref &e) const
void setXdivsA (const Eref &e, unsigned int value)
double getYminA (const Eref &e) const
void setYminA (const Eref &e, double value)
double getYmaxA (const Eref &e) const
void setYmaxA (const Eref &e, double value)
unsigned int getYdivsA (const Eref &e) const
void setYdivsA (const Eref &e, unsigned int value)
double getXminB (const Eref &e) const
void setXminB (const Eref &e, double value)
double getXmaxB (const Eref &e) const
void setXmaxB (const Eref &e, double value)
unsigned int getXdivsB (const Eref &e) const
void setXdivsB (const Eref &e, unsigned int value)
double getYminB (const Eref &e) const
void setYminB (const Eref &e, double value)
double getYmaxB (const Eref &e) const
void setYmaxB (const Eref &e, double value)
unsigned int getYdivsB (const Eref &e) const
void setYdivsB (const Eref &e, unsigned int value)
Static Public Member Functions
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
HHGate2D::HHGate2D ()
HHGate2D::HHGate2D (Id originalChanId, Id originalGateId)
Member Function Documentation
bool HHGate2D::checkOriginal (Id id, const string & field) const
Checks if the provided Id is the one that the HHGate was created on. If true, fine, otherwise complains about trying to set the field.
vector< vector< double > > HHGate2D::getTableA (const Eref & e) const
Returns the A interpol
References Interpol2D::getTableVector().
Referenced by initCinfo().
vector< vector< double > > HHGate2D::getTableB (const Eref & e) const
Returns the B interpol
References Interpol2D::getTableVector().
Referenced by initCinfo().
unsigned int HHGate2D::getXdivsA (const Eref & e) const
References Interpol2D::getXdivs().
Referenced by initCinfo().
unsigned int HHGate2D::getXdivsB (const Eref & e) const
References Interpol2D::getXdivs().
Referenced by initCinfo().
double HHGate2D::getXmaxA (const Eref & e) const
References Interpol2D::getXmax().
Referenced by initCinfo().
double HHGate2D::getXmaxB (const Eref & e) const
References Interpol2D::getXmax().
Referenced by initCinfo().
double HHGate2D::getXminA (const Eref & e) const
References Interpol2D::getXmin().
Referenced by initCinfo().
double HHGate2D::getXminB (const Eref & e) const
References Interpol2D::getXmin().
Referenced by initCinfo().
unsigned int HHGate2D::getYdivsA (const Eref & e) const
References Interpol2D::getYdivs().
Referenced by initCinfo().
unsigned int HHGate2D::getYdivsB (const Eref & e) const
References Interpol2D::getYdivs().
Referenced by initCinfo().
double HHGate2D::getYmaxA (const Eref & e) const
References Interpol2D::getYmax().
Referenced by initCinfo().
double HHGate2D::getYmaxB (const Eref & e) const
References Interpol2D::getYmax().
Referenced by initCinfo().
double HHGate2D::getYminA (const Eref & e) const
References Interpol2D::getYmin().
Referenced by initCinfo().
double HHGate2D::getYminB (const Eref & e) const
References Interpol2D::getYmin().
Referenced by initCinfo().
const Cinfo * HHGate2D::initCinfo () static
References getTableA(), getTableB(), getXdivsA(), getXdivsB(), getXmaxA(), getXmaxB(), getXminA(), getXminB(), getYdivsA(), getYdivsB(), getYmaxA(), getYmaxB(), getYminA(), getYminB(), Neutral::initCinfo(), lookupA(), lookupB(), setTableA(), setTableB(), setXdivsA(), setXdivsB(), setXmaxA(), setXmaxB(), setXminA(), setXminB(), setYdivsA(), setYdivsB(), setYmaxA(), setYmaxB(), setYminA(), and setYminB().
Referenced by HHChannel2D::initCinfo().
bool HHGate2D::isOriginalChannel (Id id) const
isOriginalChannel returns true if the provided Id is the Id of the channel on which the HHGate was created.
Referenced by HHChannel2D::checkOriginal().
bool HHGate2D::isOriginalGate (Id id) const
isOriginalChannel returns true if the provided Id is the Id of the Gate created at the same time as the original channel.
double HHGate2D::lookupA (vector< double > v) const
References Interpol2D::innerLookup().
Referenced by initCinfo().
double HHGate2D::lookupB (vector< double > v) const
References Interpol2D::innerLookup().
Referenced by initCinfo().
void HHGate2D::lookupBoth (double v, double c, double * A, double * B) const
Single call to get both A and B values in a single lookup
References Interpol2D::innerLookup().
Referenced by HHChannel2D::vProcess(), and HHChannel2D::vReinit().
Id HHGate2D::originalChannelId () const
Returns the Id of the original Channel.
void HHGate2D::setTableA (const Eref & e, vector< vector< double > > value)
References Interpol2D::setTableVector().
Referenced by initCinfo().
void HHGate2D::setTableB (const Eref & e, vector< vector< double > > value)
References Interpol2D::setTableVector().
Referenced by initCinfo().
void HHGate2D::setXdivsA (const Eref & e, unsigned int value)
References Interpol2D::setXdivs().
Referenced by initCinfo().
void HHGate2D::setXdivsB (const Eref & e, unsigned int value)
References Interpol2D::setXdivs().
Referenced by initCinfo().
void HHGate2D::setXmaxA (const Eref & e, double value)
References Interpol2D::setXmax().
Referenced by initCinfo().
void HHGate2D::setXmaxB (const Eref & e, double value)
References Interpol2D::setXmax().
Referenced by initCinfo().
void HHGate2D::setXminA (const Eref & e, double value)
References Interpol2D::setXmin().
Referenced by initCinfo().
void HHGate2D::setXminB (const Eref & e, double value)
References Interpol2D::setXmin().
Referenced by initCinfo().
void HHGate2D::setYdivsA (const Eref & e, unsigned int value)
References Interpol2D::setYdivs().
Referenced by initCinfo().
void HHGate2D::setYdivsB (const Eref & e, unsigned int value)
References Interpol2D::setYdivs().
Referenced by initCinfo().
void HHGate2D::setYmaxA (const Eref & e, double value)
References Interpol2D::setYmax().
Referenced by initCinfo().
void HHGate2D::setYmaxB (const Eref & e, double value)
References Interpol2D::setYmax().
Referenced by initCinfo().
void HHGate2D::setYminA (const Eref & e, double value)
References Interpol2D::setYmin().
Referenced by initCinfo().
void HHGate2D::setYminB (const Eref & e, double value)
References Interpol2D::setYmin().
Referenced by initCinfo().
The documentation for this class was generated from the following files:
biophysics/HHGate2D.h
biophysics/HHGate2D.cpp