MOOSE: Cell Class Reference
Cell Class Reference
#include <Cell.h>
Public Member Functions
Cell ()
void setupf (Id cell)
Id getSetup () const
void setMethod (string value)
string getMethod () const
void setSolverClock (unsigned int value)
unsigned int getSolverClock () const
void setSolverName (string value)
string getSolverName () const
int getVariableDt () const
int getImplicit () const
string getDescription () const
void processDummy (const Eref &e, ProcPtr p)
void reinit (const Eref &e, ProcPtr p)
Static Public Member Functions
static void addMethod (const string &name, const string &description, int isVariableDt, int isImplicit)
static const Cinfo * initCinfo ()
Constructor & Destructor Documentation
Cell::Cell ()
References setMethod().
Member Function Documentation
void Cell::addMethod (const string & name, const string & description, int isVariableDt, int isImplicit) static
Referenced by initCinfo().
string Cell::getDescription () const
Referenced by initCinfo().
int Cell::getImplicit () const
Referenced by initCinfo().
string Cell::getMethod () const
Referenced by initCinfo().
Id Cell::getSetup () const
Referenced by initCinfo().
unsigned int Cell::getSolverClock () const
Referenced by initCinfo().
string Cell::getSolverName () const
Referenced by initCinfo().
int Cell::getVariableDt () const
Referenced by initCinfo().
const Cinfo * Cell::initCinfo () static
References addMethod(), getDescription(), getImplicit(), getMethod(), getSetup(), getSolverClock(), getSolverName(), getVariableDt(), Neutral::initCinfo(), processDummy(), reinit(), setMethod(), setSolverClock(), setSolverName(), and setupf().
void Cell::processDummy (const Eref & e, ProcPtr p)
Referenced by initCinfo().
void Cell::reinit (const Eref & e, ProcPtr p)
References Eref::id().
Referenced by initCinfo().
void Cell::setMethod (string value)
Referenced by Cell(), and initCinfo().
void Cell::setSolverClock (unsigned int value)
Referenced by initCinfo().
void Cell::setSolverName (string value)
Referenced by initCinfo().
void Cell::setupf (Id cell)
References Id::destroy(), and Id::path().
Referenced by initCinfo().
The documentation for this class was generated from the following files:
hsolve/Cell.h
hsolve/Cell.cpp