MOOSE: SetGet0 Class Reference
SetGet0 Class Reference
#include <SetGet.h>
Public Member Functions
SetGet0 ()
bool checkOpClass (const OpFunc *op) const
Public Member Functions inherited from SetGet
SetGet ()
virtual ~SetGet ()
Static Public Member Functions
static bool set (const ObjId &dest, const string &field)
static bool innerStrSet (const ObjId &dest, const string &field, const string &val)
Static Public Member Functions inherited from SetGet
static const OpFunc * checkSet (const string &field, ObjId &tgt, FuncId &fid)
static bool strGet (const ObjId &tgt, const string &field, string &ret)
static bool strSet (const ObjId &dest, const string &field, const string &val)
static const vector< double * > * dispatchGet (const ObjId &tgt, FuncId tgtFid, const double *arg, unsigned int size)
Sends out request for data, and awaits its return.
Constructor & Destructor Documentation
SetGet0::SetGet0 () inline
Member Function Documentation
bool SetGet0::checkOpClass (const OpFunc * op) const inline virtual
Implements SetGet.
static bool SetGet0::innerStrSet (const ObjId & dest, const string & field, const string & val) inline static
Blocking call using string conversion
References set().
static bool SetGet0::set (const ObjId & dest, const string & field) inline static
Blocking, typed 'Set' call
References SetGet::checkSet(), ObjId::eref(), ObjId::isGlobal(), ObjId::isOffNode(), OpFunc0Base::makeHopFunc(), MooseSetHop, OpFunc0Base::op(), and OpFunc::opIndex().
Referenced by Shell::doQuit(), Shell::doReinit(), Shell::doStop(), and innerStrSet().
The documentation for this class was generated from the following file:
basecode/SetGet.h