MOOSE: kinetics/CplxEnzBase.cpp File Reference
CplxEnzBase.cpp File Reference
#include "header.h"
#include "ElementValueFinfo.h"
#include "lookupVolumeFromMesh.h"
#include "EnzBase.h"
#include "CplxEnzBase.h"
Functions
DestFinfo * enzDest ()
Function Documentation
DestFinfo* enzDest ()
References Cinfo::findFinfo(), and EnzBase::initCinfo().
Referenced by CplxEnzBase::initCinfo(), and EnzBase::initCinfo().