MOOSE: basecode/doubleEq.h File Reference
doubleEq.h File Reference
Functions
bool doubleEq (double x, double y)
bool doubleApprox (double x, double y)
Function Documentation
bool doubleApprox (double x, double y)
References EPS1, and EPS3.
Referenced by CubeMesh::compareMeshSpacing(), Vec::orthogonalAxes(), Interpol2D::setXmax(), Interpol2D::setXmin(), Interpol2D::setYmax(), Interpol2D::setYmin(), testMMenzProcess(), and testStats().
bool doubleEq (double x, double y)
References EPS1, and EPS2.
Referenced by checkOutput(), doPartialPivot(), NeuroMesh::insertSingleDummy(), Interpol2D::Interpol2D(), VectorTable::lookupByValue(), matInv(), SynChan::normalizeGbar(), Vec::operator==(), Vec::orthogonalAxes(), HHChannelBase::selectPower(), Stoich::setCompartment(), CubeMesh::setDiffScale(), Interpol2D::setDx(), Interpol2D::setDy(), HHChannel2D::setGatePower(), HHChannel::setGatePower(), StimulusTable::setStopTime(), Interpol2D::setSy(), SynChan::setTau2(), test2ArgSetVec(), testClock(), testConvVectorOfVectors(), testCopyFieldElement(), testCopyMsgOps(), testCreateMsg(), testCubeMesh(), testFuncTerm(), testGet(), testGetMsg(), testHopFunc(), testIntFireNetwork(), testLookupSetGet(), testMMenz(), testMpiFibonacci(), testMsgField(), testObjIdToAndFromPath(), testPoolVolumeScaling(), testReacVolumeScaling(), ReadCspace::testReadModel(), testReMesh(), testSendMsg(), testSendSpike(), testSetGet(), testSetGetDouble(), testSetGetExtField(), testSetGetSynapse(), testSetRepeat(), testShellAddMsg(), testShellSetGet(), testTable(), testUtilsForCompareXplot(), testUtilsForLoadXplot(), testVec(), testVolScaling(), CylMesh::updateCoords(), MarkovRateTable::updateRates(), and SynChan::vReinit().