MOOSE: biophysics/HHChannelBase.cpp File Reference
HHChannelBase.cpp File Reference
#include "header.h"
#include "ElementValueFinfo.h"
#include "HHGate.h"
#include "ChanBase.h"
#include "HHChannelBase.h"
Functions
bool checkPower (double power)
Function Documentation
bool checkPower (double power)
Referenced by HHChannelBase::setXpower(), HHChannelBase::setYpower(), and HHChannelBase::setZpower().