MOOSE: hsolve/HinesMatrix.cpp File Reference
HinesMatrix.cpp File Reference
#include "header.h"
#include "HinesMatrix.h"
#include <sstream>
#include <iomanip>
#include <stdexcept>
Functions
bool groupCompare (const vector< unsigned int > &A, const vector< unsigned int > &B)
ostream & operator<< (ostream &s, const HinesMatrix &m)
Function Documentation
bool groupCompare (const vector< unsigned int > & A, const vector< unsigned int > & B)
ostream& operator<< (ostream & s, const HinesMatrix & m)
References HinesMatrix::getA(), HinesMatrix::getB(), HinesMatrix::getSize(), and HinesMatrix::getVMid().