MOOSE: randnum/mt19937ar.cpp File Reference
mt19937ar.cpp File Reference
#include <sys/time.h>
#include <stdlib.h>
#include "randnum.h"
Macros
#define N 624
#define M 397
#define MATRIX_A 0x9908b0dfUL /* constant vector a */
#define UPPER_MASK 0x80000000UL /* most significant w-r bits */
#define LOWER_MASK 0x7fffffffUL /* least significant r bits */
Functions
void init_genrand (unsigned long s)
void init_by_array (long int init_key[], int key_length)
unsigned long genrand_int32 (void)
void mtseed (long seed=0)
double mtrand (void)
Macro Definition Documentation
#define LOWER_MASK 0x7fffffffUL /* least significant r bits */
Referenced by genrand_int32().
#define M 397
Referenced by genrand_int32().
#define MATRIX_A 0x9908b0dfUL /* constant vector a */
Referenced by genrand_int32().
#define N 624
Referenced by genrand_int32(), init_by_array(), init_genrand(), VoxelPools::updateRates(), GssaVoxelPools::updateReacVelocities(), and VoxelPools::updateReacVelocities().
#define UPPER_MASK 0x80000000UL /* most significant w-r bits */
Referenced by genrand_int32().
Function Documentation
unsigned long genrand_int32 (void)
References init_genrand(), LOWER_MASK, M, MATRIX_A, N, UPPER_MASK, and y.
Referenced by mtrand().
void init_by_array (long int init_key[], int key_length)
References init_genrand(), and N.
Referenced by mtseed().
void init_genrand (unsigned long s)
References N.
Referenced by genrand_int32(), init_by_array(), and mtseed().
double mtrand (void)
References genrand_int32().
Referenced by GssaVoxelPools::advance(), Uniform::getNextSample(), Binomial::getNextSample(), GssaVoxelPools::pickReac(), RandSpike::process(), SparseMsg::randomConnect(), RandSpike::reinit(), GssaVoxelPools::reinit(), testIntFireNetwork(), testSparseMsg(), and moose::Compartment::vRandInject().
void mtseed (long seed = 0)
References init(), init_by_array(), and init_genrand().
Referenced by SparseMsg::setProbability(), SparseMsg::setRandomConnectivity(), SparseMsg::setSeed(), and testSparseMsg().