MOOSE: moose Namespace Reference
moose Namespace Reference
Classes
class Compartment
class CompartmentBase
class CompartmentDataHolder
class VClamp
Functions
int checkPath (const string &path)
Checks if given path is correct. If not, return false and error-code as well.
string joinPath (string pathA, string pathB)
Append pathB to pathA and return the result.
string fixPath (string path)
Fix a path. For testing purpose.
Detailed Description
The Compartment class sets up an asymmetric compartment for branched nerve calculations. Handles electronic structure and also channels. This is not a particularly efficient way of doing this, so we should use a solver for any substantial calculations.
The CompartmentBase class sets up the interface for all the derived Compartment classes, used in branched nerve calculations. Handles electronic structure and also channels.
Function Documentation
int moose::checkPath (const string & path)
Checks if given path is correct. If not, return false and error-code as well.
Parameters
path Path name.
Returns
0 if path is all-right. Negative number if path is not OK.
References BAD_CHARACTER_IN_PATH, EMPTY_PATH, and MISSING_BRACKET_AT_END.
Referenced by fixPath().
string moose::fixPath (string path)
Fix a path. For testing purpose.
Parameters
path Path as string.
Returns
A fixed path.
References checkPath(), and MISSING_BRACKET_AT_END.
Referenced by HSolveUtils::gates(), and joinPath().
string moose::joinPath (string pathA, string pathB)
Append pathB to pathA and return the result.
If pathA does not have [indexs] at the end, append "[0]" to pathA and then add pathB to it. This version does not care if the result has '[0]' at its end.
Parameters
pathA First path.
pathB Second path.
Returns
A string representing moose-path.
References errorSS, and fixPath().