MOOSE: randnum/randnum.h File Reference
randnum.h File Reference
Functions
double mtrand (void)
void mtseed (long seed)
unsigned long genrand_int32 (void)
Function Documentation
unsigned long genrand_int32 (void)
References init_genrand(), LOWER_MASK, M, MATRIX_A, N, UPPER_MASK, and y.
Referenced by mtrand().
double mtrand (void)
References genrand_int32().
Referenced by GssaVoxelPools::advance(), Uniform::getNextSample(), Binomial::getNextSample(), GssaVoxelPools::pickReac(), RandSpike::process(), SparseMsg::randomConnect(), RandSpike::reinit(), GssaVoxelPools::reinit(), testIntFireNetwork(), testSparseMsg(), and moose::Compartment::vRandInject().
void mtseed (long seed)
References init(), init_by_array(), and init_genrand().
Referenced by SparseMsg::setProbability(), SparseMsg::setRandomConnectivity(), SparseMsg::setSeed(), and testSparseMsg().