MOOSE: kinetics/ReadKkit.cpp File Reference
ReadKkit.cpp File Reference
#include <iomanip>
#include <fstream>
#include "header.h"
#include "../utility/utility.h"
#include "PoolBase.h"
#include "Pool.h"
#include "BufPool.h"
#include "ReacBase.h"
#include "EnzBase.h"
#include "lookupVolumeFromMesh.h"
#include "../shell/Shell.h"
#include "../shell/Wildcard.h"
#include "ReadKkit.h"
Enumerations
enum GenesisTableModes {
TAB_IO, TAB_LOOP, TAB_ONCE, TAB_BUF,
TAB_SPIKE, TAB_FIELDS, TAB_DELAY
}
Functions
unsigned int chopLine (const string &line, vector< string > &ret)
string lower (const string &input)
Id makeStandardElements (Id pa, const string &modelname)
void setMethod (Shell *s, Id mgr, double simdt, double plotdt, const string &method)
void assignArgs (map< string, int > &argConv, const vector< string > &args)
bool volCompare (const pair< unsigned int, double > &A, const pair< unsigned int, double > &B)
vector< unsigned int > findVolOrder (const vector< double > &vols)
Id findParentComptOfReac (Id reac)
Id findMeshOfEnz (Id enz)
Enumeration Type Documentation
enum GenesisTableModes
Enumerator
TAB_IO
TAB_LOOP
TAB_ONCE
TAB_BUF
TAB_SPIKE
TAB_FIELDS
TAB_DELAY
Function Documentation
void assignArgs (map< string, int > & argConv, const vector< string > & args)
Referenced by ReadKkit::objdump().
unsigned int chopLine (const string & line, vector< string > & ret)
References trim().
Referenced by ReadKkit::readData(), and ReadKkit::readInit().
Id findMeshOfEnz (Id enz)
Return the MeshEntry into which the enzyme should be placed. This is simple: Just identify the compartment holding the enzyme molecule.
References Id::element(), Cinfo::findFinfo(), getCompt(), Element::getNeighbors(), and EnzBase::initCinfo().
Id findParentComptOfReac (Id reac)
References Id::element(), Cinfo::findFinfo(), getCompt(), Element::getNeighbors(), and ReacBase::initCinfo().
Referenced by ReadKkit::assignReacCompartments().
vector< unsigned int > findVolOrder (const vector< double > & vols)
References volCompare().
Referenced by ReadKkit::assignPoolCompartments(), and testVolSort().
string lower (const string & input)
Referenced by setMethod().
Id makeStandardElements (Id pa, const string & modelname)
References Eref::data(), Shell::doCreate(), Id::eref(), MooseGlobal, Id::path(), and SetGet2< A1, A2 >::set().
Referenced by ReadKkit::read(), and ReadCspace::readModelString().
void setMethod (Shell * s, Id mgr, double simdt, double plotdt, const string & method)
References Shell::doCreate(), Shell::doSetClock(), Shell::doUseClock(), lower(), Id::path(), and Field< A >::set().
Referenced by ReadKkit::read().
bool volCompare (const pair< unsigned int, double > & A, const pair< unsigned int, double > & B)
Referenced by findVolOrder().