MOOSE: utility/setupenv.cpp File Reference
setupenv.cpp File Reference
#include <map>
#include <string>
#include <sstream>
#include <cstdlib>
Functions
unsigned getNumCores ()
const map< string, string > & getArgMap ()
Function Documentation
const map<string, string>& getArgMap ()
References getNumCores().
unsigned getNumCores ()
Referenced by getArgMap(), and init().