MOOSE: shell/Shell.cpp File Reference
Shell.cpp File Reference
#include "header.h"
#include "global.h"
#include "SingleMsg.h"
#include "DiagonalMsg.h"
#include "OneToOneMsg.h"
#include "OneToAllMsg.h"
#include "SparseMatrix.h"
#include "SparseMsg.h"
#include "Shell.h"
#include "Dinfo.h"
#include "Wildcard.h"
#include "../scheduling/Clock.h"
#include "../external/debug/simple_logger.hpp"
Functions
bool isDoingReinit ()
bool extractIndex (const string &s, unsigned int &index)
void insertSharedMsgs (const Finfo *f, const Element *e, vector< ObjId > &msgs)
Function Documentation
bool extractIndex (const string & s, unsigned int & index)
Referenced by Shell::chopPath(), and testExtractIndices().
void insertSharedMsgs (const Finfo * f, const Element * e, vector< ObjId > & msgs)
References SharedFinfo::dest(), DestFinfo::getFid(), and Element::getInputMsgs().
Referenced by Shell::dropClockMsgs().
bool isDoingReinit ()
References Eref::data(), Id::element(), and Id::eref().