MOOSE: shell/ShellCopy.cpp File Reference
ShellCopy.cpp File Reference
#include "header.h"
#include "OneToAllMsg.h"
#include "Shell.h"
#include "../scheduling/Clock.h"
Functions
Element * innerCopyElements (Id orig, ObjId newParent, Id newId, unsigned int n, bool toGlobal, map< Id, Id > &tree)
void innerCopyMsgs (map< Id, Id > &tree, unsigned int n, bool copyExtMsgs)
Function Documentation
Element* innerCopyElements (Id orig, ObjId newParent, Id newId, unsigned int n, bool toGlobal, map< Id, Id > & tree)
Runs in parallel on all nodes. Note that 'n' is the number of complete duplicates. If there were 10 dataEntries in the original, there will now be 10 x n.
References Shell::adopt(), Neutral::children(), Element::cinfo(), Element::copyElement(), ObjId::dataIndex, Id::element(), Id::eref(), Element::id(), Clock::lookupDefaultTick(), Cinfo::name(), Id::nextId(), Element::numData(), Neutral::parent(), and Element::setTick().
Referenced by Shell::innerCopy().
void innerCopyMsgs (map< Id, Id > & tree, unsigned int n, bool copyExtMsgs)
References Msg::copy(), Msg::e1(), Msg::e2(), Cinfo::findFinfo(), SrcFinfo::getBindIndex(), Msg::getMsg(), Element::getMsgAndFunc(), Element::id(), and Neutral::initCinfo().
Referenced by Shell::innerCopy().