MOOSE: ksolve/Stoich.cpp File Reference
Stoich.cpp File Reference
#include "header.h"
#include "ElementValueFinfo.h"
#include "PoolBase.h"
#include "ReacBase.h"
#include "EnzBase.h"
#include "CplxEnzBase.h"
#include "FuncTerm.h"
#include "RateTerm.h"
#include "FuncRateTerm.h"
#include "SparseMatrix.h"
#include "KinSparseMatrix.h"
#include "VoxelPoolsBase.h"
#include "../mesh/VoxelJunction.h"
#include "XferInfo.h"
#include "ZombiePoolInterface.h"
#include "Stoich.h"
#include "lookupVolumeFromMesh.h"
#include "../scheduling/Clock.h"
#include "../shell/Shell.h"
#include "../shell/Wildcard.h"
Functions
void convWildcards (vector< Id > &ret, const vector< ObjId > &elist)
void filterWildcards (vector< Id > &ret, const vector< ObjId > &elist)
pair< Id, Id > extractCompts (const vector< Id > &compts)
void installDummy (RateTerm **entry, Id enzId, const string &s)
Function Documentation
void convWildcards (vector< Id > & ret, const vector< ObjId > & elist)
pair< Id, Id > extractCompts (const vector< Id > & compts)
Extracts and orders the compartments associated with a given reac.
Referenced by Stoich::locateOffSolverReacs().
void filterWildcards (vector< Id > & ret, const vector< ObjId > & elist)
Referenced by Stoich::setElist().
void installDummy (RateTerm ** entry, Id enzId, const string & s)
References Id::path().
Referenced by Stoich::installMMenz().