MOOSE: utility/strutil.h File Reference
strutil.h File Reference
#include <string>
#include <vector>
Functions
void tokenize (const std::string &str, const std::string &delimiters, std::vector< std::string > &tokens)
std::string trim (const std::string myString, const std::string &delimiters=" \t\r\n")
std::string & clean_type_name (std::string &arg)
bool endswith (const std::string &full, const std::string &ending)
Function Documentation
std::string& clean_type_name (std::string & arg)
bool endswith (const std::string & full, const std::string & ending)
void tokenize (const std::string & str, const std::string & delimiters, std::vector< std::string > & tokens)
Splits given string into tokens
std::string trim (const std::string myString, const std::string & delimiters = " \t\r\n")
trims the leading and trailing white spaces
Referenced by chopLine(), findModelType(), innerLoadXplot(), ReadKkit::innerRead(), Interpol2D::load(), Func::reinit(), Function::reinit(), and testTrim().