MOOSE: utility/strutil.cpp File Reference
strutil.cpp File Reference
#include <string>
#include <iostream>
#include <vector>
#include "strutil.h"
Functions
void tokenize (const string &str, const string &delimiters, vector< string > &tokens)
string & clean_type_name (string &arg)
std::string trim (const std::string myString, const string &delimiters)
int testTrim ()
bool endswith (const string &full, const string &ending)
Function Documentation
string& clean_type_name (string & arg)
bool endswith (const string & full, const string & ending)
int testTrim ()
References trim().
void tokenize (const std::string & str, const std::string & delimiters, std::vector< std::string > & tokens)
Splits given string into tokens
std::string trim (const std::string myString, const std::string & delimiters = " \t\r\n")
trims the leading and trailing white spaces
Referenced by chopLine(), findModelType(), innerLoadXplot(), ReadKkit::innerRead(), Interpol2D::load(), Func::reinit(), Function::reinit(), and testTrim().