MOOSE: CaConcStruct Struct Reference
CaConcStruct Struct Reference
#include <HSolveStruct.h>
Public Member Functions
CaConcStruct ()
CaConcStruct (double Ca, double CaBasal, double tau, double B, double ceiling, double floor, double dt)
void setCa (double Ca)
void setCaBasal (double CaBasal)
void setTauB (double tau, double B, double dt)
double process (double activation)
Public Attributes
double c_
double CaBasal_
Dynamic calcium concentration, over CaBasal_
double factor1_
Reference calcium concentration
double factor2_
Both these factors are functions of tau, B and dt.
double ceiling_
double floor_
Ceiling and floor for lookup tables
Constructor & Destructor Documentation
CaConcStruct::CaConcStruct ()
CaConcStruct::CaConcStruct (double Ca, double CaBasal, double tau, double B, double ceiling, double floor, double dt)
References ceiling_, floor_, setCa(), setCaBasal(), and setTauB().
Member Function Documentation
double CaConcStruct::process (double activation)
Compute Ca concentration from factors and activation value. Also takes care of Ca concetration exceeding min and max values.
References c_, CaBasal_, ceiling_, factor1_, factor2_, floor_, and setCa().
void CaConcStruct::setCa (double Ca)
References c_, and CaBasal_.
Referenced by CaConcStruct(), and process().
void CaConcStruct::setCaBasal (double CaBasal)
change CaBasal_ and update c_ accordingly.
References c_, and CaBasal_.
Referenced by CaConcStruct().
void CaConcStruct::setTauB (double tau, double B, double dt)
Sets the factors using the appropriate functions.
References factor1_, and factor2_.
Referenced by CaConcStruct().
Member Data Documentation
double CaConcStruct::c_
Referenced by process(), setCa(), and setCaBasal().
double CaConcStruct::CaBasal_
Dynamic calcium concentration, over CaBasal_
Referenced by process(), setCa(), and setCaBasal().
double CaConcStruct::ceiling_
Referenced by CaConcStruct(), and process().
double CaConcStruct::factor1_
Reference calcium concentration
Referenced by process(), and setTauB().
double CaConcStruct::factor2_
Both these factors are functions of tau, B and dt.
Referenced by process(), and setTauB().
double CaConcStruct::floor_
Ceiling and floor for lookup tables
Referenced by CaConcStruct(), and process().
The documentation for this struct was generated from the following files:
hsolve/HSolveStruct.h
hsolve/HSolveStruct.cpp