MOOSE: biophysics/testBiophysics.cpp File Reference
testBiophysics.cpp File Reference
#include "header.h"
#include "../shell/Shell.h"
#include "../randnum/randnum.h"
#include "CompartmentBase.h"
#include "Compartment.h"
Functions
void testCompartment ()
void testCompartmentProcess ()
void testMarkovRateTable ()
void testVectorTable ()
void testIntFireNetwork (unsigned int runsteps=5)
Function Documentation
void testCompartment ()
void testCompartmentProcess ()
void testIntFireNetwork (unsigned int runsteps = 5)
References ObjId::bad(), Eref::data(), Shell::doAddMsg(), Shell::doCreate(), Shell::doDelete(), Shell::doReinit(), Shell::doSetClock(), Shell::doStart(), doubleEq(), Shell::doUseClock(), Id::element(), Field< A >::get(), Element::getName(), Field< A >::getVec(), mtrand(), Shell::numNodes(), SetGet2< A1, A2 >::set(), and Field< A >::setVec().
void testMarkovRateTable ()
void testVectorTable ()