find . -name '*.txt' -execdir todos {} +
find . -name '*.bat' -execdir todos {} +
find . -name '*.plot' -execdir todos {} +
find . -name '*.gnuplot' -execdir todos {} +
find . -name '*.g' -execdir todos {} +
find . -name '*.p' -execdir todos {} +
find . -name '*.py' -execdir todos {} +
find . -name '*.xml' -execdir todos {} +
find . -name '*.0' -execdir todos {} +
find . -name '*.x' -execdir todos {} +
