@echo off

REM
REM This batch file is used to launch .g script files using MOOSE.
REM You can drag-and-drop the script onto the batch file's icon, or
REM simply double-click on the script file.
REM

REM
REM First extract the drive letter
REM

set drive=%~d1


REM
REM This extracts the path of the directory from the first argument passed
REM to this batch file.
REM

set simpath=%~dp1


REM
REM This extracts the name of the script file from the first argument passed
REM to this batch file.
REM

set script=%~nx1


REM
REM Switch to correct drive
REM

%drive%


REM
REM We 'cd' into that directory. This is perhaps the most convenient way to
REM have the script to work. This way MOOSE can find other files which the
REM script needs ( e.g.: *.g, *.p files ). Also, output files generated by
REM the simulation will be written in locations relative to the script's path.
REM

cd %simpath%


REM 
REM Finally we execute MOOSE. It helps to pass only the script name, because
REM the directory path may contain spaces in it, which MOOSE cannot handle.
REM This is another advantage of cd-ing into the script's path.
REM 
REM To handle scripts with non-DOS names (long names or with spaces),
REM we copy the script into a temporary (hidden) script file with a
REM nice name.
REM 

copy %script% temp_.g > NUL
attrib +H temp_.g
moose temp_.g
del /A:H temp_.g

pause
