#!/bin/sh

if [ -z $LD_LIBRARY_PATH ]
then
	export LD_LIBRARY_PATH=/usr/share/moose1.4/lib
else
	export LD_LIBRARY_PATH=/usr/share/moose1.4/lib:$LD_LIBRARY_PATH
fi
if [ -z $PYTHONPATH ]
then
	export PYTHONPATH=/usr/lib/python2.6/dist-packages/
else
	export PYTHONPATH=/usr/lib/python2.6/dist-packages/:$PYTHONPATH
fi

if [ -f $HOME/.moose/moose1.4 ]
then
	/usr/bin/moosegui-bin "$@"
else 
	mkdir $HOME/moose1.4
	echo "Copying Moose demos and documentation to your home directory.This may take some time."
	cp -R /usr/share/doc/moose1.4/DEMOS  /usr/share/doc/moose1.4/TESTS /usr/share/doc/moose1.4/README $HOME/moose1.4
	ln -s /usr/share/doc/moose1.4/DOCS $HOME/moose1.4/DOCS 
	
	if [ -d $HOME/Desktop ]
	then
		ln -s $HOME/moose1.4 $HOME/Desktop/moose1.4
	fi
	
	echo "Demos and documentation have been copied to " $HOME/moose1.4
	/usr/bin/moosegui-bin "$@"
	
	mkdir $HOME/.moose
	touch $HOME/.moose/moose1.4
fi
