Summary: Multiscale Object-Oriented Simulation Environment
Name: moose
Version: 1.4
Release: 0
License: LGPL
Group: Applications/Science
URL: http://moose.ncbs.res.in/
Source0: %{name}-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
Requires: libstdc++ >= 4.1.2, readline >= 5
BuildRequires: libstdc++ >= 4.1.2, readline >= 5, readline-devel >= 5, gsl >= 1.11, gsl-devel >= 1.11, python26-devel >= 2.6, swig >= 1.4.29
%description
MOOSE is the Multiscale Object-Oriented Simulation Environment. 
 It is the base and numerical core for large, detailed simulations including 
 Computational Neuroscience and Systems Biology. 
 . 
 MOOSE spans the range from single molecules to subcellular networks, from 
 single cells to neuronal networks, and to still larger systems. It is 
 backwards-compatible with GENESIS, and forward compatible with Python 
 and XML-based model definition standards like SBML and MorphML. It supports
 transparent parallelization, that is, it can run models on a cluster with no
 user effort required to parallelize them.
%prep
%setup -q

%build
make pymoose USE_NEUROML=1
mv external/neuroML_src/libneuroml.so ./
mv _moose.so _moose.so.tmp
mv moose.py moose.py.tmp
make clean
make moose USE_NEUROML=1
mv external/neuroML_src/libneuroml.a ./
g++ TESTS/regression/neardiff.cpp -o TESTS/regression/neardiff
%install
rm -rf $RPM_BUILD_ROOT
mkdir -p "$RPM_BUILD_ROOT/usr/bin"
mkdir -p "$RPM_BUILD_ROOT/usr/share/doc/moose1.4"
mkdir -p "$RPM_BUILD_ROOT/usr/share/man/man1"
mkdir -p "$RPM_BUILD_ROOT/usr/share/info"
mkdir -p "$RPM_BUILD_ROOT/usr/share/moose1.4/lib"
mkdir -p "$RPM_BUILD_ROOT/usr/share/moose1.4/py_stage"
install -m 755 moosegui "$RPM_BUILD_ROOT/usr/bin/"
install -s -m 755 moose "$RPM_BUILD_ROOT/usr/bin/moose-bin"
install -s -m 644 _moose.so.tmp "$RPM_BUILD_ROOT/usr/share/moose1.4/py_stage/_moose.so"
install -m 755 moose.py.tmp "$RPM_BUILD_ROOT/usr/share/moose1.4/py_stage/moose.py"
install -m 755 pymoose/pymoose.py "$RPM_BUILD_ROOT/usr/share/moose1.4/py_stage/"
cp -r DEMOS "$RPM_BUILD_ROOT/usr/share/doc/moose1.4/"
cp -r TESTS "$RPM_BUILD_ROOT/usr/share/doc/moose1.4/"
cp -r DOCS "$RPM_BUILD_ROOT/usr/share/doc/moose1.4/"
cp -r pymoose/gui/qt "$RPM_BUILD_ROOT/usr/share/moose1.4/moosegui"
cp -r gl/colormaps "$RPM_BUILD_ROOT/usr/share/moose1.4/colormaps/"
install -m 644 "DOCS/Beta-1.4/moose.1" "$RPM_BUILD_ROOT/usr/share/man/man1/"
install -m 644 DOCS/pymoose/pymoose.info "$RPM_BUILD_ROOT/usr/share/info/pymoose.info"
install -s -m 755 TESTS/regression/neardiff  "$RPM_BUILD_ROOT/usr/share/doc/moose1.4/TESTS/regression/"
install -m 755 TESTS/regression/do_regression.bat "$RPM_BUILD_ROOT/usr/share/doc/moose1.4/TESTS/regression/"
chmod 755 "$RPM_BUILD_ROOT/usr/share/moose1.4/moosegui/moosegui.py"

# Copy the libraries to lib directory in moose-shared deirectory
#( ldd _moose.so )    | while read line; do 
( ldd _moose.so.tmp)    | while read line; do 
    a=`echo $line |sed -e 's/(.*$//'`; 
    b=`echo $a | cut -s -d '>' -f2`
    if [ ! -z `echo $b | tr -d [:space:]` ]; then
	for libname in libsbml libxml2 libgsl ; do
	    echo $b $libname 
	    if [[ $b =~ $libname ]] ; then
		echo "Copying $b to lib/"  
		install -m 644 $b "$RPM_BUILD_ROOT/usr/share/moose1.4/lib"
		break
	     fi
	done
    fi
done

%post
ln -s "$RPM_BUILD_ROOT/usr/share/moose1.4/moosegui/moosegui.py" "$RPM_BUILD_ROOT/usr/bin/moosegui-bin"
echo "$RPM_BUILD_ROOT/usr/share/moose1.4/lib/" > /etc/ld.so.conf.d/moose.conf
ldconfig
install-info --infodir="$RPM_BUILD_ROOT/usr/share/info" "$RPM_BUILD_ROOT/usr/share/info/pymoose.info"

%clean
rm -rf $RPM_BUILD_ROOT

%preun
if [ -d /usr/share/moose1.4 ];
then
	rm -r /usr/share/moose1.4
fi
if [ -d /usr/share/doc/moose1.4 ];
then
	rm -r /usr/share/doc/moose1.4
fi
rm /usr/bin/moosegui-bin
if [ -f /usr/lib/python2.6/dist-packages/_moose.so ];
then 
	rm /usr/lib/python2.6/dist-packages/_moose.so
fi
if [ -f /usr/lib/python2.6/dist-packages/moose.py ];
then 
	rm /usr/lib/python2.6/dist-packages/moose.py
fi
if [ -f /usr/lib/python2.6/dist-packages/moose.pyc ];
then
	rm /usr/lib/python2.6/dist-packages/moose.pyc
fi
if [ -f /usr/lib/python2.5/site-packages/_moose.so ];
then 
	rm /usr/lib/python2.5/site-packages/_moose.so
fi
if [ -f /usr/lib/python2.5/site-packages/moose.py ];
then 
	rm /usr/lib/python2.5/site-packages/moose.py
fi
if [ -f /usr/lib/python2.5/site-packages/moose.pyc ];
then
	rm /usr/lib/python2.5/site-packages/moose.pyc
fi
if [ -f /etc/ld.so.conf.d/moose.conf ];
then
	rm /etc/ld.so.conf.d/moose.conf
fi
if [ -f /usr/share/info/pymoose.info ];
then
	sudo install-info --remove --info-dir=/usr/share/info /usr/share/info/pymoose.info
fi

%postun
ldconfig

%files
%defattr(-,root,root,-)
/usr/bin/moose-bin
/usr/bin/moosegui
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/Ca.moose.plot
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/Ca1.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/CaConductance.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/CaPool.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/Ca_NMDA.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/K_AConductance.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/K_AHPConductance.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/K_CConductance.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/K_DRConductance.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/LeakConductance.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/NMDA.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/NMDA_Ca_conc.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/NaConductance.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/Reader.g
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/Vm.moose.plot
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/glu.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/CA1/plotUtil.g
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/GranGolgiSyn.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/GranPurkSyn.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/GranuleCell.morph.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/KConductance.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/MFGranSyn.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/NaConductance.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/PassiveCond.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/PurkinjeCell.morph.xml
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/README
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/Reader.g
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/Vm.genesis.plot
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/Vm.moose.plot
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/moose.plot
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/NeuroML_Reader/plotUtil.g
/usr/share/doc/moose1.4/DEMOS/axon/Axon.g
/usr/share/doc/moose1.4/DEMOS/axon/axon.p
/usr/share/doc/moose1.4/DEMOS/axon/axon.png
/usr/share/doc/moose1.4/DEMOS/axon/axon0.genesis.plot
/usr/share/doc/moose1.4/DEMOS/axon/axon100.genesis.plot
/usr/share/doc/moose1.4/DEMOS/axon/axon200.genesis.plot
/usr/share/doc/moose1.4/DEMOS/axon/axon300.genesis.plot
/usr/share/doc/moose1.4/DEMOS/axon/axon400.genesis.plot
/usr/share/doc/moose1.4/DEMOS/axon/bulbchan.g
/usr/share/doc/moose1.4/DEMOS/axon/compatibility.g
/usr/share/doc/moose1.4/DEMOS/axon/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/channels/Ca_hip_traub91.png
/usr/share/doc/moose1.4/DEMOS/channels/Channels.g
/usr/share/doc/moose1.4/DEMOS/channels/K2_mit_usb.png
/usr/share/doc/moose1.4/DEMOS/channels/KA_bsg_yka.png
/usr/share/doc/moose1.4/DEMOS/channels/KM_bsg_yka.png
/usr/share/doc/moose1.4/DEMOS/channels/K_bsg_yka.png
/usr/share/doc/moose1.4/DEMOS/channels/K_hh_tchan.png
/usr/share/doc/moose1.4/DEMOS/channels/K_mit_usb.png
/usr/share/doc/moose1.4/DEMOS/channels/Ka_hip_traub91.png
/usr/share/doc/moose1.4/DEMOS/channels/Kahp_hip_traub91.png
/usr/share/doc/moose1.4/DEMOS/channels/Kdr_hip_traub91.png
/usr/share/doc/moose1.4/DEMOS/channels/LCa3_mit_usb.png
/usr/share/doc/moose1.4/DEMOS/channels/Na_bsg_yka.png
/usr/share/doc/moose1.4/DEMOS/channels/Na_hh_tchan.png
/usr/share/doc/moose1.4/DEMOS/channels/Na_hip_traub91.png
/usr/share/doc/moose1.4/DEMOS/channels/Na_mit_usb.png
/usr/share/doc/moose1.4/DEMOS/channels/Na_rat_smsnn.png
/usr/share/doc/moose1.4/DEMOS/channels/SMSNNchan.g
/usr/share/doc/moose1.4/DEMOS/channels/bulbchan.g
/usr/share/doc/moose1.4/DEMOS/channels/compatibility.g
/usr/share/doc/moose1.4/DEMOS/channels/hh_tchan.g
/usr/share/doc/moose1.4/DEMOS/channels/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Ca_bsg_yka.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Ca_hip_traub.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Ca_hip_traub91.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/K2_mit_usb.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/KA_bsg_yka.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/KM_bsg_yka.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/K_bsg_yka.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/K_hh_tchan.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/K_hip_traub.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/K_mit_usb.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Ka_hip_traub91.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Kahp_hip_traub91.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Kc_hip_traub91.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Kca_hip_traub.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Kca_mit_usb.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Kdr_hip_traub91.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/LCa3_mit_usb.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Na_bsg_yka.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Na_hh_tchan.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Na_hip_traub91.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Na_mit_usb.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/reference_plots/Na_rat_smsnn.genesis.plot
/usr/share/doc/moose1.4/DEMOS/channels/traub91chan.g
/usr/share/doc/moose1.4/DEMOS/channels/traubchan.g
/usr/share/doc/moose1.4/DEMOS/channels/yamadachan.g
/usr/share/doc/moose1.4/DEMOS/gl-demo/README
/usr/share/doc/moose1.4/DEMOS/gl-demo/channels/bulbchan.g
/usr/share/doc/moose1.4/DEMOS/gl-demo/channels/compatibility.g
/usr/share/doc/moose1.4/DEMOS/gl-demo/colormaps/grey
/usr/share/doc/moose1.4/DEMOS/gl-demo/colormaps/hot
/usr/share/doc/moose1.4/DEMOS/gl-demo/colormaps/rainbow2
/usr/share/doc/moose1.4/DEMOS/gl-demo/colormaps/redhot
/usr/share/doc/moose1.4/DEMOS/gl-demo/morphologies/Purk2M9s.p
/usr/share/doc/moose1.4/DEMOS/gl-demo/morphologies/Purkinje4M9.p
/usr/share/doc/moose1.4/DEMOS/gl-demo/morphologies/ca1passive.p
/usr/share/doc/moose1.4/DEMOS/gl-demo/morphologies/mit.p
/usr/share/doc/moose1.4/DEMOS/gl-demo/morphologies/n123.p
/usr/share/doc/moose1.4/DEMOS/gl-demo/morphologies/psmall.p
/usr/share/doc/moose1.4/DEMOS/gl-demo/morphologies/small.p
/usr/share/doc/moose1.4/DEMOS/gl-demo/run-glcellclient.sh
/usr/share/doc/moose1.4/DEMOS/gl-demo/run-glviewclient.sh
/usr/share/doc/moose1.4/DEMOS/gl-demo/visualize-glcell.g
/usr/share/doc/moose1.4/DEMOS/gl-demo/visualize-glview.g
/usr/share/doc/moose1.4/DEMOS/integrate_fire/README
/usr/share/doc/moose1.4/DEMOS/integrate_fire/intfire.g
/usr/share/doc/moose1.4/DEMOS/integrate_fire/plot.gp
/usr/share/doc/moose1.4/DEMOS/kholodenko/Kholodenko.g
/usr/share/doc/moose1.4/DEMOS/kholodenko/kkit.g
/usr/share/doc/moose1.4/DEMOS/kholodenko/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/kholodenko/reference.plot
/usr/share/doc/moose1.4/DEMOS/mitral-ee/Mitral.g
/usr/share/doc/moose1.4/DEMOS/mitral-ee/bulbchan.g
/usr/share/doc/moose1.4/DEMOS/mitral-ee/compatibility.g
/usr/share/doc/moose1.4/DEMOS/mitral-ee/mit.p
/usr/share/doc/moose1.4/DEMOS/mitral-ee/mitral.genesis.plot
/usr/share/doc/moose1.4/DEMOS/mitral-ee/mitral.png
/usr/share/doc/moose1.4/DEMOS/mitral-ee/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/music-network/MusicNetwork.g
/usr/share/doc/moose1.4/DEMOS/music-network/README
/usr/share/doc/moose1.4/DEMOS/music-network/compatibility.g
/usr/share/doc/moose1.4/DEMOS/music-network/hh_tchan.g
/usr/share/doc/moose1.4/DEMOS/music-network/net-1.music
/usr/share/doc/moose1.4/DEMOS/music-network/net-2.music
/usr/share/doc/moose1.4/DEMOS/music-network/output/c0.png
/usr/share/doc/moose1.4/DEMOS/music-network/output/c1.png
/usr/share/doc/moose1.4/DEMOS/music-network/output/c2.png
/usr/share/doc/moose1.4/DEMOS/music-network/output/c3.png
/usr/share/doc/moose1.4/DEMOS/music-network/output/c4.png
/usr/share/doc/moose1.4/DEMOS/music-network/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/network-ee/I0.png
/usr/share/doc/moose1.4/DEMOS/network-ee/Network.g
/usr/share/doc/moose1.4/DEMOS/network-ee/V0.png
/usr/share/doc/moose1.4/DEMOS/network-ee/V9.png
/usr/share/doc/moose1.4/DEMOS/network-ee/compatibility.g
/usr/share/doc/moose1.4/DEMOS/network-ee/hh_tchan.g
/usr/share/doc/moose1.4/DEMOS/network-ee/network.genesis.plot
/usr/share/doc/moose1.4/DEMOS/network-ee/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/PulseAsc.g
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/PulseAsc.py
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/compatibility.g
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/output/a1.genesis.plot
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/output/a1.png
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/output/a2.genesis.plot
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/output/a2.png
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/output/diff1.png
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/output/diff2.png
/usr/share/doc/moose1.4/DEMOS/pulsegen-ascfile/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/pymoose/channels/bulbchan.g
/usr/share/doc/moose1.4/DEMOS/pymoose/channels/bulbchan.py
/usr/share/doc/moose1.4/DEMOS/pymoose/channels/bulbchan.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/channels/bulbchan.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/channels/compatibility.g
/usr/share/doc/moose1.4/DEMOS/pymoose/channels/test_bulbchan.g
/usr/share/doc/moose1.4/DEMOS/pymoose/channels/test_bulbchan.py
/usr/share/doc/moose1.4/DEMOS/pymoose/channels/test_bulbchan.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/channels/test_bulbchan.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/colormaps/grey
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/colormaps/hot
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/colormaps/rainbow2
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/colormaps/redhot
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/config.py
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/config.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/config.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/demo.py
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/demo.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/demo.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glcelldemo.py
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glcelldemo.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glcelldemo.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glcellloader.py
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glcellloader.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glcellloader.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glclient.py
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glclient.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glclient.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glclientgui.py
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glclientgui.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glclientgui.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glviewdemo.py
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glviewdemo.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glviewdemo.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glviewloader.py
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glviewloader.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/glviewloader.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/morphologies/Purk2M9s.p
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/morphologies/Purkinje4M9.p
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/morphologies/ca1passive.p
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/morphologies/mit.p
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/morphologies/n123.p
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/morphologies/psmall.p
/usr/share/doc/moose1.4/DEMOS/pymoose/gl/morphologies/small.p
/usr/share/doc/moose1.4/DEMOS/pymoose/izhikevich/Izhikevich.py
/usr/share/doc/moose1.4/DEMOS/pymoose/izhikevich/Izhikevich.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/izhikevich/Izhikevich.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/izhikevich/demogui_qt.py
/usr/share/doc/moose1.4/DEMOS/pymoose/izhikevich/demogui_qt.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/izhikevich/demogui_qt.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/izhikevich/demogui_tk.py
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/Help.py
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/Help.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/Help.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/Michaelis.py
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/Michaelis.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/Michaelis.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/explicit.py
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/explicit.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/explicit.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/guimichaelis.py
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/guimichaelis.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/guimichaelis.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/simple.py
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/simple.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/michaelis_menten/simple.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/pulsegen.py
/usr/share/doc/moose1.4/DEMOS/pymoose/pulsegen.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/pulsegen.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/README.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/acc79.g
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/borgka.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/borgkm.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/ca3_db.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/ca3a.geo
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/cadiv.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/cagk.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/cal2.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/can2.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/cat.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/kahp.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/kdr.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/kkit.g
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/moosenrn.py
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/moosenrn.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/moosenrn.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/mosinit.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/nahh.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/mus_nrn/test_a.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/README.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/qtSquid.py
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/qtSquid.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/qtSquid.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/squid.py
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/squid.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/squid.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/squidModel.py
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/squidModel.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid/squidModel.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/README.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/model.py
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/model.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/model.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/runtest.py
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/runtest.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/runtest.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/squid.py
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/squid.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/ray_bhalla_2008/squid_fft/squid.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/genesis/dend_v27.g
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/genesis/diffmol_dend.g
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/genesis/diffmol_spine.g
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/genesis/proto16.g
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/genesis/simpleca1.p
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/model.py
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/model.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/model.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/protocol/oneSpike.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/protocol/pulseLTPProtocol1.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/protocol/pulse_LTP_protocol2.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/protocol/res.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/sbml/kinase_loop.xml
/usr/share/doc/moose1.4/DEMOS/pymoose/signeur/sbml/psd12.xml
/usr/share/doc/moose1.4/DEMOS/pymoose/spikegen.py
/usr/share/doc/moose1.4/DEMOS/pymoose/spikegen.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/spikegen.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/squid/qtSquid.py
/usr/share/doc/moose1.4/DEMOS/pymoose/squid/qtSquid.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/squid/qtSquid.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/squid/squid.py
/usr/share/doc/moose1.4/DEMOS/pymoose/squid/squid.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/squid/squid.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/squid/squidModel.py
/usr/share/doc/moose1.4/DEMOS/pymoose/squid/squidModel.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/squid/squidModel.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/README.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/comps.cvs
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/README
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cell_templates.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/TCR_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/deepLTS_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/deepaxax_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/deepbask_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/nRT_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/nontuftRS_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/spinstell_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/supLTS_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/supaxax_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/supbask_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/suppyrFRB_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/suppyrRS_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/tuftIB_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/cells/tuftRS_template.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_TCR.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_deepLTS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_deepaxax.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_deepbask.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_nRT.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_nontuftRS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_spinstell.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_supLTS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_supaxax.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_supbask.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_suppyrFRB.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_suppyrRS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_tuftIB.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Ca_tuftRS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_TCR.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_deepLTS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_deepaxax.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_deepbask.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_nRT.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_nontuftRS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_spinstell.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_supLTS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_supaxax.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_supbask.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_suppyrFRB.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_suppyrRS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_tuftIB.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/data/Vm_tuftRS.plot.gz
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/finit.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/fortmap.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/gidcell.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/gidcell.ses
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/hoc/parlib.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/hoc/parlib2.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/hoc/traubcon.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/hoc/traubcon_net.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/init.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/alphasyndiffeq.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/alphasynkin.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/alphasynkint.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/ampa.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/ar.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/cad.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/cal.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/cat.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/cat_a.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/gabaa.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/ggap.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/iclamp_const.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/k2.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/ka.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/ka_ib.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/kahp.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/kahp_deeppyr.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/kahp_slower.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/kc.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/kc_fast.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/kdr.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/kdr_fs.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/km.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/naf.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/naf2.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/naf_tcr.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/nap.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/napf.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/napf_spinstell.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/napf_tcr.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/par_ggap.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/pulsesyn.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/rampsyn.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/rand.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/ri.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mod/traub_nmda.mod
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/mosinit.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/net/durand.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/net/groucho.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/net/groucho_gapbld.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/net/groucho_gapbld_mix.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/net/network_specification_interface.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/net/serial_or_par_wrapper.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/net/synaptic_compmap_construct.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/net/synaptic_map_construct.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/nrntime.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/nrntime.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/nrntime.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/onecell.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/onecell.ses
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/spkplt.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_TCR.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_deepLTS.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_deepaxax.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_deepbask.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_nRT.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_nontuftRS.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_spinstell.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_supLTS.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_supaxax.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_supbask.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_suppyrFRB.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_suppyrRS.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_tuftIB.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/nrn/test_tuftRS.hoc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/DeepAxoaxonic.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/DeepBasket.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/DeepLTS.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/NontuftedRS.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/SpinyStellate.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/SupAxoaxonic.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/SupBasket.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/SupLTS.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/SupPyrFRB.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/SupPyrRS.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/TCR.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/TuftedIB.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/TuftedRS.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/archan.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/archan.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/archan.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/cachans.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/cachans.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/cachans.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/capool.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/capool.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/capool.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/cell.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/cell.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/cell.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/cells.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/channel.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/channel.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/channel.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/compartment.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/compartment.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/compartment.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/config.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/deepLTS.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/deepLTS.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/deepLTS.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/deepaxoaxonic.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/deepaxoaxonic.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/deepaxoaxonic.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/deepbasket.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/deepbasket.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/deepbasket.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/kchans.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/kchans.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/kchans.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nRT.p
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nRT.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nRT.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nRT.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nachans.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nachans.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nachans.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nontuftedRS.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nontuftedRS.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/nontuftedRS.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/simulation.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/simulation.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/simulation.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/spinystellate.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/spinystellate.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/spinystellate.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/supLTS.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/supLTS.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/supLTS.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/supaxoaxonic.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/supaxoaxonic.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/supaxoaxonic.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/supbasket.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/supbasket.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/supbasket.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/suppyrFRB.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/suppyrFRB.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/suppyrFRB.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/suppyrFRB.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/suppyrRS.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/suppyrRS.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/suppyrRS.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tcr.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tcr.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tcr.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/times.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/times.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/trbutil.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/trbutil.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/trbutil.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tuftIB.txt
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tuftedIB.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tuftedIB.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tuftedIB.pyo
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tuftedRS.py
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tuftedRS.pyc
/usr/share/doc/moose1.4/DEMOS/pymoose/traub2005/py/tuftedRS.pyo
/usr/share/doc/moose1.4/DEMOS/rallpack2/Rallpack2.g
/usr/share/doc/moose1.4/DEMOS/rallpack2/branch-0.analytical.plot
/usr/share/doc/moose1.4/DEMOS/rallpack2/branch-0.genesis.plot
/usr/share/doc/moose1.4/DEMOS/rallpack2/branch-0.png
/usr/share/doc/moose1.4/DEMOS/rallpack2/branch-x.analytical.plot
/usr/share/doc/moose1.4/DEMOS/rallpack2/branch-x.genesis.plot
/usr/share/doc/moose1.4/DEMOS/rallpack2/branch-x.png
/usr/share/doc/moose1.4/DEMOS/rallpack2/compatibility.g
/usr/share/doc/moose1.4/DEMOS/rallpack2/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/rallpack2/util.g
/usr/share/doc/moose1.4/DEMOS/rallpack3/Rallpack3.g
/usr/share/doc/moose1.4/DEMOS/rallpack3/axon-0.genesis.plot
/usr/share/doc/moose1.4/DEMOS/rallpack3/axon-0.png
/usr/share/doc/moose1.4/DEMOS/rallpack3/axon-x.genesis.plot
/usr/share/doc/moose1.4/DEMOS/rallpack3/axon-x.png
/usr/share/doc/moose1.4/DEMOS/rallpack3/compatibility.g
/usr/share/doc/moose1.4/DEMOS/rallpack3/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/rallpack3/squidchan.g
/usr/share/doc/moose1.4/DEMOS/rallpack3/util.g
/usr/share/doc/moose1.4/DEMOS/sbml_Reader/README
/usr/share/doc/moose1.4/DEMOS/sbml_Reader/Reader.g
/usr/share/doc/moose1.4/DEMOS/sbml_Reader/acc88.xml
/usr/share/doc/moose1.4/DEMOS/sbml_Reader/copasi.plot
/usr/share/doc/moose1.4/DEMOS/sbml_Reader/copasi.xsd
/usr/share/doc/moose1.4/DEMOS/sbml_Reader/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/sbml_Reader/plotUtil.g
/usr/share/doc/moose1.4/DEMOS/sbml_Writer/README
/usr/share/doc/moose1.4/DEMOS/sbml_Writer/Writer.g
/usr/share/doc/moose1.4/DEMOS/sbml_Writer/acc88.g
/usr/share/doc/moose1.4/DEMOS/sbml_Writer/copasi.plot
/usr/share/doc/moose1.4/DEMOS/sbml_Writer/copasi.xsd
/usr/share/doc/moose1.4/DEMOS/sbml_Writer/kkit.g
/usr/share/doc/moose1.4/DEMOS/sbml_Writer/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/sbml_Writer/plotUtil.g
/usr/share/doc/moose1.4/DEMOS/sbml_roundtrip/README
/usr/share/doc/moose1.4/DEMOS/sbml_roundtrip/RoundTrip.g
/usr/share/doc/moose1.4/DEMOS/sbml_roundtrip/acc88.xml
/usr/share/doc/moose1.4/DEMOS/sbml_roundtrip/copasi.plot
/usr/share/doc/moose1.4/DEMOS/sbml_roundtrip/copasi.xsd
/usr/share/doc/moose1.4/DEMOS/sbml_roundtrip/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/sbml_roundtrip/plotUtil.g
/usr/share/doc/moose1.4/DEMOS/squid-ee/Squid.g
/usr/share/doc/moose1.4/DEMOS/squid/plot.gp
/usr/share/doc/moose1.4/DEMOS/squid/plot.py
/usr/share/doc/moose1.4/DEMOS/squid/plot.pyc
/usr/share/doc/moose1.4/DEMOS/squid/plot.pyo
/usr/share/doc/moose1.4/DEMOS/squid/squid.g
/usr/share/doc/moose1.4/DEMOS/synapse/Gk.genesis.plot
/usr/share/doc/moose1.4/DEMOS/synapse/Gk.png
/usr/share/doc/moose1.4/DEMOS/synapse/NMDA.g
/usr/share/doc/moose1.4/DEMOS/synapse/Synapse.g
/usr/share/doc/moose1.4/DEMOS/synapse/Vm.genesis.plot
/usr/share/doc/moose1.4/DEMOS/synapse/Vm.png
/usr/share/doc/moose1.4/DEMOS/synapse/cable.p
/usr/share/doc/moose1.4/DEMOS/synapse/compatibility.g
/usr/share/doc/moose1.4/DEMOS/synapse/myelin2.p
/usr/share/doc/moose1.4/DEMOS/synapse/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/synapse/simplechan.g
/usr/share/doc/moose1.4/DEMOS/tab2Dchannel/MoczydKC.g
/usr/share/doc/moose1.4/DEMOS/tab2Dchannel/XA.txt
/usr/share/doc/moose1.4/DEMOS/tab2Dchannel/XB.txt
/usr/share/doc/moose1.4/DEMOS/tab2Dchannel/compatibility.g
/usr/share/doc/moose1.4/DEMOS/tab2Dchannel/loadMoc.g
/usr/share/doc/moose1.4/DEMOS/tab2Dchannel/printtab.g
/usr/share/doc/moose1.4/DEMOS/tab2Dchannel/testmoc.g
/usr/share/doc/moose1.4/DEMOS/timetable/TimeTable.g
/usr/share/doc/moose1.4/DEMOS/timetable/TimeTable.py
/usr/share/doc/moose1.4/DEMOS/timetable/TimeTable.pyc
/usr/share/doc/moose1.4/DEMOS/timetable/TimeTable.pyo
/usr/share/doc/moose1.4/DEMOS/timetable/compatibility.g
/usr/share/doc/moose1.4/DEMOS/timetable/output/Gk.genesis.plot
/usr/share/doc/moose1.4/DEMOS/timetable/output/Gk.png
/usr/share/doc/moose1.4/DEMOS/timetable/output/Vm.genesis.plot
/usr/share/doc/moose1.4/DEMOS/timetable/output/Vm.png
/usr/share/doc/moose1.4/DEMOS/timetable/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/timetable/spikes.txt
/usr/share/doc/moose1.4/DEMOS/traub91/CA1.p
/usr/share/doc/moose1.4/DEMOS/traub91/CA3.p
/usr/share/doc/moose1.4/DEMOS/traub91/Ca.genesis.plot
/usr/share/doc/moose1.4/DEMOS/traub91/Ca.png
/usr/share/doc/moose1.4/DEMOS/traub91/Traub91.g
/usr/share/doc/moose1.4/DEMOS/traub91/Vm.genesis.plot
/usr/share/doc/moose1.4/DEMOS/traub91/Vm.png
/usr/share/doc/moose1.4/DEMOS/traub91/acute.p
/usr/share/doc/moose1.4/DEMOS/traub91/compatibility.g
/usr/share/doc/moose1.4/DEMOS/traub91/plot.gnuplot
/usr/share/doc/moose1.4/DEMOS/traub91/traub91proto.g
/usr/share/doc/moose1.4/DOCS/Beta-1.1/README
/usr/share/doc/moose1.4/DOCS/Beta-1.1/RELEASE_NOTES_BETA_1.1.0
/usr/share/doc/moose1.4/DOCS/Beta-1.1/demos-readme
/usr/share/doc/moose1.4/DOCS/Beta-1.1/moose.1
/usr/share/doc/moose1.4/DOCS/Beta-1.2/README
/usr/share/doc/moose1.4/DOCS/Beta-1.2/RELEASE_NOTES_BETA_1.2.0
/usr/share/doc/moose1.4/DOCS/Beta-1.2/demos-readme
/usr/share/doc/moose1.4/DOCS/Beta-1.2/moose.1
/usr/share/doc/moose1.4/DOCS/Beta-1.4/README
/usr/share/doc/moose1.4/DOCS/Beta-1.4/RELEASE_NOTES_BETA_1.4.0
/usr/share/doc/moose1.4/DOCS/Beta-1.4/moose.1
/usr/share/doc/moose1.4/DOCS/Demos/DiffAmpDemo.g
/usr/share/doc/moose1.4/DOCS/Demos/DiffAmpDemo.gp
/usr/share/doc/moose1.4/DOCS/Demos/PIDTest.g
/usr/share/doc/moose1.4/DOCS/Demos/PulseGenDemo.g
/usr/share/doc/moose1.4/DOCS/Demos/RCDemo.g
/usr/share/doc/moose1.4/DOCS/Demos/UpiCell.txt
/usr/share/doc/moose1.4/DOCS/Demos/axon.p
/usr/share/doc/moose1.4/DOCS/Demos/bigtabsumtot.g
/usr/share/doc/moose1.4/DOCS/Demos/bulbchan.g
/usr/share/doc/moose1.4/DOCS/Demos/kholodenko.g
/usr/share/doc/moose1.4/DOCS/Demos/kkit.g
/usr/share/doc/moose1.4/DOCS/Demos/kkit_MMenz.g
/usr/share/doc/moose1.4/DOCS/Demos/kkit_enz.g
/usr/share/doc/moose1.4/DOCS/Demos/kkit_enz_1000mol.g
/usr/share/doc/moose1.4/DOCS/Demos/kkit_reac.g
/usr/share/doc/moose1.4/DOCS/Demos/mit.p
/usr/share/doc/moose1.4/DOCS/Demos/myelin/Myelin.g
/usr/share/doc/moose1.4/DOCS/Demos/myelin/chan.g
/usr/share/doc/moose1.4/DOCS/Demos/myelin/defaults.g
/usr/share/doc/moose1.4/DOCS/Demos/myelin/myelin.gnuplot
/usr/share/doc/moose1.4/DOCS/Demos/myelin/myelin2.p
/usr/share/doc/moose1.4/DOCS/Demos/myelin/nonmyelin2.p
/usr/share/doc/moose1.4/DOCS/Demos/parallel_squid.g
/usr/share/doc/moose1.4/DOCS/Demos/pulsegen.g
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/README
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.1.array/rall.1.array.g
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.1.array/util.g
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.1/cable.png
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.1/rall.1.g
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.1/rall.1.gnuplot
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.1/ref_cable.0
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.1/ref_cable.x
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.1/util.g
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.2/branch.0.png
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.2/branch.x.png
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.2/rall.2.g
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.2/rall.2.gnuplot
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.2/ref_branch.0
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.2/ref_branch.x
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.2/sim_branch.0
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.2/sim_branch.x
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.2/util.g
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.3/axon.0.png
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.3/axon.x.png
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.3/rall.3.g
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.3/rall.3.gnuplot
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.3/ref_axon.0.genesis
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.3/ref_axon.x.genesis
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.3/sim_axon.0
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.3/sim_axon.x
/usr/share/doc/moose1.4/DOCS/Demos/rallpack/rall.3/util.g
/usr/share/doc/moose1.4/DOCS/Demos/squid_gen.g
/usr/share/doc/moose1.4/DOCS/Demos/squid_solver.g
/usr/share/doc/moose1.4/DOCS/Demos/sumtot.g
/usr/share/doc/moose1.4/DOCS/Demos/tabsumtot.g
/usr/share/doc/moose1.4/DOCS/Demos/test_axon.g
/usr/share/doc/moose1.4/DOCS/Demos/test_foreach.g
/usr/share/doc/moose1.4/DOCS/Demos/test_kinsolver.g
/usr/share/doc/moose1.4/DOCS/Demos/test_readcell.g
/usr/share/doc/moose1.4/DOCS/Demos/test_showmsg.g
/usr/share/doc/moose1.4/DOCS/Demos/test_smoldyn.g
/usr/share/doc/moose1.4/DOCS/DesignDocument.rtf
/usr/share/doc/moose1.4/DOCS/HSOLVE
/usr/share/doc/moose1.4/DOCS/IDS
/usr/share/doc/moose1.4/DOCS/KinSynChan.tex
/usr/share/doc/moose1.4/DOCS/MESSAGING
/usr/share/doc/moose1.4/DOCS/MOOSE2007_INTRO
/usr/share/doc/moose1.4/DOCS/PARALLEL
/usr/share/doc/moose1.4/DOCS/ParallelNeuronSimulation.doc
/usr/share/doc/moose1.4/DOCS/PyMOOSE_HowTo.doc
/usr/share/doc/moose1.4/DOCS/README.parallel
/usr/share/doc/moose1.4/DOCS/RELEASE_NOTES_BETA_1.0.0
/usr/share/doc/moose1.4/DOCS/SOLVERS
/usr/share/doc/moose1.4/DOCS/benchmark/RESULTS
/usr/share/doc/moose1.4/DOCS/benchmark/acc.plot
/usr/share/doc/moose1.4/DOCS/benchmark/acc4_1.6e-21.g
/usr/share/doc/moose1.4/DOCS/benchmark/kh.plot
/usr/share/doc/moose1.4/DOCS/benchmark/kholodenko.g
/usr/share/doc/moose1.4/DOCS/benchmark/kkit.g
/usr/share/doc/moose1.4/DOCS/benchmark/mega.plot
/usr/share/doc/moose1.4/DOCS/benchmark/mega_1.6e-21.g
/usr/share/doc/moose1.4/DOCS/benchmark/nonscaf.plot
/usr/share/doc/moose1.4/DOCS/benchmark/nonscaf6_1.6e-21b.g
/usr/share/doc/moose1.4/DOCS/gui/Makefile
/usr/share/doc/moose1.4/DOCS/gui/README
/usr/share/doc/moose1.4/DOCS/gui/connect_0_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/connect_1_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/connect_2_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/element_tree.png
/usr/share/doc/moose1.4/DOCS/gui/file_types.png
/usr/share/doc/moose1.4/DOCS/gui/first_time_wizard.png
/usr/share/doc/moose1.4/DOCS/gui/first_time_wizard_1.png
/usr/share/doc/moose1.4/DOCS/gui/first_time_wizard_2.png
/usr/share/doc/moose1.4/DOCS/gui/first_time_wizard_3.png
/usr/share/doc/moose1.4/DOCS/gui/kholodenko.png
/usr/share/doc/moose1.4/DOCS/gui/kholodenko_plots.png
/usr/share/doc/moose1.4/DOCS/gui/load_model.png
/usr/share/doc/moose1.4/DOCS/gui/moose_class_tooltip_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/moose_classes.png
/usr/share/doc/moose1.4/DOCS/gui/moose_field_tooltip_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/moose_shell.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui.pdf
/usr/share/doc/moose1.4/DOCS/gui/moosegui.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui.texi
/usr/share/doc/moose1.4/DOCS/gui/moosegui/Adding-elements-in-a-model.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui/Getting-Started.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui/Getting-help.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui/Loading-a-file-in-the-GUI.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui/Overview-of-the-GUI-window.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui/Recording-and-plotting-data.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui/Using-the-GUI.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui/connect_0_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/connect_1_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/connect_2_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/element_tree.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/file_types.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/first_time_wizard.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/first_time_wizard_1.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/first_time_wizard_2.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/first_time_wizard_3.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/index.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui/kholodenko.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/kholodenko_plots.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/load_model.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/moose_002dclasses_002dwidget.html
/usr/share/doc/moose1.4/DOCS/gui/moosegui/moose_class_tooltip_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/moose_classes.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/moose_field_tooltip_lowres.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/moose_shell.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/moosegui.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/object_editor.png
/usr/share/doc/moose1.4/DOCS/gui/moosegui/simulation_control.png
/usr/share/doc/moose1.4/DOCS/gui/object_editor.png
/usr/share/doc/moose1.4/DOCS/gui/simulation_control.png
/usr/share/doc/moose1.4/DOCS/hsolve.ppt
/usr/share/doc/moose1.4/DOCS/mooseLogo.ppt
/usr/share/doc/moose1.4/DOCS/moose_logo.png
/usr/share/doc/moose1.4/DOCS/moose_thumbnail.png
/usr/share/doc/moose1.4/DOCS/moose_thumbnail2.png
/usr/share/doc/moose1.4/DOCS/pymoose/Makefile
/usr/share/doc/moose1.4/DOCS/pymoose/copying.texi
/usr/share/doc/moose1.4/DOCS/pymoose/detailed.texi
/usr/share/doc/moose1.4/DOCS/pymoose/faq.texi
/usr/share/doc/moose1.4/DOCS/pymoose/fdl.texi
/usr/share/doc/moose1.4/DOCS/pymoose/index.texi
/usr/share/doc/moose1.4/DOCS/pymoose/install.texi
/usr/share/doc/moose1.4/DOCS/pymoose/intro.texi
/usr/share/doc/moose1.4/DOCS/pymoose/pymoose.html
/usr/share/doc/moose1.4/DOCS/pymoose/pymoose.info
/usr/share/doc/moose1.4/DOCS/pymoose/pymoose.pdf
/usr/share/doc/moose1.4/DOCS/pymoose/pymoose.texi
/usr/share/doc/moose1.4/DOCS/pymoose/quickstart.texi
/usr/share/doc/moose1.4/TESTS/regression/NeuroML_Reader/GranuleCell.morph.xml
/usr/share/doc/moose1.4/TESTS/regression/NeuroML_Reader/KConductance.xml
/usr/share/doc/moose1.4/TESTS/regression/NeuroML_Reader/NaConductance.xml
/usr/share/doc/moose1.4/TESTS/regression/NeuroML_Reader/PassiveCond.xml
/usr/share/doc/moose1.4/TESTS/regression/NeuroML_Reader/PurkinjeCell.morph.xml
/usr/share/doc/moose1.4/TESTS/regression/NeuroML_Reader/README
/usr/share/doc/moose1.4/TESTS/regression/NeuroML_Reader/moose_NeuroML_reader.g
/usr/share/doc/moose1.4/TESTS/regression/NeuroML_Reader/plotUtil.g
/usr/share/doc/moose1.4/TESTS/regression/README
/usr/share/doc/moose1.4/TESTS/regression/SMSNNchan.g
/usr/share/doc/moose1.4/TESTS/regression/acc88_copasi.plot
/usr/share/doc/moose1.4/TESTS/regression/axon/axon.p
/usr/share/doc/moose1.4/TESTS/regression/axon/bulbchan.g
/usr/share/doc/moose1.4/TESTS/regression/axon/compatibility.g
/usr/share/doc/moose1.4/TESTS/regression/bulbchan.g
/usr/share/doc/moose1.4/TESTS/regression/cable.p
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Ca_bsg_yka.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Ca_hip_traub.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Ca_hip_traub91.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_K2_mit_usb.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_KA_bsg_yka.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_KM_bsg_yka.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_K_bsg_yka.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_K_hh_tchan.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_K_hip_traub.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_K_mit_usb.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Ka_hip_traub91.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Kahp_hip_traub91.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Kc_hip_traub91.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Kca_hip_traub.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Kdr_hip_traub91.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_LCa3_mit_usb.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Na_bsg_yka.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Na_hh_tchan.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Na_hip_traub91.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Na_mit_usb.plot
/usr/share/doc/moose1.4/TESTS/regression/channelplots/moose_Na_rat_smsnn.plot
/usr/share/doc/moose1.4/TESTS/regression/do_regression.bat
/usr/share/doc/moose1.4/TESTS/regression/do_regression_win.bat
/usr/share/doc/moose1.4/TESTS/regression/globalParms.p
/usr/share/doc/moose1.4/TESTS/regression/hh_tchan.g
/usr/share/doc/moose1.4/TESTS/regression/mit.p
/usr/share/doc/moose1.4/TESTS/regression/mitral-ee/bulbchan.g
/usr/share/doc/moose1.4/TESTS/regression/mitral-ee/compatibility.g
/usr/share/doc/moose1.4/TESTS/regression/mitral-ee/mit.p
/usr/share/doc/moose1.4/TESTS/regression/moose_NeuroMLReader.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_NeuroML_reader.g
/usr/share/doc/moose1.4/TESTS/regression/moose_axon.g
/usr/share/doc/moose1.4/TESTS/regression/moose_axon.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_channels.g
/usr/share/doc/moose1.4/TESTS/regression/moose_file2tab.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_file2tab2file.g
/usr/share/doc/moose1.4/TESTS/regression/moose_kholodenko.g
/usr/share/doc/moose1.4/TESTS/regression/moose_kholodenko.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_mitral.g
/usr/share/doc/moose1.4/TESTS/regression/moose_mitral.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_network.g
/usr/share/doc/moose1.4/TESTS/regression/moose_network.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_rallpack1.g
/usr/share/doc/moose1.4/TESTS/regression/moose_rallpack1.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_rallpack2.g
/usr/share/doc/moose1.4/TESTS/regression/moose_rallpack2.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_rallpack3.g
/usr/share/doc/moose1.4/TESTS/regression/moose_rallpack3.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_readcell.g
/usr/share/doc/moose1.4/TESTS/regression/moose_readcell.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_readcell_global_parms.g
/usr/share/doc/moose1.4/TESTS/regression/moose_readcell_global_parms.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_sbml_read_write.g
/usr/share/doc/moose1.4/TESTS/regression/moose_sbml_reader.g
/usr/share/doc/moose1.4/TESTS/regression/moose_squid.g
/usr/share/doc/moose1.4/TESTS/regression/moose_squid.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_synapse.g
/usr/share/doc/moose1.4/TESTS/regression/moose_synapse.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_synchan.g
/usr/share/doc/moose1.4/TESTS/regression/moose_synchan.plot
/usr/share/doc/moose1.4/TESTS/regression/moose_traub91.g
/usr/share/doc/moose1.4/TESTS/regression/moose_traub91.plot
/usr/share/doc/moose1.4/TESTS/regression/myelin2.p
/usr/share/doc/moose1.4/TESTS/regression/neardiff
/usr/share/doc/moose1.4/TESTS/regression/neardiff.cpp
/usr/share/doc/moose1.4/TESTS/regression/network-ee/compatibility.g
/usr/share/doc/moose1.4/TESTS/regression/network-ee/hh_tchan.g
/usr/share/doc/moose1.4/TESTS/regression/rallpack1/compatibility.g
/usr/share/doc/moose1.4/TESTS/regression/rallpack1/util.g
/usr/share/doc/moose1.4/TESTS/regression/rallpack2/compatibility.g
/usr/share/doc/moose1.4/TESTS/regression/rallpack2/util.g
/usr/share/doc/moose1.4/TESTS/regression/rallpack3/compatibility.g
/usr/share/doc/moose1.4/TESTS/regression/rallpack3/squidchan.g
/usr/share/doc/moose1.4/TESTS/regression/rallpack3/util.g
/usr/share/doc/moose1.4/TESTS/regression/sbml_Read_Write/README
/usr/share/doc/moose1.4/TESTS/regression/sbml_Read_Write/acc88.xml
/usr/share/doc/moose1.4/TESTS/regression/sbml_Read_Write/plotUtil.g
/usr/share/doc/moose1.4/TESTS/regression/sbml_Reader/README
/usr/share/doc/moose1.4/TESTS/regression/sbml_Reader/acc88.xml
/usr/share/doc/moose1.4/TESTS/regression/sbml_Reader/acc88_moose.plot
/usr/share/doc/moose1.4/TESTS/regression/sbml_Reader/long_copasi.plot
/usr/share/doc/moose1.4/TESTS/regression/sbml_Reader/plotUtil.g
/usr/share/doc/moose1.4/TESTS/regression/sbml_Reader/v20.xml
/usr/share/doc/moose1.4/TESTS/regression/sbml_Reader/v20_copasi.plot
/usr/share/doc/moose1.4/TESTS/regression/sbml_Reader/v20_long.plot
/usr/share/doc/moose1.4/TESTS/regression/sbml_Reader/v20_moose.plot
/usr/share/doc/moose1.4/TESTS/regression/simplechan.g
/usr/share/doc/moose1.4/TESTS/regression/soma.p
/usr/share/doc/moose1.4/TESTS/regression/synapse/cable.p
/usr/share/doc/moose1.4/TESTS/regression/synapse/compatibility.g
/usr/share/doc/moose1.4/TESTS/regression/synapse/myelin2.p
/usr/share/doc/moose1.4/TESTS/regression/synapse/simplechan.g
/usr/share/doc/moose1.4/TESTS/regression/traub91/CA3.p
/usr/share/doc/moose1.4/TESTS/regression/traub91/compatibility.g
/usr/share/doc/moose1.4/TESTS/regression/traub91/traub91proto.g
/usr/share/doc/moose1.4/TESTS/regression/traub91chan.g
/usr/share/doc/moose1.4/TESTS/regression/traubchan.g
/usr/share/doc/moose1.4/TESTS/regression/v20_copasi.plot
/usr/share/doc/moose1.4/TESTS/regression/v20_moose.plot
/usr/share/doc/moose1.4/TESTS/regression/yamadachan.g
/usr/share/info/pymoose.info.gz
/usr/share/man/man1/moose.1.gz
/usr/share/moose1.4/colormaps/grey
/usr/share/moose1.4/colormaps/hot
/usr/share/moose1.4/colormaps/rainbow2
/usr/share/moose1.4/colormaps/redhot
/usr/share/moose1.4/lib/libgsl.so.0
/usr/share/moose1.4/lib/libgslcblas.so.0
/usr/share/moose1.4/lib/libsbml.so
/usr/share/moose1.4/lib/libxml2.so.2
/usr/share/moose1.4/moosegui/PyCute.py
/usr/share/moose1.4/moosegui/PyCute.pyc
/usr/share/moose1.4/moosegui/PyCute.pyo
/usr/share/moose1.4/moosegui/biomodelsclient.py
/usr/share/moose1.4/moosegui/biomodelsclient.pyc
/usr/share/moose1.4/moosegui/biomodelsclient.pyo
/usr/share/moose1.4/moosegui/config.py
/usr/share/moose1.4/moosegui/config.pyc
/usr/share/moose1.4/moosegui/config.pyo
/usr/share/moose1.4/moosegui/firsttime.py
/usr/share/moose1.4/moosegui/firsttime.pyc
/usr/share/moose1.4/moosegui/firsttime.pyo
/usr/share/moose1.4/moosegui/glcelldemo.py
/usr/share/moose1.4/moosegui/glcelldemo.pyc
/usr/share/moose1.4/moosegui/glcelldemo.pyo
/usr/share/moose1.4/moosegui/glcellloader.py
/usr/share/moose1.4/moosegui/glcellloader.pyc
/usr/share/moose1.4/moosegui/glcellloader.pyo
/usr/share/moose1.4/moosegui/glclient.py
/usr/share/moose1.4/moosegui/glclient.pyc
/usr/share/moose1.4/moosegui/glclient.pyo
/usr/share/moose1.4/moosegui/glclientgui.py
/usr/share/moose1.4/moosegui/glclientgui.pyc
/usr/share/moose1.4/moosegui/glclientgui.pyo
/usr/share/moose1.4/moosegui/glviewdemo.py
/usr/share/moose1.4/moosegui/glviewdemo.pyc
/usr/share/moose1.4/moosegui/glviewdemo.pyo
/usr/share/moose1.4/moosegui/glviewloader.py
/usr/share/moose1.4/moosegui/glviewloader.pyc
/usr/share/moose1.4/moosegui/glviewloader.pyo
/usr/share/moose1.4/moosegui/glwizard.py
/usr/share/moose1.4/moosegui/layout.py
/usr/share/moose1.4/moosegui/layout.pyc
/usr/share/moose1.4/moosegui/layout.pyo
/usr/share/moose1.4/moosegui/moose_icon.png
/usr/share/moose1.4/moosegui/mooseclasses.py
/usr/share/moose1.4/moosegui/mooseclasses.pyc
/usr/share/moose1.4/moosegui/mooseclasses.pyo
/usr/share/moose1.4/moosegui/mooseglobals.py
/usr/share/moose1.4/moosegui/mooseglobals.pyc
/usr/share/moose1.4/moosegui/mooseglobals.pyo
/usr/share/moose1.4/moosegui/moosegui.py
/usr/share/moose1.4/moosegui/moosehandler.py
/usr/share/moose1.4/moosegui/mooseplot.py
/usr/share/moose1.4/moosegui/mooseplot.pyc
/usr/share/moose1.4/moosegui/mooseplot.pyo
/usr/share/moose1.4/moosegui/mooseshell.py
/usr/share/moose1.4/moosegui/mooseshell.pyc
/usr/share/moose1.4/moosegui/mooseshell.pyo
/usr/share/moose1.4/moosegui/moosetree.py
/usr/share/moose1.4/moosegui/moosetree.pyc
/usr/share/moose1.4/moosegui/moosetree.pyo
/usr/share/moose1.4/moosegui/objectedit.py
/usr/share/moose1.4/moosegui/objectedit.pyc
/usr/share/moose1.4/moosegui/objectedit.pyo
/usr/share/moose1.4/moosegui/plotconfig.py
/usr/share/moose1.4/moosegui/plotconfig.pyc
/usr/share/moose1.4/moosegui/plotconfig.pyo
/usr/share/moose1.4/moosegui/test_soap.py
/usr/share/moose1.4/moosegui/test_soap.pyc
/usr/share/moose1.4/moosegui/test_soap.pyo
/usr/share/moose1.4/moosegui/test_urldownload.py
/usr/share/moose1.4/moosegui/test_urldownload.pyc
/usr/share/moose1.4/moosegui/test_urldownload.pyo
/usr/share/moose1.4/py_stage/_moose.so
/usr/share/moose1.4/py_stage/moose.py
/usr/share/moose1.4/py_stage/moose.pyc
/usr/share/moose1.4/py_stage/moose.pyo
/usr/share/moose1.4/py_stage/pymoose.py
/usr/share/moose1.4/py_stage/pymoose.pyc
/usr/share/moose1.4/py_stage/pymoose.pyo

%doc README 
%doc INSTALL 
%doc COPYING.LIB 


%changelog
* Thu Nov 11 2010  <subhasis@ncbs.res.in> - beta-1.4.0
- Initial RPM build.

